#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_FVG9mW_iV00Sd5jvvtdbAo=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((
pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(sizeof(
mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern=(
PmSparsityPattern*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(PmSparsityPattern)),(1))));
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr=(PmRealVector*)(((pm__8zlSpb2Hixod149p2zadR)->
mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(sizeof(PmRealVector)),(1))));*(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern)= *pm__6H5I5OnY3KoY5YVL6mLgG;*(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr)= *mc_VTddUsjDkUlHXyWpbnu_X6;return
mc_FVG9mW_iV00Sd5jvvtdbAo;}void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){{void*const mc__nXet41dE8_kZelZPVMcOT=(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern);PmAllocator*const
mc_Frm9k6MhgTdp_qVSQABULF=(pm__8zlSpb2Hixod149p2zadR);if(
mc__nXet41dE8_kZelZPVMcOT){(mc_Frm9k6MhgTdp_qVSQABULF)->mFreeFcn(
mc_Frm9k6MhgTdp_qVSQABULF,mc__nXet41dE8_kZelZPVMcOT);}};{void*const
mc_Vq3NNJdKzbtHfe8WeFbDg9=(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr);PmAllocator*const
mc_VBqGHWZ7CldnePAFp61g0Y=(pm__8zlSpb2Hixod149p2zadR);if(
mc_Vq3NNJdKzbtHfe8WeFbDg9){(mc_VBqGHWZ7CldnePAFp61g0Y)->mFreeFcn(
mc_VBqGHWZ7CldnePAFp61g0Y,mc_Vq3NNJdKzbtHfe8WeFbDg9);}};{void*const
mc_FiQnVwFvdWOsZq7B7HjOOu=(mc_FVG9mW_iV00Sd5jvvtdbAo);PmAllocator*const
mc_FUEy1LyQ9H_WfmKZ7x6Eym=(pm__8zlSpb2Hixod149p2zadR);if(
mc_FiQnVwFvdWOsZq7B7HjOOu){(mc_FUEy1LyQ9H_WfmKZ7x6Eym)->mFreeFcn(
mc_FUEy1LyQ9H_WfmKZ7x6Eym,mc_FiQnVwFvdWOsZq7B7HjOOu);}};}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z(size_t
pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*result=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((
pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(sizeof(
mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));result->mPattern=pm_create_sparsity_pattern
(pm_keOJjiAyBTtFhyWf033kni,pm_kJxontPsxndNYXwDXdE1iy,pm_kPvICtSd_wWNieTWLEBFD1
,pm__8zlSpb2Hixod149p2zadR);result->mPr=pm_create_real_vector(
pm_keOJjiAyBTtFhyWf033kni,pm__8zlSpb2Hixod149p2zadR);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*result=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((
pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(sizeof(
mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));result->mPattern=pm_FQMLyYzCQ5CtgHjze1nNJP(
mc__H_R6laiZnCcXyegjjDM0e->mPattern,pm__8zlSpb2Hixod149p2zadR);result->mPr=
pm_V_q_QnwoVVl6fHS_0pLvYo(mc__H_R6laiZnCcXyegjjDM0e->mPr,
pm__8zlSpb2Hixod149p2zadR);return result;}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo=(mc__mbv8xxcLWlA_qjxkZ_Zr3
*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(
sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern=
pm__TNI3M36rThlaTetY4tWiB(n,pm__8zlSpb2Hixod149p2zadR);
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr=pm_create_real_vector(n,
pm__8zlSpb2Hixod149p2zadR);mc__dsFCQJjA6p_j1tGhi2wWe(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPr,1.0);return mc_FVG9mW_iV00Sd5jvvtdbAo;}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc__oFzjr34Rc8NYmhojkCr9E(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo=(mc__mbv8xxcLWlA_qjxkZ_Zr3
*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(
sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern=
mc_VI58f6RQKXS_Y5sclnoOPT(a->mPattern,b->mPattern,pm__8zlSpb2Hixod149p2zadR);
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr=pm_create_real_vector(a->mPr->mN+b->mPr->mN,
pm__8zlSpb2Hixod149p2zadR);mc__aNO1s5qwzt6fXwft5YgCz(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPr);mc__WqQP6u7DtdYVDzUK5y971(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr,a->mPr,b->mPr)
;return mc_FVG9mW_iV00Sd5jvvtdbAo;}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kutbbLKiKk43hyBnfSGAST=mc__uIK1az5Q0lU_9qiZoDp2w(
a,pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_VPPSxR3RRt0pXLadx2tWo7=mc__uIK1az5Q0lU_9qiZoDp2w(b,
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__7ORV8zRHztKX1vdpi__yY
=mc__oFzjr34Rc8NYmhojkCr9E(mc_kutbbLKiKk43hyBnfSGAST,mc_VPPSxR3RRt0pXLadx2tWo7
,pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_FVG9mW_iV00Sd5jvvtdbAo=mc__uIK1az5Q0lU_9qiZoDp2w(mc__7ORV8zRHztKX1vdpi__yY,
pm__8zlSpb2Hixod149p2zadR);mc_kXL8zBVnOn4yZLHVqnqmYJ(mc__7ORV8zRHztKX1vdpi__yY
,pm__8zlSpb2Hixod149p2zadR);mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc_VPPSxR3RRt0pXLadx2tWo7,pm__8zlSpb2Hixod149p2zadR);mc_kXL8zBVnOn4yZLHVqnqmYJ
(mc_kutbbLKiKk43hyBnfSGAST,pm__8zlSpb2Hixod149p2zadR);return
mc_FVG9mW_iV00Sd5jvvtdbAo;}mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_F3GYxtOuUXStZuaKTYqPSh,size_t mc_kdV6gi9UV7C3busQ054WhO,size_t
mc_kF0899509L4BdTLCApD17a,size_t mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_k2GhanXRrSOR_egl7A8Yx_
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
mc_k2GhanXRrSOR_egl7A8Yx_->mPattern=mc__JB9jUvbb10FaTie1cmY8_(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,mc_F3GYxtOuUXStZuaKTYqPSh,
mc_kdV6gi9UV7C3busQ054WhO,mc_kF0899509L4BdTLCApD17a,mc_kk1VpoYYYRxBgi6A0xe6ww,
pm__8zlSpb2Hixod149p2zadR);mc_k2GhanXRrSOR_egl7A8Yx_->mPr=
pm_create_real_vector(((size_t)(((mc_k2GhanXRrSOR_egl7A8Yx_->mPattern)->mJc[(
mc_k2GhanXRrSOR_egl7A8Yx_->mPattern)->mNumCol]))),pm__8zlSpb2Hixod149p2zadR);
mc_Fzylow9cnZxIhyL1O9nM0I(mc_k2GhanXRrSOR_egl7A8Yx_->mPr,
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr,mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,
mc_F3GYxtOuUXStZuaKTYqPSh,mc_kdV6gi9UV7C3busQ054WhO,mc_kF0899509L4BdTLCApD17a,
mc_kk1VpoYYYRxBgi6A0xe6ww);return mc_k2GhanXRrSOR_egl7A8Yx_;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__2Fk0Pwf3n8dgXgLeTpNL6=(mc__mbv8xxcLWlA_qjxkZ_Zr3
*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((pm__8zlSpb2Hixod149p2zadR),(
sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));mc__2Fk0Pwf3n8dgXgLeTpNL6->mPattern=
mc_kAZzxJsz9tloc11S9uThaF(mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,
pm__8zlSpb2Hixod149p2zadR);mc__2Fk0Pwf3n8dgXgLeTpNL6->mPr=
pm_create_real_vector(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->mN,
pm__8zlSpb2Hixod149p2zadR);mc_klSR73f0rO4LhXVlV6gmb7(mc__2Fk0Pwf3n8dgXgLeTpNL6
->mPr->mX,mc__2Fk0Pwf3n8dgXgLeTpNL6->mPattern,mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->
mX,mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern);return mc__2Fk0Pwf3n8dgXgLeTpNL6;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F8Wahboz7_hFgLIaeSqe1a
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
mc_F8Wahboz7_hFgLIaeSqe1a->mPattern=mc__OkC5ssIRclKeDF7PdRNWG(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,perm,pm__8zlSpb2Hixod149p2zadR);
mc_F8Wahboz7_hFgLIaeSqe1a->mPr=pm_create_real_vector(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPr->mN,pm__8zlSpb2Hixod149p2zadR);mc_VgJ42P0i5f4Hby5_Ow7gtm(
mc_F8Wahboz7_hFgLIaeSqe1a->mPr->mX,mc_F8Wahboz7_hFgLIaeSqe1a->mPattern,
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->mX,mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,perm);
return mc_F8Wahboz7_hFgLIaeSqe1a;}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_VlrliqitUo4vbaopHr9nhF(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__qmnXhADkT_Fc9DOtIIj7r
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
mc__qmnXhADkT_Fc9DOtIIj7r->mPattern=mc__tKZgLZup1pKXLQCAtP8rU(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,perm,pm__8zlSpb2Hixod149p2zadR);
mc__qmnXhADkT_Fc9DOtIIj7r->mPr=pm_create_real_vector(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPr->mN,pm__8zlSpb2Hixod149p2zadR);mc_kpAmYrZzcKGOgq9qpxzj07(
mc__qmnXhADkT_Fc9DOtIIj7r->mPr->mX,mc__qmnXhADkT_Fc9DOtIIj7r->mPattern,
mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->mX,mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,perm,
pm__8zlSpb2Hixod149p2zadR);return mc__qmnXhADkT_Fc9DOtIIj7r;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__CegvZb0tQlxYDBGNuMOWI
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
mc__CegvZb0tQlxYDBGNuMOWI->mPattern=mc_VJlBwQnSeLpciXVTLb_llB(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,mc_FIvSpRV20s_Jcm1tm_edj6,
pm__8zlSpb2Hixod149p2zadR);mc__CegvZb0tQlxYDBGNuMOWI->mPr=
pm_V_q_QnwoVVl6fHS_0pLvYo(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr,
pm__8zlSpb2Hixod149p2zadR);return mc__CegvZb0tQlxYDBGNuMOWI;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__CegvZb0tQlxYDBGNuMOWI
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
mc__CegvZb0tQlxYDBGNuMOWI->mPattern=pm_FQMLyYzCQ5CtgHjze1nNJP(
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,pm__8zlSpb2Hixod149p2zadR);
mc_kNxwVTI76g4kj9P52yKhA5(mc__CegvZb0tQlxYDBGNuMOWI->mPattern,
mc_FIvSpRV20s_Jcm1tm_edj6);mc__CegvZb0tQlxYDBGNuMOWI->mPr=
pm_V_q_QnwoVVl6fHS_0pLvYo(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr,
pm__8zlSpb2Hixod149p2zadR);return mc__CegvZb0tQlxYDBGNuMOWI;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__R02re94H_h8XX5u4PNNdz
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
PmRealVector*mc_VRZCD_UL_ESThy75dC9J8D=NULL;mc__R02re94H_h8XX5u4PNNdz->
mPattern=mc_kyCwDjPxmBGRiTH73vrjJL(A->mPattern,mc_Vqiy96WqvuhCaXm5e_vvT0->
mPattern,pm__8zlSpb2Hixod149p2zadR);mc__R02re94H_h8XX5u4PNNdz->mPr=
pm_create_real_vector(((size_t)(((mc__R02re94H_h8XX5u4PNNdz->mPattern)->mJc[(
mc__R02re94H_h8XX5u4PNNdz->mPattern)->mNumCol]))),pm__8zlSpb2Hixod149p2zadR);
mc_VRZCD_UL_ESThy75dC9J8D=pm_create_real_vector(mc__R02re94H_h8XX5u4PNNdz->
mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);mc__tyTSVoY7fpafmg4sUl1P3(
mc__R02re94H_h8XX5u4PNNdz->mPr,mc__R02re94H_h8XX5u4PNNdz->mPattern,A->mPr,A->
mPattern,mc_Vqiy96WqvuhCaXm5e_vvT0->mPr,mc_Vqiy96WqvuhCaXm5e_vvT0->mPattern,
mc_VRZCD_UL_ESThy75dC9J8D);pm_destroy_real_vector(mc_VRZCD_UL_ESThy75dC9J8D,
pm__8zlSpb2Hixod149p2zadR);return mc__R02re94H_h8XX5u4PNNdz;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_Vzz7fHz6oElvjujXUEM3YM
=(mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));
PmRealVector*mc_VRZCD_UL_ESThy75dC9J8D=NULL;mc_Vzz7fHz6oElvjujXUEM3YM->
mPattern=mc__5C6m_ZyP9_NYekcJCEULM(A->mPattern,mc_Vqiy96WqvuhCaXm5e_vvT0->
mPattern,pm__8zlSpb2Hixod149p2zadR);mc_Vzz7fHz6oElvjujXUEM3YM->mPr=
pm_create_real_vector(((size_t)(((mc_Vzz7fHz6oElvjujXUEM3YM->mPattern)->mJc[(
mc_Vzz7fHz6oElvjujXUEM3YM->mPattern)->mNumCol]))),pm__8zlSpb2Hixod149p2zadR);
mc_VRZCD_UL_ESThy75dC9J8D=pm_create_real_vector(mc_Vzz7fHz6oElvjujXUEM3YM->
mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);mc__8x7kz_627_gXDli_FJo22(
mc_Vzz7fHz6oElvjujXUEM3YM->mPr,mc_Vzz7fHz6oElvjujXUEM3YM->mPattern,A->mPr,A->
mPattern,mc_Vqiy96WqvuhCaXm5e_vvT0->mPr,mc_Vqiy96WqvuhCaXm5e_vvT0->mPattern,
mc_VRZCD_UL_ESThy75dC9J8D);pm_destroy_real_vector(mc_VRZCD_UL_ESThy75dC9J8D,
pm__8zlSpb2Hixod149p2zadR);return mc_Vzz7fHz6oElvjujXUEM3YM;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=(
mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));result->
mPattern=mc_V_3Bm28Cx08dj9ZMdrwaJg(mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,
mc_VlZMmzn2z2dpZyy2834RK6,mc_kYm9_Bnh90tjXTI8q_HusO,pm__8zlSpb2Hixod149p2zadR)
;result->mPr=pm_create_real_vector(((size_t)(((result->mPattern)->mJc[(result
->mPattern)->mNumCol]))),pm__8zlSpb2Hixod149p2zadR);mc_Fv2sZggivbSOc5zulDbRra(
result->mPr,mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->mX,mc_FVG9mW_iV00Sd5jvvtdbAo->
mPattern,mc_VlZMmzn2z2dpZyy2834RK6,mc_kYm9_Bnh90tjXTI8q_HusO);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,
PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*
mc_FZx3iFiX1YW7j5eEojoAPc){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=(
mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((
mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));result->
mPattern=mc__mBVa3_c658wjuT_cJe_Qy(mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,
mc_F8fT7naL9bOcimTADCVzTC,mc_VCVhWy_VaDhraHrlfFWxBa,mc_FZx3iFiX1YW7j5eEojoAPc)
;result->mPr=pm_V_q_QnwoVVl6fHS_0pLvYo(mc_FVG9mW_iV00Sd5jvvtdbAo->mPr,
mc_FZx3iFiX1YW7j5eEojoAPc);return result;}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=(
mc__mbv8xxcLWlA_qjxkZ_Zr3*)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(mc__mbv8xxcLWlA_qjxkZ_Zr3)),(1))));result->
mPattern=mc__qAqv2Z2m7K0VPPGKiCpwD(mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern,
mc_VlZMmzn2z2dpZyy2834RK6,mc_kYm9_Bnh90tjXTI8q_HusO,pm__8zlSpb2Hixod149p2zadR)
;result->mPr=pm_create_real_vector(((size_t)(((result->mPattern)->mJc[(result
->mPattern)->mNumCol]))),pm__8zlSpb2Hixod149p2zadR);mc_Fv2sZggivbSOc5zulDbRra(
result->mPr,mc_FVG9mW_iV00Sd5jvvtdbAo->mPr->mX,mc_FVG9mW_iV00Sd5jvvtdbAo->
mPattern,mc_VlZMmzn2z2dpZyy2834RK6,mc_kYm9_Bnh90tjXTI8q_HusO);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=NULL;PmBoolVector*
mc_FIRQmUoZ8GOih5Os6NY5A_=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
mc_F50LHIM89Xpj_mZvqqCQnH=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumCol,pm__8zlSpb2Hixod149p2zadR);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_FIRQmUoZ8GOih5Os6NY5A_,true);mc_VWloU5QD6gpaXeK8lmytFA(
mc_F50LHIM89Xpj_mZvqqCQnH);mc_F50LHIM89Xpj_mZvqqCQnH->mX[
pm_Fr_bHKkQKFWbfi50VWd5Pw]=true;result=mc_F6NuiNPSsu0yf1TluQ0__s(
mc_FVG9mW_iV00Sd5jvvtdbAo,mc_FIRQmUoZ8GOih5Os6NY5A_,mc_F50LHIM89Xpj_mZvqqCQnH,
pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(mc_FIRQmUoZ8GOih5Os6NY5A_
,pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(
mc_F50LHIM89Xpj_mZvqqCQnH,pm__8zlSpb2Hixod149p2zadR);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=NULL;PmBoolVector*
mc_FIRQmUoZ8GOih5Os6NY5A_=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
mc_F50LHIM89Xpj_mZvqqCQnH=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumCol,pm__8zlSpb2Hixod149p2zadR);mc_VWloU5QD6gpaXeK8lmytFA(
mc_FIRQmUoZ8GOih5Os6NY5A_);mc_FIRQmUoZ8GOih5Os6NY5A_->mX[
pm_kplAJmOlA30feiNcOzi7oj]=true;mc_k1sxUtEClkOZVuHMQ91JqD(
mc_F50LHIM89Xpj_mZvqqCQnH,true);result=mc_F6NuiNPSsu0yf1TluQ0__s(
mc_FVG9mW_iV00Sd5jvvtdbAo,mc_FIRQmUoZ8GOih5Os6NY5A_,mc_F50LHIM89Xpj_mZvqqCQnH,
pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(mc_FIRQmUoZ8GOih5Os6NY5A_
,pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(
mc_F50LHIM89Xpj_mZvqqCQnH,pm__8zlSpb2Hixod149p2zadR);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=NULL;PmBoolVector*
mc_FIRQmUoZ8GOih5Os6NY5A_=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
mc_F50LHIM89Xpj_mZvqqCQnH=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumCol,pm__8zlSpb2Hixod149p2zadR);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_FIRQmUoZ8GOih5Os6NY5A_,true);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_F50LHIM89Xpj_mZvqqCQnH,true);mc_F50LHIM89Xpj_mZvqqCQnH->mX[
pm_Fr_bHKkQKFWbfi50VWd5Pw]=false;result=mc_F6NuiNPSsu0yf1TluQ0__s(
mc_FVG9mW_iV00Sd5jvvtdbAo,mc_FIRQmUoZ8GOih5Os6NY5A_,mc_F50LHIM89Xpj_mZvqqCQnH,
pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(mc_FIRQmUoZ8GOih5Os6NY5A_
,pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(
mc_F50LHIM89Xpj_mZvqqCQnH,pm__8zlSpb2Hixod149p2zadR);return result;}
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR){mc__mbv8xxcLWlA_qjxkZ_Zr3*result=NULL;PmBoolVector*
mc_FIRQmUoZ8GOih5Os6NY5A_=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumRow,pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
mc_F50LHIM89Xpj_mZvqqCQnH=pm__jbisDMumXdocXANx5LhhY(mc_FVG9mW_iV00Sd5jvvtdbAo
->mPattern->mNumCol,pm__8zlSpb2Hixod149p2zadR);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_FIRQmUoZ8GOih5Os6NY5A_,true);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_F50LHIM89Xpj_mZvqqCQnH,true);mc_FIRQmUoZ8GOih5Os6NY5A_->mX[
pm_kplAJmOlA30feiNcOzi7oj]=false;result=mc_F6NuiNPSsu0yf1TluQ0__s(
mc_FVG9mW_iV00Sd5jvvtdbAo,mc_FIRQmUoZ8GOih5Os6NY5A_,mc_F50LHIM89Xpj_mZvqqCQnH,
pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(mc_FIRQmUoZ8GOih5Os6NY5A_
,pm__8zlSpb2Hixod149p2zadR);pm_VuaGyqV_9K0Ia9Qgn65rsj(
mc_F50LHIM89Xpj_mZvqqCQnH,pm__8zlSpb2Hixod149p2zadR);return result;}void
mc_kXL8zBVnOn4yZLHVqnqmYJ(mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,
PmAllocator*pm__8zlSpb2Hixod149p2zadR){pm_VYooJBURCwKrVu6RXzQZ_5(
mc__H_R6laiZnCcXyegjjDM0e->mPattern,pm__8zlSpb2Hixod149p2zadR);
pm_destroy_real_vector(mc__H_R6laiZnCcXyegjjDM0e->mPr,
pm__8zlSpb2Hixod149p2zadR);{void*const mc__ebelPZd73SLYueU295P3Q=(
mc__H_R6laiZnCcXyegjjDM0e);PmAllocator*const mc_F3hU8lEm6WC1eLjzk2uWjI=(
pm__8zlSpb2Hixod149p2zadR);if(mc__ebelPZd73SLYueU295P3Q){(
mc_F3hU8lEm6WC1eLjzk2uWjI)->mFreeFcn(mc_F3hU8lEm6WC1eLjzk2uWjI,
mc__ebelPZd73SLYueU295P3Q);}};}mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_VJSNkp4nxul3XLhr4R_sS6(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY){mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VgqbsB_3R4GTjLQeEYi1Qc
=mc_kSyG2aZimWxIhPxax8Yu0Z(((size_t)(((mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern)->
mJc[(mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern)->mNumCol])))-1,
mc_FVG9mW_iV00Sd5jvvtdbAo->mPattern->mNumRow,mc_FVG9mW_iV00Sd5jvvtdbAo->
mPattern->mNumCol,pm_FbYb_iLqY2hwZTVlVaiqJY);int32_T mc_kh3C5f6ZAPlGWXfJykpWPn
=0;size_t j=0;int32_T*mc_kXeDcvuOSpSqamcA4a5jc_=mc_FVG9mW_iV00Sd5jvvtdbAo->
mPattern->mJc;int32_T*mc_VEXzFHKjFN87iiOtLrddNz=mc_FVG9mW_iV00Sd5jvvtdbAo->
mPattern->mIr;real_T*mc_VlnhKi82gfCLgumIqeduOq=mc_FVG9mW_iV00Sd5jvvtdbAo->mPr
->mX;int32_T*mc__32hmUz_GWWHjPUY6P_T1j=mc_VgqbsB_3R4GTjLQeEYi1Qc->mPattern->
mJc;int32_T*mc_F1ZTBCwDtzChh1N54p9zlS=mc_VgqbsB_3R4GTjLQeEYi1Qc->mPattern->mIr
;real_T*mc_keN5V34CYLtSZedvskINtw=mc_VgqbsB_3R4GTjLQeEYi1Qc->mPr->mX;(void)0;;
(void)0;;for(j=0;j<mc_VgqbsB_3R4GTjLQeEYi1Qc->mPattern->mNumCol;j++){if(
mc_kXeDcvuOSpSqamcA4a5jc_[j]<=(int32_T)mc_FG9ZSShR1cC8i1m0e45L1r){
mc__32hmUz_GWWHjPUY6P_T1j[j]=mc_kXeDcvuOSpSqamcA4a5jc_[j];}else{
mc__32hmUz_GWWHjPUY6P_T1j[j]=mc_kXeDcvuOSpSqamcA4a5jc_[j]-1;}for(
mc_kh3C5f6ZAPlGWXfJykpWPn=mc_kXeDcvuOSpSqamcA4a5jc_[j];
mc_kh3C5f6ZAPlGWXfJykpWPn<mc_kXeDcvuOSpSqamcA4a5jc_[j+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){if(mc_kh3C5f6ZAPlGWXfJykpWPn<(int32_T)
mc_FG9ZSShR1cC8i1m0e45L1r){mc_F1ZTBCwDtzChh1N54p9zlS[mc_kh3C5f6ZAPlGWXfJykpWPn
]=mc_VEXzFHKjFN87iiOtLrddNz[mc_kh3C5f6ZAPlGWXfJykpWPn];
mc_keN5V34CYLtSZedvskINtw[mc_kh3C5f6ZAPlGWXfJykpWPn]=mc_VlnhKi82gfCLgumIqeduOq
[mc_kh3C5f6ZAPlGWXfJykpWPn];}else if(mc_kh3C5f6ZAPlGWXfJykpWPn>(int32_T)
mc_FG9ZSShR1cC8i1m0e45L1r){mc_F1ZTBCwDtzChh1N54p9zlS[mc_kh3C5f6ZAPlGWXfJykpWPn
-1]=mc_VEXzFHKjFN87iiOtLrddNz[mc_kh3C5f6ZAPlGWXfJykpWPn];
mc_keN5V34CYLtSZedvskINtw[mc_kh3C5f6ZAPlGWXfJykpWPn-1]=
mc_VlnhKi82gfCLgumIqeduOq[mc_kh3C5f6ZAPlGWXfJykpWPn];}}}return
mc_VgqbsB_3R4GTjLQeEYi1Qc;}mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY){size_t mc_kNgcOktCtQxdYedrGvFn5i=
mc__fQVSVSgEBG6fuximVFlkw(mc__XfQXtB6cfd9fyc_v3eEup->mPr);size_t
pm_kplAJmOlA30feiNcOzi7oj=mc__XfQXtB6cfd9fyc_v3eEup->mPattern->mNumRow;size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw=mc__XfQXtB6cfd9fyc_v3eEup->mPattern->mNumCol;real_T*
mc_VH3sQDvMfNxNgXo1Tb51rk=mc__XfQXtB6cfd9fyc_v3eEup->mPr->mX;int32_T*
mc_k60LrI_T5MS8Vm0DcJ5er_=mc__XfQXtB6cfd9fyc_v3eEup->mPattern->mJc;int32_T*
mc__CAMW9odIkti_D3RrC1Owk=mc__XfQXtB6cfd9fyc_v3eEup->mPattern->mIr;
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_V2mBNcV1EqCifyH9UdCbkF=mc_kSyG2aZimWxIhPxax8Yu0Z(
mc_kNgcOktCtQxdYedrGvFn5i,pm_kplAJmOlA30feiNcOzi7oj,pm_Fr_bHKkQKFWbfi50VWd5Pw,
pm_FbYb_iLqY2hwZTVlVaiqJY);real_T*mc_ko6nDrBMyMhBhuX_MVk79Z=
mc_V2mBNcV1EqCifyH9UdCbkF->mPr->mX;int32_T*mc__GCptdpoQo0g_XZLlPzjXr=
mc_V2mBNcV1EqCifyH9UdCbkF->mPattern->mJc;int32_T*mc_V3Qao0OrmzO8fLPp_ztxE2=
mc_V2mBNcV1EqCifyH9UdCbkF->mPattern->mIr;int32_T mc_Vndh5uAny9lHbuXtkvKc34=0;
size_t mc_F3V_jqB7s_xnVajoX_C4gF=0;size_t j=0;mc__GCptdpoQo0g_XZLlPzjXr[0]=0;
for(j=0;j<pm_Fr_bHKkQKFWbfi50VWd5Pw;j++){for(mc_Vndh5uAny9lHbuXtkvKc34=
mc_k60LrI_T5MS8Vm0DcJ5er_[j];mc_Vndh5uAny9lHbuXtkvKc34<
mc_k60LrI_T5MS8Vm0DcJ5er_[j+1];mc_Vndh5uAny9lHbuXtkvKc34++){if(
mc_VH3sQDvMfNxNgXo1Tb51rk[mc_Vndh5uAny9lHbuXtkvKc34]!=0){
mc_ko6nDrBMyMhBhuX_MVk79Z[mc_F3V_jqB7s_xnVajoX_C4gF]=mc_VH3sQDvMfNxNgXo1Tb51rk
[mc_Vndh5uAny9lHbuXtkvKc34];mc_V3Qao0OrmzO8fLPp_ztxE2[
mc_F3V_jqB7s_xnVajoX_C4gF]=mc__CAMW9odIkti_D3RrC1Owk[mc_Vndh5uAny9lHbuXtkvKc34
];mc_F3V_jqB7s_xnVajoX_C4gF++;}}mc__GCptdpoQo0g_XZLlPzjXr[j+1]=(int32_T)(
mc_F3V_jqB7s_xnVajoX_C4gF);}(void)0;;return mc_V2mBNcV1EqCifyH9UdCbkF;}
