#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
typedef struct mc_VJso_Ah_vRlyieKx7wwFZK{int32_T n;PmIntVector*
mc_F8fT7naL9bOcimTADCVzTC;PmIntVector*mc_VCVhWy_VaDhraHrlfFWxBa;}
mc_VJso_Ah_vRlyieKx7wwFZK;mc_VJso_Ah_vRlyieKx7wwFZK mc_FJkmPU3ICBClZLBjnANVUy(
PmSparsityPattern const*a);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct
mc_FhhCEjBpBR_Ib902GEVwnS{int32_T n;PmIntVector*mc_kYVhBJKlndKGi9KvU7lJMg;}
mc_FhhCEjBpBR_Ib902GEVwnS;mc_FhhCEjBpBR_Ib902GEVwnS mc__DL4NS9_g6GTieYrMwi7Ma(
PmSparsityPattern const*mc_VoTkdAz8Qxd2iDKiMSyIbK);
#include "pm_inline.h"
#include "pm_std.h"
typedef struct pm_V1heuUPdFYSBhXSTZrzev1{size_t mNumRow;size_t mNumCol;real_T*
mX;}pm_FMSUHHOOKD8acuFWLEq4lL;pm_FMSUHHOOKD8acuFWLEq4lL*
pm__IzxUodah3x2_u_ENKAuGk(size_t pm__6bYkkT4Shd0e1DZPlpqqb,size_t
pm__g5DiU2QzFtUiL4XoU6SMs,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_FMSUHHOOKD8acuFWLEq4lL*pm__vffvPR7IsS2XyyCPqmNPs(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
pm__uc9LGWqLf03gLt6Sr9mtw(pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VuZ05R76dw4R_5mH59xUl3(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60);size_t
pm_kXhhlZLW3c8yiTFYZWcurB(pm_FMSUHHOOKD8acuFWLEq4lL const*
pm_k5aqR5haGY_ZXuGDU2ua60);PMF_DEPLOY_STATIC real_T pm_VWoHHtf6OqO6YXA_khGhQm(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t
pm_kplAJmOlA30feiNcOzi7oj,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw){return
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow];}
PMF_DEPLOY_STATIC void pm_kzEZvMeJLvOmgX1qMXsT0P(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t pm_kplAJmOlA30feiNcOzi7oj,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,real_T pm_kpzAtHMD4_WnheH0UiioSE){
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow]=
pm_kpzAtHMD4_WnheH0UiioSE;}void pm_kqNP_VNVXgWGcLsAqt8n_A(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_kUO9H2UqXf8k_y6THPribZ,PmRealVector const*
pm_V9BoL4F3KMGcYqNc2RhxW_,PmSparsityPattern const*pm_FbpiqbN30g8sY9B6YI6RUP);
void pm_kRraI4tqfotp_aUXOIifb6(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,
pm_FMSUHHOOKD8acuFWLEq4lL const*src);boolean_T pm__DD6QRkN3jGod5UZotcfi8(
pm_FMSUHHOOKD8acuFWLEq4lL const*dst,pm_FMSUHHOOKD8acuFWLEq4lL const*src);
boolean_T pm__Wj7kGLfa8_wfmNCNFVchb(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);void
pm_VL4rp2NEaF8Tcu2gE6TeeU(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
mc__QFp_Gwyen4pg5YWQYpO3H(char const*mc__U8NYtiFyNpCjuJN65HCEo,PmRealVector
const*mc__LA_p_vKNdOf_an832S3i6,PmSparsityPattern const*
mc_FEnmBOZ5cfxL_y4SmwvqMI);void mc___0fsWZwiwCeiHr99h_pdS(char const*
mc__U8NYtiFyNpCjuJN65HCEo,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_kPF7K9YwQrlqYyhOzVDc9F);void mc_VVlY03tEyt8Te1_JAhPeqb(char const*
mc__U8NYtiFyNpCjuJN65HCEo,pm_FMSUHHOOKD8acuFWLEq4lL const*
pm_k5aqR5haGY_ZXuGDU2ua60);void mc_F_aDZE5jsQtShDKMpxPeT4(char const*
mc__U8NYtiFyNpCjuJN65HCEo,PmRealVector const*mc_kQcHGEyhefpmWPPKUJsLBB);void
mc_VrrTkw_etgSPcyaUfEsd2F(char const*mc__U8NYtiFyNpCjuJN65HCEo,PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd);void mc__OI_HwmeBECxi15PsgBd55(char const*
mc__U8NYtiFyNpCjuJN65HCEo,PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH);void
mc_VL29uTrWwttHayl9VA84sd(char const*mc__U8NYtiFyNpCjuJN65HCEo,double value);
static PmSparsityPattern*mc_FjqIWuVgNB4OjTDSjPGNCk(PmSparsityPattern const*
mc_VoTkdAz8Qxd2iDKiMSyIbK){PmSparsityPattern*mc_kRanJt7RZPtAdHDq07QECQ=NULL;
PmSparsityPattern*a=pm_FQMLyYzCQ5CtgHjze1nNJP(mc_VoTkdAz8Qxd2iDKiMSyIbK,
pm_default_allocator());PmSparsityPattern*mc_kutbbLKiKk43hyBnfSGAST=
mc_kAZzxJsz9tloc11S9uThaF(mc_VoTkdAz8Qxd2iDKiMSyIbK,pm_default_allocator());
mc_FY8ifnDZsXphdqo3UGrtOk(a,mc_VoTkdAz8Qxd2iDKiMSyIbK->mNumCol);
mc_kNxwVTI76g4kj9P52yKhA5(mc_kutbbLKiKk43hyBnfSGAST,mc_VoTkdAz8Qxd2iDKiMSyIbK
->mNumRow);mc_kRanJt7RZPtAdHDq07QECQ=mc_VI58f6RQKXS_Y5sclnoOPT(a,
mc_kutbbLKiKk43hyBnfSGAST,pm_default_allocator());pm_VYooJBURCwKrVu6RXzQZ_5(a,
pm_default_allocator());pm_VYooJBURCwKrVu6RXzQZ_5(mc_kutbbLKiKk43hyBnfSGAST,
pm_default_allocator());return mc_kRanJt7RZPtAdHDq07QECQ;}static PmIntVector*
mc_FW8wLUMz64CNheemHkGnJv(PmIntVector const*mc__XfQXtB6cfd9fyc_v3eEup,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq){PmIntVector
mc_Fk2O4u6vQUpibmbv8Kjgnn;mc_Fk2O4u6vQUpibmbv8Kjgnn.mX=
mc__XfQXtB6cfd9fyc_v3eEup->mX+mc_Fyss_XM3F_C4dm6IKoDw4G;
mc_Fk2O4u6vQUpibmbv8Kjgnn.mN=mc_Vs6xonQX17Krc5vXv8T_zq-
mc_Fyss_XM3F_C4dm6IKoDw4G;return pm__fSS_VMqhWlobeqe6mQF_x(&
mc_Fk2O4u6vQUpibmbv8Kjgnn,pm_default_allocator());}mc_VJso_Ah_vRlyieKx7wwFZK
mc_FJkmPU3ICBClZLBjnANVUy(PmSparsityPattern const*a){PmSparsityPattern*
mc_kRanJt7RZPtAdHDq07QECQ=mc_FjqIWuVgNB4OjTDSjPGNCk(a);
mc_FhhCEjBpBR_Ib902GEVwnS mc_Fet2g81LNVG6_mJHNhUAfo=mc__DL4NS9_g6GTieYrMwi7Ma(
mc_kRanJt7RZPtAdHDq07QECQ);mc_VJso_Ah_vRlyieKx7wwFZK mc_V2mBNcV1EqCifyH9UdCbkF
;mc_V2mBNcV1EqCifyH9UdCbkF.n=mc_Fet2g81LNVG6_mJHNhUAfo.n;
mc_V2mBNcV1EqCifyH9UdCbkF.mc_VCVhWy_VaDhraHrlfFWxBa=mc_FW8wLUMz64CNheemHkGnJv(
mc_Fet2g81LNVG6_mJHNhUAfo.mc_kYVhBJKlndKGi9KvU7lJMg,0,a->mNumCol);
mc_V2mBNcV1EqCifyH9UdCbkF.mc_F8fT7naL9bOcimTADCVzTC=mc_FW8wLUMz64CNheemHkGnJv(
mc_Fet2g81LNVG6_mJHNhUAfo.mc_kYVhBJKlndKGi9KvU7lJMg,a->mNumCol,
mc_Fet2g81LNVG6_mJHNhUAfo.mc_kYVhBJKlndKGi9KvU7lJMg->mN);pm_destroy_int_vector
(mc_Fet2g81LNVG6_mJHNhUAfo.mc_kYVhBJKlndKGi9KvU7lJMg,pm_default_allocator());
pm_VYooJBURCwKrVu6RXzQZ_5(mc_kRanJt7RZPtAdHDq07QECQ,pm_default_allocator());
return mc_V2mBNcV1EqCifyH9UdCbkF;}
