#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_FzXHxaC_zhO_j9ob7zq7Cu(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc__4fFDnwFhbSuaLZ4NJB06a(PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,void
const*mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc_Vl4aaEoJK_KwYaROiytCdQ(PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,void const*
mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc_keWxvg6kivCmgu_AS8haey(PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,
McMatrixFunction*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct mc_VJso_Ah_vRlyieKx7wwFZK{int32_T n;
PmIntVector*mc_F8fT7naL9bOcimTADCVzTC;PmIntVector*mc_VCVhWy_VaDhraHrlfFWxBa;}
mc_VJso_Ah_vRlyieKx7wwFZK;mc_VJso_Ah_vRlyieKx7wwFZK mc_FJkmPU3ICBClZLBjnANVUy(
PmSparsityPattern const*a);
#include "pm_std.h"
#include "mc_std.h"
PmfMessageId mc_kfurBusHpmK3ii_yoisMKW(PmSparsityPattern**
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector**mc_FXE5BOU2zapujDAvVByFCm,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_V8ujEMKrDU8Q_mvu4yja1b,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);typedef struct
mc_FR4LZYN36HhAbXQciJKg4b mc_kbNZS6WABdpGXqIUWG8uHD;typedef struct
mc_F4xoGyxlc8C2i1wN43AI_h mc_VvIMaZZGi8CxWLrLDuE1VI;struct
mc_F4xoGyxlc8C2i1wN43AI_h{mc_kbNZS6WABdpGXqIUWG8uHD*mPrivateData;
McLinearAlgebraStatus(*mFactor)(mc_VvIMaZZGi8CxWLrLDuE1VI*,real_T const*);
PmfMessageId(*mSolve)(mc_VvIMaZZGi8CxWLrLDuE1VI*mc__GvuTmhLl7xoeDFnehgZw6,
PmSparsityPattern**mc_kHHEpbrdfIWJVHI2ZlxK22,PmRealVector**
mc_k3a0Qu5k3mdvXmV5mJLkVI,PmSparsityPattern*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector*mc_FXE5BOU2zapujDAvVByFCm);size_t(*mMemusage)(
mc_VvIMaZZGi8CxWLrLDuE1VI const*);void(*mDestructor)(mc_VvIMaZZGi8CxWLrLDuE1VI
*);};McLinearAlgebraStatus mc_FhCkJRmjeCKncXSqcrUlnc(mc_VvIMaZZGi8CxWLrLDuE1VI
**mc__xkURRHAa0_mdT34ydcjaI,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ)
;typedef struct mc___xTPDvXle0zj1HyArTk27{PmIntVector*
mc__SrF0Qn2APpDVy1HnpNaK7;PmSparsityPattern*mPattern;PmRealVector*mPr;
PmSparsityPattern*mc_kVLEUr1XKT86e9oGvvBBV9;PmRealVector*
mc_FtAdOCHmb6_Uga51VmRFLf;PmRealVector*mc_VT13oevJOHdChicXKgnfwR;PmRealVector*
mc_k325pLzTp_Oi_yMqrStYWO;PmIntVector*mc_FWIq9HXon08PVLt_4VRF_g;}
mc__33ABnrYgu_wa9g7oGrL2S;struct mc_kIf5GUUnTAOChauG3_6hhe{PmAllocator*
mc_Ff9S1xA4Ip4ZXeljM4_eEa;McMatrixFunction*mc__uIYeNLSnHGRZXhjsXLvL4;
PmRealVector*mc_FzZDAMHNwclliim1X7UY61;int32_T mc_kSCCKXg1HSObVi4S3Ltkz7;
mc__33ABnrYgu_wa9g7oGrL2S*mc_Fba3IHq_b4S2cDOwAhMU51;PmSparsityPattern*
mc_VENzi4QhQmSfiTAPZFGXMJ;};static void mc_Fc9IXxU_1h_Bjiri1cO30T(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK){int32_T
mc_kYpLAaqSWY4kW5V2RO5Kvt;(*((mc__d1alWYexptL_X5HTFhbNK->
mc__uIYeNLSnHGRZXhjsXLvL4)->mc_VAvAkWmhpT_WWme_3E1U91))((
mc_kDRphcAfRHSbf1ZLKEDW9k),(mc__d1alWYexptL_X5HTFhbNK->
mc_FzZDAMHNwclliim1X7UY61),((mc__d1alWYexptL_X5HTFhbNK->
mc__uIYeNLSnHGRZXhjsXLvL4)->mc_ko6_hiERTRldgDROOJBQCH));for(
mc_kYpLAaqSWY4kW5V2RO5Kvt=0;mc_kYpLAaqSWY4kW5V2RO5Kvt<
mc__d1alWYexptL_X5HTFhbNK->mc_kSCCKXg1HSObVi4S3Ltkz7;mc_kYpLAaqSWY4kW5V2RO5Kvt
++){PmfMessageId id;PmSparsityPattern*mc__lvtKVZR4zCv_D_Nbrh4eH=NULL;
PmRealVector*mc_V6FhGIVTzpShcDJLWyanvy=NULL;mc__33ABnrYgu_wa9g7oGrL2S const*
mc_kozcyYkxMvOHfeg9l7McOP= &mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51[mc_kYpLAaqSWY4kW5V2RO5Kvt];size_t j;(void)0;;(void)0
;;for(j=0;j<mc_kozcyYkxMvOHfeg9l7McOP->mc__SrF0Qn2APpDVy1HnpNaK7->mN;j++){
mc_kozcyYkxMvOHfeg9l7McOP->mPr->mX[j]=mc__d1alWYexptL_X5HTFhbNK->
mc_FzZDAMHNwclliim1X7UY61->mX[mc_kozcyYkxMvOHfeg9l7McOP->
mc__SrF0Qn2APpDVy1HnpNaK7->mX[j]];}id=mc_kfurBusHpmK3ii_yoisMKW(&
mc__lvtKVZR4zCv_D_Nbrh4eH,&mc_V6FhGIVTzpShcDJLWyanvy,mc_kozcyYkxMvOHfeg9l7McOP
->mPattern,mc_kozcyYkxMvOHfeg9l7McOP->mPr,mc__d1alWYexptL_X5HTFhbNK->
mc_Ff9S1xA4Ip4ZXeljM4_eEa);if(id!=NULL){mc__dsFCQJjA6p_j1tGhi2wWe(
mc_VgqbsB_3R4GTjLQeEYi1Qc,pmf_get_nan());return;}mc__8x7kz_627_gXDli_FJo22(
mc_kozcyYkxMvOHfeg9l7McOP->mc_VT13oevJOHdChicXKgnfwR,mc_kozcyYkxMvOHfeg9l7McOP
->mc_kVLEUr1XKT86e9oGvvBBV9,mc_kozcyYkxMvOHfeg9l7McOP->
mc_FtAdOCHmb6_Uga51VmRFLf,mc_kozcyYkxMvOHfeg9l7McOP->mc_kVLEUr1XKT86e9oGvvBBV9
,mc_V6FhGIVTzpShcDJLWyanvy,mc__lvtKVZR4zCv_D_Nbrh4eH,mc_kozcyYkxMvOHfeg9l7McOP
->mc_k325pLzTp_Oi_yMqrStYWO);pm_VYooJBURCwKrVu6RXzQZ_5(
mc__lvtKVZR4zCv_D_Nbrh4eH,mc__d1alWYexptL_X5HTFhbNK->mc_Ff9S1xA4Ip4ZXeljM4_eEa
);pm_destroy_real_vector(mc_V6FhGIVTzpShcDJLWyanvy,mc__d1alWYexptL_X5HTFhbNK->
mc_Ff9S1xA4Ip4ZXeljM4_eEa);for(j=0;j<mc_kozcyYkxMvOHfeg9l7McOP->
mc_FWIq9HXon08PVLt_4VRF_g->mN;j++){mc_VgqbsB_3R4GTjLQeEYi1Qc->mX[
mc_kozcyYkxMvOHfeg9l7McOP->mc_FWIq9HXon08PVLt_4VRF_g->mX[j]]=
mc_kozcyYkxMvOHfeg9l7McOP->mc_VT13oevJOHdChicXKgnfwR->mX[j];}}}static void
const*mc_Vn7PrqSXS40IjTtZ0NLZ7d(McMatrixFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ){return(mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->mc__uIYeNLSnHGRZXhjsXLvL4)->
mc_FXz9GdGvpOKnh5e2dYstBe((mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->mc__uIYeNLSnHGRZXhjsXLvL4));}static void
mc_FQyGP_lT4gxSjD_2E_04SC(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ){
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK=mc_k0CXwzVaibdnZiGUCx6PMZ
->mc_ko6_hiERTRldgDROOJBQCH;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc__d1alWYexptL_X5HTFhbNK->mc_Ff9S1xA4Ip4ZXeljM4_eEa;int32_T
mc_kYpLAaqSWY4kW5V2RO5Kvt;(mc__d1alWYexptL_X5HTFhbNK->
mc__uIYeNLSnHGRZXhjsXLvL4)->mDestroy(mc__d1alWYexptL_X5HTFhbNK->
mc__uIYeNLSnHGRZXhjsXLvL4);pm_destroy_real_vector(mc__d1alWYexptL_X5HTFhbNK->
mc_FzZDAMHNwclliim1X7UY61,pm_FbYb_iLqY2hwZTVlVaiqJY);for(
mc_kYpLAaqSWY4kW5V2RO5Kvt=0;mc_kYpLAaqSWY4kW5V2RO5Kvt<
mc__d1alWYexptL_X5HTFhbNK->mc_kSCCKXg1HSObVi4S3Ltkz7;mc_kYpLAaqSWY4kW5V2RO5Kvt
++){mc__33ABnrYgu_wa9g7oGrL2S*mc_kozcyYkxMvOHfeg9l7McOP= &
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[mc_kYpLAaqSWY4kW5V2RO5Kvt
];pm_destroy_int_vector(mc_kozcyYkxMvOHfeg9l7McOP->mc__SrF0Qn2APpDVy1HnpNaK7,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_VYooJBURCwKrVu6RXzQZ_5(mc_kozcyYkxMvOHfeg9l7McOP
->mPattern,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(
mc_kozcyYkxMvOHfeg9l7McOP->mPr,pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_VYooJBURCwKrVu6RXzQZ_5(mc_kozcyYkxMvOHfeg9l7McOP->mc_kVLEUr1XKT86e9oGvvBBV9
,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(mc_kozcyYkxMvOHfeg9l7McOP->
mc_FtAdOCHmb6_Uga51VmRFLf,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(
mc_kozcyYkxMvOHfeg9l7McOP->mc_VT13oevJOHdChicXKgnfwR,pm_FbYb_iLqY2hwZTVlVaiqJY
);pm_destroy_real_vector(mc_kozcyYkxMvOHfeg9l7McOP->mc_k325pLzTp_Oi_yMqrStYWO,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(mc_kozcyYkxMvOHfeg9l7McOP->
mc_FWIq9HXon08PVLt_4VRF_g,pm_FbYb_iLqY2hwZTVlVaiqJY);}{void*const
mc__5J972Qn2CWdf1Wj2K2xRj=(mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51);PmAllocator*const mc_VTN0iHlnx6tajPDf992baT=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc__5J972Qn2CWdf1Wj2K2xRj){(
mc_VTN0iHlnx6tajPDf992baT)->mFreeFcn(mc_VTN0iHlnx6tajPDf992baT,
mc__5J972Qn2CWdf1Wj2K2xRj);}};pm_VYooJBURCwKrVu6RXzQZ_5(
mc__d1alWYexptL_X5HTFhbNK->mc_VENzi4QhQmSfiTAPZFGXMJ,pm_FbYb_iLqY2hwZTVlVaiqJY
);{void*const mc_kwJePbWLoX44fyLwt7Iz2Z=(mc__d1alWYexptL_X5HTFhbNK);
PmAllocator*const mc_VlRVgD7etLxNf1jy5x1G_L=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_kwJePbWLoX44fyLwt7Iz2Z){(mc_VlRVgD7etLxNf1jy5x1G_L)->mFreeFcn(
mc_VlRVgD7etLxNf1jy5x1G_L,mc_kwJePbWLoX44fyLwt7Iz2Z);}};{void*const
mc_Vt_WSJlikHhihPXzNSjSca=(mc_k0CXwzVaibdnZiGUCx6PMZ);PmAllocator*const
mc_V4Hgw40h1xCGjDqDWysRpC=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_Vt_WSJlikHhihPXzNSjSca){(mc_V4Hgw40h1xCGjDqDWysRpC)->mFreeFcn(
mc_V4Hgw40h1xCGjDqDWysRpC,mc_Vt_WSJlikHhihPXzNSjSca);}};}static PmIntVector*
mc_k4oShbwDhr_ydmmzwDBoq2(PmIntVector const*mc_kYVhBJKlndKGi9KvU7lJMg,int32_T n
){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=pm_default_allocator();PmIntVector*
mc_Vd_OBSshLQOXau87ArpN_L=pm_create_int_vector(n,pm_FbYb_iLqY2hwZTVlVaiqJY);
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF=pm__fSS_VMqhWlobeqe6mQF_x(
mc_kYVhBJKlndKGi9KvU7lJMg,pm_FbYb_iLqY2hwZTVlVaiqJY);size_t i;for(i=0;i<
mc_V2mBNcV1EqCifyH9UdCbkF->mN;i++){mc_V2mBNcV1EqCifyH9UdCbkF->mX[i]=
mc_Vd_OBSshLQOXau87ArpN_L->mX[mc_kYVhBJKlndKGi9KvU7lJMg->mX[i]];
mc_Vd_OBSshLQOXau87ArpN_L->mX[mc_kYVhBJKlndKGi9KvU7lJMg->mX[i]]++;}
pm_destroy_int_vector(mc_Vd_OBSshLQOXau87ArpN_L,pm_FbYb_iLqY2hwZTVlVaiqJY);
return mc_V2mBNcV1EqCifyH9UdCbkF;}static McMatrixFunction*
mc_FWvQNgdvF6lJdmXLMEz4XH(McMatrixFunction*mc_VczxSHedl4K3YeYnoZVuMW,
mc_VJso_Ah_vRlyieKx7wwFZK mc_Fet2g81LNVG6_mJHNhUAfo,PmIntVector*
mc_Vd_OBSshLQOXau87ArpN_L){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
pm_default_allocator();McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ=(
McMatrixFunction*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(McMatrixFunction)),(1))));
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK=(mc_k3jb_ssG91tZa9bwLjlWEj
*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
sizeof(mc_k3jb_ssG91tZa9bwLjlWEj)),(1))));PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ=mc_VczxSHedl4K3YeYnoZVuMW->mc_kjWUPQN_Ui4d_enzFJIsF_
;int32_T j,mc_kh3C5f6ZAPlGWXfJykpWPn;PmIntVector*mc__qHZ_V9ajmO6aqKi26lC7w=
mc_k4oShbwDhr_ydmmzwDBoq2(mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC,
mc_Fet2g81LNVG6_mJHNhUAfo.n);PmIntVector*mc_VqcH9X3Ca5CpiDwqzVo5wq=
mc_k4oShbwDhr_ydmmzwDBoq2(mc_Fet2g81LNVG6_mJHNhUAfo.mc_VCVhWy_VaDhraHrlfFWxBa,
mc_Fet2g81LNVG6_mJHNhUAfo.n);PmIntVector**mc_kpL4jj6cUEhYd15xXOs71t=NULL;
PmIntVector*mc_kNgcOktCtQxdYedrGvFn5i=pm_create_int_vector(
mc_Fet2g81LNVG6_mJHNhUAfo.n,pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY
;mc__d1alWYexptL_X5HTFhbNK->mc__uIYeNLSnHGRZXhjsXLvL4=
mc_VczxSHedl4K3YeYnoZVuMW;mc__d1alWYexptL_X5HTFhbNK->mc_FzZDAMHNwclliim1X7UY61
=pm_create_real_vector(((size_t)(((mc__d1alWYexptL_X5HTFhbNK->
mc__uIYeNLSnHGRZXhjsXLvL4->mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(
mc__d1alWYexptL_X5HTFhbNK->mc__uIYeNLSnHGRZXhjsXLvL4->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_kSCCKXg1HSObVi4S3Ltkz7=mc_Fet2g81LNVG6_mJHNhUAfo
.n;for(j=0;j<(int32_T)(mc__srK5LmyWw42ZyPnbOWDWJ->mNumCol);++j){for(
mc_kh3C5f6ZAPlGWXfJykpWPn=mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j];
mc_kh3C5f6ZAPlGWXfJykpWPn<mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){(void)0;;mc_kNgcOktCtQxdYedrGvFn5i->mX[
mc_Fet2g81LNVG6_mJHNhUAfo.mc_VCVhWy_VaDhraHrlfFWxBa->mX[j]]++;}}
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51=(
mc__33ABnrYgu_wa9g7oGrL2S*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc__33ABnrYgu_wa9g7oGrL2S)),(
mc_Fet2g81LNVG6_mJHNhUAfo.n))));for(j=0;j<mc_Fet2g81LNVG6_mJHNhUAfo.n;++j){
size_t mc__tkMDyOa8FlSW1FLI7_mxY=mc_Vd_OBSshLQOXau87ArpN_L->mX[j]*
mc_Vd_OBSshLQOXau87ArpN_L->mX[j];mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51[j].mc__SrF0Qn2APpDVy1HnpNaK7=pm_create_int_vector(
mc_kNgcOktCtQxdYedrGvFn5i->mX[j],pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].mPattern=
pm_create_sparsity_pattern(mc_kNgcOktCtQxdYedrGvFn5i->mX[j],
mc_Vd_OBSshLQOXau87ArpN_L->mX[j],mc_Vd_OBSshLQOXau87ArpN_L->mX[j],
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51[j].mPr=pm_create_real_vector(
mc_kNgcOktCtQxdYedrGvFn5i->mX[j],pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].
mc_kVLEUr1XKT86e9oGvvBBV9=pm__YwdRBXissh3bPWPl30Fpe(mc_Vd_OBSshLQOXau87ArpN_L
->mX[j],mc_Vd_OBSshLQOXau87ArpN_L->mX[j],pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].
mc_FtAdOCHmb6_Uga51VmRFLf=pm_create_real_vector(mc__tkMDyOa8FlSW1FLI7_mxY,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51[j].mc_VT13oevJOHdChicXKgnfwR=pm_create_real_vector(
mc__tkMDyOa8FlSW1FLI7_mxY,pm_FbYb_iLqY2hwZTVlVaiqJY);mc__d1alWYexptL_X5HTFhbNK
->mc_Fba3IHq_b4S2cDOwAhMU51[j].mc_k325pLzTp_Oi_yMqrStYWO=pm_create_real_vector
(mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].
mc_kVLEUr1XKT86e9oGvvBBV9->mNumRow,pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].
mc_FWIq9HXon08PVLt_4VRF_g=pm_create_int_vector(mc__tkMDyOa8FlSW1FLI7_mxY,
pm_FbYb_iLqY2hwZTVlVaiqJY);}mc_k9wkPuvMCi4DY1yebDQPHf(
mc_kNgcOktCtQxdYedrGvFn5i);for(j=0;j<(int32_T)(mc__srK5LmyWw42ZyPnbOWDWJ->
mNumCol);++j){int32_T const mc_kYpLAaqSWY4kW5V2RO5Kvt=
mc_Fet2g81LNVG6_mJHNhUAfo.mc_VCVhWy_VaDhraHrlfFWxBa->mX[j];
mc__33ABnrYgu_wa9g7oGrL2S const*mc_kozcyYkxMvOHfeg9l7McOP= &
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[mc_kYpLAaqSWY4kW5V2RO5Kvt
];for(mc_kh3C5f6ZAPlGWXfJykpWPn=mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j];
mc_kh3C5f6ZAPlGWXfJykpWPn<mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){mc_kozcyYkxMvOHfeg9l7McOP->
mc__SrF0Qn2APpDVy1HnpNaK7->mX[mc_kNgcOktCtQxdYedrGvFn5i->mX[
mc_kYpLAaqSWY4kW5V2RO5Kvt]]=mc_kh3C5f6ZAPlGWXfJykpWPn;
mc_kozcyYkxMvOHfeg9l7McOP->mPattern->mIr[mc_kNgcOktCtQxdYedrGvFn5i->mX[
mc_kYpLAaqSWY4kW5V2RO5Kvt]]=mc__qHZ_V9ajmO6aqKi26lC7w->mX[
mc__srK5LmyWw42ZyPnbOWDWJ->mIr[mc_kh3C5f6ZAPlGWXfJykpWPn]];
mc_kNgcOktCtQxdYedrGvFn5i->mX[mc_kYpLAaqSWY4kW5V2RO5Kvt]++;}
mc_kozcyYkxMvOHfeg9l7McOP->mPattern->mJc[mc_VqcH9X3Ca5CpiDwqzVo5wq->mX[j]+1]=
mc_kozcyYkxMvOHfeg9l7McOP->mPattern->mJc[mc_VqcH9X3Ca5CpiDwqzVo5wq->mX[j]]+(
mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j+1]-mc__srK5LmyWw42ZyPnbOWDWJ->mJc[j]);}{
PmIntVector*mc_V2_EVLIAs84gbaujdpLUkG=pm_create_int_vector(
mc_Fet2g81LNVG6_mJHNhUAfo.n,pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kpL4jj6cUEhYd15xXOs71t=(PmIntVector**)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->
mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(PmIntVector*)),(
mc_Fet2g81LNVG6_mJHNhUAfo.n))));for(j=0;j<mc_Fet2g81LNVG6_mJHNhUAfo.n;++j){
mc__33ABnrYgu_wa9g7oGrL2S const*mc_kozcyYkxMvOHfeg9l7McOP= &
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j];
mc_kpL4jj6cUEhYd15xXOs71t[j]=pm_create_int_vector(mc_kozcyYkxMvOHfeg9l7McOP->
mPattern->mNumCol,pm_FbYb_iLqY2hwZTVlVaiqJY);}for(j=0;j<(int32_T)(
mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC->mN);++j){int32_T const
mc_kYpLAaqSWY4kW5V2RO5Kvt=mc_Fet2g81LNVG6_mJHNhUAfo.mc_VCVhWy_VaDhraHrlfFWxBa
->mX[j];mc_kpL4jj6cUEhYd15xXOs71t[mc_kYpLAaqSWY4kW5V2RO5Kvt]->mX[
mc_V2_EVLIAs84gbaujdpLUkG->mX[mc_kYpLAaqSWY4kW5V2RO5Kvt]]=j;
mc_V2_EVLIAs84gbaujdpLUkG->mX[mc_kYpLAaqSWY4kW5V2RO5Kvt]++;}
pm_destroy_int_vector(mc_V2_EVLIAs84gbaujdpLUkG,pm_FbYb_iLqY2hwZTVlVaiqJY);}{
int32_T mc__s27530hBVSMaiXbF30MQY=0;for(j=0;j<mc_Fet2g81LNVG6_mJHNhUAfo.n;++j)
{mc__s27530hBVSMaiXbF30MQY+=((size_t)(((mc__d1alWYexptL_X5HTFhbNK->
mc_Fba3IHq_b4S2cDOwAhMU51[j].mc_kVLEUr1XKT86e9oGvvBBV9)->mJc[(
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[j].
mc_kVLEUr1XKT86e9oGvvBBV9)->mNumCol])));}mc__d1alWYexptL_X5HTFhbNK->
mc_VENzi4QhQmSfiTAPZFGXMJ=pm_create_sparsity_pattern(mc__s27530hBVSMaiXbF30MQY
,mc__srK5LmyWw42ZyPnbOWDWJ->mNumCol,mc__srK5LmyWw42ZyPnbOWDWJ->mNumRow,
pm_FbYb_iLqY2hwZTVlVaiqJY);}{int32_T mc__BwCbGCDlrx2gDK5rof3H8=0;
mc_k9wkPuvMCi4DY1yebDQPHf(mc_kNgcOktCtQxdYedrGvFn5i);for(j=0;j<(int32_T)(
mc__srK5LmyWw42ZyPnbOWDWJ->mNumCol);++j){int32_T const
mc_kYpLAaqSWY4kW5V2RO5Kvt=mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC
->mX[j];mc__33ABnrYgu_wa9g7oGrL2S const*mc_kozcyYkxMvOHfeg9l7McOP= &
mc__d1alWYexptL_X5HTFhbNK->mc_Fba3IHq_b4S2cDOwAhMU51[mc_kYpLAaqSWY4kW5V2RO5Kvt
];for(mc_kh3C5f6ZAPlGWXfJykpWPn=0;mc_kh3C5f6ZAPlGWXfJykpWPn<(int32_T)(
mc_kozcyYkxMvOHfeg9l7McOP->mPattern->mNumRow);mc_kh3C5f6ZAPlGWXfJykpWPn++){
mc__d1alWYexptL_X5HTFhbNK->mc_VENzi4QhQmSfiTAPZFGXMJ->mIr[
mc__BwCbGCDlrx2gDK5rof3H8]=mc_kpL4jj6cUEhYd15xXOs71t[mc_kYpLAaqSWY4kW5V2RO5Kvt
]->mX[mc_kh3C5f6ZAPlGWXfJykpWPn];mc_kozcyYkxMvOHfeg9l7McOP->
mc_FWIq9HXon08PVLt_4VRF_g->mX[mc_kNgcOktCtQxdYedrGvFn5i->mX[
mc_kYpLAaqSWY4kW5V2RO5Kvt]]=mc__BwCbGCDlrx2gDK5rof3H8;
mc__BwCbGCDlrx2gDK5rof3H8++;mc_kNgcOktCtQxdYedrGvFn5i->mX[
mc_kYpLAaqSWY4kW5V2RO5Kvt]++;}mc__d1alWYexptL_X5HTFhbNK->
mc_VENzi4QhQmSfiTAPZFGXMJ->mJc[j+1]=mc__BwCbGCDlrx2gDK5rof3H8;}}
pm_destroy_int_vector(mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(mc_Fet2g81LNVG6_mJHNhUAfo.
mc_VCVhWy_VaDhraHrlfFWxBa,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(
mc_Vd_OBSshLQOXau87ArpN_L,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(
mc__qHZ_V9ajmO6aqKi26lC7w,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(
mc_VqcH9X3Ca5CpiDwqzVo5wq,pm_FbYb_iLqY2hwZTVlVaiqJY);for(j=0;j<
mc_Fet2g81LNVG6_mJHNhUAfo.n;++j){pm_destroy_int_vector(
mc_kpL4jj6cUEhYd15xXOs71t[j],pm_FbYb_iLqY2hwZTVlVaiqJY);}{void*const
mc__1CTTtF8r8OcYTIu_i4CLv=(mc_kpL4jj6cUEhYd15xXOs71t);PmAllocator*const
mc__PIOn6pOvnhjY5EDVcnEOS=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc__1CTTtF8r8OcYTIu_i4CLv){(mc__PIOn6pOvnhjY5EDVcnEOS)->mFreeFcn(
mc__PIOn6pOvnhjY5EDVcnEOS,mc__1CTTtF8r8OcYTIu_i4CLv);}};pm_destroy_int_vector(
mc_kNgcOktCtQxdYedrGvFn5i,pm_FbYb_iLqY2hwZTVlVaiqJY);mc_k0CXwzVaibdnZiGUCx6PMZ
->mc_ko6_hiERTRldgDROOJBQCH=mc__d1alWYexptL_X5HTFhbNK;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_kjWUPQN_Ui4d_enzFJIsF_=mc__d1alWYexptL_X5HTFhbNK
->mc_VENzi4QhQmSfiTAPZFGXMJ;mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_VAvAkWmhpT_WWme_3E1U91= &mc_Fc9IXxU_1h_Bjiri1cO30T;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_FXz9GdGvpOKnh5e2dYstBe= &
mc_Vn7PrqSXS40IjTtZ0NLZ7d;mc_k0CXwzVaibdnZiGUCx6PMZ->mDestroy= &
mc_FQyGP_lT4gxSjD_2E_04SC;return mc_k0CXwzVaibdnZiGUCx6PMZ;}static PmIntVector
*mc_kFvMfkZwput_Y5hQQyjtlr(mc_VJso_Ah_vRlyieKx7wwFZK mc_Fet2g81LNVG6_mJHNhUAfo
){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=pm_default_allocator();PmIntVector*
mc_Vd_OBSshLQOXau87ArpN_L=pm_create_int_vector(mc_Fet2g81LNVG6_mJHNhUAfo.n,
pm_FbYb_iLqY2hwZTVlVaiqJY);PmIntVector*mc_Fk2O4u6vQUpibmbv8Kjgnn=NULL;size_t i
=0;boolean_T mc_FfwLjsg_YDO8YL8NmQp_T_=false;for(i=0;i<
mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC->mN;++i){
mc_Vd_OBSshLQOXau87ArpN_L->mX[mc_Fet2g81LNVG6_mJHNhUAfo.
mc_F8fT7naL9bOcimTADCVzTC->mX[i]]++;}mc_Fk2O4u6vQUpibmbv8Kjgnn=
pm__fSS_VMqhWlobeqe6mQF_x(mc_Vd_OBSshLQOXau87ArpN_L,pm_FbYb_iLqY2hwZTVlVaiqJY)
;for(i=0;i<mc_Fet2g81LNVG6_mJHNhUAfo.mc_VCVhWy_VaDhraHrlfFWxBa->mN;++i){if(
mc_Fk2O4u6vQUpibmbv8Kjgnn->mX[mc_Fet2g81LNVG6_mJHNhUAfo.
mc_VCVhWy_VaDhraHrlfFWxBa->mX[i]]==0){mc_FfwLjsg_YDO8YL8NmQp_T_=true;}
mc_Fk2O4u6vQUpibmbv8Kjgnn->mX[mc_Fet2g81LNVG6_mJHNhUAfo.
mc_VCVhWy_VaDhraHrlfFWxBa->mX[i]]--;}for(i=0;i<mc_Fk2O4u6vQUpibmbv8Kjgnn->mN;
++i){if(mc_Fk2O4u6vQUpibmbv8Kjgnn->mX[i]>0){mc_FfwLjsg_YDO8YL8NmQp_T_=true;}}
pm_destroy_int_vector(mc_Fk2O4u6vQUpibmbv8Kjgnn,pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_FfwLjsg_YDO8YL8NmQp_T_){pm_destroy_int_vector(mc_Vd_OBSshLQOXau87ArpN_L,
pm_FbYb_iLqY2hwZTVlVaiqJY);return NULL;}else{return mc_Vd_OBSshLQOXau87ArpN_L;
}}McMatrixFunction*mc_FzXHxaC_zhO_j9ob7zq7Cu(McMatrixFunction*
mc_VczxSHedl4K3YeYnoZVuMW){(void)0;;{mc_VJso_Ah_vRlyieKx7wwFZK
mc_Fet2g81LNVG6_mJHNhUAfo=mc_FJkmPU3ICBClZLBjnANVUy(mc_VczxSHedl4K3YeYnoZVuMW
->mc_kjWUPQN_Ui4d_enzFJIsF_);PmIntVector*mc_Vd_OBSshLQOXau87ArpN_L=
mc_kFvMfkZwput_Y5hQQyjtlr(mc_Fet2g81LNVG6_mJHNhUAfo);if(
mc_Vd_OBSshLQOXau87ArpN_L==NULL){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
pm_default_allocator();size_t n=mc_VczxSHedl4K3YeYnoZVuMW->
mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow;PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ
=pm__TNI3M36rThlaTetY4tWiB(n,pm_FbYb_iLqY2hwZTVlVaiqJY);PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K=pm_create_real_vector(n,pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__dsFCQJjA6p_j1tGhi2wWe(mc_kVkvrfpzuVduaPTr5FLF8K,pmf_get_nan());
pm_destroy_int_vector(mc_Fet2g81LNVG6_mJHNhUAfo.mc_F8fT7naL9bOcimTADCVzTC,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_int_vector(mc_Fet2g81LNVG6_mJHNhUAfo.
mc_VCVhWy_VaDhraHrlfFWxBa,pm_FbYb_iLqY2hwZTVlVaiqJY);return
mc_keWxvg6kivCmgu_AS8haey(mc__srK5LmyWw42ZyPnbOWDWJ,mc_kVkvrfpzuVduaPTr5FLF8K,
mc_VczxSHedl4K3YeYnoZVuMW,pm_FbYb_iLqY2hwZTVlVaiqJY);}else{return
mc_FWvQNgdvF6lJdmXLMEz4XH(mc_VczxSHedl4K3YeYnoZVuMW,mc_Fet2g81LNVG6_mJHNhUAfo,
mc_Vd_OBSshLQOXau87ArpN_L);}}}
