#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_kv3fXx6PfXt7cekeoT00mk
mc_kgKqfPHHGatO_9OUxR4PRK;struct mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;
void(*mc_FapEct1OXaSugDZ6N_u_kA)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH);void(*
mc_FVdv01I3SEC4hD41rxmnRM)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,real_T
mc__d1alWYexptL_X5HTFhbNK);void(*mc_kPHJTxMUjl8Oi1EQSHes2Q)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);void(*
mc__WEKdqi2uo0m_Dm8w8T_ZO)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc__d1alWYexptL_X5HTFhbNK);};typedef struct mc__nZqLQp3m1lFaHyLAzyG2a
mc__39VLhR7TBCGYH016BQq8W;typedef struct mc__UzXDLpnAvdw_eUt0mYuul
mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct mc__sr5lnPbYjO_Wyo_mmPUmd
mc_Fw_IO5LchthA_LoeiSceRf;struct mc__sr5lnPbYjO_Wyo_mmPUmd{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc__dVSVIr5IcxYgT3A1aaohx
mc_FKEB_KeCGI_DXy1xGMMwkj;typedef struct mc_VCMrVs3_qch2e9_O4TE7vE
mc_F4w5DimUQvtpjap7_Ir11M;struct mc_VCMrVs3_qch2e9_O4TE7vE{
mc_FKEB_KeCGI_DXy1xGMMwkj*mPrivateData;mc__39VLhR7TBCGYH016BQq8W const*
mc_FI68gfOwQ4C_ZmAB_JXEM0;void(*mc_VvxtMKveGIdNXan8lRb_uv)(
mc_F4w5DimUQvtpjap7_Ir11M const*mc_kpyeXH2RWcWG_DVSgKEG_O,real_T s);void(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(mc_F4w5DimUQvtpjap7_Ir11M const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector*x);void(*mDestroy)(
mc_F4w5DimUQvtpjap7_Ir11M*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kaeFjqxw3yGp_TQOIqkvj3 mc_khpvnU9fUTWvV5q3NhO_yh;typedef struct
mc_kJ_0AbL6HDGofHdqgndENk mc_kuKO_mN0hQljfi2S3b5TKN;struct
mc_kJ_0AbL6HDGofHdqgndENk{mc_khpvnU9fUTWvV5q3NhO_yh*mPrivateData;
mc_F4w5DimUQvtpjap7_Ir11M*(*mc__B06nILrPXW_bPz__pLJwl)(
mc_kuKO_mN0hQljfi2S3b5TKN const*mc_FX_ivTD1E1K3Z16XUq1VHF,
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(
mc_kuKO_mN0hQljfi2S3b5TKN*mc_kpyeXH2RWcWG_DVSgKEG_O);};
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__XjXW_X3rjOsZ10IOexigE(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,mc_kuKO_mN0hQljfi2S3b5TKN*mc__Mrd3i9pD4hhcDdC7tyja7,
mc_kKrwrwNLgB_NYDY0UUZRVA*mc_FN7xLc4h1wtoW9h_uAsJ11,size_t
mc_kF77yGs8Y4pbZunORy8X8l,size_t mc__tsjAPDH6y0lc5lkf_keB1);
#include "math.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);typedef struct
mc_Var10krMyESoVH5ms3BC9B mc__WlvosIwzPCsYqQiQK98uS;typedef struct
mc_kqfi0XZ31I8oVa0UrBAUOQ mc__5DSuSOY5EGKVHbPTvScZ2;struct
mc_Var10krMyESoVH5ms3BC9B{void(*mc_VrNsQKHIiLOFaL3PHRFxZL)(
mc__WlvosIwzPCsYqQiQK98uS const*mc_kvQDtolRtcCacq65L23hPv);void(*
mc_kt9hW2swhpxchivzz5BlCP)(mc__WlvosIwzPCsYqQiQK98uS const*
mc_kvQDtolRtcCacq65L23hPv,real_T time,PmRealVector const*value);size_t(*
mc_F1CrZ_uwhg_eju4CALy3h1)(mc__WlvosIwzPCsYqQiQK98uS const*
mc_kvQDtolRtcCacq65L23hPv);void(*mc_ka3KJ9VlXFK0ZidY3O7sZM)(
mc__WlvosIwzPCsYqQiQK98uS const*mc_kvQDtolRtcCacq65L23hPv,size_t
mc_FruBC65sPgSaZ5e_Y8cbTC,real_T time,PmRealVector const*value);void(*mDestroy
)(mc__WlvosIwzPCsYqQiQK98uS*);size_t mc_kNhmJUZe0oOm_1XC7EH51R;
mc__5DSuSOY5EGKVHbPTvScZ2*mData;};mc__WlvosIwzPCsYqQiQK98uS*
mc_k43ukWhB7ctcYqEtIqIF2t(size_t mc_FDFXbMvo_20_WeM4X5aZux,size_t
mc_ksP_VoZ3t_SqgyYvFYlpj7,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);struct
mc_kesYKdRukKtCYLfoQ0YRJ5{struct{char const*mc__ZetJu9avwdPd5xPJYEDKv;}
mc_VnzOe8465jdG_axxqAa7xK;struct{char const*mc_Vw_h4iGOyYpSbHgncbpeJR;}
mc_FPG2IDtkW00qZuPcEPzdbQ;struct{char const*mc_VnFMFkYMV1hK_93KVSQlPS;char
const*mc_FiJyK1iSBtdCeX4lO2v9nY;char const*mc_VkxMYnjBAcGQaL_MMhf2c4;char const
*mc_VIVB1sZ6mPpEWqHtxlL_yx;char const*mc_VNex3Bmd_7loc1Aqi0L_UG;char const*
mc_FyMwcutNPwS6dy28GFjovq;char const*mc_kxY2G0anZa4pbmS3sSr4tQ;char const*
mc_kdx9sBpyxKhBiiNn9qNSJp;char const*mc__woIs8rUGsdSjmmPBvTUmN;}
mc_k1IEdrLtsfxw_XhxVjzMwW;};extern struct mc_kesYKdRukKtCYLfoQ0YRJ5
mc__oZL0AImZoh2ZTzHdubvRL;size_t mc_VG1y_LrErwtMc9AoQz7Nqj(real_T value,real_T
mc_kGgE55Nh9o0jfioSr_OONY,real_T mc_VVSC9LtbrC_kb15awLhs5p,size_t
mc_kFY5eMmSKnGdeHaIB_KZfR);struct mc_k577Fzud3mpCe91P_z0Qf_{PmAllocator*
mc_Ff9S1xA4Ip4ZXeljM4_eEa;mc_kuKO_mN0hQljfi2S3b5TKN*mc_k34_wY0IFRdbfHl_rltVwF;
mc_kKrwrwNLgB_NYDY0UUZRVA*mc_VMFiPDPJti80aLW2m1OHia;size_t
mc__NwRaGOaLsKY_5EufWPIPx;size_t mc_kNhmJUZe0oOm_1XC7EH51R;};struct
mc_FpSYgeBscUCg_qWX4io4Kb{PmAllocator*mc_Ff9S1xA4Ip4ZXeljM4_eEa;
mc_F4w5DimUQvtpjap7_Ir11M*mc__1zQKz51Xzpkfe0T1u5WXH;mc_kxnFIpkyuc0YdXbZO41ABc*
mc_VMFiPDPJti80aLW2m1OHia;mc__WlvosIwzPCsYqQiQK98uS*mc_kf9uxJXOkD_2ciMoq6ipi7;
size_t mc__NwRaGOaLsKY_5EufWPIPx;mc_F3czdn9EwuxfaaYWgN0vfZ
mc_FUVohWS6TwleYPUktlo1qp;PmRealVector*mc__ERgtpAr_fdTcmO70I3iqR;};static
size_t mc_FkBpCMMIU400fPEr3KDze1(real_T mc_VMSQAPnWeD4eaH0QSen3xB,size_t
mc_ksP_VoZ3t_SqgyYvFYlpj7){real_T const mc_Fyss_XM3F_C4dm6IKoDw4G=exp(log(
1.5e-8)*2.0/3.0);if(mc_VMSQAPnWeD4eaH0QSen3xB<=mc_Fyss_XM3F_C4dm6IKoDw4G){
return 0;}else{return mc_VG1y_LrErwtMc9AoQz7Nqj(mc_VMSQAPnWeD4eaH0QSen3xB,
mc_Fyss_XM3F_C4dm6IKoDw4G,1.0,mc_ksP_VoZ3t_SqgyYvFYlpj7+1);}}static
mc_kQtOKCqS08dIbumyDnHNDL mc_FeGXN7ACwUOMhmIZBnuYq_(mc_kxnFIpkyuc0YdXbZO41ABc
const*mc_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector*x){mc_FSKepYWjsK8mbHLmdHWO58*d=
mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData;real_T s=0.0;real_T
mc_Fk0GB9HEM__MaantCk0tim=0.0;real_T mc___kC4T6u0_SofuHhqiytyD=0.0;size_t
mc_kfWhETDKfWpDi9poiiZxth=0;size_t mc_Ve0kLmyfjB_gXLSQpJS3i_=0;
mc_kQtOKCqS08dIbumyDnHNDL mc_VVI09JsWtv_qjDiVTVx_YU=mc_VUd8H_Dz0yp8cmQqTd7DxF;
mc_kQtOKCqS08dIbumyDnHNDL mc__kLM3D6pfK0fcqY6ML_XkU=mc_VUd8H_Dz0yp8cmQqTd7DxF;
boolean_T mc_khfHbD1RcMOq_5GErvWUQF=false;pm_rv_equals_rv(d->
mc__ERgtpAr_fdTcmO70I3iqR,x);mc__DTHzUefrrtY_P8UuyCf38:s=1.0;
mc_Fk0GB9HEM__MaantCk0tim=0.0;mc___kC4T6u0_SofuHhqiytyD=0.0;
mc_kfWhETDKfWpDi9poiiZxth=0;mc_Ve0kLmyfjB_gXLSQpJS3i_=0;
mc_VVI09JsWtv_qjDiVTVx_YU=mc_VUd8H_Dz0yp8cmQqTd7DxF;mc__kLM3D6pfK0fcqY6ML_XkU=
mc_VUd8H_Dz0yp8cmQqTd7DxF;(d->mc_kf9uxJXOkD_2ciMoq6ipi7)->
mc_VrNsQKHIiLOFaL3PHRFxZL((d->mc_kf9uxJXOkD_2ciMoq6ipi7));(d->
mc_kf9uxJXOkD_2ciMoq6ipi7)->mc_kt9hW2swhpxchivzz5BlCP((d->
mc_kf9uxJXOkD_2ciMoq6ipi7),(0.0),(x));(d->mc__1zQKz51Xzpkfe0T1u5WXH)->
mc_k0h0NPxQNyl2XD95RLG6Hy((d->mc__1zQKz51Xzpkfe0T1u5WXH),(x));d->
mc_FUVohWS6TwleYPUktlo1qp=mc_FL6WWuhINbWMW5KJKs2y9t();while((
mc_Ve0kLmyfjB_gXLSQpJS3i_<d->mc__NwRaGOaLsKY_5EufWPIPx)&&((s-
mc_Fk0GB9HEM__MaantCk0tim>=1.5e-8)||(mc___kC4T6u0_SofuHhqiytyD>0.0))&&!
pmf_is_interrupt_pending()){size_t mc_FblKIa30uK07VLs42KgECQ=
mc_FkBpCMMIU400fPEr3KDze1(s-mc_Fk0GB9HEM__MaantCk0tim,(d->
mc_kf9uxJXOkD_2ciMoq6ipi7)->mc_F1CrZ_uwhg_eju4CALy3h1((d->
mc_kf9uxJXOkD_2ciMoq6ipi7)));size_t mc_FruBC65sPgSaZ5e_Y8cbTC=0;(void)0;;
mc_Ve0kLmyfjB_gXLSQpJS3i_++;for(mc_FruBC65sPgSaZ5e_Y8cbTC=0;
mc_FruBC65sPgSaZ5e_Y8cbTC<=mc_FblKIa30uK07VLs42KgECQ;mc_FruBC65sPgSaZ5e_Y8cbTC
++){(d->mc_kf9uxJXOkD_2ciMoq6ipi7)->mc_ka3KJ9VlXFK0ZidY3O7sZM((d->
mc_kf9uxJXOkD_2ciMoq6ipi7),(mc_FruBC65sPgSaZ5e_Y8cbTC),(s),(x));(d->
mc__1zQKz51Xzpkfe0T1u5WXH)->mc_VvxtMKveGIdNXan8lRb_uv((d->
mc__1zQKz51Xzpkfe0T1u5WXH),(s));if(s!=1.0){if((d->mc__1zQKz51Xzpkfe0T1u5WXH->
mc_FI68gfOwQ4C_ZmAB_JXEM0)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc_kge3zWSlSoSRhTYHfGl24K){(d->mc__1zQKz51Xzpkfe0T1u5WXH->
mc_FI68gfOwQ4C_ZmAB_JXEM0)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc_kge3zWSlSoSRhTYHfGl24K->mc_FVdv01I3SEC4hD41rxmnRM((d->
mc__1zQKz51Xzpkfe0T1u5WXH->mc_FI68gfOwQ4C_ZmAB_JXEM0)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K,mc__oZL0AImZoh2ZTzHdubvRL.
mc_k1IEdrLtsfxw_XhxVjzMwW.mc_VnFMFkYMV1hK_93KVSQlPS,mc__oZL0AImZoh2ZTzHdubvRL.
mc_k1IEdrLtsfxw_XhxVjzMwW.mc_kdx9sBpyxKhBiiNn9qNSJp,s);};}
mc__kLM3D6pfK0fcqY6ML_XkU=(d->mc_VMFiPDPJti80aLW2m1OHia)->mSolve((d->
mc_VMFiPDPJti80aLW2m1OHia),(x));if(mc__kLM3D6pfK0fcqY6ML_XkU==
mc_FFaaXY_gkbSTcyLBvtfrzS){break;}}if(mc__kLM3D6pfK0fcqY6ML_XkU!=
mc_FFaaXY_gkbSTcyLBvtfrzS){mc_VVI09JsWtv_qjDiVTVx_YU=mc__kLM3D6pfK0fcqY6ML_XkU
;if(mc__kLM3D6pfK0fcqY6ML_XkU==mc_kmVKy2ciwP4fcTEzXFmnvU){if((++
mc_kfWhETDKfWpDi9poiiZxth)>10){break;}}if(mc__kLM3D6pfK0fcqY6ML_XkU==
mc_VW_0L0rb93GgXq8_OmdwHv){d->mc_FUVohWS6TwleYPUktlo1qp=(d->
mc_VMFiPDPJti80aLW2m1OHia)->mc__vHH72jqKt44cXWzB3_tSu((d->
mc_VMFiPDPJti80aLW2m1OHia));}s=mc_Fk0GB9HEM__MaantCk0tim+1.0/3.0*(s-
mc_Fk0GB9HEM__MaantCk0tim);mc___kC4T6u0_SofuHhqiytyD= -1.0;if(!
mc_khfHbD1RcMOq_5GErvWUQF&&s-mc_Fk0GB9HEM__MaantCk0tim<1.5e-8&&
mc_Fk0GB9HEM__MaantCk0tim==0.0){if((d->mc__1zQKz51Xzpkfe0T1u5WXH->
mc_FI68gfOwQ4C_ZmAB_JXEM0)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc_kge3zWSlSoSRhTYHfGl24K){(d->mc__1zQKz51Xzpkfe0T1u5WXH->
mc_FI68gfOwQ4C_ZmAB_JXEM0)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc_kge3zWSlSoSRhTYHfGl24K->mc_FapEct1OXaSugDZ6N_u_kA((d->
mc__1zQKz51Xzpkfe0T1u5WXH->mc_FI68gfOwQ4C_ZmAB_JXEM0)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K,mc__oZL0AImZoh2ZTzHdubvRL.
mc_k1IEdrLtsfxw_XhxVjzMwW.mc_VnFMFkYMV1hK_93KVSQlPS,mc__oZL0AImZoh2ZTzHdubvRL.
mc_k1IEdrLtsfxw_XhxVjzMwW.mc_VNex3Bmd_7loc1Aqi0L_UG);};pm_rv_equals_rv(x,d->
mc__ERgtpAr_fdTcmO70I3iqR);mc_FzkrLuS4xMOvaTv5dUw3j7(x,sqrt(pmf_get_eps()));
mc_khfHbD1RcMOq_5GErvWUQF=true;goto mc__DTHzUefrrtY_P8UuyCf38;}}else{if(s==1.0
){mc_VVI09JsWtv_qjDiVTVx_YU=mc_FFaaXY_gkbSTcyLBvtfrzS;break;}
mc___kC4T6u0_SofuHhqiytyD=s-mc_Fk0GB9HEM__MaantCk0tim;
mc_Fk0GB9HEM__MaantCk0tim=s;(d->mc_kf9uxJXOkD_2ciMoq6ipi7)->
mc_kt9hW2swhpxchivzz5BlCP((d->mc_kf9uxJXOkD_2ciMoq6ipi7),(
mc_Fk0GB9HEM__MaantCk0tim),(x));s+=2.5*mc___kC4T6u0_SofuHhqiytyD;s=(s>1.0)?1.0
:s;}}if(mc_VVI09JsWtv_qjDiVTVx_YU==mc_FFaaXY_gkbSTcyLBvtfrzS){d->
mc_FUVohWS6TwleYPUktlo1qp=mc_FL6WWuhINbWMW5KJKs2y9t();}return
mc_VVI09JsWtv_qjDiVTVx_YU;}static void mc_FJPVGlXLnWWNfm_E3h7T_6(
mc_kxnFIpkyuc0YdXbZO41ABc*mc_V8a_FQ2T6YWLgu_s5UfAPx){mc_FSKepYWjsK8mbHLmdHWO58
*d=mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData;PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=d->mc_Ff9S1xA4Ip4ZXeljM4_eEa;(d->
mc__1zQKz51Xzpkfe0T1u5WXH)->mDestroy(d->mc__1zQKz51Xzpkfe0T1u5WXH);(
mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->mc_VMFiPDPJti80aLW2m1OHia)->mDestroy(
mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->mc_VMFiPDPJti80aLW2m1OHia);(d->
mc_kf9uxJXOkD_2ciMoq6ipi7)->mDestroy(d->mc_kf9uxJXOkD_2ciMoq6ipi7);
pm_destroy_real_vector(d->mc__ERgtpAr_fdTcmO70I3iqR,pm_FbYb_iLqY2hwZTVlVaiqJY)
;{void*const mc__VkGlHUCwoWicTqygg4Pvt=(d);PmAllocator*const
mc__3DCs5EwhwG8Va1hfjwRGm=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc__VkGlHUCwoWicTqygg4Pvt){(mc__3DCs5EwhwG8Va1hfjwRGm)->mFreeFcn(
mc__3DCs5EwhwG8Va1hfjwRGm,mc__VkGlHUCwoWicTqygg4Pvt);}};{void*const
mc_V6n0VPGrD8lTaaNgFjrKHh=(mc_V8a_FQ2T6YWLgu_s5UfAPx);PmAllocator*const
mc_Fm3KPTUhY_WjdLmixZM07K=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_V6n0VPGrD8lTaaNgFjrKHh){(mc_Fm3KPTUhY_WjdLmixZM07K)->mFreeFcn(
mc_Fm3KPTUhY_WjdLmixZM07K,mc_V6n0VPGrD8lTaaNgFjrKHh);}};}
mc_F3czdn9EwuxfaaYWgN0vfZ mc_kBjZnR7SwfWsdyQM_6p_OQ(mc_kxnFIpkyuc0YdXbZO41ABc
const*mc_V8a_FQ2T6YWLgu_s5UfAPx){return mc_V8a_FQ2T6YWLgu_s5UfAPx->
mPrivateData->mc_FUVohWS6TwleYPUktlo1qp;}static void mc_kzzjyKwFg1d9Vaw2JtmN_z
(mc_kxnFIpkyuc0YdXbZO41ABc const*mc_V8a_FQ2T6YWLgu_s5UfAPx,real_T
mc_kTckK8teUpOlhm8Ippu8XP){(mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
mc_VMFiPDPJti80aLW2m1OHia)->mc_FF_Aq2b8Cx_iduzooh_sWO((
mc_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->mc_VMFiPDPJti80aLW2m1OHia),(
mc_kTckK8teUpOlhm8Ippu8XP));}static void mc_Fz88ePavslCOXTdRatMSuU(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO){(
mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->mc_VMFiPDPJti80aLW2m1OHia)->
mc_F_be_I5uNaSddegs3UZPvG((mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->
mc_VMFiPDPJti80aLW2m1OHia));}static mc_kxnFIpkyuc0YdXbZO41ABc*
mc_VYv_I_NqETC9hiMw7szvH6(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc_Fp_Y7mfw0AWIZasCiUfQCN,mc__39VLhR7TBCGYH016BQq8W const*
mc_FyHpf9laLdOKa9__Qkrrko){mc_FuB6ZnvWHlGVe5AYB_qh1v*d=
mc_Fp_Y7mfw0AWIZasCiUfQCN->mPrivateData;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
d->mc_Ff9S1xA4Ip4ZXeljM4_eEa;mc_kxnFIpkyuc0YdXbZO41ABc*
mc_V8a_FQ2T6YWLgu_s5UfAPx=(mc_kxnFIpkyuc0YdXbZO41ABc*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
mc_kxnFIpkyuc0YdXbZO41ABc)),(1))));mc_FSKepYWjsK8mbHLmdHWO58*
mc__d1alWYexptL_X5HTFhbNK=(mc_FSKepYWjsK8mbHLmdHWO58*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
mc_FSKepYWjsK8mbHLmdHWO58)),(1))));size_t mc__bVyeWKHNFpu_5gxm_rTwS=
mc_FyHpf9laLdOKa9__Qkrrko->mPattern->mNumCol;mc__d1alWYexptL_X5HTFhbNK->
mc_Ff9S1xA4Ip4ZXeljM4_eEa=d->mc_Ff9S1xA4Ip4ZXeljM4_eEa;
mc__d1alWYexptL_X5HTFhbNK->mc__1zQKz51Xzpkfe0T1u5WXH=(d->
mc_k34_wY0IFRdbfHl_rltVwF)->mc__B06nILrPXW_bPz__pLJwl((d->
mc_k34_wY0IFRdbfHl_rltVwF),(mc_FyHpf9laLdOKa9__Qkrrko));
mc__d1alWYexptL_X5HTFhbNK->mc_VMFiPDPJti80aLW2m1OHia=(d->
mc_VMFiPDPJti80aLW2m1OHia)->mc_k_hVWBJWCUlCdPNZka5iZF((d->
mc_VMFiPDPJti80aLW2m1OHia),(mc__d1alWYexptL_X5HTFhbNK->
mc__1zQKz51Xzpkfe0T1u5WXH->mc_FI68gfOwQ4C_ZmAB_JXEM0));
mc__d1alWYexptL_X5HTFhbNK->mc_kf9uxJXOkD_2ciMoq6ipi7=mc_k43ukWhB7ctcYqEtIqIF2t
(mc__bVyeWKHNFpu_5gxm_rTwS,d->mc_kNhmJUZe0oOm_1XC7EH51R,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__d1alWYexptL_X5HTFhbNK->
mc__NwRaGOaLsKY_5EufWPIPx=d->mc__NwRaGOaLsKY_5EufWPIPx;
mc__d1alWYexptL_X5HTFhbNK->mc_FUVohWS6TwleYPUktlo1qp=mc_FL6WWuhINbWMW5KJKs2y9t
();mc__d1alWYexptL_X5HTFhbNK->mc__ERgtpAr_fdTcmO70I3iqR=pm_create_real_vector(
mc__bVyeWKHNFpu_5gxm_rTwS,pm_FbYb_iLqY2hwZTVlVaiqJY);mc_V8a_FQ2T6YWLgu_s5UfAPx
->mPrivateData=mc__d1alWYexptL_X5HTFhbNK;mc_V8a_FQ2T6YWLgu_s5UfAPx->mSolve= &
mc_FeGXN7ACwUOMhmIZBnuYq_;mc_V8a_FQ2T6YWLgu_s5UfAPx->mc__vHH72jqKt44cXWzB3_tSu
= &mc_kBjZnR7SwfWsdyQM_6p_OQ;mc_V8a_FQ2T6YWLgu_s5UfAPx->
mc_FF_Aq2b8Cx_iduzooh_sWO= &mc_kzzjyKwFg1d9Vaw2JtmN_z;
mc_V8a_FQ2T6YWLgu_s5UfAPx->mc_F_be_I5uNaSddegs3UZPvG= &
mc_Fz88ePavslCOXTdRatMSuU;mc_V8a_FQ2T6YWLgu_s5UfAPx->mDestroy= &
mc_FJPVGlXLnWWNfm_E3h7T_6;return mc_V8a_FQ2T6YWLgu_s5UfAPx;}static void
mc_V0B6_uRWCd81a1epbOemmQ(mc_kKrwrwNLgB_NYDY0UUZRVA*mc__RtkHrrPEelBbDRCt5cBnV)
{mc_FuB6ZnvWHlGVe5AYB_qh1v*d=mc__RtkHrrPEelBbDRCt5cBnV->mPrivateData;
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=d->mc_Ff9S1xA4Ip4ZXeljM4_eEa;(d->
mc_k34_wY0IFRdbfHl_rltVwF)->mDestroy(d->mc_k34_wY0IFRdbfHl_rltVwF);(d->
mc_VMFiPDPJti80aLW2m1OHia)->mDestroy(d->mc_VMFiPDPJti80aLW2m1OHia);{void*const
mc_FB8ug0Eor5KYfqGRCOCGMU=(d);PmAllocator*const mc_kzX2GsQzWM8lVuWYM3Xlpt=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc_FB8ug0Eor5KYfqGRCOCGMU){(
mc_kzX2GsQzWM8lVuWYM3Xlpt)->mFreeFcn(mc_kzX2GsQzWM8lVuWYM3Xlpt,
mc_FB8ug0Eor5KYfqGRCOCGMU);}};{void*const mc_FrJ3HFvnBVWLjLjKw_ZYdM=(
mc__RtkHrrPEelBbDRCt5cBnV);PmAllocator*const mc__4mHIpIjPd4KgueyxuvKE5=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc_FrJ3HFvnBVWLjLjKw_ZYdM){(
mc__4mHIpIjPd4KgueyxuvKE5)->mFreeFcn(mc__4mHIpIjPd4KgueyxuvKE5,
mc_FrJ3HFvnBVWLjLjKw_ZYdM);}};}mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__XjXW_X3rjOsZ10IOexigE(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,
mc_kuKO_mN0hQljfi2S3b5TKN*mc__Mrd3i9pD4hhcDdC7tyja7,mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FN7xLc4h1wtoW9h_uAsJ11,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc__tsjAPDH6y0lc5lkf_keB1){mc_kKrwrwNLgB_NYDY0UUZRVA*mc__RtkHrrPEelBbDRCt5cBnV
=(mc_kKrwrwNLgB_NYDY0UUZRVA*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_kKrwrwNLgB_NYDY0UUZRVA)),(1))));
mc_FuB6ZnvWHlGVe5AYB_qh1v*mc_FJ2Y0frA7_Sle9T2qXzJdY=(mc_FuB6ZnvWHlGVe5AYB_qh1v
*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
sizeof(mc_FuB6ZnvWHlGVe5AYB_qh1v)),(1))));mc_FJ2Y0frA7_Sle9T2qXzJdY->
mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;mc_FJ2Y0frA7_Sle9T2qXzJdY
->mc_k34_wY0IFRdbfHl_rltVwF=mc__Mrd3i9pD4hhcDdC7tyja7;
mc_FJ2Y0frA7_Sle9T2qXzJdY->mc_VMFiPDPJti80aLW2m1OHia=mc_FN7xLc4h1wtoW9h_uAsJ11
;mc_FJ2Y0frA7_Sle9T2qXzJdY->mc__NwRaGOaLsKY_5EufWPIPx=
mc_kF77yGs8Y4pbZunORy8X8l;mc_FJ2Y0frA7_Sle9T2qXzJdY->mc_kNhmJUZe0oOm_1XC7EH51R
=mc__tsjAPDH6y0lc5lkf_keB1;mc__RtkHrrPEelBbDRCt5cBnV->mPrivateData=
mc_FJ2Y0frA7_Sle9T2qXzJdY;mc__RtkHrrPEelBbDRCt5cBnV->mc_k_hVWBJWCUlCdPNZka5iZF
= &mc_VYv_I_NqETC9hiMw7szvH6;mc__RtkHrrPEelBbDRCt5cBnV->mDestroy= &
mc_V0B6_uRWCd81a1epbOemmQ;return mc__RtkHrrPEelBbDRCt5cBnV;}
