#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};void
mc__L_GrIRY2oxWauBPmclsdh(PmSparsityPattern**mc_kkX9Rpf7ClxifeD5UefJuO,
PmRealVector**mc_kWSn8HFfgDSx_DJzVYzqKl,PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_,PmSparsityPattern const*mc_kd5Ay1mfEqWBi5FGbP6rXO,
PmSparsityPattern const*mc_kbWA_RUXQoOVbXTHMU3Y8d,PmRealVector const*
mc_k4vfOo2N8JOlcyH_GS_hk6,PmRealVector const*mc_k1exL1n4ca4cWDwoUWRLZv,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);static
boolean_T mc_V_xdoYBmlEGdd5SQ3Sb1NY(int32_T pm_kplAJmOlA30feiNcOzi7oj,
PmSparsityPattern const*pm__6H5I5OnY3KoY5YVL6mLgG,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw){int32_T*mc_VEXzFHKjFN87iiOtLrddNz=
pm__6H5I5OnY3KoY5YVL6mLgG->mIr;int32_T*mc_kXeDcvuOSpSqamcA4a5jc_=
pm__6H5I5OnY3KoY5YVL6mLgG->mJc;int32_T mc_kh3C5f6ZAPlGWXfJykpWPn=0;boolean_T
mc___z51GVfsGC9aTBXoZDddx=false;for(mc_kh3C5f6ZAPlGWXfJykpWPn=
mc_kXeDcvuOSpSqamcA4a5jc_[pm_Fr_bHKkQKFWbfi50VWd5Pw];mc_kh3C5f6ZAPlGWXfJykpWPn
<mc_kXeDcvuOSpSqamcA4a5jc_[pm_Fr_bHKkQKFWbfi50VWd5Pw+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){if(pm_kplAJmOlA30feiNcOzi7oj==
mc_VEXzFHKjFN87iiOtLrddNz[mc_kh3C5f6ZAPlGWXfJykpWPn]){
mc___z51GVfsGC9aTBXoZDddx=true;break;}else if(mc_VEXzFHKjFN87iiOtLrddNz[
mc_kh3C5f6ZAPlGWXfJykpWPn]>pm_kplAJmOlA30feiNcOzi7oj){break;}}return
mc___z51GVfsGC9aTBXoZDddx;}static size_t mc_Fz9_b92tbJ_MiLY6opIkZ_(
PmSparsityPattern const*mc_FmLpJop9LJdcV9994iMyd1,size_t i,PmSparsityPattern
const*mc__A7G1Km_PM0yhiTrB1BEqO,size_t j){size_t mc_V_1L1je9xWKpgym3TEz2it=0;
int32_T*mc_VEXzFHKjFN87iiOtLrddNz=mc_FmLpJop9LJdcV9994iMyd1->mIr;int32_T*
mc_kXeDcvuOSpSqamcA4a5jc_=mc_FmLpJop9LJdcV9994iMyd1->mJc;int32_T
mc_kh3C5f6ZAPlGWXfJykpWPn=0;for(mc_kh3C5f6ZAPlGWXfJykpWPn=
mc_kXeDcvuOSpSqamcA4a5jc_[i];mc_kh3C5f6ZAPlGWXfJykpWPn<
mc_kXeDcvuOSpSqamcA4a5jc_[i+1];mc_kh3C5f6ZAPlGWXfJykpWPn++){
mc_V_1L1je9xWKpgym3TEz2it+=mc_V_xdoYBmlEGdd5SQ3Sb1NY(mc_VEXzFHKjFN87iiOtLrddNz
[mc_kh3C5f6ZAPlGWXfJykpWPn],mc__A7G1Km_PM0yhiTrB1BEqO,j)?1:0;}return
mc_V_1L1je9xWKpgym3TEz2it;}static int32_T mc_VlvqLCcsYwdLjaMU2O3CBT(
PmSparsityPattern const*pm__6H5I5OnY3KoY5YVL6mLgG,int32_T
pm_kplAJmOlA30feiNcOzi7oj,size_t mc_FXhDEG4gYkdMY1gKaIjHPH){boolean_T
mc_k6MGcrzbxa07XP0wma_2hv=false;int32_T mc_kh3C5f6ZAPlGWXfJykpWPn=0;int32_T*
mc_kXeDcvuOSpSqamcA4a5jc_=pm__6H5I5OnY3KoY5YVL6mLgG->mJc;int32_T*
mc_VEXzFHKjFN87iiOtLrddNz=pm__6H5I5OnY3KoY5YVL6mLgG->mIr;for(
mc_kh3C5f6ZAPlGWXfJykpWPn=mc_kXeDcvuOSpSqamcA4a5jc_[mc_FXhDEG4gYkdMY1gKaIjHPH]
;mc_kh3C5f6ZAPlGWXfJykpWPn<mc_kXeDcvuOSpSqamcA4a5jc_[mc_FXhDEG4gYkdMY1gKaIjHPH
+1];mc_kh3C5f6ZAPlGWXfJykpWPn++){if(mc_VEXzFHKjFN87iiOtLrddNz[
mc_kh3C5f6ZAPlGWXfJykpWPn]==pm_kplAJmOlA30feiNcOzi7oj){
mc_k6MGcrzbxa07XP0wma_2hv=true;break;}}(void)0;;return
mc_kh3C5f6ZAPlGWXfJykpWPn;}static void mc_VegGSqpdn_CpiHeXuiEMHK(
PmSparsityPattern**mc_kkX9Rpf7ClxifeD5UefJuO,PmRealVector**
mc_kWSn8HFfgDSx_DJzVYzqKl,PmSparsityPattern const*mc_kd5Ay1mfEqWBi5FGbP6rXO,
PmSparsityPattern const*mc_kbWA_RUXQoOVbXTHMU3Y8d,PmSparsityPattern const*
mc_kb4NUCQCTM0CVa5tLLt6JC,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
boolean_T mc_VmKUXXOOQaKPa9uXe0oPD4,PmAllocator*pm__8zlSpb2Hixod149p2zadR){
size_t mc_FIxFweA3fcKFfuFXAKfA47=0;size_t j=0;int32_T mc_kh3C5f6ZAPlGWXfJykpWPn
=0;int32_T i=0;PmSparsityPattern*mc_k4bs1bp5JSGeW17YAgwmCd=NULL;
PmSparsityPattern*mc_kHqpfg_jZGK0Zm8SQYAw22=NULL;PmRealVector*
mc__n_mgRIqfvKii1STQHPBhF=NULL;int32_T*mc_ki9zGKHnh68ec1Y703P484=NULL;int32_T*
mc__BF_a3bbTLOAiuhjWNnEsC=NULL;int32_T*mc_VR_Cxf4vZS8yY5B9N_pKOK=
mc_kb4NUCQCTM0CVa5tLLt6JC->mJc;int32_T*mc_kClMsGI6hA_6_PC0J2fHoW=
mc_kb4NUCQCTM0CVa5tLLt6JC->mIr;int32_T*mc__4m8viASe60ubD4ndIJ6Pi=NULL;int32_T*
mc__rodAJSBRzWIfaRH6oeE3Y=NULL;size_t mc__qLftOjM6_GTfP9blW_yfh=0;
mc_k4bs1bp5JSGeW17YAgwmCd=mc_kAZzxJsz9tloc11S9uThaF(mc_kd5Ay1mfEqWBi5FGbP6rXO,
pm__8zlSpb2Hixod149p2zadR);mc_ki9zGKHnh68ec1Y703P484=mc_k4bs1bp5JSGeW17YAgwmCd
->mJc;mc__BF_a3bbTLOAiuhjWNnEsC=mc_k4bs1bp5JSGeW17YAgwmCd->mIr;
mc_FIxFweA3fcKFfuFXAKfA47=0;for(j=0;j<mc_kb4NUCQCTM0CVa5tLLt6JC->mNumCol;j++){
for(mc_kh3C5f6ZAPlGWXfJykpWPn=mc_VR_Cxf4vZS8yY5B9N_pKOK[j];
mc_kh3C5f6ZAPlGWXfJykpWPn<mc_VR_Cxf4vZS8yY5B9N_pKOK[j+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){mc_FIxFweA3fcKFfuFXAKfA47+=
mc_Fz9_b92tbJ_MiLY6opIkZ_(mc_k4bs1bp5JSGeW17YAgwmCd,mc_kClMsGI6hA_6_PC0J2fHoW[
mc_kh3C5f6ZAPlGWXfJykpWPn],mc_kbWA_RUXQoOVbXTHMU3Y8d,j);}}if(
mc_VmKUXXOOQaKPa9uXe0oPD4){mc__qLftOjM6_GTfP9blW_yfh=((size_t)(((
mc_kbWA_RUXQoOVbXTHMU3Y8d)->mJc[(mc_kbWA_RUXQoOVbXTHMU3Y8d)->mNumCol])));}else
{mc__qLftOjM6_GTfP9blW_yfh=((size_t)(((mc_kd5Ay1mfEqWBi5FGbP6rXO)->mJc[(
mc_kd5Ay1mfEqWBi5FGbP6rXO)->mNumCol])));}mc_kHqpfg_jZGK0Zm8SQYAw22=
pm_create_sparsity_pattern(mc_FIxFweA3fcKFfuFXAKfA47,mc__qLftOjM6_GTfP9blW_yfh
,((size_t)(((mc_kb4NUCQCTM0CVa5tLLt6JC)->mJc[(mc_kb4NUCQCTM0CVa5tLLt6JC)->
mNumCol]))),pm__8zlSpb2Hixod149p2zadR);mc__n_mgRIqfvKii1STQHPBhF=
pm_create_real_vector(mc_FIxFweA3fcKFfuFXAKfA47,pm__8zlSpb2Hixod149p2zadR);
mc__4m8viASe60ubD4ndIJ6Pi=mc_kHqpfg_jZGK0Zm8SQYAw22->mJc;
mc__rodAJSBRzWIfaRH6oeE3Y=mc_kHqpfg_jZGK0Zm8SQYAw22->mIr;
mc__4m8viASe60ubD4ndIJ6Pi[0]=0;for(j=0;j<mc_kb4NUCQCTM0CVa5tLLt6JC->mNumCol;j
++){for(mc_kh3C5f6ZAPlGWXfJykpWPn=mc_VR_Cxf4vZS8yY5B9N_pKOK[j];
mc_kh3C5f6ZAPlGWXfJykpWPn<mc_VR_Cxf4vZS8yY5B9N_pKOK[j+1];
mc_kh3C5f6ZAPlGWXfJykpWPn++){size_t mc__Dit_2Y98YSqcm2c6TVvaD=0;int32_T k=0;i=
mc_kClMsGI6hA_6_PC0J2fHoW[mc_kh3C5f6ZAPlGWXfJykpWPn];for(k=
mc_ki9zGKHnh68ec1Y703P484[i];k<mc_ki9zGKHnh68ec1Y703P484[i+1];k++){if(
mc_V_xdoYBmlEGdd5SQ3Sb1NY(mc__BF_a3bbTLOAiuhjWNnEsC[k],
mc_kbWA_RUXQoOVbXTHMU3Y8d,j)){int32_T mc_V0c6tQ3Gju8VhaJ4azUymv=(int32_T)(
mc__4m8viASe60ubD4ndIJ6Pi[mc_kh3C5f6ZAPlGWXfJykpWPn]+mc__Dit_2Y98YSqcm2c6TVvaD
);if(mc_VmKUXXOOQaKPa9uXe0oPD4){mc__rodAJSBRzWIfaRH6oeE3Y[
mc_V0c6tQ3Gju8VhaJ4azUymv]=mc_VlvqLCcsYwdLjaMU2O3CBT(mc_kbWA_RUXQoOVbXTHMU3Y8d
,mc__BF_a3bbTLOAiuhjWNnEsC[k],j);mc__n_mgRIqfvKii1STQHPBhF->mX[
mc_V0c6tQ3Gju8VhaJ4azUymv]=mc_VTddUsjDkUlHXyWpbnu_X6->mX[
mc_VlvqLCcsYwdLjaMU2O3CBT(mc_kd5Ay1mfEqWBi5FGbP6rXO,i,
mc__BF_a3bbTLOAiuhjWNnEsC[k])];}else{mc__rodAJSBRzWIfaRH6oeE3Y[
mc_V0c6tQ3Gju8VhaJ4azUymv]=mc_VlvqLCcsYwdLjaMU2O3CBT(mc_kd5Ay1mfEqWBi5FGbP6rXO
,i,mc__BF_a3bbTLOAiuhjWNnEsC[k]);mc__n_mgRIqfvKii1STQHPBhF->mX[
mc_V0c6tQ3Gju8VhaJ4azUymv]=mc_VTddUsjDkUlHXyWpbnu_X6->mX[
mc_VlvqLCcsYwdLjaMU2O3CBT(mc_kbWA_RUXQoOVbXTHMU3Y8d,mc__BF_a3bbTLOAiuhjWNnEsC[
k],j)];}mc__Dit_2Y98YSqcm2c6TVvaD++;}}(void)0;;mc__4m8viASe60ubD4ndIJ6Pi[
mc_kh3C5f6ZAPlGWXfJykpWPn+1]=(int32_T)(mc__4m8viASe60ubD4ndIJ6Pi[
mc_kh3C5f6ZAPlGWXfJykpWPn]+mc__Dit_2Y98YSqcm2c6TVvaD);}}*
mc_kkX9Rpf7ClxifeD5UefJuO=mc_kAZzxJsz9tloc11S9uThaF(mc_kHqpfg_jZGK0Zm8SQYAw22,
pm__8zlSpb2Hixod149p2zadR);*mc_kWSn8HFfgDSx_DJzVYzqKl=pm_create_real_vector(((
size_t)((((*mc_kkX9Rpf7ClxifeD5UefJuO))->mJc[((*mc_kkX9Rpf7ClxifeD5UefJuO))->
mNumCol]))),pm__8zlSpb2Hixod149p2zadR);mc_klSR73f0rO4LhXVlV6gmb7((*
mc_kWSn8HFfgDSx_DJzVYzqKl)->mX,*mc_kkX9Rpf7ClxifeD5UefJuO,
mc__n_mgRIqfvKii1STQHPBhF->mX,mc_kHqpfg_jZGK0Zm8SQYAw22);
pm_VYooJBURCwKrVu6RXzQZ_5(mc_kHqpfg_jZGK0Zm8SQYAw22,pm__8zlSpb2Hixod149p2zadR)
;pm_destroy_real_vector(mc__n_mgRIqfvKii1STQHPBhF,pm__8zlSpb2Hixod149p2zadR);
pm_VYooJBURCwKrVu6RXzQZ_5(mc_k4bs1bp5JSGeW17YAgwmCd,pm__8zlSpb2Hixod149p2zadR)
;}void mc__L_GrIRY2oxWauBPmclsdh(PmSparsityPattern**mc_kkX9Rpf7ClxifeD5UefJuO,
PmRealVector**mc_kWSn8HFfgDSx_DJzVYzqKl,PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_,PmSparsityPattern const*mc_kd5Ay1mfEqWBi5FGbP6rXO,
PmSparsityPattern const*mc_kbWA_RUXQoOVbXTHMU3Y8d,PmRealVector const*
mc_k4vfOo2N8JOlcyH_GS_hk6,PmRealVector const*mc_k1exL1n4ca4cWDwoUWRLZv,
PmAllocator*pm__8zlSpb2Hixod149p2zadR){PmSparsityPattern*
mc_F196_GfPVCdVd1lMfexyT1=NULL;PmSparsityPattern*mc_FDzY_S_CBg0Cg1IsO9ZN1i=
NULL;PmSparsityPattern*mc_Fo4hQqYOIWOea5vkER7GV7=NULL;PmSparsityPattern*
mc_kBRZQ20GQ7d4eLAj_oJ4qZ=NULL;PmRealVector*mc_F_IP94P4IAt4cTCw2qMhOF=NULL;
PmRealVector*mc_kxHIMhU9BYhJZPjk2_2b_I=NULL;PmRealVector*
mc_VRZCD_UL_ESThy75dC9J8D=NULL;mc_F196_GfPVCdVd1lMfexyT1=
mc_kyCwDjPxmBGRiTH73vrjJL(mc_kjWUPQN_Ui4d_enzFJIsF_,mc_kbWA_RUXQoOVbXTHMU3Y8d,
pm__8zlSpb2Hixod149p2zadR);mc_VegGSqpdn_CpiHeXuiEMHK(&
mc_Fo4hQqYOIWOea5vkER7GV7,&mc_F_IP94P4IAt4cTCw2qMhOF,mc_kjWUPQN_Ui4d_enzFJIsF_
,mc_kbWA_RUXQoOVbXTHMU3Y8d,mc_F196_GfPVCdVd1lMfexyT1,mc_k1exL1n4ca4cWDwoUWRLZv
,false,pm__8zlSpb2Hixod149p2zadR);if(mc_kd5Ay1mfEqWBi5FGbP6rXO==NULL){*
mc_kkX9Rpf7ClxifeD5UefJuO=mc_Fo4hQqYOIWOea5vkER7GV7;*mc_kWSn8HFfgDSx_DJzVYzqKl
=mc_F_IP94P4IAt4cTCw2qMhOF;pm_VYooJBURCwKrVu6RXzQZ_5(mc_F196_GfPVCdVd1lMfexyT1
,pm__8zlSpb2Hixod149p2zadR);return;}(void)0;;mc_FDzY_S_CBg0Cg1IsO9ZN1i=
mc_kyCwDjPxmBGRiTH73vrjJL(mc_kd5Ay1mfEqWBi5FGbP6rXO,mc_F196_GfPVCdVd1lMfexyT1,
pm__8zlSpb2Hixod149p2zadR);mc_VegGSqpdn_CpiHeXuiEMHK(&
mc_kBRZQ20GQ7d4eLAj_oJ4qZ,&mc_kxHIMhU9BYhJZPjk2_2b_I,mc_kd5Ay1mfEqWBi5FGbP6rXO
,mc_F196_GfPVCdVd1lMfexyT1,mc_FDzY_S_CBg0Cg1IsO9ZN1i,mc_k4vfOo2N8JOlcyH_GS_hk6
,true,pm__8zlSpb2Hixod149p2zadR);*mc_kkX9Rpf7ClxifeD5UefJuO=
mc_kyCwDjPxmBGRiTH73vrjJL(mc_kBRZQ20GQ7d4eLAj_oJ4qZ,mc_Fo4hQqYOIWOea5vkER7GV7,
pm__8zlSpb2Hixod149p2zadR);*mc_kWSn8HFfgDSx_DJzVYzqKl=pm_create_real_vector(((
size_t)((((*mc_kkX9Rpf7ClxifeD5UefJuO))->mJc[((*mc_kkX9Rpf7ClxifeD5UefJuO))->
mNumCol]))),pm__8zlSpb2Hixod149p2zadR);mc_VRZCD_UL_ESThy75dC9J8D=
pm_create_real_vector((*mc_kkX9Rpf7ClxifeD5UefJuO)->mNumRow,
pm__8zlSpb2Hixod149p2zadR);mc__tyTSVoY7fpafmg4sUl1P3((*
mc_kWSn8HFfgDSx_DJzVYzqKl),*mc_kkX9Rpf7ClxifeD5UefJuO,
mc_kxHIMhU9BYhJZPjk2_2b_I,mc_kBRZQ20GQ7d4eLAj_oJ4qZ,mc_F_IP94P4IAt4cTCw2qMhOF,
mc_Fo4hQqYOIWOea5vkER7GV7,mc_VRZCD_UL_ESThy75dC9J8D);pm_destroy_real_vector(
mc_VRZCD_UL_ESThy75dC9J8D,pm__8zlSpb2Hixod149p2zadR);pm_VYooJBURCwKrVu6RXzQZ_5
(mc_kBRZQ20GQ7d4eLAj_oJ4qZ,pm__8zlSpb2Hixod149p2zadR);pm_destroy_real_vector(
mc_kxHIMhU9BYhJZPjk2_2b_I,pm__8zlSpb2Hixod149p2zadR);pm_VYooJBURCwKrVu6RXzQZ_5
(mc_FDzY_S_CBg0Cg1IsO9ZN1i,pm__8zlSpb2Hixod149p2zadR);
pm_VYooJBURCwKrVu6RXzQZ_5(mc_Fo4hQqYOIWOea5vkER7GV7,pm__8zlSpb2Hixod149p2zadR)
;pm_destroy_real_vector(mc_F_IP94P4IAt4cTCw2qMhOF,pm__8zlSpb2Hixod149p2zadR);
pm_VYooJBURCwKrVu6RXzQZ_5(mc_F196_GfPVCdVd1lMfexyT1,pm__8zlSpb2Hixod149p2zadR)
;}
