#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_kv3fXx6PfXt7cekeoT00mk
mc_kgKqfPHHGatO_9OUxR4PRK;struct mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;
void(*mc_FapEct1OXaSugDZ6N_u_kA)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH);void(*
mc_FVdv01I3SEC4hD41rxmnRM)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,real_T
mc__d1alWYexptL_X5HTFhbNK);void(*mc_kPHJTxMUjl8Oi1EQSHes2Q)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);void(*
mc__WEKdqi2uo0m_Dm8w8T_ZO)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc__d1alWYexptL_X5HTFhbNK);};typedef struct mc__nZqLQp3m1lFaHyLAzyG2a
mc__39VLhR7TBCGYH016BQq8W;typedef struct mc__UzXDLpnAvdw_eUt0mYuul
mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct mc__sr5lnPbYjO_Wyo_mmPUmd
mc_Fw_IO5LchthA_LoeiSceRf;struct mc__sr5lnPbYjO_Wyo_mmPUmd{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc__dVSVIr5IcxYgT3A1aaohx
mc_FKEB_KeCGI_DXy1xGMMwkj;typedef struct mc_VCMrVs3_qch2e9_O4TE7vE
mc_F4w5DimUQvtpjap7_Ir11M;struct mc_VCMrVs3_qch2e9_O4TE7vE{
mc_FKEB_KeCGI_DXy1xGMMwkj*mPrivateData;mc__39VLhR7TBCGYH016BQq8W const*
mc_FI68gfOwQ4C_ZmAB_JXEM0;void(*mc_VvxtMKveGIdNXan8lRb_uv)(
mc_F4w5DimUQvtpjap7_Ir11M const*mc_kpyeXH2RWcWG_DVSgKEG_O,real_T s);void(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(mc_F4w5DimUQvtpjap7_Ir11M const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector*x);void(*mDestroy)(
mc_F4w5DimUQvtpjap7_Ir11M*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kaeFjqxw3yGp_TQOIqkvj3 mc_khpvnU9fUTWvV5q3NhO_yh;typedef struct
mc_kJ_0AbL6HDGofHdqgndENk mc_kuKO_mN0hQljfi2S3b5TKN;struct
mc_kJ_0AbL6HDGofHdqgndENk{mc_khpvnU9fUTWvV5q3NhO_yh*mPrivateData;
mc_F4w5DimUQvtpjap7_Ir11M*(*mc__B06nILrPXW_bPz__pLJwl)(
mc_kuKO_mN0hQljfi2S3b5TKN const*mc_FX_ivTD1E1K3Z16XUq1VHF,
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(
mc_kuKO_mN0hQljfi2S3b5TKN*mc_kpyeXH2RWcWG_DVSgKEG_O);};
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__XjXW_X3rjOsZ10IOexigE(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,mc_kuKO_mN0hQljfi2S3b5TKN*mc__Mrd3i9pD4hhcDdC7tyja7,
mc_kKrwrwNLgB_NYDY0UUZRVA*mc_FN7xLc4h1wtoW9h_uAsJ11,size_t
mc_kF77yGs8Y4pbZunORy8X8l,size_t mc__tsjAPDH6y0lc5lkf_keB1);
mc_kuKO_mN0hQljfi2S3b5TKN*mc_kp4nZj06pvtfX9vv5B6sPN(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,real_T mc_VoTkdAz8Qxd2iDKiMSyIbK);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);struct
mc__UzXDLpnAvdw_eUt0mYuul{PmAllocator*mc_Ff9S1xA4Ip4ZXeljM4_eEa;
mc__39VLhR7TBCGYH016BQq8W const*mc__Zx_MPUSDXK_YXBwnozkI3;real_T mS;real_T
mc_kGBvcp14Z00__qdjpir77x;PmRealVector*mc__ERgtpAr_fdTcmO70I3iqR;PmRealVector*
mc__7SVExS9jVKFhuqAK5dXdo;PmRealVector*mc_VvTHRzC_zvC9XP_mz924fP;PmRealVector*
mc__8I5UIwzNgtyfumBLGOGKC;PmRealVector*mc_F994ATkHlqSRd5n2Qr3dgS;
PmSparsityPattern*mc_k_HVpnnadmKWaqjN1yUv0Q;PmSparsityPattern*
mc__wj1_JN0_iGvXqDHk7OgNh;};static void mc_k4qaDApJr9OX_akPxNcn2O(
mc__39VLhR7TBCGYH016BQq8W const*mc_kdsXob1LpUtbZmJz_Puapn,PmRealVector const*x
,PmRealVector*mc__I45QXDj9vhGZeg1ViY2wU){mc_FJ2e3LJXmLlbhebizOW1SJ*
mc__d1alWYexptL_X5HTFhbNK=mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData;real_T s=
mc__d1alWYexptL_X5HTFhbNK->mS;pm_rv_equals_rv(mc__d1alWYexptL_X5HTFhbNK->
mc__7SVExS9jVKFhuqAK5dXdo,x);mc__w_RD4J1MZlqcL7as8FLdk(
mc__d1alWYexptL_X5HTFhbNK->mc__7SVExS9jVKFhuqAK5dXdo,mc__d1alWYexptL_X5HTFhbNK
->mc__ERgtpAr_fdTcmO70I3iqR);mc__dsFCQJjA6p_j1tGhi2wWe(
mc__d1alWYexptL_X5HTFhbNK->mc__8I5UIwzNgtyfumBLGOGKC,(1.0-s)*
mc__d1alWYexptL_X5HTFhbNK->mc_kGBvcp14Z00__qdjpir77x);(
mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3)->
mc_VF0z4xtGYCxzcHJNRB8l2n((mc__d1alWYexptL_X5HTFhbNK->
mc__Zx_MPUSDXK_YXBwnozkI3),x,mc__I45QXDj9vhGZeg1ViY2wU);
mc_V7hiVZfxKK0Uj9rPai4LYw(mc__I45QXDj9vhGZeg1ViY2wU,s);
mc_kM_Y9u9U2F_Cf9sWAtmMMu(mc__I45QXDj9vhGZeg1ViY2wU,mc__d1alWYexptL_X5HTFhbNK
->mc__8I5UIwzNgtyfumBLGOGKC,mc__d1alWYexptL_X5HTFhbNK->
mc_k_HVpnnadmKWaqjN1yUv0Q,mc__d1alWYexptL_X5HTFhbNK->mc__7SVExS9jVKFhuqAK5dXdo
);}static void mc_VktPxr_lRjGCViPF2mOCv_(mc__39VLhR7TBCGYH016BQq8W const*
mc_kdsXob1LpUtbZmJz_Puapn,PmRealVector const*x,PmRealVector*
mc_kr54pdOF7m03iip5bybdRd){mc_FJ2e3LJXmLlbhebizOW1SJ*mc__d1alWYexptL_X5HTFhbNK
=mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData;real_T s=mc__d1alWYexptL_X5HTFhbNK->
mS;mc__dsFCQJjA6p_j1tGhi2wWe(mc__d1alWYexptL_X5HTFhbNK->
mc__8I5UIwzNgtyfumBLGOGKC,(1.0-s)*mc__d1alWYexptL_X5HTFhbNK->
mc_kGBvcp14Z00__qdjpir77x);(mc__d1alWYexptL_X5HTFhbNK->
mc__Zx_MPUSDXK_YXBwnozkI3)->mc_kchvhvYJSIl4dyKnk7tfEC((
mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3),x,
mc__d1alWYexptL_X5HTFhbNK->mc_VvTHRzC_zvC9XP_mz924fP);
mc_V7hiVZfxKK0Uj9rPai4LYw(mc__d1alWYexptL_X5HTFhbNK->mc_VvTHRzC_zvC9XP_mz924fP
,s);mc__8x7kz_627_gXDli_FJo22(mc_kr54pdOF7m03iip5bybdRd,
mc__d1alWYexptL_X5HTFhbNK->mc__wj1_JN0_iGvXqDHk7OgNh,mc__d1alWYexptL_X5HTFhbNK
->mc__8I5UIwzNgtyfumBLGOGKC,mc__d1alWYexptL_X5HTFhbNK->
mc_k_HVpnnadmKWaqjN1yUv0Q,mc__d1alWYexptL_X5HTFhbNK->mc_VvTHRzC_zvC9XP_mz924fP
,mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3->mPattern,
mc__d1alWYexptL_X5HTFhbNK->mc_F994ATkHlqSRd5n2Qr3dgS);}static void
mc_VLNLo6pRiK8GaDDIBPq_aQ(mc__39VLhR7TBCGYH016BQq8W const*
mc_kdsXob1LpUtbZmJz_Puapn,PmRealVector const*x,PmRealVector*
mc_V91rYIvDBkGRba7MvGcPUK){mc_FJ2e3LJXmLlbhebizOW1SJ*mc__d1alWYexptL_X5HTFhbNK
=mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData;(mc__d1alWYexptL_X5HTFhbNK->
mc__Zx_MPUSDXK_YXBwnozkI3)->mc_VLMY1ozRY0Kkj5P0kyXMgl((
mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3),x,
mc_V91rYIvDBkGRba7MvGcPUK);}static void mc_kpVHaGVsvDdfXyOEfMSEBJ(
mc__39VLhR7TBCGYH016BQq8W const*mc_kdsXob1LpUtbZmJz_Puapn,PmRealVector const*x
,char const*mc_FgZTwZqzhmd8haAibGoheR){mc_FJ2e3LJXmLlbhebizOW1SJ*
mc__d1alWYexptL_X5HTFhbNK=mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData;if((
mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc__6Do0w_54Hh7hDw5A7kAcK){(
mc__d1alWYexptL_X5HTFhbNK->mc__Zx_MPUSDXK_YXBwnozkI3)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc__6Do0w_54Hh7hDw5A7kAcK(mc__d1alWYexptL_X5HTFhbNK
->mc__Zx_MPUSDXK_YXBwnozkI3,x,mc_FgZTwZqzhmd8haAibGoheR);};}static void
mc__f1TEJSUlLKjZPKrGHnHuX(mc__39VLhR7TBCGYH016BQq8W*mc_kdsXob1LpUtbZmJz_Puapn)
{mc_FJ2e3LJXmLlbhebizOW1SJ*mc__d1alWYexptL_X5HTFhbNK=mc_kdsXob1LpUtbZmJz_Puapn
->mPrivateData;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK
->mc_Ff9S1xA4Ip4ZXeljM4_eEa;pm_destroy_real_vector(mc__d1alWYexptL_X5HTFhbNK->
mc__ERgtpAr_fdTcmO70I3iqR,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(
mc__d1alWYexptL_X5HTFhbNK->mc__7SVExS9jVKFhuqAK5dXdo,pm_FbYb_iLqY2hwZTVlVaiqJY
);pm_destroy_real_vector(mc__d1alWYexptL_X5HTFhbNK->mc_VvTHRzC_zvC9XP_mz924fP,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(mc__d1alWYexptL_X5HTFhbNK->
mc__8I5UIwzNgtyfumBLGOGKC,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_destroy_real_vector(
mc__d1alWYexptL_X5HTFhbNK->mc_F994ATkHlqSRd5n2Qr3dgS,pm_FbYb_iLqY2hwZTVlVaiqJY
);pm_VYooJBURCwKrVu6RXzQZ_5(mc__d1alWYexptL_X5HTFhbNK->
mc_k_HVpnnadmKWaqjN1yUv0Q,pm_FbYb_iLqY2hwZTVlVaiqJY);pm_VYooJBURCwKrVu6RXzQZ_5
(mc__d1alWYexptL_X5HTFhbNK->mc__wj1_JN0_iGvXqDHk7OgNh,
pm_FbYb_iLqY2hwZTVlVaiqJY);{void*const mc_knDrCFSwkY_ubXv04bF5z6=(
mc__d1alWYexptL_X5HTFhbNK);PmAllocator*const mc_FrauC_Uzja0Sde9AALRmoT=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc_knDrCFSwkY_ubXv04bF5z6){(
mc_FrauC_Uzja0Sde9AALRmoT)->mFreeFcn(mc_FrauC_Uzja0Sde9AALRmoT,
mc_knDrCFSwkY_ubXv04bF5z6);}};{void*const mc_V0GNWS8jd2CNjek_jxKpvK=(
mc_kdsXob1LpUtbZmJz_Puapn);PmAllocator*const mc_kRJQe3tgURpNcTrXYjj8nL=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc_V0GNWS8jd2CNjek_jxKpvK){(
mc_kRJQe3tgURpNcTrXYjj8nL)->mFreeFcn(mc_kRJQe3tgURpNcTrXYjj8nL,
mc_V0GNWS8jd2CNjek_jxKpvK);}};}static mc__39VLhR7TBCGYH016BQq8W*
mc_kQX_oomLAPKqfXcSMlFyPo(mc__39VLhR7TBCGYH016BQq8W const*
mc_VJBSpxYfaqC_aDkIK5aPL_,real_T mc_VoTkdAz8Qxd2iDKiMSyIbK,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY){mc__39VLhR7TBCGYH016BQq8W*mc_kDvxdw9Z7q4jha0OeO2_ui
=(mc__39VLhR7TBCGYH016BQq8W*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc__39VLhR7TBCGYH016BQq8W)),(1))));
mc_FJ2e3LJXmLlbhebizOW1SJ*mc__IkxIiUPqUCzfa_F50Xl2r=(mc_FJ2e3LJXmLlbhebizOW1SJ
*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
sizeof(mc_FJ2e3LJXmLlbhebizOW1SJ)),(1))));size_t mc_Fol7VPru5_d7diNJkJAWvC=
mc_VJBSpxYfaqC_aDkIK5aPL_->mPattern->mNumRow;mc__IkxIiUPqUCzfa_F50Xl2r->
mc_kGBvcp14Z00__qdjpir77x=mc_VoTkdAz8Qxd2iDKiMSyIbK;mc__IkxIiUPqUCzfa_F50Xl2r
->mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;
mc__IkxIiUPqUCzfa_F50Xl2r->mc__Zx_MPUSDXK_YXBwnozkI3=mc_VJBSpxYfaqC_aDkIK5aPL_
;mc__IkxIiUPqUCzfa_F50Xl2r->mc__ERgtpAr_fdTcmO70I3iqR=pm_create_real_vector(
mc_Fol7VPru5_d7diNJkJAWvC,pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r
->mc__7SVExS9jVKFhuqAK5dXdo=pm_create_real_vector(mc_Fol7VPru5_d7diNJkJAWvC,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r->
mc_VvTHRzC_zvC9XP_mz924fP=pm_create_real_vector(((size_t)(((
mc_VJBSpxYfaqC_aDkIK5aPL_->mPattern)->mJc[(mc_VJBSpxYfaqC_aDkIK5aPL_->mPattern
)->mNumCol]))),pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r->
mc__8I5UIwzNgtyfumBLGOGKC=pm_create_real_vector(mc_Fol7VPru5_d7diNJkJAWvC,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r->
mc_F994ATkHlqSRd5n2Qr3dgS=pm_create_real_vector(mc_Fol7VPru5_d7diNJkJAWvC,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r->
mc_k_HVpnnadmKWaqjN1yUv0Q=pm__TNI3M36rThlaTetY4tWiB(mc_Fol7VPru5_d7diNJkJAWvC,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__IkxIiUPqUCzfa_F50Xl2r->
mc__wj1_JN0_iGvXqDHk7OgNh=mc__5C6m_ZyP9_NYekcJCEULM(mc__IkxIiUPqUCzfa_F50Xl2r
->mc_k_HVpnnadmKWaqjN1yUv0Q,mc_VJBSpxYfaqC_aDkIK5aPL_->mPattern,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc_kDvxdw9Z7q4jha0OeO2_ui->
mc_VF0z4xtGYCxzcHJNRB8l2n= &mc_k4qaDApJr9OX_akPxNcn2O;
mc_kDvxdw9Z7q4jha0OeO2_ui->mc_kchvhvYJSIl4dyKnk7tfEC= &
mc_VktPxr_lRjGCViPF2mOCv_;mc_kDvxdw9Z7q4jha0OeO2_ui->mc_VLMY1ozRY0Kkj5P0kyXMgl
= &mc_VLNLo6pRiK8GaDDIBPq_aQ;mc_kDvxdw9Z7q4jha0OeO2_ui->mDestroy= &
mc__f1TEJSUlLKjZPKrGHnHuX;mc_kDvxdw9Z7q4jha0OeO2_ui->mPrivateData=
mc__IkxIiUPqUCzfa_F50Xl2r;mc_kDvxdw9Z7q4jha0OeO2_ui->mPattern=
mc_kDvxdw9Z7q4jha0OeO2_ui->mPrivateData->mc__wj1_JN0_iGvXqDHk7OgNh;if((
mc_VJBSpxYfaqC_aDkIK5aPL_)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc__6Do0w_54Hh7hDw5A7kAcK!=NULL){(void)0;;(mc_kDvxdw9Z7q4jha0OeO2_ui)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc__6Do0w_54Hh7hDw5A7kAcK= &
mc_kpVHaGVsvDdfXyOEfMSEBJ;(mc_kDvxdw9Z7q4jha0OeO2_ui)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K=(mc_VJBSpxYfaqC_aDkIK5aPL_
)->mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K;}else{(void)0;;(
mc_kDvxdw9Z7q4jha0OeO2_ui)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc__6Do0w_54Hh7hDw5A7kAcK=NULL;(mc_kDvxdw9Z7q4jha0OeO2_ui)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K=NULL;};return
mc_kDvxdw9Z7q4jha0OeO2_ui;}struct mc__dVSVIr5IcxYgT3A1aaohx{PmAllocator*
mc_Ff9S1xA4Ip4ZXeljM4_eEa;mc__39VLhR7TBCGYH016BQq8W*mc_FI68gfOwQ4C_ZmAB_JXEM0;
};void mc_VJhASOdjCwCTXPSfcQmiAC(mc_F4w5DimUQvtpjap7_Ir11M const*
mc_kpyeXH2RWcWG_DVSgKEG_O,real_T s){mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
mc_FI68gfOwQ4C_ZmAB_JXEM0->mPrivateData->mS=s;}void mc__FCDNC8N_XtyceUGaOVaCq(
mc_F4w5DimUQvtpjap7_Ir11M const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector*x){
pm_rv_equals_rv(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
mc_FI68gfOwQ4C_ZmAB_JXEM0->mPrivateData->mc__ERgtpAr_fdTcmO70I3iqR,x);}static
void mc_k13IjVrdByCviybqka4G3W(mc_F4w5DimUQvtpjap7_Ir11M*
mc_kdsXob1LpUtbZmJz_Puapn){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData->mc_Ff9S1xA4Ip4ZXeljM4_eEa;(
mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData->mc_FI68gfOwQ4C_ZmAB_JXEM0)->mDestroy(
mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData->mc_FI68gfOwQ4C_ZmAB_JXEM0);{void*
const mc_F262nQpensl8XXgAOV0DN3=(mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData);
PmAllocator*const mc__b5StimpH4dTZu_u3Thb7C=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_F262nQpensl8XXgAOV0DN3){(mc__b5StimpH4dTZu_u3Thb7C)->mFreeFcn(
mc__b5StimpH4dTZu_u3Thb7C,mc_F262nQpensl8XXgAOV0DN3);}};{void*const
mc_VTWO6Igy8yd7a9w_nQoeoE=(mc_kdsXob1LpUtbZmJz_Puapn);PmAllocator*const
mc__pLnk1iS75hDgyCQbJln3f=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_VTWO6Igy8yd7a9w_nQoeoE){(mc__pLnk1iS75hDgyCQbJln3f)->mFreeFcn(
mc__pLnk1iS75hDgyCQbJln3f,mc_VTWO6Igy8yd7a9w_nQoeoE);}};}static
mc_F4w5DimUQvtpjap7_Ir11M*mc_Ff1X5uVqgJl9haVdcB8cfb(mc__39VLhR7TBCGYH016BQq8W
const*mc_VJBSpxYfaqC_aDkIK5aPL_,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,real_T
mc_VoTkdAz8Qxd2iDKiMSyIbK){mc_F4w5DimUQvtpjap7_Ir11M*mc_kdsXob1LpUtbZmJz_Puapn
=(mc_F4w5DimUQvtpjap7_Ir11M*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_F4w5DimUQvtpjap7_Ir11M)),(1))));
mc_FKEB_KeCGI_DXy1xGMMwkj*mc__pjhMo7ThFOzgqKygmnE_V=(mc_FKEB_KeCGI_DXy1xGMMwkj
*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
sizeof(mc_FKEB_KeCGI_DXy1xGMMwkj)),(1))));mc__39VLhR7TBCGYH016BQq8W*
mc_kDvxdw9Z7q4jha0OeO2_ui=mc_kQX_oomLAPKqfXcSMlFyPo(mc_VJBSpxYfaqC_aDkIK5aPL_,
mc_VoTkdAz8Qxd2iDKiMSyIbK,pm_FbYb_iLqY2hwZTVlVaiqJY);mc__pjhMo7ThFOzgqKygmnE_V
->mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;
mc__pjhMo7ThFOzgqKygmnE_V->mc_FI68gfOwQ4C_ZmAB_JXEM0=mc_kDvxdw9Z7q4jha0OeO2_ui
;mc_kdsXob1LpUtbZmJz_Puapn->mPrivateData=mc__pjhMo7ThFOzgqKygmnE_V;
mc_kdsXob1LpUtbZmJz_Puapn->mc_FI68gfOwQ4C_ZmAB_JXEM0=mc_kDvxdw9Z7q4jha0OeO2_ui
;mc_kdsXob1LpUtbZmJz_Puapn->mc_VvxtMKveGIdNXan8lRb_uv= &
mc_VJhASOdjCwCTXPSfcQmiAC;mc_kdsXob1LpUtbZmJz_Puapn->mc_k0h0NPxQNyl2XD95RLG6Hy
= &mc__FCDNC8N_XtyceUGaOVaCq;mc_kdsXob1LpUtbZmJz_Puapn->mDestroy= &
mc_k13IjVrdByCviybqka4G3W;return mc_kdsXob1LpUtbZmJz_Puapn;}struct
mc_kaeFjqxw3yGp_TQOIqkvj3{PmAllocator*mc_Ff9S1xA4Ip4ZXeljM4_eEa;real_T
mc_kGBvcp14Z00__qdjpir77x;};static mc_F4w5DimUQvtpjap7_Ir11M*
mc_Vbb97dz5mcCEhyfcOC3sZM(mc_kuKO_mN0hQljfi2S3b5TKN const*
mc_FX_ivTD1E1K3Z16XUq1VHF,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O){return mc_Ff1X5uVqgJl9haVdcB8cfb(
mc_kpyeXH2RWcWG_DVSgKEG_O,mc_FX_ivTD1E1K3Z16XUq1VHF->mPrivateData->
mc_Ff9S1xA4Ip4ZXeljM4_eEa,mc_FX_ivTD1E1K3Z16XUq1VHF->mPrivateData->
mc_kGBvcp14Z00__qdjpir77x);}static void mc_VJP6VQVk3PpPeHICDLO696(
mc_kuKO_mN0hQljfi2S3b5TKN*mc_kpyeXH2RWcWG_DVSgKEG_O){PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
mc_Ff9S1xA4Ip4ZXeljM4_eEa;{void*const mc_ktdETLCZUN4qai3_9OFIu1=(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData);PmAllocator*const
mc_k4U5kPKUufKcaq35l_Sp1T=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc_ktdETLCZUN4qai3_9OFIu1){(mc_k4U5kPKUufKcaq35l_Sp1T)->mFreeFcn(
mc_k4U5kPKUufKcaq35l_Sp1T,mc_ktdETLCZUN4qai3_9OFIu1);}};{void*const
mc__Drpq5reLm44iXTli3F9Hj=(mc_kpyeXH2RWcWG_DVSgKEG_O);PmAllocator*const
mc_VJYiE9fJYvxJhHq2m2B4RN=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
mc__Drpq5reLm44iXTli3F9Hj){(mc_VJYiE9fJYvxJhHq2m2B4RN)->mFreeFcn(
mc_VJYiE9fJYvxJhHq2m2B4RN,mc__Drpq5reLm44iXTli3F9Hj);}};}
mc_kuKO_mN0hQljfi2S3b5TKN*mc_kp4nZj06pvtfX9vv5B6sPN(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,real_T mc_VoTkdAz8Qxd2iDKiMSyIbK){
mc_kuKO_mN0hQljfi2S3b5TKN*mc_FrCZJE2tGcCmjLa5OoD91O=(mc_kuKO_mN0hQljfi2S3b5TKN
*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
sizeof(mc_kuKO_mN0hQljfi2S3b5TKN)),(1))));mc_khpvnU9fUTWvV5q3NhO_yh*
mc_VqOfTCxx4odDhL_w6WyhoO=(mc_khpvnU9fUTWvV5q3NhO_yh*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
mc_khpvnU9fUTWvV5q3NhO_yh)),(1))));mc_VqOfTCxx4odDhL_w6WyhoO->
mc_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;mc_VqOfTCxx4odDhL_w6WyhoO
->mc_kGBvcp14Z00__qdjpir77x=mc_VoTkdAz8Qxd2iDKiMSyIbK;
mc_FrCZJE2tGcCmjLa5OoD91O->mPrivateData=mc_VqOfTCxx4odDhL_w6WyhoO;
mc_FrCZJE2tGcCmjLa5OoD91O->mc__B06nILrPXW_bPz__pLJwl= &
mc_Vbb97dz5mcCEhyfcOC3sZM;mc_FrCZJE2tGcCmjLa5OoD91O->mDestroy= &
mc_VJP6VQVk3PpPeHICDLO696;return mc_FrCZJE2tGcCmjLa5OoD91O;}
