#include "multibody_model_macros.h"
#include "ne_std.h"
#include "ne_std.h"
NeSimulationParameters neu_extract_simulation_parameters(NeModelParameters
const*pm_st_FSGvWwJ5a8CYdT8a_C4tA5){NeSimulationParameters
pm_st_kH7c9UGCUNOFXqT6Omambe;pm_st_kH7c9UGCUNOFXqT6Omambe.mStartTime=
pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mStartTime;pm_st_kH7c9UGCUNOFXqT6Omambe.
mVariableStepSolver=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mVariableStepSolver;
pm_st_kH7c9UGCUNOFXqT6Omambe.mUsingODEN=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->
mIsUsingODEN;pm_st_kH7c9UGCUNOFXqT6Omambe.mFixedStepSolver= !
pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mVariableStepSolver;pm_st_kH7c9UGCUNOFXqT6Omambe
.mFixedStepSize=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mFixedStepSize;
pm_st_kH7c9UGCUNOFXqT6Omambe.mZcDisabled=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->
mZcDisabled;pm_st_kH7c9UGCUNOFXqT6Omambe.mLoadInitialState=
pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mLoadInitialState;pm_st_kH7c9UGCUNOFXqT6Omambe.
mUseSimState=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mUseSimState;
pm_st_kH7c9UGCUNOFXqT6Omambe.mLinTrimCompile=pm_st_FSGvWwJ5a8CYdT8a_C4tA5->
mLinTrimCompile;pm_st_kH7c9UGCUNOFXqT6Omambe.mRTWModifiedTimeStamp=
pm_st_FSGvWwJ5a8CYdT8a_C4tA5->mRTWModifiedTimeStamp;return
pm_st_kH7c9UGCUNOFXqT6Omambe;}
