#include "multibody_model_macros.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
typedef struct pm_st_kVAtZCZNf88lYiQwM5AQKG pm_st__fsqLDrbYpKihm1eGDg1Gt;
typedef struct pm_st_VFZYs2bhQ7hfVPoiZraac0 pm_st_VBBN_xeCnNxOVL_sk_83e_;
struct pm_st_kVAtZCZNf88lYiQwM5AQKG{pm_st_VBBN_xeCnNxOVL_sk_83e_*mPrivateData;
char const*(*pm_st_VNwUYfxptElMayUsox2R6t)(pm_st__fsqLDrbYpKihm1eGDg1Gt*
pm_st_VAHb4SwSnpW6d5eaPKPVMS,NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ);void(*mDestroy)(pm_st__fsqLDrbYpKihm1eGDg1Gt*
pm_st_VAHb4SwSnpW6d5eaPKPVMS);};pm_st__fsqLDrbYpKihm1eGDg1Gt*
neu_create_diagnostic_tree_printer(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
#include "string.h"
#include "pm_std.h"
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
char const*pm_st_FklPsIWdcv4ra9YnF_YSgF(NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ);char const*pm_st__2lqkvRfia4Meqpodds2S6(
NeuDiagnosticTree const*pm_st_kBj0wT0jErl0hDNP9N5QnJ);NeuDiagnosticLevel
pm_st__6mDXRaqmlWxceo9irjPSa(NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ);size_t pm_st__lBbVf0HSftzcLnQ_Z0qa_(
NeuDiagnosticTree const*pm_st_kBj0wT0jErl0hDNP9N5QnJ);NeuDiagnosticTree const*
pm_st__FHcTUUP4s_rbu4n0hd0z2(NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ,size_t k);static char const
pm_st_F8nSLbQ9zyKOVLOSxhVFgO[]="...";struct pm_st_VFZYs2bhQ7hfVPoiZraac0{
PmAllocator*pm_st_FyUeLiATLG4zWes0mMKZnu;PmCharVector*
pm_st_FVAGVcEpPglKf178ZQBdWZ;};static void pm_st_V_0WydFVLhGbiuytTTelqK(
pm_st__fsqLDrbYpKihm1eGDg1Gt*pm_st_VAHb4SwSnpW6d5eaPKPVMS){
pm_st_VBBN_xeCnNxOVL_sk_83e_*mc__d1alWYexptL_X5HTFhbNK=
pm_st_VAHb4SwSnpW6d5eaPKPVMS->mPrivateData;PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z=mc__d1alWYexptL_X5HTFhbNK->
pm_st_FyUeLiATLG4zWes0mMKZnu;if(mc__d1alWYexptL_X5HTFhbNK->
pm_st_FVAGVcEpPglKf178ZQBdWZ!=NULL){pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ,
mc__d1alWYexptL_X5HTFhbNK->pm_st_FyUeLiATLG4zWes0mMKZnu);}{void*const
pm_st_V8auRzi6odOgdHpvvW0Q5J=(mc__d1alWYexptL_X5HTFhbNK);PmAllocator*const
pm_st_VsypLqvnMxGQjLuuStqYAN=(mc_FOGg0ZWot2WdYenO8zaD4Z);if(
pm_st_V8auRzi6odOgdHpvvW0Q5J){(pm_st_VsypLqvnMxGQjLuuStqYAN)->mFreeFcn(
pm_st_VsypLqvnMxGQjLuuStqYAN,pm_st_V8auRzi6odOgdHpvvW0Q5J);}};{void*const
pm_st_FdEAdgCuaL84dy_WnVZiZR=(pm_st_VAHb4SwSnpW6d5eaPKPVMS);PmAllocator*const
pm_st__Ag5ub5wf_OjVHxJvkkiV0=(mc_FOGg0ZWot2WdYenO8zaD4Z);if(
pm_st_FdEAdgCuaL84dy_WnVZiZR){(pm_st__Ag5ub5wf_OjVHxJvkkiV0)->mFreeFcn(
pm_st__Ag5ub5wf_OjVHxJvkkiV0,pm_st_FdEAdgCuaL84dy_WnVZiZR);}};}static size_t
pm_st_kmHjf1XLMGCsem98QY24iY(PmCharVector const*pm_st_V94OHC32_a85j1a8nI0gLx,
NeuDiagnosticTree const*pm_st_kBj0wT0jErl0hDNP9N5QnJ,size_t
pm_st_kbxkQEWv8mlLdTo87g_18w,size_t pm_st_Vt3_M9S3gx4UZeZCPt_o3L){size_t const
pm_st_k4qi89Yx5_OWhmwMcqtZii=strlen(pm_st_F8nSLbQ9zyKOVLOSxhVFgO);size_t i=0;
char*pm_st__T6LxNAGBLCjYquSrBRKx8=pm_st_V94OHC32_a85j1a8nI0gLx->mX+
pm_st_Vt3_M9S3gx4UZeZCPt_o3L;size_t pm_st__bZHfOPxqA__dT_dD_3Er0=strlen(
pm_st__2lqkvRfia4Meqpodds2S6(pm_st_kBj0wT0jErl0hDNP9N5QnJ));(void)0;;for(i=0;i
<pm_st_kbxkQEWv8mlLdTo87g_18w;i++){strcpy(pm_st__T6LxNAGBLCjYquSrBRKx8,
pm_st_F8nSLbQ9zyKOVLOSxhVFgO);pm_st__T6LxNAGBLCjYquSrBRKx8+=
pm_st_k4qi89Yx5_OWhmwMcqtZii;}strcpy(pm_st__T6LxNAGBLCjYquSrBRKx8,
pm_st__2lqkvRfia4Meqpodds2S6(pm_st_kBj0wT0jErl0hDNP9N5QnJ));
pm_st__T6LxNAGBLCjYquSrBRKx8+=pm_st__bZHfOPxqA__dT_dD_3Er0;*
pm_st__T6LxNAGBLCjYquSrBRKx8++='\n';{size_t pm_st__mPHsTDOsfGxXDwIn51HNM=
pm_st__T6LxNAGBLCjYquSrBRKx8-(pm_st_V94OHC32_a85j1a8nI0gLx->mX+
pm_st_Vt3_M9S3gx4UZeZCPt_o3L);for(i=0;i<pm_st__lBbVf0HSftzcLnQ_Z0qa_(
pm_st_kBj0wT0jErl0hDNP9N5QnJ);i++){pm_st__mPHsTDOsfGxXDwIn51HNM+=
pm_st_kmHjf1XLMGCsem98QY24iY(pm_st_V94OHC32_a85j1a8nI0gLx,
pm_st__FHcTUUP4s_rbu4n0hd0z2(pm_st_kBj0wT0jErl0hDNP9N5QnJ,i),
pm_st_kbxkQEWv8mlLdTo87g_18w+1,pm_st_Vt3_M9S3gx4UZeZCPt_o3L+
pm_st__mPHsTDOsfGxXDwIn51HNM);}return pm_st__mPHsTDOsfGxXDwIn51HNM;}}static
size_t pm_st_VnJneMXn9x0FdTLXss8RBe(NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ,size_t pm_st_kbxkQEWv8mlLdTo87g_18w){size_t
pm_st_Vtqf1yhlNf8Y_PDLhW7Clp=pm_st_kbxkQEWv8mlLdTo87g_18w*strlen(
pm_st_F8nSLbQ9zyKOVLOSxhVFgO)+strlen(pm_st__2lqkvRfia4Meqpodds2S6(
pm_st_kBj0wT0jErl0hDNP9N5QnJ))+1;size_t i=0;for(i=0;i<
pm_st__lBbVf0HSftzcLnQ_Z0qa_(pm_st_kBj0wT0jErl0hDNP9N5QnJ);i++){
pm_st_Vtqf1yhlNf8Y_PDLhW7Clp+=pm_st_VnJneMXn9x0FdTLXss8RBe(
pm_st__FHcTUUP4s_rbu4n0hd0z2(pm_st_kBj0wT0jErl0hDNP9N5QnJ,i),
pm_st_kbxkQEWv8mlLdTo87g_18w+1);}return pm_st_Vtqf1yhlNf8Y_PDLhW7Clp;}static
char const*pm_st_Vv_yidQhJDCld9_s4W3M9s(pm_st__fsqLDrbYpKihm1eGDg1Gt*
pm_st_VAHb4SwSnpW6d5eaPKPVMS,NeuDiagnosticTree const*
pm_st_kBj0wT0jErl0hDNP9N5QnJ){size_t pm__dZ3R3yisKSMd19Osaf1CO=
pm_st_VnJneMXn9x0FdTLXss8RBe(pm_st_kBj0wT0jErl0hDNP9N5QnJ,0);
pm_st_VBBN_xeCnNxOVL_sk_83e_*mc__d1alWYexptL_X5HTFhbNK=
pm_st_VAHb4SwSnpW6d5eaPKPVMS->mPrivateData;if(mc__d1alWYexptL_X5HTFhbNK->
pm_st_FVAGVcEpPglKf178ZQBdWZ!=NULL){pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ,
mc__d1alWYexptL_X5HTFhbNK->pm_st_FyUeLiATLG4zWes0mMKZnu);}
mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ=
pm_VUwRqkQ4oj4FjX20jJYKVB(pm__dZ3R3yisKSMd19Osaf1CO+1,
mc__d1alWYexptL_X5HTFhbNK->pm_st_FyUeLiATLG4zWes0mMKZnu);{size_t
pm_st_Vtqf1yhlNf8Y_PDLhW7Clp=pm_st_kmHjf1XLMGCsem98QY24iY(
mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ,
pm_st_kBj0wT0jErl0hDNP9N5QnJ,0,0);(void)pm_st_Vtqf1yhlNf8Y_PDLhW7Clp;(void)0;;
}return mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ->mX;}
pm_st__fsqLDrbYpKihm1eGDg1Gt*neu_create_diagnostic_tree_printer(PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z){pm_st__fsqLDrbYpKihm1eGDg1Gt*
pm_st_VAHb4SwSnpW6d5eaPKPVMS=(pm_st__fsqLDrbYpKihm1eGDg1Gt*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
pm_st__fsqLDrbYpKihm1eGDg1Gt)),(1))));pm_st_VBBN_xeCnNxOVL_sk_83e_*
mc__d1alWYexptL_X5HTFhbNK=(pm_st_VBBN_xeCnNxOVL_sk_83e_*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
pm_st_VBBN_xeCnNxOVL_sk_83e_)),(1))));mc__d1alWYexptL_X5HTFhbNK->
pm_st_FyUeLiATLG4zWes0mMKZnu=mc_FOGg0ZWot2WdYenO8zaD4Z;
mc__d1alWYexptL_X5HTFhbNK->pm_st_FVAGVcEpPglKf178ZQBdWZ=NULL;
pm_st_VAHb4SwSnpW6d5eaPKPVMS->mPrivateData=mc__d1alWYexptL_X5HTFhbNK;
pm_st_VAHb4SwSnpW6d5eaPKPVMS->pm_st_VNwUYfxptElMayUsox2R6t= &
pm_st_Vv_yidQhJDCld9_s4W3M9s;pm_st_VAHb4SwSnpW6d5eaPKPVMS->mDestroy= &
pm_st_V_0WydFVLhGbiuytTTelqK;return pm_st_VAHb4SwSnpW6d5eaPKPVMS;}
