#include "multibody_model_macros.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_FBFcaG_MQqpUY9tvxkzRNB ssc_core__9_bst0n_6hsfTYxDzlBx3
;typedef struct ssc_core_FG_MGSeorK89aDQgcPyBhB ssc_core_V8uCz_1gtBdHjP1W0a12dX
;struct ssc_core_FG_MGSeorK89aDQgcPyBhB{PmfMessageId(*mFactor)(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*s,NeSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);PmfMessageId(*mCheck)(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*s,size_t ssc_core_kUQBO1dSP8_IVqRAUx4R8G);
PmfMessageId(*mSolve)(ssc_core_V8uCz_1gtBdHjP1W0a12dX*s,NeSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*ssc_core_kiWXQiEPGG_qaTkp2QcRMd,
PmRealVector const*ssc_core_FdmAbCPPD4CjYyYD3ELMgz);void(*mDestroy)(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*s);ssc_core__9_bst0n_6hsfTYxDzlBx3*mData;};
ssc_core_V8uCz_1gtBdHjP1W0a12dX*ssc_core_k8xgG2LxT4xgXXubjv15_o(
McMatrixFunction*mc_VoTkdAz8Qxd2iDKiMSyIbK,PmAllocator*
mc_FZx3iFiX1YW7j5eEojoAPc);
#include "math.h"
#include "string.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_FvfmwR5Z4udFdmA89MySHd(McMatrixFunction*mc_kEQ7ZkhePUp8eHqnX6lLap,
McMatrixFunction*mc_VRqcAPiI_zWzcaWghAD8Ra,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_F41vm5CeApOpiPIy1rZa2m(
McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_inline.h"
#include "pm_std.h"
typedef struct pm_V1heuUPdFYSBhXSTZrzev1{size_t mNumRow;size_t mNumCol;real_T*
mX;}pm_FMSUHHOOKD8acuFWLEq4lL;pm_FMSUHHOOKD8acuFWLEq4lL*
pm__IzxUodah3x2_u_ENKAuGk(size_t pm__6bYkkT4Shd0e1DZPlpqqb,size_t
pm__g5DiU2QzFtUiL4XoU6SMs,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_FMSUHHOOKD8acuFWLEq4lL*pm__vffvPR7IsS2XyyCPqmNPs(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
pm__uc9LGWqLf03gLt6Sr9mtw(pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VuZ05R76dw4R_5mH59xUl3(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60);size_t
pm_kXhhlZLW3c8yiTFYZWcurB(pm_FMSUHHOOKD8acuFWLEq4lL const*
pm_k5aqR5haGY_ZXuGDU2ua60);PMF_DEPLOY_STATIC real_T pm_VWoHHtf6OqO6YXA_khGhQm(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t
pm_kplAJmOlA30feiNcOzi7oj,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw){return
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow];}
PMF_DEPLOY_STATIC void pm_kzEZvMeJLvOmgX1qMXsT0P(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t pm_kplAJmOlA30feiNcOzi7oj,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,real_T pm_kpzAtHMD4_WnheH0UiioSE){
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow]=
pm_kpzAtHMD4_WnheH0UiioSE;}void pm_kqNP_VNVXgWGcLsAqt8n_A(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_kUO9H2UqXf8k_y6THPribZ,PmRealVector const*
pm_V9BoL4F3KMGcYqNc2RhxW_,PmSparsityPattern const*pm_FbpiqbN30g8sY9B6YI6RUP);
void pm_kRraI4tqfotp_aUXOIifb6(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,
pm_FMSUHHOOKD8acuFWLEq4lL const*src);boolean_T pm__DD6QRkN3jGod5UZotcfi8(
pm_FMSUHHOOKD8acuFWLEq4lL const*dst,pm_FMSUHHOOKD8acuFWLEq4lL const*src);
boolean_T pm__Wj7kGLfa8_wfmNCNFVchb(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);void
pm_VL4rp2NEaF8Tcu2gE6TeeU(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);typedef struct
mc_VSpV1kj40D8RY9HkUsdI9A mc__mPsQ8V6SzW4c97L9cFyiT;typedef struct
mc__w_PiAX5XUGFda1QEKun0R mc_FoiVRy68eNKXdXlR9clkj9;struct
mc_VSpV1kj40D8RY9HkUsdI9A{pm_FMSUHHOOKD8acuFWLEq4lL const*
mc_kXZtSGM_7S0HWXqFxFKO9Q;PmIntVector const*mc_VjeXnPMgpGOk_PncvX2i2h;void(*
mc_F8jYh1XJ10K_emvBxS7m6z)(mc__mPsQ8V6SzW4c97L9cFyiT const*
mc_FleGJLV78MSFf5qx1JOm0Z,size_t mc_Fyss_XM3F_C4dm6IKoDw4G,size_t
mc_Vs6xonQX17Krc5vXv8T_zq);size_t(*mc__h_bTuBtpZhZZuHwef1rNn)(
mc__mPsQ8V6SzW4c97L9cFyiT const*mc_FleGJLV78MSFf5qx1JOm0Z);real_T(*
mc_kuJm9J2opvOrWLNs_OadzE)(mc__mPsQ8V6SzW4c97L9cFyiT const*
mc_FleGJLV78MSFf5qx1JOm0Z);boolean_T(*mc_V2eI1QgtIrCYeLJdteQbAG)(
mc__mPsQ8V6SzW4c97L9cFyiT const*mc_FleGJLV78MSFf5qx1JOm0Z,PmRealVector const*v
);void(*mc__m5kzglAA8GbhqzJEU9tFQ)(mc__mPsQ8V6SzW4c97L9cFyiT const*
mc_FleGJLV78MSFf5qx1JOm0Z,PmBoolVector const*mc_V2mBNcV1EqCifyH9UdCbkF,
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K);void(*mc__uwMrSGWCVlEW1HO2TxQle)(
mc__mPsQ8V6SzW4c97L9cFyiT const*mc_FleGJLV78MSFf5qx1JOm0Z);void(*
mc_kj_oOGqml_xqaXiiWNvUfG)(mc__mPsQ8V6SzW4c97L9cFyiT const*
mc_FleGJLV78MSFf5qx1JOm0Z,PmRealVector const*x,PmRealVector const*y);void(*
mSolve)(mc__mPsQ8V6SzW4c97L9cFyiT const*mc_FleGJLV78MSFf5qx1JOm0Z,PmRealVector
const*x,PmRealVector const*y);void(*mDestroy)(mc__mPsQ8V6SzW4c97L9cFyiT*
mc_FleGJLV78MSFf5qx1JOm0Z);mc_FoiVRy68eNKXdXlR9clkj9*mData;};
mc__mPsQ8V6SzW4c97L9cFyiT*mc_Vf73j5Fnw7ltjets1WrRk_(size_t
pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_core__gGmO67Uzy_Yg1j4Tgxf21 ssc_core_FDsIo_8VzL4t_qzfDJ75HO
;struct ssc_core__gGmO67Uzy_Yg1j4Tgxf21{boolean_T
ssc_core_kl_DW_ItP_GQYuf5d0Vxdx;boolean_T ssc_core_Vesiv0_gXg0M_XD5Q_eXiA;
boolean_T ssc_core_kYRPIC8P4o8CYXme9CRbxR;real_T
ssc_core_kSsQH5I8Tk_lW9d8fx9Lty;size_t ssc_core__lV4aWNmCPpNZ1eHGhAUGx;size_t
ssc_core_F9ST0a3paVSkaXYlWy4lTh;};ssc_core_FDsIo_8VzL4t_qzfDJ75HO const*
ssc_core_FrZn_AlaHt4XXP_Pc_5_3W(void);void ssc_core_FVfouN9e4S_yiXnDsCeVIN(
ssc_core_FDsIo_8VzL4t_qzfDJ75HO const*ssc_core_kv7GnpbgsfSGjTKLxq5SvA);struct
ssc_core_kesYKdRukKtCYLfoQ0YRJ5{struct{struct{struct{char const*
ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*ssc_core__qEXoys3NqhTc5aGZjoM0i;}
ssc_core_kvZlvqC1JqdoYahhfIqkPq;struct{char const*
ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*ssc_core__qEXoys3NqhTc5aGZjoM0i;}
ssc_core__CmZebP7mNptWDMef1TTIl;}ssc_core_V01A11djsUSPhydgdGoEM8;struct{struct
{char const*ssc_core__EXYd0BpsApngXjCLU66Qq;char const*
ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;}ssc_core_F0zPq17YGsWWY9f__3XLFE;struct{char
const*ssc_core__EXYd0BpsApngXjCLU66Qq;char const*
ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;char const*ssc_core_V_r1xwjDx7lwguJ2YCpUai;}
ssc_core__YmatZ07z0_k_ulppGYT3M;}ssc_core_kCihPvTAZxpx_H5ihyr_kC;struct{char
const*ssc_core_kpMuDXM8W__FWaXECbGWgq;char const*
ssc_core_kZL4P0QovRSWiqHRt1WIC6;}ssc_core_VWYj_r5wXZ0gbi3aGkkirz;}
ssc_core_VNb3dQocUud1ieYKQWZKSY;struct{struct{char const*
ssc_core_V63i95p2LLdg_5IdB06gkx;char const*ssc_core_VxPQol5LzB_eaDZ9jfsvgc;}
ssc_core__aT2sx0pgFCPiP8nk_pRK_;}ssc_core_VJgtn_cGgzdoceadTmm3t6;struct{struct
{char const*ssc_core_kTdqak9AqCGKcHj5IXmfZe;char const*
ssc_core__ZW8YII_QJ4wiHEnAMUOgB;char const*ssc_core__MNSKfpi3jteauByrrb2q7;}
ssc_core_kdx8eT3TLLtTjLxaVSammf;}ssc_core_Vb8i6ka6Ps0zj9AYvH4Qsj;};extern
struct ssc_core_kesYKdRukKtCYLfoQ0YRJ5 ssc_core_VrvQtlpclEKjVTpcoDIr6q;struct
ssc_core_FBFcaG_MQqpUY9tvxkzRNB{McMatrixFunction*
ssc_core__GZgpfAxmtt__DAkMX6fQl;PmRealVector*ssc_core__KXu9Nqw8NG2iuaUrMho93;
mc__mbv8xxcLWlA_qjxkZ_Zr3 ssc_core_FzzCy0s7rK0rc9Yuo8cvkR;
mc__mbv8xxcLWlA_qjxkZ_Zr3 ssc_core_kbkXEwKk68KygelCtBbNLM;
mc__mPsQ8V6SzW4c97L9cFyiT*ssc_core_FobFX43y9iOubDC_5c4pla;PmRealVector*
ssc_core_F994ATkHlqSRd5n2Qr3dgS;PmAllocator*ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;};
static PmfMessageId ssc_core_V69kqsl_LZOqYPUEHJemYo(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,size_t exp){
ssc_core__9_bst0n_6hsfTYxDzlBx3*mc__d1alWYexptL_X5HTFhbNK=
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mData;PmfMessageId id=NULL;size_t
ssc_core_V43XzkQODRhUg1_1Rh85Gs;ssc_core_V43XzkQODRhUg1_1Rh85Gs=(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla)->
mc__h_bTuBtpZhZZuHwef1rNn((mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla));if(ssc_core_V43XzkQODRhUg1_1Rh85Gs!=exp){id=
ssc_core_VrvQtlpclEKjVTpcoDIr6q.ssc_core_VNb3dQocUud1ieYKQWZKSY.
ssc_core_V01A11djsUSPhydgdGoEM8 .ssc_core_kvZlvqC1JqdoYahhfIqkPq.
ssc_core__qEXoys3NqhTc5aGZjoM0i;}return id;}static PmfMessageId
ssc_core_FTSUfWUrYRl1aeTeecLGGU(ssc_core_V8uCz_1gtBdHjP1W0a12dX*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
{boolean_T const ssc_core_kTfubdotkPxEV93l_4hCcD=
ssc_core_FrZn_AlaHt4XXP_Pc_5_3W()->ssc_core_Vesiv0_gXg0M_XD5Q_eXiA;
ssc_core__9_bst0n_6hsfTYxDzlBx3*mc__d1alWYexptL_X5HTFhbNK=
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mData;PmfMessageId id=NULL;(*((
mc__d1alWYexptL_X5HTFhbNK->ssc_core__GZgpfAxmtt__DAkMX6fQl)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__KXu9Nqw8NG2iuaUrMho93),((
mc__d1alWYexptL_X5HTFhbNK->ssc_core__GZgpfAxmtt__DAkMX6fQl)->
mc_ko6_hiERTRldgDROOJBQCH));mc_klSR73f0rO4LhXVlV6gmb7(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr->mX,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern,
mc__d1alWYexptL_X5HTFhbNK->ssc_core__KXu9Nqw8NG2iuaUrMho93->mX,
mc__d1alWYexptL_X5HTFhbNK->ssc_core__GZgpfAxmtt__DAkMX6fQl->
mc_kjWUPQN_Ui4d_enzFJIsF_);if(ssc_core_kTfubdotkPxEV93l_4hCcD){
mc__tyTSVoY7fpafmg4sUl1P3(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPr,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__KXu9Nqw8NG2iuaUrMho93,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GZgpfAxmtt__DAkMX6fQl->mc_kjWUPQN_Ui4d_enzFJIsF_,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_F994ATkHlqSRd5n2Qr3dgS);
pm_kqNP_VNVXgWGcLsAqt8n_A(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla->mc_kXZtSGM_7S0HWXqFxFKO9Q,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPr,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern);(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla)->
mc_F8jYh1XJ10K_emvBxS7m6z((mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla),(0),(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern->mNumCol));id=
ssc_core_V69kqsl_LZOqYPUEHJemYo(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern->mNumRow);
}else{pm_kqNP_VNVXgWGcLsAqt8n_A(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla->mc_kXZtSGM_7S0HWXqFxFKO9Q,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern);(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla)->
mc_F8jYh1XJ10K_emvBxS7m6z((mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla),(0),(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern->mNumCol));id=
ssc_core_V69kqsl_LZOqYPUEHJemYo(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern->mNumCol);
}return id;}static PmfMessageId ssc_core_kON5SX4QqhtGZa_p9dyjWo(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeSystemInput
const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
ssc_core_kiWXQiEPGG_qaTkp2QcRMd,PmRealVector const*
ssc_core_FdmAbCPPD4CjYyYD3ELMgz){boolean_T const
ssc_core_kTfubdotkPxEV93l_4hCcD=ssc_core_FrZn_AlaHt4XXP_Pc_5_3W()->
ssc_core_Vesiv0_gXg0M_XD5Q_eXiA;ssc_core__9_bst0n_6hsfTYxDzlBx3*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mData;(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;if(ssc_core_kTfubdotkPxEV93l_4hCcD){(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla)->mSolve((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla),(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_F994ATkHlqSRd5n2Qr3dgS),(
ssc_core_FdmAbCPPD4CjYyYD3ELMgz));mc__aNO1s5qwzt6fXwft5YgCz(
ssc_core_kiWXQiEPGG_qaTkp2QcRMd);mc_kM_Y9u9U2F_Cf9sWAtmMMu(
ssc_core_kiWXQiEPGG_qaTkp2QcRMd,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_F994ATkHlqSRd5n2Qr3dgS);}else{(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla)->mc_kj_oOGqml_xqaXiiWNvUfG((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FobFX43y9iOubDC_5c4pla),(
ssc_core_kiWXQiEPGG_qaTkp2QcRMd),(ssc_core_FdmAbCPPD4CjYyYD3ELMgz));}return
NULL;}static void ssc_core_FKXAIt1RUStHVillg_Vahx(
ssc_core_V8uCz_1gtBdHjP1W0a12dX*s){ssc_core__9_bst0n_6hsfTYxDzlBx3*d=s->mData;
PmAllocator*a=d->ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;(d->
ssc_core__GZgpfAxmtt__DAkMX6fQl)->mDestroy(d->ssc_core__GZgpfAxmtt__DAkMX6fQl)
;pm_destroy_real_vector(d->ssc_core__KXu9Nqw8NG2iuaUrMho93,a);
pm_VYooJBURCwKrVu6RXzQZ_5(d->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern,a);
pm_destroy_real_vector(d->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr,a);if(d->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern!=NULL){pm_VYooJBURCwKrVu6RXzQZ_5(d->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern,a);}if(d->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPr!=NULL){pm_destroy_real_vector(d->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPr,a);}(d->ssc_core_FobFX43y9iOubDC_5c4pla)->
mDestroy(d->ssc_core_FobFX43y9iOubDC_5c4pla);if(d->
ssc_core_F994ATkHlqSRd5n2Qr3dgS!=NULL){pm_destroy_real_vector(d->
ssc_core_F994ATkHlqSRd5n2Qr3dgS,a);}{void*const ssc_core__ztxQHeWHXOegLPk7C_yBh
=(d);PmAllocator*const ssc_core__DjR17KDF3tBjaYOt6BARC=(a);if(
ssc_core__ztxQHeWHXOegLPk7C_yBh){(ssc_core__DjR17KDF3tBjaYOt6BARC)->mFreeFcn(
ssc_core__DjR17KDF3tBjaYOt6BARC,ssc_core__ztxQHeWHXOegLPk7C_yBh);}};{void*
const ssc_core_V65nW_kE2ExKeew5aQPdZS=(s);PmAllocator*const
ssc_core___8kbK45NvCwd1pTTEgIlm=(a);if(ssc_core_V65nW_kE2ExKeew5aQPdZS){(
ssc_core___8kbK45NvCwd1pTTEgIlm)->mFreeFcn(ssc_core___8kbK45NvCwd1pTTEgIlm,
ssc_core_V65nW_kE2ExKeew5aQPdZS);}};}ssc_core_V8uCz_1gtBdHjP1W0a12dX*
ssc_core_k8xgG2LxT4xgXXubjv15_o(McMatrixFunction*mc_VoTkdAz8Qxd2iDKiMSyIbK,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){ssc_core_V8uCz_1gtBdHjP1W0a12dX*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx=(ssc_core_V8uCz_1gtBdHjP1W0a12dX*)(((
mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(
ssc_core_V8uCz_1gtBdHjP1W0a12dX)),(1))));ssc_core__9_bst0n_6hsfTYxDzlBx3*
mc__d1alWYexptL_X5HTFhbNK=(ssc_core__9_bst0n_6hsfTYxDzlBx3*)(((
mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(
ssc_core__9_bst0n_6hsfTYxDzlBx3)),(1))));boolean_T const
ssc_core_kTfubdotkPxEV93l_4hCcD=ssc_core_FrZn_AlaHt4XXP_Pc_5_3W()->
ssc_core_Vesiv0_gXg0M_XD5Q_eXiA;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GZgpfAxmtt__DAkMX6fQl=mc_VoTkdAz8Qxd2iDKiMSyIbK;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__KXu9Nqw8NG2iuaUrMho93=
pm_create_real_vector(((size_t)(((mc_VoTkdAz8Qxd2iDKiMSyIbK->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(mc_VoTkdAz8Qxd2iDKiMSyIbK->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),mc_FZx3iFiX1YW7j5eEojoAPc);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern=
mc_kAZzxJsz9tloc11S9uThaF(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GZgpfAxmtt__DAkMX6fQl->mc_kjWUPQN_Ui4d_enzFJIsF_,
mc_FZx3iFiX1YW7j5eEojoAPc);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPr=pm_create_real_vector(((size_t)(((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern)->mJc[(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern)->mNumCol]
))),mc_FZx3iFiX1YW7j5eEojoAPc);if(ssc_core_kTfubdotkPxEV93l_4hCcD){
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern=
mc_kyCwDjPxmBGRiTH73vrjJL(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GZgpfAxmtt__DAkMX6fQl->mc_kjWUPQN_Ui4d_enzFJIsF_,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern,
mc_FZx3iFiX1YW7j5eEojoAPc);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kbkXEwKk68KygelCtBbNLM.mPr=pm_create_real_vector(((size_t)(((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern)->mJc[(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern)->mNumCol]
))),mc_FZx3iFiX1YW7j5eEojoAPc);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla=mc_Vf73j5Fnw7ltjets1WrRk_(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern->mNumRow,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kbkXEwKk68KygelCtBbNLM.mPattern->mNumCol,
mc_FZx3iFiX1YW7j5eEojoAPc);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_F994ATkHlqSRd5n2Qr3dgS=pm_create_real_vector(
mc_VoTkdAz8Qxd2iDKiMSyIbK->mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,
mc_FZx3iFiX1YW7j5eEojoAPc);}else{mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FobFX43y9iOubDC_5c4pla=mc_Vf73j5Fnw7ltjets1WrRk_(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern->mNumRow,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FzzCy0s7rK0rc9Yuo8cvkR.mPattern->mNumCol,
mc_FZx3iFiX1YW7j5eEojoAPc);}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa=mc_FZx3iFiX1YW7j5eEojoAPc;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mData=mc__d1alWYexptL_X5HTFhbNK;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mFactor=ssc_core_FTSUfWUrYRl1aeTeecLGGU;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mCheck=ssc_core_V69kqsl_LZOqYPUEHJemYo;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mSolve=ssc_core_kON5SX4QqhtGZa_p9dyjWo;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mDestroy=ssc_core_FKXAIt1RUStHVillg_Vahx;
return ssc_core_V8a_FQ2T6YWLgu_s5UfAPx;}
