#include "multibody_model_macros.h"
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;
#include "ne_std.h"
#include "ne_std.h"
typedef enum{ssc_core__ioOg4ScKX0EZDRCgs08_8= -1,
ssc_core_VUvhZChBwCxhcDNbwou1aT,ssc_core__QYxQXlKud8zbLGuiUNTmv,
ssc_core_VNLm8DNiLLxzVDGeWBpIJV,ssc_core_V36UEe9kiR_Qcm5dDei5__}
ssc_core_VMObUicZgDGkXuH3R8jgeY;
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VWJbTwnVZB_LVqIIM_COT0{int32_T mc_FvxKbdtfPKOYaymjtthQ0G,
mc__0REJ38_cKO_bunM1JCRT_,id;struct mc_VWJbTwnVZB_LVqIIM_COT0*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;}
mc_FSz7cV1MCGScXq_M5VT121;typedef struct mc_kjlHS2Mzxsh6gyVZ329fra{
mc_FSz7cV1MCGScXq_M5VT121*mc__a1o_SOX2HC3f9QpH_hO5s;PmIntVector*
mc__5uLb2__blGtb9EQ9Zwa2_;PmIntVector*mQ;}mc_F9HbKNDZMeOehmlKWGUdea;typedef
struct mc__fV9rOH7ci_OWykNO7xTBO{size_t mc_VLHhnPUiNQpve5VIL9P3O9,n;int32_T*
mc_FvxKbdtfPKOYaymjtthQ0G,*mc__0REJ38_cKO_bunM1JCRT_,*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;int32_T*
pm__lqjegyKuwStj56WZLiC_e,*mc__AExROh1PVWNeP7hmMWuJv;}
mc_FwUXSPCwCAC_jydGHlCZxe;PmIntVector*mc__oCV63DXBpKVZL_8tU2Wiz(
mc_FSz7cV1MCGScXq_M5VT121 const*mc_VPPSxR3RRt0pXLadx2tWo7,PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
mc__RLQweDZtv0hhLXz_f8MMi(mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt)
;mc_FSz7cV1MCGScXq_M5VT121*mc_VCdOZjcBUFORayuNvO7rtI(mc_FSz7cV1MCGScXq_M5VT121
*mc_Fxl4i6XHkE8cY9kYmlJixt);void mc_VbHMSzzYu5_WZiNG_fSW8Q(
mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt,int32_T
mc_FvxKbdtfPKOYaymjtthQ0G);int32_T mc__1AbngzPnBGnXXDldWop_b(
mc_FSz7cV1MCGScXq_M5VT121*mc_VPPSxR3RRt0pXLadx2tWo7);void
mc_VBCIjXiCCT_RXmHVT9WPVa(mc_F9HbKNDZMeOehmlKWGUdea*mc_VpSwxG2uxL4JaLmMQqUqTJ)
;mc_FwUXSPCwCAC_jydGHlCZxe*mc_F79LLfWDdKORZ1K7KKqAke(mc_F9HbKNDZMeOehmlKWGUdea
const*mc_VpSwxG2uxL4JaLmMQqUqTJ);mc_F9HbKNDZMeOehmlKWGUdea*
mc_perm_data_from_flat(mc_FwUXSPCwCAC_jydGHlCZxe const*
mc_Fw6WJxuximC4jHgRLzUSDo);void mc_Vq5AUJWyc3xVgP5Ff1_aP6(
mc_FwUXSPCwCAC_jydGHlCZxe*mc_Fw6WJxuximC4jHgRLzUSDo);
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
typedef enum{ssc_sli_kiIb5xamJm8uXPyOkLeM64= -1,ssc_sli_FRFqZTqvUYlL_1GmhnSKa9
,ssc_sli_F_n1U4dfhIKmZeTb79_bhk,ssc_sli_Vje8c4NwMs8edaUv9kAKU5,
ssc_sli_F95A2pmjwJGycuR83ALBWW,ssc_sli_FRC3ujZIQjdba9ZBxy4ztV}
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ;typedef struct ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv
ssc_sli_FTmXA5ksLdxWam9tKEDDRp;typedef union ssc_sli_V3VjUqcAjgGUfa9pjdr9Vc{
PmIntVector mMODE;PmRealVector mY;PmRealVector ssc_sli_kxq2De1a8BxzemrdMYbh_Z;
PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;PmIntVector
mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector mUPDATE_R;
PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;PmRealVector
mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector ssc_sli_VjGKBH58LAdsYPWWs6sfbL;PmRealVector mLOG;}
ssc_sli_kkoV3MWI3Olsj9ue_OTrKB;typedef enum ssc_sli__gFYpQJuFtpEfTSOOLoPeL{
ssc_sli_kcaKKN8GXoxUdyPIz9ME4P= -1,ssc_sli_VFlLQfEII_dCjPOLZCKl1h,
ssc_sli_FQmAUq5mRNGbVih2F3PCCN,ssc_sli_FHA50iTf0YOSaPrq60uYIa,
ssc_sli__d4NvF_TU8xhiPidhlSBeU,ssc_sli_kje3FEfA_VOecqlGobEPlW,
ssc_sli_V2lBgEm_1wOKgP3OF7OhA2,ssc_sli__HZXcTW2uIp1b5VW7Lmaiz,
ssc_sli__iC2umSSBnhLdaou8jCK4Q,ssc_sli__cdqw5QDTiWb_HxgGzJupf,
ssc_sli_VzRYNhOLez0fcahY6OfqAT,ssc_sli_ksyP1mhwOx_gdi_qxA1XwQ,
ssc_sli_FdbT7DDFOod_gD62wqPcy_,ssc_sli_FxDcIIX1_0WChuVyeYIziJ,
ssc_sli_km8PqndzZYCHbPN_lUtQcC,ssc_sli_Fh3EMcmCEi0cfaU6jdkIj2,
ssc_sli_k2mBp0rugDOniPAiyz8Hig,ssc_sli_FPv0_UNPp8__hPT18mmlhp,
ssc_sli_kxwvUNoEGCOiceCilpf1YD,ssc_sli__nuLYOAWg4luhub2duGQQ_,
ssc_sli_kjrjD1N2_uWBXaVD9TSx7N,ssc_sli_VLEO4HXvRlGQaqqGghTyqa,
ssc_sli__kD90nzGGZSGWTWEkw1Cis,ssc_sli_k8wcDa_7rDts_9nPV5dfjq,
ssc_sli_VujW_EuJpidTduLntgaxe6}ssc_sli_Vfu07t_igc0ehHkC_w2Ar_;typedef int32_T(
*ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5)(ssc_sli_FTmXA5ksLdxWam9tKEDDRp const*,
NeDynamicSystemInput const*,ssc_sli_kkoV3MWI3Olsj9ue_OTrKB*);struct
ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv{ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5 mMethods[
ssc_sli_VujW_EuJpidTduLntgaxe6];size_t ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t
ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t mNumAsserts;NeAssertData const*
mAssertData;size_t mNumAssertRanges;NeRange const*mAssertRanges;size_t
mNumInitialAsserts;NeAssertData const*mInitialAssertData;size_t
mNumInitialAssertRanges;NeRange const*mInitialAssertRanges;NeParameterInfo
mParameterInfo;PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;};typedef struct ssc_sli_knlRBEvE2xlTdL9XQDsraA
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO;typedef struct ssc_sli__M0yHGxYdRh6WeZsp03MsF
ssc_sli_ktYRHip3ZVhEdLZEQWORqW;typedef struct ssc_sli__C7xfBs4_wtZdybDh_1S17
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ;typedef union ssc_sli_kEJscBISiC0cW1zDnm5FFI{
PmSparsityPattern mMCON_P;PmRealVector mMCON;PmSparsityPattern mMPAR_P;
PmRealVector mMPAR;PmSparsityPattern mMNL_P;PmRealVector mMNL;
PmSparsityPattern ssc_sli__iV7cpieH5lkhLu3Lg9TbF;PmRealVector
ssc_sli_kpJ_qciQSWpsiPiK3aYpC6;PmSparsityPattern ssc_sli_FCUwBAadDl4jdTbQJs191b
;PmRealVector ssc_sli__4wk9aw_kxhdamxJBndVFp;PmSparsityPattern
ssc_sli_kpP4jzbAmSSabDQ2Rr8bL8;PmRealVector ssc_sli_kKsgUsw2JgtEYPjXL27qpf;
PmRealVector ssc_sli_FisUhCWjCaKZVHMV_vZE5q;PmRealVector mF;PmRealVector
ssc_sli__EEaI0glzV_ziunIayuQB_;PmIntVector mMODE;PmBoolVector mSLF;}
ssc_sli_Vp0c29ygDdlujTOV9DIZY0;typedef enum ssc_sli_VD2_Ev_HuH0of9gNrHze9d{
ssc_sli_VXnsMGX_7cGRb55H42tfn7= -1,ssc_sli_k_8QN9x5_k42cyQrpZzjsI,
ssc_sli_kqMvQKKxuVtEea_8OzY2TM,ssc_sli_VfTboTvpAHCDgqUBkJD5Rl,
ssc_sli_k2Owy_sJ_40uh9KZRFIdY5,ssc_sli_kmQ2_m3O6DG6euIv_XuxVg,
ssc_sli_VQO8dLIZX78oa5taxlg_vo,ssc_sli_V7DyxzVA0QGofTFR6YdqYq,
ssc_sli__DRGltAScIGfeu43CxFuG8,ssc_sli__sxV91jCfEGzYXaVBkddIG,
ssc_sli_k0IoR8Wj3MdBiLa4ZtAvTI,ssc_sli_kFNU_9_j_MOSead4baHt3T,
ssc_sli_Vx3D_PUFnUhXeH6lNfeh3d,ssc_sli__pmgH1Up57xCbH_C454qdO,
ssc_sli_kVzQQaaqlPt8bmsY4qvPjV,ssc_sli_kTfE4dqxl7OZdqxWw7pewy,
ssc_sli_VazOOCfCtUhdYPCvduXfsJ,ssc_sli__a5HvR7wGotUf9fcjCj4Zw,
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C}ssc_sli_FSls2IGSVBpdeeBJHp6ST7;typedef int32_T(
*ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT)(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*,
NeDynamicSystemInput const*,ssc_sli_Vp0c29ygDdlujTOV9DIZY0*);typedef enum
ssc_sli__I1_0bn1tlpndTZaRA_ZPl{ssc_sli_kIVETWACXbp0d94SP8_dc1= -1,
ssc_sli_F5_rBq64Lj4aWXXU0PyiUb,ssc_sli_FshPfGethuxwX9btxT6saT,
ssc_sli__uxzr382yeG7jXfsoRvs2Z}ssc_sli_V79S98fiH1S7byo5F9wnzk;typedef
PmSizeVector*ssc_sli__C96EutllrWlgykXJW4e3Y;struct
ssc_sli_koMvWW1l_F_oi5bwovAr78{PmSparsityPattern*mPattern;};struct
ssc_sli__M0yHGxYdRh6WeZsp03MsF{PmSparsityPattern*mPattern;PmRealVector*mPr;};
struct ssc_sli_knlRBEvE2xlTdL9XQDsraA{ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT mMethods[
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C];ssc_sli_ktYRHip3ZVhEdLZEQWORqW
ssc_sli_kb5sBAIsNGx3h5TSZDK2nO[ssc_sli__uxzr382yeG7jXfsoRvs2Z];
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ*ssc_sli__he79Qtc4y4abmydbMrr9d;size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_k3ro8_fNFeG3YHRPCSyK_y;size_t
ssc_sli_VimjrZhJPvSkgeFbqT7DNg;size_t ssc_sli_Vd47fO4esQxG_HpE1mPb9b;size_t
ssc_sli_F0sp_kii_WGhgeeqy_FSs6;boolean_T ssc_sli_Vq7NNhAfxIO_j9IbOG6sAS;
NeDynamicSystemInputSizes mSizes;ssc_sli__C96EutllrWlgykXJW4e3Y
ssc_sli__jDRUOD243tjgTxKYEsbsv[NE_NUM_DYNAMIC_SYSTEM_INPUT_ID];PmIntVector*
ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*ssc_sli__ysspeBWLwt9fe39xFzdmF;
PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ
ssc_sli_FA2YAvRyL2h_f9kmmok0RW;boolean_T ssc_sli_V6uMeGVfspW_ju_lkeNWOq;};
typedef struct ssc_sli__we9OgtXM80Beq3Pau0ORa ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ;
typedef union ssc_sli_kZbOKlPIFU_2ZqIJ7Wxuxt{PmSparsityPattern mM_P;
PmRealVector mM;PmRealVector mF;PmSparsityPattern
ssc_sli__aw0Y7gxbhS0_LvT4MtW1M;PmRealVector mJ;}ssc_sli_FXl61xRLPE47iP1Q_pvk2u
;typedef enum ssc_sli_V1Ph_XOAJoKRYqSqeTnmEx{ssc_sli_V3bEzwx1u0lOVPYRbuCqcW= -
1,ssc_sli_Fn41P1GumQ42i9T8pr7NwB,ssc_sli_F2Ws5ikk0qOaWyeJpDP8bj,
ssc_sli_FYPImDMfyFhqYmN4WZY0Gv,ssc_sli_kAf_QyKmY34ZVLgh19055f,
ssc_sli_kKEx7mxjxwKzZTWlJaaDbC,ssc_sli_FEtyoYrn_ttHf99kNFRkob}
ssc_sli_FD25vRYmqOCeX9QMP0Yb86;typedef int32_T(*ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW
)(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*,NeDynamicSystemInput const*,
ssc_sli_FXl61xRLPE47iP1Q_pvk2u*);struct ssc_sli__we9OgtXM80Beq3Pau0ORa{
ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW mMethods[ssc_sli_FEtyoYrn_ttHf99kNFRkob];size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;
PmIntVector*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;};typedef struct
ssc_sli_VAuysnx4S7lBcPba8gefmX ssc_sli_kTxQKABEQA__dXDaX6_8lx;struct
ssc_sli_VAuysnx4S7lBcPba8gefmX{NeDynamicSystemInputSizes mSizes;PmIntVector*
ssc_sli_FtEj7nrAMw8EX1WVETDajL;ssc_sli_FTmXA5ksLdxWam9tKEDDRp*
ssc_sli_ki5qToeyQ7tPheF11zZqgB;size_t ssc_sli__MBuKzK8US4ghTfNeJrQSZ;
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO**ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH;
ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ*ssc_sli__Rb1pGJJ50KLfagQM39h_L;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;
mc_F9HbKNDZMeOehmlKWGUdea*(*ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,size_t mc_k0zHKt3B8EloaeisOobs3u);void(*
ssc_sli_kkIk538kkH4PjT_BdbbDnq)(ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,NeDynamicSystemInput**ssc_sli_FI3oLMQhBMhqhTN_ohgA9w
);void(*mDestroy)(ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM);};
typedef struct ssc_sli_kHIFobdjcPOC_L80URMnml ssc_sli_keyt_1XV42W_WHpMBhjyZm;
typedef struct ssc_sli_VCmJfYBdjb4v_TzTIhsRnD ssc_sli_VyiY43pddkdAdm8k5LKgo1;
struct ssc_sli_kHIFobdjcPOC_L80URMnml{ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
ssc_sli_V1mPIKX1Qix3hqyCWyWx3V;size_t ssc_sli_k3mbO8G__i_whL1wWV_J6X;double
ssc_sli__BzytCIJqpK6X9hlBST23v;ssc_sli_VyiY43pddkdAdm8k5LKgo1*mData;
PmSizeVector const*ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u;PmIntVector const*
ssc_sli_FfCc3GD8SitwaPgm1V8xBZ;void(*ssc_sli_FPn9er7iSOhfc1umT1tmGB)(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k);boolean_T(*mStart)(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k);void(*
ssc_sli_VC5mmdlw_3dpjqitDYBJ94)(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k);mc_kQtOKCqS08dIbumyDnHNDL(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k);void(*ssc_sli_kKZbL_4KD_dlfXO9Z4Zely)(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc);mc_kQtOKCqS08dIbumyDnHNDL(*
ssc_core__A0n8EhE_GdLWudFqHsqyZ)(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*ssc_sli_VWb7PgNmUAW6_a6WS7zTSc);
void(*mPushInfo)(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,IterationsLogCore*
ssc_sli_kFG1cmkvYqxhhXEyS95YdT);mc_F9HbKNDZMeOehmlKWGUdea const*(*
ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(ssc_sli_keyt_1XV42W_WHpMBhjyZm*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*ssc_sli_kkIk538kkH4PjT_BdbbDnq)(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
NeDynamicSystemInput const*ssc_sli_Fi_du5uFlgGne5wvGXKElE);void(*mDestroy)(
ssc_sli_keyt_1XV42W_WHpMBhjyZm*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);};
ssc_sli_keyt_1XV42W_WHpMBhjyZm*ssc_sli__8k0JPxblNCkbDpc0SQhyu(const
ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM,const
NeSolverParameters ssc_core_kv7GnpbgsfSGjTKLxq5SvA,const McLinearAlgebraFactory
*la,const ssc_core_VMObUicZgDGkXuH3R8jgeY ssc_core_VkEZfX8sDrW2fPxW5Ht5d2);
ssc_sli_keyt_1XV42W_WHpMBhjyZm*ssc_sli__KMRq9MhmPGtc5GixC6jwv(const
ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM,const
NeSolverParameters ssc_core_kv7GnpbgsfSGjTKLxq5SvA);
#include "math.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
#include "mc_std.h"
typedef struct mc_kliG8gHxBrxqj5ltdQ3DJD mc_kJsFDy1CO0l5dyXhvSJuDN;typedef
struct mc_VhjphwCXH7__fHKgu37JRE mc_VGNLn3tcnxGsZHDhbVLyGd;struct
mc_VhjphwCXH7__fHKgu37JRE{mc_kJsFDy1CO0l5dyXhvSJuDN*mPrivateData;void(*
mc_F8Dcwq9WFktdeeDmRbw6aA)(mc_VGNLn3tcnxGsZHDhbVLyGd*mc_F_TJDueNLJOndXKGCcZHYX
);void(*mc__oYQIQhVQj86gqh3GNzLwi)(mc_VGNLn3tcnxGsZHDhbVLyGd*
mc_F_TJDueNLJOndXKGCcZHYX,int32_T mc_k4fezk4PyMt9aaqZChy_kL);
McLinearAlgebraStatus(*mc_VrMh138Yw_4dYmfdgfHovn)(mc_VGNLn3tcnxGsZHDhbVLyGd*
mc_F_TJDueNLJOndXKGCcZHYX,real_T const*mc_kcMuz7xytzhifPfhbjJNYL);void(*mSolve
)(mc_VGNLn3tcnxGsZHDhbVLyGd*mc_F_TJDueNLJOndXKGCcZHYX,real_T*x,real_T const*b)
;void(*mc_kgs20c5hABGVcq5FPAxzvT)(mc_VGNLn3tcnxGsZHDhbVLyGd*
mc_F_TJDueNLJOndXKGCcZHYX,real_T const*mc_kcMuz7xytzhifPfhbjJNYL,real_T*y,
real_T const*b);void(*mDestructor)(mc_VGNLn3tcnxGsZHDhbVLyGd*);};typedef struct
mc_F_cy17uGruGSdyws3J3hSC mc_kZnCLv7SarWzW1JVcSryvy;typedef struct
mc_VddjRb2VexhLePvu4fFNXS mc_VbdKn6rLejW9YT9HeL_lir;struct
mc_VddjRb2VexhLePvu4fFNXS{mc_kZnCLv7SarWzW1JVcSryvy*mPrivateData;void*(*
mc_kEFAsWMpsu_XgPKb5Ge_UO)(mc_VbdKn6rLejW9YT9HeL_lir*,real_T const*
mc_kcMuz7xytzhifPfhbjJNYL,real_T*y,real_T const*b);void*(*
mc_kgs20c5hABGVcq5FPAxzvT)(void*);McLinearAlgebraStatus(*
mc__fvz26Zk1fKGdulV_g_F5N)(mc_VbdKn6rLejW9YT9HeL_lir*);void(*mDestructor)(
mc_VbdKn6rLejW9YT9HeL_lir*);};mc_VbdKn6rLejW9YT9HeL_lir*
mc_FEm6WJeLOdORjPVbu__PTt(mc_F9HbKNDZMeOehmlKWGUdea*mc_VpSwxG2uxL4JaLmMQqUqTJ,
PmSparsityPattern const*mc_FNLG4N0Qc3OxdmBVwutDsy,int32_T
mc_F5WfvJZgg6pBiHOz_1m50n);typedef void*(*mc_FkLPw5qSgbtfXPjiTTsMib)(void*);
typedef struct mc__X_HHcuYRKSoeadMsf6h0a{void*mc_kJaPD0SF9bKtdHPQJyrhtv;size_t
mc_Vbr5eqH3ENhKgPrE0rHGwZ;}mc_kW6ayL4fFaxvcajE0EcNHC;typedef struct
mc_VUoa7yJ8oPdcVyAh1JpD3y mc_kTtzoaRBzntliy1LEJfc0r;typedef struct
mc_F4Uk_muRArKTWiMEBFR7PO{mc_kTtzoaRBzntliy1LEJfc0r*(*
mc__wc2tCUDwk87X1QDBaJiKw)(mc_FkLPw5qSgbtfXPjiTTsMib mc_kYZL2_ypSZp_beKV07wnOI
,size_t n);int(*mc_F5UYWROxhuW7bXP2qFH6l5)(mc_kTtzoaRBzntliy1LEJfc0r*tm,void*
arg);void(*mc_FxdfIsrDZ_OpXHH2KZQasB)(mc_kTtzoaRBzntliy1LEJfc0r*tm);}
mc_FEi_3IF8psl_XH4yBOu3mh;typedef struct mc__GU3aKCcfhldXiBd1lQ_fp
mc__zHJTsqokd8xjuXHijLpG6;void mc_register_thread_support(
mc_FEi_3IF8psl_XH4yBOu3mh*mc__LOE3NllYqGGcHiwg6fX5o);mc_FEi_3IF8psl_XH4yBOu3mh
*mc_FEl3DXb7ypKke5uZ90Xlyw(void);mc__zHJTsqokd8xjuXHijLpG6*
mc_V4Y8IvqWFgGLZ1YthqZz6A(size_t mc_F5WfvJZgg6pBiHOz_1m50n);void
mc_kbfEOfn7DOGmfyLmEcjphP(mc__zHJTsqokd8xjuXHijLpG6*mc_FTrf1ab_5kp6a9RTKMrrkU)
;void mc__oQL_XqhEStTZ5g5jEdh6_(mc__zHJTsqokd8xjuXHijLpG6*
mc_FTrf1ab_5kp6a9RTKMrrkU,size_t id);
#include "mc_std.h"
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "ne_std.h"
typedef struct ssc_sli__nZTUaqBX_8WjLa9SNF8OI ssc_sli_FzLpHYC8pbORfLs1HQ5tx8;
typedef struct ssc_sli_VM8UVTrsCYCuX54rf7azJe ssc_sli_VUa2TSfWIUlueyhCKkORiK;
struct ssc_sli_VM8UVTrsCYCuX54rf7azJe{ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*
mPrivateData;PmSparsityPattern const*mPattern;NeDynamicSystemInputSizes mSizes
;PmIntVector const*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector const*
ssc_sli__ysspeBWLwt9fe39xFzdmF;PmIntVector const*
ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector const*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector const*
ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;void(*
ssc_sli_k98doWegV6xNVLpUJF775m)(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_Vewa2aEFH2p4eyRGN0BdA4)
(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_FrnJvV2zDsWGhiwD7eB0IS)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmIntVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli__WkMCltDVadkZuQRjGYmXq)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector const*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_FsX__XbkKPdEYTPBZsyQSK)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(ssc_sli_VUa2TSfWIUlueyhCKkORiK*);};
ssc_sli_VUa2TSfWIUlueyhCKkORiK*ssc_sli_kU6RGLNSfLduZy4lmRaMio(const
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO*ssc_sli__IqjUOFkW8_nauH_Moi97j,real_T
mc_kTckK8teUpOlhm8Ippu8XP);static void ssc_sli__XIlxPES1MdkcPvc6Ha5NE(
NeDynamicSystemInput const*ssc_sli_VlvyXd0hDih9fH2Eq73cVl,NeDynamicSystemInput
const*ssc_sli__d4y_aGJIaKJ_aX3hYAaWm,ssc_sli__C96EutllrWlgykXJW4e3Y const*
ssc_sli_VoES6scNMD_0h97GdxUHNb){size_t i=0;(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_Q]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mQ.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mQ.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_Q]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_M]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mM.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mM.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_M]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_T]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mT.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mT.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_T]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_U]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mU.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mU.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_U]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_V]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mV.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mV.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_V]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mX.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mX.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_D]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mD.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mD.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_D]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_E]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mE.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mE.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_E]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_CR]->mN;++i){(void)0
;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mCR.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mCR.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_CR]->mX[i]];}
(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_CI]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mCI.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mCI.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_CI]->mX[i]];}(
void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_A]
->mN;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mA.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mA.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_A]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_J]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mJ.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mJ.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_J]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_W]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mW.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mW.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_W]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_S]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mS.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mS.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_S]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_P_L]->
mN;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mP_L.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mP_L.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_P_L]->mX[i]];}(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_P_I]->mN;++i){(void)
0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mP_I.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mP_I.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_P_I]->mX[i]]
;}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_P_J]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mP_J.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mP_J.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_P_J]->mX[i]]
;}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_P_R]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mP_R.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mP_R.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_P_R]->mX[i]]
;}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_DP_L]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mDP_L.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mDP_L.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_DP_L]->mX[i
]];}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_DP_I]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mDP_I.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mDP_I.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_DP_I]->mX[i
]];}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_DP_J]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mDP_J.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mDP_J.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_DP_J]->mX[i
]];}(void)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_DP_R]->mN;++i){(void)0;;
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mDP_R.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->
mDP_R.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_DP_R]->mX[i
]];}}static void ssc_sli_k0ZiVN_UeCWxhPUkrd_z0Z(NeDynamicSystemInput const*
ssc_sli_VlvyXd0hDih9fH2Eq73cVl,NeDynamicSystemInput const*
ssc_sli__d4y_aGJIaKJ_aX3hYAaWm,ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*
ssc_sli_VuuDDstKjlCvZPAShodhzy){size_t i=0;ssc_sli__C96EutllrWlgykXJW4e3Y const
*ssc_sli_VoES6scNMD_0h97GdxUHNb=ssc_sli_VuuDDstKjlCvZPAShodhzy->
ssc_sli__jDRUOD243tjgTxKYEsbsv;(void)0;;for(i=0;i<
ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mN;++i){(void)0;
;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mX.mX[i]=ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mX.
mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mX[i]];}(void
)0;;for(i=0;i<ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_M]->mN
;++i){(void)0;;ssc_sli__d4y_aGJIaKJ_aX3hYAaWm->mM.mX[i]=
ssc_sli_VlvyXd0hDih9fH2Eq73cVl->mM.mX[ssc_sli_VoES6scNMD_0h97GdxUHNb[
NE_DYNAMIC_SYSTEM_INPUT_ID_M]->mX[i]];}}struct ssc_sli_FffXXF558s_PXmpCNVzFA_{
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*ssc_sli_kHltm73fJGSfa1UuwwRiII;
NeDynamicSystemInput*ssc_sli_FkEy9deu86hada0092eFGq;
ssc_sli_VUa2TSfWIUlueyhCKkORiK*ssc_sli_FFdBBQGxAyxCjazMctyaap;PmIntVector*
ssc_sli_VCsNwCsvXyG1Z1cc4Q7KF4;PmIntVector*ssc_sli__dwI5g8rLXSKVqejogItfe;
PmRealVector*ssc_sli_V0UUcX83oJCyVDQrAdN4ai;PmRealVector*
ssc_sli__HKFYzrt3RxcZqzFAcqapU;PmRealVector*ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ;
PmRealVector*ssc_sli_Vb5HRZnh56C1XuonP51flj;PmRealVector*
ssc_sli__MFvUfV7xJWQWygMM1Eoiw;size_t ssc_sli__NwRaGOaLsKY_5EufWPIPx;};typedef
struct ssc_sli_FffXXF558s_PXmpCNVzFA_ ssc_sli_VYd6QxXL9z8ba9yU7zI27e;struct
ssc_sli_VCmJfYBdjb4v_TzTIhsRnD{ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
ssc_sli_V1mPIKX1Qix3hqyCWyWx3V;mc_F9HbKNDZMeOehmlKWGUdea*
ssc_sli_kGNveH_k1RhUeiz9X00EeL;mc_VbdKn6rLejW9YT9HeL_lir*
ssc_sli__FZ4dAYrXe89eP_Ma5XLmn;PmIntVector*ssc_sli_k7koSU9rCoSYa5RERgn6F_;
PmSizeVector*ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u;PmIntVector*
ssc_sli_FfCc3GD8SitwaPgm1V8xBZ;ssc_sli_VYd6QxXL9z8ba9yU7zI27e**
ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh;PmSparsityPattern*
ssc_sli_k2MW3X1xMDW7hLRm_yMLlx;PmRealVector*ssc_sli_kvOBG5idQvpEZXzSmLOxzp;
PmRealVector*ssc_sli__C2ViEySBhtxXuN5TLp4Eq;PmRealVector*
ssc_sli__WoQw6DubplSaunXCUqnIy;boolean_T ssc_sli_FnNKu1U4IT8IV1Z4Y3UpvY;real_T
ssc_core_VHpOBeHDk6S_fiGSsgZ9AB;size_t ssc_sli_k2JWfv8acYtBa1zEg5kgjp;
mc__zHJTsqokd8xjuXHijLpG6*ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a;NeDynamicSystemInput
const*ssc_sli_FM2H_BztBjGNWyxKnA4Dza;mc_kQtOKCqS08dIbumyDnHNDL
ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf;boolean_T ssc_sli__KMNpQxC6gGiiTvIfQRMrd;void*
ssc_sli__j2xGhmJwV0Ij9azHYu_DJ;mc_kTtzoaRBzntliy1LEJfc0r*
ssc_sli_kbNdhAsAytKmVyMzjNTDEY;};static void ssc_sli_khP103Wy3S_1Zu2tn1Bqb0(
ssc_sli_VyiY43pddkdAdm8k5LKgo1*mc__d1alWYexptL_X5HTFhbNK,NeDynamicSystemInput
const*ssc_core_kNbvLmFI_EtAay5OpgNJFz){ssc_sli_FTmXA5ksLdxWam9tKEDDRp const*
ssc_sli_kvqhn7Vn4RdMfmSLz9521V=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_V1mPIKX1Qix3hqyCWyWx3V->ssc_sli_ki5qToeyQ7tPheF11zZqgB;size_t
ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT,i;size_t ssc_sli_Fk8l_ZcbD8OSXT827HJYyP=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k7koSU9rCoSYa5RERgn6F_->mN;if(
ssc_sli_Fk8l_ZcbD8OSXT827HJYyP==0){return;}ssc_sli_kvqhn7Vn4RdMfmSLz9521V->
mMethods[ssc_sli_VFlLQfEII_dCjPOLZCKl1h](ssc_sli_kvqhn7Vn4RdMfmSLz9521V,
ssc_core_kNbvLmFI_EtAay5OpgNJFz,(ssc_sli_kkoV3MWI3Olsj9ue_OTrKB*)
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k7koSU9rCoSYa5RERgn6F_);(void)0;for(i=0;i<
ssc_sli_Fk8l_ZcbD8OSXT827HJYyP;i++){ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=(size_t)
ssc_sli_kvqhn7Vn4RdMfmSLz9521V->ssc_sli__g89dzKHN9WyW1QK3EhGT2->mX[i];
ssc_core_kNbvLmFI_EtAay5OpgNJFz->mM.mX[ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT]=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k7koSU9rCoSYa5RERgn6F_->mX[i];}}static
mc_kQtOKCqS08dIbumyDnHNDL ssc_sli_FmTO1Vc0lE_uautI1klGsM(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_sli_kgSURVtfWz4IgH6q0OEa5O,
NeDynamicSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz){(void)
ssc_sli_kgSURVtfWz4IgH6q0OEa5O;(void)ssc_core_kNbvLmFI_EtAay5OpgNJFz;return
mc_FFaaXY_gkbSTcyLBvtfrzS;}static void ssc_sli_VbuLgMdMkftWbDBI64mNFu(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_sli_kgSURVtfWz4IgH6q0OEa5O,
NeDynamicSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz){
ssc_sli_khP103Wy3S_1Zu2tn1Bqb0(ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData,
ssc_core_kNbvLmFI_EtAay5OpgNJFz);}static boolean_T
ssc_sli_FZn4n20IMS_igXtD7F_tjD(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_sli_kgSURVtfWz4IgH6q0OEa5O,NeDynamicSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz){(void)ssc_sli_kgSURVtfWz4IgH6q0OEa5O;(void)
ssc_core_kNbvLmFI_EtAay5OpgNJFz;return false;}static void
ssc_sli_FyMIIl6UzqGoga4nFr1i1w(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_sli_kgSURVtfWz4IgH6q0OEa5O,NeDynamicSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz,PmRealVector const*
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc){(void)ssc_sli_kgSURVtfWz4IgH6q0OEa5O;(void)
ssc_core_kNbvLmFI_EtAay5OpgNJFz;(void)ssc_sli_VWb7PgNmUAW6_a6WS7zTSc;}static
boolean_T ssc_sli_Vpg51Ld2Pd8Ac1OZ2oGG2y(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_FfDTppU8N_tOWuLK37x_08){size_t i;
size_t n=pm__hARyx1bZBxVj1boVQqdtV->mN;for(i=0;i<n;++i){if(fabs(
pm__hARyx1bZBxVj1boVQqdtV->mX[i])>mc_FfDTppU8N_tOWuLK37x_08){return false;}}
return true;}static void*ssc_sli__NDnSrWfdMxxdeMWL6o3AB(void*
ssc_sli__hcrniCIqZxXXuMV0R_2Cv){mc_kW6ayL4fFaxvcajE0EcNHC*arg=(
mc_kW6ayL4fFaxvcajE0EcNHC*)ssc_sli__hcrniCIqZxXXuMV0R_2Cv;size_t id=arg->
mc_Vbr5eqH3ENhKgPrE0rHGwZ;ssc_sli_VyiY43pddkdAdm8k5LKgo1*
mc__d1alWYexptL_X5HTFhbNK=(ssc_sli_VyiY43pddkdAdm8k5LKgo1*)arg->
mc_kJaPD0SF9bKtdHPQJyrhtv;NeDynamicSystemInput const*
ssc_sli_VBuhbkXFrWxWZmu14XGkar=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FM2H_BztBjGNWyxKnA4Dza;PmRealVector*ssc_sli_F3T120KFitpvdP4FoDXoNw=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__C2ViEySBhtxXuN5TLp4Eq;PmRealVector*
ssc_sli__D14oiMRgxh6eisUvfuuQI=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_kvOBG5idQvpEZXzSmLOxzp;PmRealVector*ssc_sli__YuAqHlYlJGxZT_WQnEnVC=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__WoQw6DubplSaunXCUqnIy;
mc_VbdKn6rLejW9YT9HeL_lir*ssc_sli__fu9xGX4cndg_DqF6W0B9m=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__FZ4dAYrXe89eP_Ma5XLmn;boolean_T
mc_kw6NOvmP0mtTgTawDfvetp=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FnNKu1U4IT8IV1Z4Y3UpvY;real_T mc_FfDTppU8N_tOWuLK37x_08=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VHpOBeHDk6S_fiGSsgZ9AB;
ssc_sli_VYd6QxXL9z8ba9yU7zI27e*d=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh[id];PmRealVector*y=d->
ssc_sli_V0UUcX83oJCyVDQrAdN4ai;PmRealVector*ssc_sli_kR3Z4Y4Z1khGfi2iVdFGa1=d->
ssc_sli__HKFYzrt3RxcZqzFAcqapU;PmRealVector*x=d->
ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ;PmRealVector*mc_Fe6copTTRcKEayCm87ABO_=d->
ssc_sli_Vb5HRZnh56C1XuonP51flj;PmRealVector*ssc_sli_Vmxc5rL0GBpXb1KtEBznex=d->
ssc_sli__MFvUfV7xJWQWygMM1Eoiw;PmIntVector*ssc_sli_kZs6T7VbB0OuXPqQgNHOl_=d->
ssc_sli__dwI5g8rLXSKVqejogItfe;PmIntVector*ssc_sli_Vz9KbshvAa8ddXmHvavpWk=d->
ssc_sli_VCsNwCsvXyG1Z1cc4Q7KF4;NeDynamicSystemInput*mc__XfQXtB6cfd9fyc_v3eEup=
d->ssc_sli_FkEy9deu86hada0092eFGq;ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
ssc_sli_VHx3JOvtgIK3VPttL15wzm=d->ssc_sli_FFdBBQGxAyxCjazMctyaap;size_t
mc_kF77yGs8Y4pbZunORy8X8l=d->ssc_sli__NwRaGOaLsKY_5EufWPIPx;size_t
mc_FPwVUAP_do0ogeBnBjppr5,i,k;ssc_sli__XIlxPES1MdkcPvc6Ha5NE(
ssc_sli_VBuhbkXFrWxWZmu14XGkar,mc__XfQXtB6cfd9fyc_v3eEup,d->
ssc_sli_kHltm73fJGSfa1UuwwRiII->ssc_sli__jDRUOD243tjgTxKYEsbsv);(
ssc_sli_VHx3JOvtgIK3VPttL15wzm)->ssc_sli_FsX__XbkKPdEYTPBZsyQSK((
ssc_sli_VHx3JOvtgIK3VPttL15wzm),(mc__XfQXtB6cfd9fyc_v3eEup),(x));
pm_rv_equals_rv(y,x);for(mc_FPwVUAP_do0ogeBnBjppr5=0;mc_FPwVUAP_do0ogeBnBjppr5
<mc_kF77yGs8Y4pbZunORy8X8l;++mc_FPwVUAP_do0ogeBnBjppr5){McLinearAlgebraStatus
result=MC_LA_OK;mc_VIFqLU9Z6UtwXDWPnvd_zg(ssc_sli_kR3Z4Y4Z1khGfi2iVdFGa1,x,y);
(ssc_sli_VHx3JOvtgIK3VPttL15wzm)->ssc_sli_FrnJvV2zDsWGhiwD7eB0IS((
ssc_sli_VHx3JOvtgIK3VPttL15wzm),(ssc_sli_kR3Z4Y4Z1khGfi2iVdFGa1),(
mc__XfQXtB6cfd9fyc_v3eEup),(mc_Fe6copTTRcKEayCm87ABO_));
mc_V7hiVZfxKK0Uj9rPai4LYw(mc_Fe6copTTRcKEayCm87ABO_,-1.0);for(i=0;i<
mc_Fe6copTTRcKEayCm87ABO_->mN;i++){k=ssc_sli_kZs6T7VbB0OuXPqQgNHOl_->mX[i];
ssc_sli_F3T120KFitpvdP4FoDXoNw->mX[k]=mc_Fe6copTTRcKEayCm87ABO_->mX[i];}(
ssc_sli_VHx3JOvtgIK3VPttL15wzm)->ssc_sli_k98doWegV6xNVLpUJF775m((
ssc_sli_VHx3JOvtgIK3VPttL15wzm),(mc__XfQXtB6cfd9fyc_v3eEup),(
ssc_sli_Vmxc5rL0GBpXb1KtEBznex));for(i=0;i<ssc_sli_Vmxc5rL0GBpXb1KtEBznex->mN;
i++){k=ssc_sli_Vz9KbshvAa8ddXmHvavpWk->mX[i];ssc_sli__D14oiMRgxh6eisUvfuuQI->
mX[k]=ssc_sli_Vmxc5rL0GBpXb1KtEBznex->mX[i];}mc__oQL_XqhEStTZ5g5jEdh6_(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a,id);if(id==0){if(!
mc_kw6NOvmP0mtTgTawDfvetp&&ssc_sli_Vpg51Ld2Pd8Ac1OZ2oGG2y(
ssc_sli_F3T120KFitpvdP4FoDXoNw,mc_FfDTppU8N_tOWuLK37x_08)){
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__KMNpQxC6gGiiTvIfQRMrd=true;}
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__j2xGhmJwV0Ij9azHYu_DJ=
ssc_sli__fu9xGX4cndg_DqF6W0B9m->mc_kEFAsWMpsu_XgPKb5Ge_UO(
ssc_sli__fu9xGX4cndg_DqF6W0B9m,ssc_sli__D14oiMRgxh6eisUvfuuQI->mX,
ssc_sli__YuAqHlYlJGxZT_WQnEnVC->mX,ssc_sli_F3T120KFitpvdP4FoDXoNw->mX);}
mc__oQL_XqhEStTZ5g5jEdh6_(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a,id);if(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__KMNpQxC6gGiiTvIfQRMrd){break;}{mc_kW6ayL4fFaxvcajE0EcNHC
ssc_sli_VYHRroM95IlFXeE0b0FZ5S;ssc_sli_VYHRroM95IlFXeE0b0FZ5S.
mc_kJaPD0SF9bKtdHPQJyrhtv=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__j2xGhmJwV0Ij9azHYu_DJ;ssc_sli_VYHRroM95IlFXeE0b0FZ5S.
mc_Vbr5eqH3ENhKgPrE0rHGwZ=id;ssc_sli__fu9xGX4cndg_DqF6W0B9m->
mc_kgs20c5hABGVcq5FPAxzvT((void*)&ssc_sli_VYHRroM95IlFXeE0b0FZ5S);if(id==0){
result=(ssc_sli__fu9xGX4cndg_DqF6W0B9m)->mc__fvz26Zk1fKGdulV_g_F5N((
ssc_sli__fu9xGX4cndg_DqF6W0B9m));if(result!=MC_LA_OK){
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf=
mc_VUd8H_Dz0yp8cmQqTd7DxF;}}}mc__oQL_XqhEStTZ5g5jEdh6_(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a,id);if(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf!=
mc_FFaaXY_gkbSTcyLBvtfrzS){break;}if(id==0){mc_FGkd8Riw6p4eaDCAbwBVPv(&(
ssc_sli_VBuhbkXFrWxWZmu14XGkar->mX),ssc_sli__YuAqHlYlJGxZT_WQnEnVC);
ssc_sli_khP103Wy3S_1Zu2tn1Bqb0(mc__d1alWYexptL_X5HTFhbNK,
ssc_sli_VBuhbkXFrWxWZmu14XGkar);}mc__oQL_XqhEStTZ5g5jEdh6_(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a,id);
ssc_sli_k0ZiVN_UeCWxhPUkrd_z0Z(ssc_sli_VBuhbkXFrWxWZmu14XGkar,
mc__XfQXtB6cfd9fyc_v3eEup,d->ssc_sli_kHltm73fJGSfa1UuwwRiII);(
ssc_sli_VHx3JOvtgIK3VPttL15wzm)->ssc_sli_FsX__XbkKPdEYTPBZsyQSK((
ssc_sli_VHx3JOvtgIK3VPttL15wzm),(mc__XfQXtB6cfd9fyc_v3eEup),(y));}return NULL;
}static mc_kQtOKCqS08dIbumyDnHNDL ssc_sli_kQWny1CfzV4XWuuKJEPS8_(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_sli_kgSURVtfWz4IgH6q0OEa5O,
NeDynamicSystemInput const*ssc_sli_VBuhbkXFrWxWZmu14XGkar,PmRealVector const*
ssc_sli_VWb7PgNmUAW6_a6WS7zTSc){ssc_sli_VyiY43pddkdAdm8k5LKgo1*
mc__d1alWYexptL_X5HTFhbNK=ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData;
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf=
mc_FFaaXY_gkbSTcyLBvtfrzS;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__KMNpQxC6gGiiTvIfQRMrd=false;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FM2H_BztBjGNWyxKnA4Dza=ssc_sli_VBuhbkXFrWxWZmu14XGkar;
ssc_sli_khP103Wy3S_1Zu2tn1Bqb0(mc__d1alWYexptL_X5HTFhbNK,
ssc_sli_VBuhbkXFrWxWZmu14XGkar);{mc_FEi_3IF8psl_XH4yBOu3mh*
ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A=mc_FEl3DXb7ypKke5uZ90Xlyw();
ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A->mc_F5UYWROxhuW7bXP2qFH6l5(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kbNdhAsAytKmVyMzjNTDEY,(void*)
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData);}return(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf!=mc_FFaaXY_gkbSTcyLBvtfrzS||
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_FnNKu1U4IT8IV1Z4Y3UpvY)?
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kXW6Mdj97_S_eD2GlA7Jlf:(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__KMNpQxC6gGiiTvIfQRMrd?
mc_FFaaXY_gkbSTcyLBvtfrzS:mc_VW_0L0rb93GgXq8_OmdwHv);}static void
ssc_sli_V_21GLcjvt0bjD72k9siA5(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k){(void)ssc_core_V8a_FQ2T6YWLgu_s5UfAPx;(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;}static void ssc_sli__oir0sV2pgt9YD2k_Pe5GP(
ssc_sli_keyt_1XV42W_WHpMBhjyZm const*ssc_sli_kgSURVtfWz4IgH6q0OEa5O,
IterationsLogCore*ssc_sli_kFG1cmkvYqxhhXEyS95YdT){(void)
ssc_sli_kgSURVtfWz4IgH6q0OEa5O;(void)ssc_sli_kFG1cmkvYqxhhXEyS95YdT;}static
void ssc_sli___RmjGx3UPSBg1_RLQgcC5(ssc_sli_VYd6QxXL9z8ba9yU7zI27e*d){
PmAllocator*a=pm_default_allocator();pm_destroy_real_vector(d->
ssc_sli__MFvUfV7xJWQWygMM1Eoiw,a);pm_destroy_real_vector(d->
ssc_sli_Vb5HRZnh56C1XuonP51flj,a);pm_destroy_real_vector(d->
ssc_sli_V0UUcX83oJCyVDQrAdN4ai,a);pm_destroy_real_vector(d->
ssc_sli__HKFYzrt3RxcZqzFAcqapU,a);pm_destroy_real_vector(d->
ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ,a);neu_destroy_dynamic_system_input(d->
ssc_sli_FkEy9deu86hada0092eFGq,a);if(d->ssc_sli_FFdBBQGxAyxCjazMctyaap){(d->
ssc_sli_FFdBBQGxAyxCjazMctyaap)->mDestroy((d->ssc_sli_FFdBBQGxAyxCjazMctyaap))
;}pm_destroy_int_vector(d->ssc_sli_VCsNwCsvXyG1Z1cc4Q7KF4,a);
pm_destroy_int_vector(d->ssc_sli__dwI5g8rLXSKVqejogItfe,a);{void*const
ssc_sli_F9VUARl_s_K6dyvx7TZlbh=(d);PmAllocator*const
ssc_sli_Ftqd5xeq_jOfiHncQ88lYi=(a);if(ssc_sli_F9VUARl_s_K6dyvx7TZlbh){(
ssc_sli_Ftqd5xeq_jOfiHncQ88lYi)->mFreeFcn(ssc_sli_Ftqd5xeq_jOfiHncQ88lYi,
ssc_sli_F9VUARl_s_K6dyvx7TZlbh);}};}static ssc_sli_VYd6QxXL9z8ba9yU7zI27e**
ssc_sli__SAkqUcsNWl7V1RFCBQPxt(PmSparsityPattern**mc_FNLG4N0Qc3OxdmBVwutDsy,
ssc_sli_kTxQKABEQA__dXDaX6_8lx const*mc__JuAUR_Sob8_WqDjXwmJgM,
NeSolverParameters const ssc_core_kv7GnpbgsfSGjTKLxq5SvA){PmAllocator*a=
pm_default_allocator();PmSparsityPattern*ssc_sli_k26neMO50Cl4YPqZl_TrcK;size_t
ssc_core_V5LBNJCbhICNbmMG_hLaZ6=mc__JuAUR_Sob8_WqDjXwmJgM->mSizes.mSizes[
NE_DYNAMIC_SYSTEM_INPUT_ID_X];size_t ssc_sli_kNgcOktCtQxdYedrGvFn5i=0,
ssc_core_kUQBO1dSP8_IVqRAUx4R8G=0;size_t i;size_t
ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ=mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli__MBuKzK8US4ghTfNeJrQSZ;real_T ssc_core__lU1mWENxFpCeio7tYki0i=
ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mLocalSolverSampleTime;
ssc_sli_VYd6QxXL9z8ba9yU7zI27e**mc__d1alWYexptL_X5HTFhbNK;
mc__d1alWYexptL_X5HTFhbNK=(ssc_sli_VYd6QxXL9z8ba9yU7zI27e**)(((a)->mCallocFcn(
(a),(sizeof(ssc_sli_VYd6QxXL9z8ba9yU7zI27e*)),(ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ)
)));for(i=0;i<ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ;i++){
ssc_sli_VYd6QxXL9z8ba9yU7zI27e*d=(ssc_sli_VYd6QxXL9z8ba9yU7zI27e*)(((a)->
mCallocFcn((a),(sizeof(ssc_sli_VYd6QxXL9z8ba9yU7zI27e)),(1))));d->
ssc_sli_kHltm73fJGSfa1UuwwRiII=mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i];d->ssc_sli_FkEy9deu86hada0092eFGq=
neu_create_dynamic_system_input(mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i]->mSizes,a);d->ssc_sli_FFdBBQGxAyxCjazMctyaap
=ssc_sli_kU6RGLNSfLduZy4lmRaMio(mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i],1.0/ssc_core__lU1mWENxFpCeio7tYki0i);if(
ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mDoFixedCost){d->
ssc_sli__NwRaGOaLsKY_5EufWPIPx=ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mMaxNonlinIter;
}else{d->ssc_sli__NwRaGOaLsKY_5EufWPIPx=100;}{PmSparsityPattern const*
mc_FNLG4N0Qc3OxdmBVwutDsy=d->ssc_sli_FFdBBQGxAyxCjazMctyaap->mPattern;size_t
ssc_sli___ECRgjqShlp_PytRplerL=((size_t)(((mc_FNLG4N0Qc3OxdmBVwutDsy)->mJc[(
mc_FNLG4N0Qc3OxdmBVwutDsy)->mNumCol])));size_t ssc_sli_k11FwSWXZPtxXPZ94a_Mbu=
mc_FNLG4N0Qc3OxdmBVwutDsy->mNumRow;size_t ssc_sli_VWI2mfRhUISTWTZpjWuG2i=
mc_FNLG4N0Qc3OxdmBVwutDsy->mNumCol;d->ssc_sli_V0UUcX83oJCyVDQrAdN4ai=
pm_create_real_vector(ssc_sli_VWI2mfRhUISTWTZpjWuG2i,a);d->
ssc_sli__HKFYzrt3RxcZqzFAcqapU=pm_create_real_vector(
ssc_sli_VWI2mfRhUISTWTZpjWuG2i,a);d->ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ=
pm_create_real_vector(ssc_sli_VWI2mfRhUISTWTZpjWuG2i,a);d->
ssc_sli_Vb5HRZnh56C1XuonP51flj=pm_create_real_vector(
ssc_sli_k11FwSWXZPtxXPZ94a_Mbu,a);d->ssc_sli__MFvUfV7xJWQWygMM1Eoiw=
pm_create_real_vector(ssc_sli___ECRgjqShlp_PytRplerL,a);d->
ssc_sli_VCsNwCsvXyG1Z1cc4Q7KF4=pm_create_int_vector(
ssc_sli___ECRgjqShlp_PytRplerL,a);d->ssc_sli__dwI5g8rLXSKVqejogItfe=
pm_create_int_vector(mc_FNLG4N0Qc3OxdmBVwutDsy->mNumRow,a);
ssc_sli_kNgcOktCtQxdYedrGvFn5i+=ssc_sli___ECRgjqShlp_PytRplerL;}
mc__d1alWYexptL_X5HTFhbNK[i]=d;}ssc_sli_k26neMO50Cl4YPqZl_TrcK=
pm_create_sparsity_pattern(ssc_sli_kNgcOktCtQxdYedrGvFn5i,
ssc_core_V5LBNJCbhICNbmMG_hLaZ6,ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);for(i=0;i<=
ssc_core_V5LBNJCbhICNbmMG_hLaZ6;i++){ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[i]=0;
}for(i=0;i<ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ;i++){ssc_sli_VUa2TSfWIUlueyhCKkORiK*
ssc_sli_VHx3JOvtgIK3VPttL15wzm=mc__d1alWYexptL_X5HTFhbNK[i]->
ssc_sli_FFdBBQGxAyxCjazMctyaap;PmSparsityPattern const*
mc_FNLG4N0Qc3OxdmBVwutDsy=ssc_sli_VHx3JOvtgIK3VPttL15wzm->mPattern;
ssc_sli__C96EutllrWlgykXJW4e3Y const*ssc_sli_VoES6scNMD_0h97GdxUHNb=
mc__JuAUR_Sob8_WqDjXwmJgM->ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i]->
ssc_sli__jDRUOD243tjgTxKYEsbsv;size_t j;for(j=0;j<mc_FNLG4N0Qc3OxdmBVwutDsy->
mNumCol;j++){int32_T ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=
ssc_sli_VHx3JOvtgIK3VPttL15wzm->ssc_sli_F7t5lALbnyS5i9RsYavPtr->mX[j];size_t k
=ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mX[
ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT];ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[k+1]+=
mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[j+1]-mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[j];}}for(i=
1;i<=ssc_core_V5LBNJCbhICNbmMG_hLaZ6;i++){ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[
i]+=ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[i-1];}for(i=0;i<
ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ;i++){ssc_sli_VUa2TSfWIUlueyhCKkORiK*
ssc_sli_VHx3JOvtgIK3VPttL15wzm=mc__d1alWYexptL_X5HTFhbNK[i]->
ssc_sli_FFdBBQGxAyxCjazMctyaap;PmSparsityPattern const*
mc_FNLG4N0Qc3OxdmBVwutDsy=ssc_sli_VHx3JOvtgIK3VPttL15wzm->mPattern;
ssc_sli__C96EutllrWlgykXJW4e3Y const*ssc_sli_VoES6scNMD_0h97GdxUHNb=
mc__JuAUR_Sob8_WqDjXwmJgM->ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i]->
ssc_sli__jDRUOD243tjgTxKYEsbsv;size_t j;for(j=0;j<mc_FNLG4N0Qc3OxdmBVwutDsy->
mNumCol;j++){int32_T ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=
ssc_sli_VHx3JOvtgIK3VPttL15wzm->ssc_sli_F7t5lALbnyS5i9RsYavPtr->mX[j];size_t k
=ssc_sli_VoES6scNMD_0h97GdxUHNb[NE_DYNAMIC_SYSTEM_INPUT_ID_X]->mX[
ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT];int32_T pm__lqjegyKuwStj56WZLiC_e;for(
pm__lqjegyKuwStj56WZLiC_e=mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[j];
pm__lqjegyKuwStj56WZLiC_e<mc_FNLG4N0Qc3OxdmBVwutDsy->mJc[j+1];
pm__lqjegyKuwStj56WZLiC_e++){int32_T ssc_sli_VQ8_IE57wqKqias1a7HK06=
ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[k];mc__d1alWYexptL_X5HTFhbNK[i]->
ssc_sli_VCsNwCsvXyG1Z1cc4Q7KF4->mX[pm__lqjegyKuwStj56WZLiC_e]=
ssc_sli_VQ8_IE57wqKqias1a7HK06;ssc_sli_k26neMO50Cl4YPqZl_TrcK->mIr[
ssc_sli_VQ8_IE57wqKqias1a7HK06]=mc_FNLG4N0Qc3OxdmBVwutDsy->mIr[
pm__lqjegyKuwStj56WZLiC_e]+(int32_T)ssc_core_kUQBO1dSP8_IVqRAUx4R8G;
ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[k]++;}}for(j=0;j<mc_FNLG4N0Qc3OxdmBVwutDsy
->mNumRow;j++){mc__d1alWYexptL_X5HTFhbNK[i]->ssc_sli__dwI5g8rLXSKVqejogItfe->
mX[j]=(int32_T)(ssc_core_kUQBO1dSP8_IVqRAUx4R8G+j);}
ssc_core_kUQBO1dSP8_IVqRAUx4R8G+=mc_FNLG4N0Qc3OxdmBVwutDsy->mNumRow;}(void)0;
for(i=ssc_core_V5LBNJCbhICNbmMG_hLaZ6-1;i>0;i--){
ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[i]=ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[i-1
];}ssc_sli_k26neMO50Cl4YPqZl_TrcK->mJc[0]=0;*mc_FNLG4N0Qc3OxdmBVwutDsy=
ssc_sli_k26neMO50Cl4YPqZl_TrcK;return mc__d1alWYexptL_X5HTFhbNK;}static
mc_F9HbKNDZMeOehmlKWGUdea const*ssc_sli__GRPMZ_uY_O8cylFUxgbji(
ssc_sli_keyt_1XV42W_WHpMBhjyZm*ssc_sli_kgSURVtfWz4IgH6q0OEa5O){return
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData->ssc_sli_kGNveH_k1RhUeiz9X00EeL;}static
void ssc_sli_kKznRpR2tyOqY1OcCtMndH(ssc_sli_keyt_1XV42W_WHpMBhjyZm const*
ssc_sli_kgSURVtfWz4IgH6q0OEa5O,NeDynamicSystemInput const*
ssc_sli_Fi_du5uFlgGne5wvGXKElE){size_t i;size_t ssc_sli_VITGZHwWA5WRWHwdGSUs2_
=ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V->
ssc_sli__MBuKzK8US4ghTfNeJrQSZ;ssc_sli_VYd6QxXL9z8ba9yU7zI27e**
ssc_sli_VGs_SG8W47WVcH4ptdgnvD=ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData->
ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh;PmAllocator*pm__8zlSpb2Hixod149p2zadR=
pm_default_allocator();NeDynamicSystemInput**ssc_sli_FLMSPpEblZKlWPqrwlu83P=(
NeDynamicSystemInput**)(((pm__8zlSpb2Hixod149p2zadR)->mCallocFcn((
pm__8zlSpb2Hixod149p2zadR),(sizeof(NeDynamicSystemInput*)),(
ssc_sli_VITGZHwWA5WRWHwdGSUs2_))));for(i=0;i<ssc_sli_VITGZHwWA5WRWHwdGSUs2_;i
++){ssc_sli__XIlxPES1MdkcPvc6Ha5NE(ssc_sli_Fi_du5uFlgGne5wvGXKElE,
ssc_sli_VGs_SG8W47WVcH4ptdgnvD[i]->ssc_sli_FkEy9deu86hada0092eFGq,
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V->
ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH[i]->ssc_sli__jDRUOD243tjgTxKYEsbsv);
ssc_sli_FLMSPpEblZKlWPqrwlu83P[i]=ssc_sli_VGs_SG8W47WVcH4ptdgnvD[i]->
ssc_sli_FkEy9deu86hada0092eFGq;}(ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData->
ssc_sli_V1mPIKX1Qix3hqyCWyWx3V)->ssc_sli_kkIk538kkH4PjT_BdbbDnq((
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V),(
ssc_sli_FLMSPpEblZKlWPqrwlu83P));{void*const ssc_sli_VcwA8gt7grSBWPzWAGMsC9=(
ssc_sli_FLMSPpEblZKlWPqrwlu83P);PmAllocator*const
ssc_sli_FYsPqjPM8COpWuHlC_EyOR=(pm__8zlSpb2Hixod149p2zadR);if(
ssc_sli_VcwA8gt7grSBWPzWAGMsC9){(ssc_sli_FYsPqjPM8COpWuHlC_EyOR)->mFreeFcn(
ssc_sli_FYsPqjPM8COpWuHlC_EyOR,ssc_sli_VcwA8gt7grSBWPzWAGMsC9);}};}static void
ssc_sli_F6sGaIhRpMlOhHYVXOfz6b(ssc_sli_keyt_1XV42W_WHpMBhjyZm*
ssc_sli_kgSURVtfWz4IgH6q0OEa5O){PmAllocator*a=pm_default_allocator();
ssc_sli_VyiY43pddkdAdm8k5LKgo1*mc__d1alWYexptL_X5HTFhbNK=
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData;size_t mc_F5WfvJZgg6pBiHOz_1m50n=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k2JWfv8acYtBa1zEg5kgjp;size_t i;
pm_destroy_int_vector(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k7koSU9rCoSYa5RERgn6F_,a);pm_kWBi8ZqmeopPhmEU9I2aNH(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u,a);
pm_destroy_int_vector(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FfCc3GD8SitwaPgm1V8xBZ,a);mc_VBCIjXiCCT_RXmHVT9WPVa(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kGNveH_k1RhUeiz9X00EeL);(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__FZ4dAYrXe89eP_Ma5XLmn)->mDestructor((
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__FZ4dAYrXe89eP_Ma5XLmn));
pm_VYooJBURCwKrVu6RXzQZ_5(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2MW3X1xMDW7hLRm_yMLlx,a);pm_destroy_real_vector(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kvOBG5idQvpEZXzSmLOxzp,a);
pm_destroy_real_vector(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__C2ViEySBhtxXuN5TLp4Eq,a);pm_destroy_real_vector(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__WoQw6DubplSaunXCUqnIy,a);for(i=0;i<
mc_F5WfvJZgg6pBiHOz_1m50n;i++){ssc_sli___RmjGx3UPSBg1_RLQgcC5(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh[i]);}{void*const
ssc_sli_VfQCRSSWfwhohaUb9upksz=(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh);PmAllocator*const
ssc_sli_FHbrm3hrb_hEdmM4wTDxnq=(a);if(ssc_sli_VfQCRSSWfwhohaUb9upksz){(
ssc_sli_FHbrm3hrb_hEdmM4wTDxnq)->mFreeFcn(ssc_sli_FHbrm3hrb_hEdmM4wTDxnq,
ssc_sli_VfQCRSSWfwhohaUb9upksz);}};mc_kbfEOfn7DOGmfyLmEcjphP(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a);{
mc_FEi_3IF8psl_XH4yBOu3mh*ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A=
mc_FEl3DXb7ypKke5uZ90Xlyw();ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A->
mc_FxdfIsrDZ_OpXHH2KZQasB(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_kbNdhAsAytKmVyMzjNTDEY);}{void*const ssc_sli_V4j7ssSuDYOwXDxcRb13n8=(
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData);PmAllocator*const
ssc_sli_FHSy3VM8Ust2VDqwJxD9dF=(a);if(ssc_sli_V4j7ssSuDYOwXDxcRb13n8){(
ssc_sli_FHSy3VM8Ust2VDqwJxD9dF)->mFreeFcn(ssc_sli_FHSy3VM8Ust2VDqwJxD9dF,
ssc_sli_V4j7ssSuDYOwXDxcRb13n8);}};{void*const ssc_sli___oarmi6bfd8VezLBWIImh=
(ssc_sli_kgSURVtfWz4IgH6q0OEa5O);PmAllocator*const
ssc_sli__pW0akmIZ4GmfifGaiunq_=(a);if(ssc_sli___oarmi6bfd8VezLBWIImh){(
ssc_sli__pW0akmIZ4GmfifGaiunq_)->mFreeFcn(ssc_sli__pW0akmIZ4GmfifGaiunq_,
ssc_sli___oarmi6bfd8VezLBWIImh);}};}ssc_sli_keyt_1XV42W_WHpMBhjyZm*
ssc_sli__KMRq9MhmPGtc5GixC6jwv(ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,NeSolverParameters const
ssc_core_kv7GnpbgsfSGjTKLxq5SvA){PmAllocator*a=pm_default_allocator();size_t
ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ=mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli__MBuKzK8US4ghTfNeJrQSZ;size_t mc_F5WfvJZgg6pBiHOz_1m50n=(((size_t)1)<<
((size_t)(log(ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mFunctionEvalNumThread+0.1)/log(
2.0))));ssc_sli_keyt_1XV42W_WHpMBhjyZm*ssc_sli_kgSURVtfWz4IgH6q0OEa5O=(
ssc_sli_keyt_1XV42W_WHpMBhjyZm*)(((a)->mCallocFcn((a),(sizeof(
ssc_sli_keyt_1XV42W_WHpMBhjyZm)),(1))));ssc_sli_VyiY43pddkdAdm8k5LKgo1*
mc__d1alWYexptL_X5HTFhbNK=(ssc_sli_VyiY43pddkdAdm8k5LKgo1*)(((a)->mCallocFcn((
a),(sizeof(ssc_sli_VyiY43pddkdAdm8k5LKgo1)),(1))));(void)0;
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V=
mc__JuAUR_Sob8_WqDjXwmJgM;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u=pm_FZch3YyGWrOM_PQNdo7b2c(
ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ+1,a);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FfCc3GD8SitwaPgm1V8xBZ=pm_create_int_vector(
ssc_sli_Vp82Ws5YxWKajaIAwN2XfQ+1,a);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k7koSU9rCoSYa5RERgn6F_=pm_create_int_vector(mc__JuAUR_Sob8_WqDjXwmJgM
->ssc_sli_ki5qToeyQ7tPheF11zZqgB->ssc_sli__g89dzKHN9WyW1QK3EhGT2->mN,a);
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_VbujnTJ1G1_WZ5wNA_s5rh=
ssc_sli__SAkqUcsNWl7V1RFCBQPxt(&(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2MW3X1xMDW7hLRm_yMLlx),mc__JuAUR_Sob8_WqDjXwmJgM,
ssc_core_kv7GnpbgsfSGjTKLxq5SvA);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_kGNveH_k1RhUeiz9X00EeL=mc__JuAUR_Sob8_WqDjXwmJgM->
ssc_sli_FrHYG41gZrG7b9SBHEWeHM(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2MW3X1xMDW7hLRm_yMLlx,(size_t)(log(ssc_core_kv7GnpbgsfSGjTKLxq5SvA.
mFunctionEvalNumThread+0.1)/log(2.0)));mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__FZ4dAYrXe89eP_Ma5XLmn=mc_FEm6WJeLOdORjPVbu__PTt(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kGNveH_k1RhUeiz9X00EeL,
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k2MW3X1xMDW7hLRm_yMLlx,(int32_T)
mc_F5WfvJZgg6pBiHOz_1m50n);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_kvOBG5idQvpEZXzSmLOxzp=pm_create_real_vector(((size_t)(((
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k2MW3X1xMDW7hLRm_yMLlx)->mJc[(
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_k2MW3X1xMDW7hLRm_yMLlx)->mNumCol]))),a);
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__C2ViEySBhtxXuN5TLp4Eq=
pm_create_real_vector(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2MW3X1xMDW7hLRm_yMLlx->mNumRow,a);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__WoQw6DubplSaunXCUqnIy=pm_create_real_vector(mc__d1alWYexptL_X5HTFhbNK
->ssc_sli_k2MW3X1xMDW7hLRm_yMLlx->mNumCol,a);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FnNKu1U4IT8IV1Z4Y3UpvY=ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mDoFixedCost;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VHpOBeHDk6S_fiGSsgZ9AB=
ssc_core_kv7GnpbgsfSGjTKLxq5SvA.mResidualTolerance;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2JWfv8acYtBa1zEg5kgjp=mc_F5WfvJZgg6pBiHOz_1m50n;
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V_hsNh_T0_d2hXQOfQ8o1a=
mc_V4Y8IvqWFgGLZ1YthqZz6A(mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_k2JWfv8acYtBa1zEg5kgjp);{mc_FEi_3IF8psl_XH4yBOu3mh*
ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A=mc_FEl3DXb7ypKke5uZ90Xlyw();
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_kbNdhAsAytKmVyMzjNTDEY=
ssc_sli_Fc2kyW0rUYdaVPPGe_kH_A->mc__wc2tCUDwk87X1QDBaJiKw(&
ssc_sli__NDnSrWfdMxxdeMWL6o3AB,mc_F5WfvJZgg6pBiHOz_1m50n);}
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mData=mc__d1alWYexptL_X5HTFhbNK;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_V1mPIKX1Qix3hqyCWyWx3V;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_k3mbO8G__i_whL1wWV_J6X=0;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_FfCc3GD8SitwaPgm1V8xBZ=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli_FfCc3GD8SitwaPgm1V8xBZ;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_FPn9er7iSOhfc1umT1tmGB= &
ssc_sli_V_21GLcjvt0bjD72k9siA5;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mStart= &
ssc_sli_FZn4n20IMS_igXtD7F_tjD;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->
ssc_sli_VC5mmdlw_3dpjqitDYBJ94= &ssc_sli_VbuLgMdMkftWbDBI64mNFu;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mc_k0h0NPxQNyl2XD95RLG6Hy= &
ssc_sli_FmTO1Vc0lE_uautI1klGsM;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->
ssc_sli_kKZbL_4KD_dlfXO9Z4Zely= &ssc_sli_FyMIIl6UzqGoga4nFr1i1w;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_core__A0n8EhE_GdLWudFqHsqyZ= &
ssc_sli_kQWny1CfzV4XWuuKJEPS8_;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mPushInfo= &
ssc_sli__oir0sV2pgt9YD2k_Pe5GP;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->
ssc_sli_FrHYG41gZrG7b9SBHEWeHM= &ssc_sli__GRPMZ_uY_O8cylFUxgbji;
ssc_sli_kgSURVtfWz4IgH6q0OEa5O->ssc_sli_kkIk538kkH4PjT_BdbbDnq= &
ssc_sli_kKznRpR2tyOqY1OcCtMndH;ssc_sli_kgSURVtfWz4IgH6q0OEa5O->mDestroy= &
ssc_sli_F6sGaIhRpMlOhHYVXOfz6b;return ssc_sli_kgSURVtfWz4IgH6q0OEa5O;}
