#include "multibody_model_macros.h"
#include "pm_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
#include "pm_std.h"
#include "stdarg.h"
typedef NeuDiagnosticTree*pm_st_FjUEd5ZQJA0Ej1IosTlZ5E;typedef struct
pm_st__0atO_17n_Ci_qYhoCxFUV pm_st_F04yXT_zz14zgHdLildPgK;struct
NeuDiagnosticManagerTag{pm_st_F04yXT_zz14zgHdLildPgK*mPrivateData;
pm_st_FjUEd5ZQJA0Ej1IosTlZ5E(*pm_st_VESUSzIzeRWSV1xYVr5zH5)(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*
pm_st__RtuwtEn2c_yh1OySiqODN)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st__YxE_N42_idoWyreGeTz9t)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st_kAPwXpB5miCGVLsko_7ONE)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE);void(*pm_st__u9riBfE3RK3ZXQpAXjZW_)(
NeuDiagnosticManager const*pm_st_FgQH451kC4lOZ5A2coatZe,NeuDiagnosticManager
const*src);NeuDiagnosticTree const*(*pm_st_kqsZroyTBbpjb1za_BT1dv)(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mDestroy)(
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);};PmfMessageId
pm_st_Fj4pG1CbqChThqCdYV3xux(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_FqMmOIGGjkpTZ58Esd_XuA(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_F5XP0Is_HAWucugpsjE8XK(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st__w8As0Yf6B8Ji9iMi5WOGi(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,char const*
pm_st_kvsOBKjJwlx5dTxrw7qAwS);PmfMessageId pm_st__xrkslL_b0pOemBxsxBQx0(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel
pm_st_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,char
const*pm_st_kvsOBKjJwlx5dTxrw7qAwS);NeuDiagnosticManager*
neu_create_diagnostic_manager(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
neu_destroy_diagnostic_manager(NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0 ssc_sli__9m1LfQ2DwC_cXa8Cjj28A;
typedef struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G ssc_sli_kqioa3Wq9idS_X_JDQovlr;
struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0{ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli__X9HoYTA6GhUZPkX6FMtmN;void(*mDestroy)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
);NeParameterInfo(*mParameterInfo)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*);
boolean_T(*mSetParameters)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*,double,
NeParameterBundle const*,NeuDiagnosticManager*);};
#include "pm_std.h"
#include "mc_std.h"
#include "mc_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef enum{ssc_core__ioOg4ScKX0EZDRCgs08_8= -1,
ssc_core_VUvhZChBwCxhcDNbwou1aT,ssc_core__QYxQXlKud8zbLGuiUNTmv,
ssc_core_VNLm8DNiLLxzVDGeWBpIJV,ssc_core_V36UEe9kiR_Qcm5dDei5__}
ssc_core_VMObUicZgDGkXuH3R8jgeY;
#include "ssc_dae.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;
#include "ne_std_fwd.h"
#include "ne_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ssc_dae.h"
#include "ne_initer_fwd.h"
typedef struct ssc_core__0VZmjMI2w4nXaHABiNBr8 ssc_core_F0AWwSa5A0trfXhXr2aKC_
;typedef struct ssc_core_kldtaFq0oo_qfPZFq3YVqE ssc_core__5_SU_Rso6C_jXmFZQFRav
;typedef struct ssc_core_VMSsC0NOHnxsdHnhioprfp ssc_core_VnIq_tcCmTlseX_l_18cm8
;struct ssc_core_VMSsC0NOHnxsdHnhioprfp{ssc_core__5_SU_Rso6C_jXmFZQFRav*mData;
void(*ssc_core_F_OD3I_UDmx_WuMe7fUVLk)(ssc_core_VnIq_tcCmTlseX_l_18cm8 const*
ssc_core_F5Olyc6xUoG7ZyDq78exBD,NeSystemInput const*
ssc_core_VGP4X0I7_HhDXXNxjNIZXe,NeRealFunctor const*
ssc_core__Z_5AZiIoAdFc9je_NctfA,NeSystemInput const*
ssc_core__opt48huzX4nZinziUjEAC);void(*mDestroy)(
ssc_core_VnIq_tcCmTlseX_l_18cm8*ssc_core_F5Olyc6xUoG7ZyDq78exBD);};struct
SscComputeStateTag{ssc_core__5_SU_Rso6C_jXmFZQFRav*mData;void(*
ssc_core__NO_ZGl47xdVbPsFViPiVj)(SscComputeState const*
ssc_core_F5Olyc6xUoG7ZyDq78exBD,NeSystemInput const*
ssc_core__opt48huzX4nZinziUjEAC,NeSystemInput const*
ssc_core_VGP4X0I7_HhDXXNxjNIZXe);void(*mDestroy)(SscComputeState*
ssc_core_F5Olyc6xUoG7ZyDq78exBD);};struct SscIniterTag{PmfMessageId(*mSolve)(
SscIniter const*ssc_core_kbS4MMURfHdDjyVuFzCl4r,
ssc_core_VnIq_tcCmTlseX_l_18cm8 const*ssc_core_F5Olyc6xUoG7ZyDq78exBD,
NeSystemInput const*ssc_core_VGP4X0I7_HhDXXNxjNIZXe,NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mSetParameters)(SscIniter const*
ssc_core_kbS4MMURfHdDjyVuFzCl4r,NeParameterBundle const*
ssc_core__wmTd2KKOKd7YPG6_QANiL);void(*ssc_core_FvqZ30Ah6up8ii3n4XoNhR)(
SscIniter const*ssc_core_kbS4MMURfHdDjyVuFzCl4r,NeCgParams const*
ssc_core_V8dxNPZgtaSrh9nZ3_du_L,NeCgResults*ssc_core__hxrTSdKbWl8hHH_jhW_5W);
void(*ssc_core_FH1v9GvVLPlacPvJ2xQ7hM)(SscIniter const*
ssc_core_kbS4MMURfHdDjyVuFzCl4r,void*mc_FvxKbdtfPKOYaymjtthQ0G);
NeObservableData const*mObservableData;size_t mNumObservables;SscIniter*(*
mCloneFcn)(SscIniter const*ssc_core_kbS4MMURfHdDjyVuFzCl4r);void(*mDestroy)(
SscIniter*ssc_core_kbS4MMURfHdDjyVuFzCl4r);size_t mRefCount;
ssc_core_F0AWwSa5A0trfXhXr2aKC_*mData;};PMF_DEPLOY_STATIC void
ssc_core_VbqjDHrCHZtDWeBVtK_xl3(SscIniter*ssc_core_kbS4MMURfHdDjyVuFzCl4r){if(
ssc_core_kbS4MMURfHdDjyVuFzCl4r){++(ssc_core_kbS4MMURfHdDjyVuFzCl4r->mRefCount
);}}PMF_DEPLOY_STATIC void ssc_core_kT3zoPmGwWpNgXAHZRKSC8(SscIniter*
ssc_core_kbS4MMURfHdDjyVuFzCl4r){if(ssc_core_kbS4MMURfHdDjyVuFzCl4r){(void)0;;
if(--(ssc_core_kbS4MMURfHdDjyVuFzCl4r->mRefCount)==0){
ssc_core_kbS4MMURfHdDjyVuFzCl4r->mDestroy(ssc_core_kbS4MMURfHdDjyVuFzCl4r);}}}
#include "ne_stiffness_fwd.h"
typedef struct ssc_core_VQczuA1nKwhAZyVB7tRk_W ssc_core__I6_5VButu_XW18NL0jaqa
;struct NeStiffnessTag{ssc_core__I6_5VButu_XW18NL0jaqa*mData;void(*
ssc_core__p5TJO2NOwxWWa0hooPWf_)(NeStiffness*s,PmRealVector const*
ssc_core__olvcqfXbd0zf930kynrj8);PmRealVector*(*
ssc_core__Hy4UVQ9qSODjHPF1q7MxU)(NeStiffness*s);void(*mStart)(NeStiffness*s);
void(*ssc_core_Fmt0c_MGPStDjmILzXk95F)(NeStiffness*s,NeSystemInput*
mc_kDRphcAfRHSbf1ZLKEDW9k);size_t(*ssc_core_F9BJ_L6E6IduiHlBC_tLxG)(
NeStiffness*s);PmfMessageId(*ssc_core_FTZBRIf20L0bWXNwmlDdUJ)(NeStiffness*s,
void*ssc_core_FHqQilyqTDtBeevv_XxTm7,size_t k,NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mDestroy)(NeStiffness*s);};NeStiffness*
ssc_core_VuD1jukAQGtjgH4ucghis3(NeDae*dae,SscComputeState*
ssc_core_F5Olyc6xUoG7ZyDq78exBD,NeSystemInputSizes*sizes);
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VWJbTwnVZB_LVqIIM_COT0{int32_T mc_FvxKbdtfPKOYaymjtthQ0G,
mc__0REJ38_cKO_bunM1JCRT_,id;struct mc_VWJbTwnVZB_LVqIIM_COT0*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;}
mc_FSz7cV1MCGScXq_M5VT121;typedef struct mc_kjlHS2Mzxsh6gyVZ329fra{
mc_FSz7cV1MCGScXq_M5VT121*mc__a1o_SOX2HC3f9QpH_hO5s;PmIntVector*
mc__5uLb2__blGtb9EQ9Zwa2_;PmIntVector*mQ;}mc_F9HbKNDZMeOehmlKWGUdea;typedef
struct mc__fV9rOH7ci_OWykNO7xTBO{size_t mc_VLHhnPUiNQpve5VIL9P3O9,n;int32_T*
mc_FvxKbdtfPKOYaymjtthQ0G,*mc__0REJ38_cKO_bunM1JCRT_,*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;int32_T*
pm__lqjegyKuwStj56WZLiC_e,*mc__AExROh1PVWNeP7hmMWuJv;}
mc_FwUXSPCwCAC_jydGHlCZxe;PmIntVector*mc__oCV63DXBpKVZL_8tU2Wiz(
mc_FSz7cV1MCGScXq_M5VT121 const*mc_VPPSxR3RRt0pXLadx2tWo7,PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
mc__RLQweDZtv0hhLXz_f8MMi(mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt)
;mc_FSz7cV1MCGScXq_M5VT121*mc_VCdOZjcBUFORayuNvO7rtI(mc_FSz7cV1MCGScXq_M5VT121
*mc_Fxl4i6XHkE8cY9kYmlJixt);void mc_VbHMSzzYu5_WZiNG_fSW8Q(
mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt,int32_T
mc_FvxKbdtfPKOYaymjtthQ0G);int32_T mc__1AbngzPnBGnXXDldWop_b(
mc_FSz7cV1MCGScXq_M5VT121*mc_VPPSxR3RRt0pXLadx2tWo7);void
mc_VBCIjXiCCT_RXmHVT9WPVa(mc_F9HbKNDZMeOehmlKWGUdea*mc_VpSwxG2uxL4JaLmMQqUqTJ)
;mc_FwUXSPCwCAC_jydGHlCZxe*mc_F79LLfWDdKORZ1K7KKqAke(mc_F9HbKNDZMeOehmlKWGUdea
const*mc_VpSwxG2uxL4JaLmMQqUqTJ);mc_F9HbKNDZMeOehmlKWGUdea*
mc_perm_data_from_flat(mc_FwUXSPCwCAC_jydGHlCZxe const*
mc_Fw6WJxuximC4jHgRLzUSDo);void mc_Vq5AUJWyc3xVgP5Ff1_aP6(
mc_FwUXSPCwCAC_jydGHlCZxe*mc_Fw6WJxuximC4jHgRLzUSDo);
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
typedef enum{ssc_sli_kiIb5xamJm8uXPyOkLeM64= -1,ssc_sli_FRFqZTqvUYlL_1GmhnSKa9
,ssc_sli_F_n1U4dfhIKmZeTb79_bhk,ssc_sli_Vje8c4NwMs8edaUv9kAKU5,
ssc_sli_F95A2pmjwJGycuR83ALBWW,ssc_sli_FRC3ujZIQjdba9ZBxy4ztV}
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ;typedef struct ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv
ssc_sli_FTmXA5ksLdxWam9tKEDDRp;typedef union ssc_sli_V3VjUqcAjgGUfa9pjdr9Vc{
PmIntVector mMODE;PmRealVector mY;PmRealVector ssc_sli_kxq2De1a8BxzemrdMYbh_Z;
PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;PmIntVector
mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector mUPDATE_R;
PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;PmRealVector
mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector ssc_sli_VjGKBH58LAdsYPWWs6sfbL;PmRealVector mLOG;}
ssc_sli_kkoV3MWI3Olsj9ue_OTrKB;typedef enum ssc_sli__gFYpQJuFtpEfTSOOLoPeL{
ssc_sli_kcaKKN8GXoxUdyPIz9ME4P= -1,ssc_sli_VFlLQfEII_dCjPOLZCKl1h,
ssc_sli_FQmAUq5mRNGbVih2F3PCCN,ssc_sli_FHA50iTf0YOSaPrq60uYIa,
ssc_sli__d4NvF_TU8xhiPidhlSBeU,ssc_sli_kje3FEfA_VOecqlGobEPlW,
ssc_sli_V2lBgEm_1wOKgP3OF7OhA2,ssc_sli__HZXcTW2uIp1b5VW7Lmaiz,
ssc_sli__iC2umSSBnhLdaou8jCK4Q,ssc_sli__cdqw5QDTiWb_HxgGzJupf,
ssc_sli_VzRYNhOLez0fcahY6OfqAT,ssc_sli_ksyP1mhwOx_gdi_qxA1XwQ,
ssc_sli_FdbT7DDFOod_gD62wqPcy_,ssc_sli_FxDcIIX1_0WChuVyeYIziJ,
ssc_sli_km8PqndzZYCHbPN_lUtQcC,ssc_sli_Fh3EMcmCEi0cfaU6jdkIj2,
ssc_sli_k2mBp0rugDOniPAiyz8Hig,ssc_sli_FPv0_UNPp8__hPT18mmlhp,
ssc_sli_kxwvUNoEGCOiceCilpf1YD,ssc_sli__nuLYOAWg4luhub2duGQQ_,
ssc_sli_kjrjD1N2_uWBXaVD9TSx7N,ssc_sli_VLEO4HXvRlGQaqqGghTyqa,
ssc_sli__kD90nzGGZSGWTWEkw1Cis,ssc_sli_k8wcDa_7rDts_9nPV5dfjq,
ssc_sli_VujW_EuJpidTduLntgaxe6}ssc_sli_Vfu07t_igc0ehHkC_w2Ar_;typedef int32_T(
*ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5)(ssc_sli_FTmXA5ksLdxWam9tKEDDRp const*,
NeDynamicSystemInput const*,ssc_sli_kkoV3MWI3Olsj9ue_OTrKB*);struct
ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv{ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5 mMethods[
ssc_sli_VujW_EuJpidTduLntgaxe6];size_t ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t
ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t mNumAsserts;NeAssertData const*
mAssertData;size_t mNumAssertRanges;NeRange const*mAssertRanges;size_t
mNumInitialAsserts;NeAssertData const*mInitialAssertData;size_t
mNumInitialAssertRanges;NeRange const*mInitialAssertRanges;NeParameterInfo
mParameterInfo;PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;};typedef struct ssc_sli_knlRBEvE2xlTdL9XQDsraA
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO;typedef struct ssc_sli__M0yHGxYdRh6WeZsp03MsF
ssc_sli_ktYRHip3ZVhEdLZEQWORqW;typedef struct ssc_sli__C7xfBs4_wtZdybDh_1S17
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ;typedef union ssc_sli_kEJscBISiC0cW1zDnm5FFI{
PmSparsityPattern mMCON_P;PmRealVector mMCON;PmSparsityPattern mMPAR_P;
PmRealVector mMPAR;PmSparsityPattern mMNL_P;PmRealVector mMNL;
PmSparsityPattern ssc_sli__iV7cpieH5lkhLu3Lg9TbF;PmRealVector
ssc_sli_kpJ_qciQSWpsiPiK3aYpC6;PmSparsityPattern ssc_sli_FCUwBAadDl4jdTbQJs191b
;PmRealVector ssc_sli__4wk9aw_kxhdamxJBndVFp;PmSparsityPattern
ssc_sli_kpP4jzbAmSSabDQ2Rr8bL8;PmRealVector ssc_sli_kKsgUsw2JgtEYPjXL27qpf;
PmRealVector ssc_sli_FisUhCWjCaKZVHMV_vZE5q;PmRealVector mF;PmRealVector
ssc_sli__EEaI0glzV_ziunIayuQB_;PmIntVector mMODE;PmBoolVector mSLF;}
ssc_sli_Vp0c29ygDdlujTOV9DIZY0;typedef enum ssc_sli_VD2_Ev_HuH0of9gNrHze9d{
ssc_sli_VXnsMGX_7cGRb55H42tfn7= -1,ssc_sli_k_8QN9x5_k42cyQrpZzjsI,
ssc_sli_kqMvQKKxuVtEea_8OzY2TM,ssc_sli_VfTboTvpAHCDgqUBkJD5Rl,
ssc_sli_k2Owy_sJ_40uh9KZRFIdY5,ssc_sli_kmQ2_m3O6DG6euIv_XuxVg,
ssc_sli_VQO8dLIZX78oa5taxlg_vo,ssc_sli_V7DyxzVA0QGofTFR6YdqYq,
ssc_sli__DRGltAScIGfeu43CxFuG8,ssc_sli__sxV91jCfEGzYXaVBkddIG,
ssc_sli_k0IoR8Wj3MdBiLa4ZtAvTI,ssc_sli_kFNU_9_j_MOSead4baHt3T,
ssc_sli_Vx3D_PUFnUhXeH6lNfeh3d,ssc_sli__pmgH1Up57xCbH_C454qdO,
ssc_sli_kVzQQaaqlPt8bmsY4qvPjV,ssc_sli_kTfE4dqxl7OZdqxWw7pewy,
ssc_sli_VazOOCfCtUhdYPCvduXfsJ,ssc_sli__a5HvR7wGotUf9fcjCj4Zw,
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C}ssc_sli_FSls2IGSVBpdeeBJHp6ST7;typedef int32_T(
*ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT)(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*,
NeDynamicSystemInput const*,ssc_sli_Vp0c29ygDdlujTOV9DIZY0*);typedef enum
ssc_sli__I1_0bn1tlpndTZaRA_ZPl{ssc_sli_kIVETWACXbp0d94SP8_dc1= -1,
ssc_sli_F5_rBq64Lj4aWXXU0PyiUb,ssc_sli_FshPfGethuxwX9btxT6saT,
ssc_sli__uxzr382yeG7jXfsoRvs2Z}ssc_sli_V79S98fiH1S7byo5F9wnzk;typedef
PmSizeVector*ssc_sli__C96EutllrWlgykXJW4e3Y;struct
ssc_sli_koMvWW1l_F_oi5bwovAr78{PmSparsityPattern*mPattern;};struct
ssc_sli__M0yHGxYdRh6WeZsp03MsF{PmSparsityPattern*mPattern;PmRealVector*mPr;};
struct ssc_sli_knlRBEvE2xlTdL9XQDsraA{ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT mMethods[
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C];ssc_sli_ktYRHip3ZVhEdLZEQWORqW
ssc_sli_kb5sBAIsNGx3h5TSZDK2nO[ssc_sli__uxzr382yeG7jXfsoRvs2Z];
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ*ssc_sli__he79Qtc4y4abmydbMrr9d;size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_k3ro8_fNFeG3YHRPCSyK_y;size_t
ssc_sli_VimjrZhJPvSkgeFbqT7DNg;size_t ssc_sli_Vd47fO4esQxG_HpE1mPb9b;size_t
ssc_sli_F0sp_kii_WGhgeeqy_FSs6;boolean_T ssc_sli_Vq7NNhAfxIO_j9IbOG6sAS;
NeDynamicSystemInputSizes mSizes;ssc_sli__C96EutllrWlgykXJW4e3Y
ssc_sli__jDRUOD243tjgTxKYEsbsv[NE_NUM_DYNAMIC_SYSTEM_INPUT_ID];PmIntVector*
ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*ssc_sli__ysspeBWLwt9fe39xFzdmF;
PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ
ssc_sli_FA2YAvRyL2h_f9kmmok0RW;boolean_T ssc_sli_V6uMeGVfspW_ju_lkeNWOq;};
typedef struct ssc_sli__we9OgtXM80Beq3Pau0ORa ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ;
typedef union ssc_sli_kZbOKlPIFU_2ZqIJ7Wxuxt{PmSparsityPattern mM_P;
PmRealVector mM;PmRealVector mF;PmSparsityPattern
ssc_sli__aw0Y7gxbhS0_LvT4MtW1M;PmRealVector mJ;}ssc_sli_FXl61xRLPE47iP1Q_pvk2u
;typedef enum ssc_sli_V1Ph_XOAJoKRYqSqeTnmEx{ssc_sli_V3bEzwx1u0lOVPYRbuCqcW= -
1,ssc_sli_Fn41P1GumQ42i9T8pr7NwB,ssc_sli_F2Ws5ikk0qOaWyeJpDP8bj,
ssc_sli_FYPImDMfyFhqYmN4WZY0Gv,ssc_sli_kAf_QyKmY34ZVLgh19055f,
ssc_sli_kKEx7mxjxwKzZTWlJaaDbC,ssc_sli_FEtyoYrn_ttHf99kNFRkob}
ssc_sli_FD25vRYmqOCeX9QMP0Yb86;typedef int32_T(*ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW
)(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*,NeDynamicSystemInput const*,
ssc_sli_FXl61xRLPE47iP1Q_pvk2u*);struct ssc_sli__we9OgtXM80Beq3Pau0ORa{
ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW mMethods[ssc_sli_FEtyoYrn_ttHf99kNFRkob];size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;
PmIntVector*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;};typedef struct
ssc_sli_VAuysnx4S7lBcPba8gefmX ssc_sli_kTxQKABEQA__dXDaX6_8lx;struct
ssc_sli_VAuysnx4S7lBcPba8gefmX{NeDynamicSystemInputSizes mSizes;PmIntVector*
ssc_sli_FtEj7nrAMw8EX1WVETDajL;ssc_sli_FTmXA5ksLdxWam9tKEDDRp*
ssc_sli_ki5qToeyQ7tPheF11zZqgB;size_t ssc_sli__MBuKzK8US4ghTfNeJrQSZ;
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO**ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH;
ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ*ssc_sli__Rb1pGJJ50KLfagQM39h_L;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;
mc_F9HbKNDZMeOehmlKWGUdea*(*ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,size_t mc_k0zHKt3B8EloaeisOobs3u);void(*
ssc_sli_kkIk538kkH4PjT_BdbbDnq)(ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,NeDynamicSystemInput**ssc_sli_FI3oLMQhBMhqhTN_ohgA9w
);void(*mDestroy)(ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM);};
#include "pm_inline.h"
#include "mc_std.h"
#include "ne_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ssc_dae.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(char
const*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
#include "ne_stiffness_fwd.h"
typedef struct ssc_sli_VFWQkwsWjFO3YXl_MNZJDP ssc_sli_FfCmiDUlTHWdhTaGeWWmuy;
struct ssc_sli_VFWQkwsWjFO3YXl_MNZJDP{PmRealVector*
ssc_sli__umAQFI5A7lxePExgO_arY;mc__mbv8xxcLWlA_qjxkZ_Zr3
ssc_sli_FXYJKQreD2_Tf14HXZftwA;mc__mbv8xxcLWlA_qjxkZ_Zr3
ssc_sli__yB5r2Ovvv_1d1pc4UbomW;PmRealVector ssc_sli__sojpoqyGKxKi1MJAukVny;
boolean_T ssc_sli_kOMlZk7NTpxXgLpfPXk1fc;boolean_T
ssc_sli_Vin1htMvvV0qiD156ttlEy;};
#include "pm_inline.h"
typedef struct ssc_sli_kZxrCUA8tO0phPexWrtzmM ssc_sli_VW_ogzaTyo0kXql81JaM_l;
typedef struct ssc_sli_VzcAkZJ6ELtRge9892ouV5 ssc_sli__9vNmB0C9GK1W1pRr15dLc;
struct ssc_sli_kZxrCUA8tO0phPexWrtzmM{PmRealVector*(*
ssc_sli_FvPt29eXWrtnaywnAkTTzE)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli__JaMZNWAa__QbXiCKJnXnC)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*ssc_sli__V2GsKfXhY_p_mlJLOS6A6)
(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_k8tMlkuYj_Sih11Pcpr3ne)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmIntVector*(*ssc_sli__5_UeKPn6E8yZ5FYsZA0Qi)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli_F4k7ST_risKBWmkiDYmsGi
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*
ssc_sli_VOZQl3ssDr0hhyaiwOy11c)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_F9Xs5gc0nAGDbX3AbwXh5D)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli_FXYJKQreD2_Tf14HXZftwA
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_FbaMgAuDQXtkd5RShI3o7C)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_FamvhohjbzCm_umircxMjq)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_core_FyOwljf5rtGFdmq18I_hmE)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmSparsityPattern*(*mM_P)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*
(*ssc_sli__0tB_km2jUKvXPhyTmThux)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmSparsityPattern*(*ssc_sli_kU1IKNSGg4dpha8WaWkPZ_)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli__WXl5FgRW90TjX0RRwUEci
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmSparsityPattern*(*
ssc_sli__2DhE5J_fFWhbadILLrm1L)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli__UQIrcKp8d8UbLqyvXnQyv)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli__8inMtesCR0FgXaTeArkt_
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_FUpUzGnPnv0m_qSXZnwv4E)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_VvtT_los6httV9uBdX1mPJ)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*ssc_sli_Vpna_7I4l94jjTxsYGOBlk)
(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli__djxsoGTYk8_WHFWI6CE2e)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_kTgaWou2ePGi_T83eVmFB4)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli__aK6RhIri2lsiPw9024AWm)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_VnYSekQWhpOYYPjDWhTOod)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_VfTUkRE7gRtXfXDqOCNgGn)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli_kjeAwr4pAFloZ9ZzA_nG8M)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_kdrm8_CkIRdyZLDWuc4lOV)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_ka77aS1n6yCxcerEl7v1wG)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli__Hq42Wk_zm0tf57HHJNb8K)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_F2GpUH_z4lKcYyKqirODC3)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli_VdyOM3ac9ktjgT8rdrPUIH)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);void(*mDestroy)(
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);ssc_sli__9vNmB0C9GK1W1pRr15dLc*mData;};
PMF_DEPLOY_STATIC PmRealVector ssc_sli_FbNDE2Rr_DtMXHgwY7qW3A(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FvPt29eXWrtnaywnAkTTzE(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_Fj6FoMj5Dl0q_a_prqq3bR(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__JaMZNWAa__QbXiCKJnXnC(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_FSjcBIED8tKmiay_NyK7zQ(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__V2GsKfXhY_p_mlJLOS6A6(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kOWE0zHM8m0wY93asHJwLe(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_k8tMlkuYj_Sih11Pcpr3ne(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_kxY1noz2O7pcb1hLLo5nhR(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__5_UeKPn6E8yZ5FYsZA0Qi(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kqV3lDja_PhgfDmC9KZQTj(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_F4k7ST_risKBWmkiDYmsGi(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_kqLQwTUQI3CnaLR7ld3n7Q(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VOZQl3ssDr0hhyaiwOy11c(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_FzWdjDQLk9WW_ujd7Jcybq(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_F9Xs5gc0nAGDbX3AbwXh5D(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli__XqvlNMriUSFgmk2jTZSu6(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FXYJKQreD2_Tf14HXZftwA(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli__MpM_ZZQhot7Vml7PvXRok(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_FbaMgAuDQXtkd5RShI3o7C(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kOSTk1s82US5aDFQKpH067(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FamvhohjbzCm_umircxMjq(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_F_0yf_qMGxxjZHpE9HfXPe(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_core_FyOwljf5rtGFdmq18I_hmE(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmSparsityPattern ssc_sli_kZDsMQqCvulggHj1JCoqJb(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->mM_P(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_VlhTWAbwxnGkeXPRc_CIBs(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__0tB_km2jUKvXPhyTmThux(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmSparsityPattern
ssc_sli_kDea3SpoCkl1ciMKcHlJ41(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kU1IKNSGg4dpha8WaWkPZ_(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kYjn6kSV9TGZWirFUKegIj(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__WXl5FgRW90TjX0RRwUEci(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmSparsityPattern
ssc_sli_k9NjcG39_i80hPvHCeLl6v(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__2DhE5J_fFWhbadILLrm1L(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kXzjAyYPzYhQf5GxACFOOR(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__UQIrcKp8d8UbLqyvXnQyv(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kg2z3WNMy9xU_mlnYjkP15(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__8inMtesCR0FgXaTeArkt_(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_FrV7CfQG67dTeuOwvsv9fy(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FUpUzGnPnv0m_qSXZnwv4E(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kpox7sctNc8Xbaocx9zi8G(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VvtT_los6httV9uBdX1mPJ(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli__zK4QBKRV14lcyf_S2N3Gf(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_Vpna_7I4l94jjTxsYGOBlk(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli__JosVOTFU_tPgaLZK_6MIS(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__djxsoGTYk8_WHFWI6CE2e(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_Fu3sYKZIuVhWVqwSrNMy2f(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kTgaWou2ePGi_T83eVmFB4(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kE4ggXPRuoKbg9HQdpE4D9(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__aK6RhIri2lsiPw9024AWm(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_kZtJNvHqhaC2YXYlEWrh3k(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VnYSekQWhpOYYPjDWhTOod(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kwuFB_guvCORXTdOY4UzOM(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VfTUkRE7gRtXfXDqOCNgGn(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli__JqOJzB0KxdqgXfjaKtWIa(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kjeAwr4pAFloZ9ZzA_nG8M(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_VUg_nT8OzmSqY5SEaTPMyk(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kdrm8_CkIRdyZLDWuc4lOV(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_VBMd0tXODmxLda_dFV9uP8(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_ka77aS1n6yCxcerEl7v1wG(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_k3bobvwthx8Ziu2mn2F0GJ(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__Hq42Wk_zm0tf57HHJNb8K(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli__NyFjOIc89hGfaOX6LZHDS(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_F2GpUH_z4lKcYyKqirODC3(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC void
ssc_sli_kqN8aEQ2NgxN_D8dwZHHbj(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB,boolean_T value){*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB))=value;}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kCobpMmYSpxPdTEetzTICi(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC void ssc_sli_F8IwhpQUksl7XmkQJ97tWd(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB,boolean_T value)
{*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VdyOM3ac9ktjgT8rdrPUIH(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB))=value;}PMF_DEPLOY_STATIC boolean_T
ssc_sli__fZq__Q0E2xqfiI3oL4jo1(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VdyOM3ac9ktjgT8rdrPUIH(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_kosjTda6DbKpcPl1wp4aRa(
ssc_sli_VW_ogzaTyo0kXql81JaM_l const*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){size_t i;
PmIntVector ssc_sli__WLSFXXyRPp_XDpYDyBjwh=ssc_sli_kqLQwTUQI3CnaLR7ld3n7Q(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB);for(i=0;i<ssc_sli__WLSFXXyRPp_XDpYDyBjwh.mN;i
++){if(ssc_sli__WLSFXXyRPp_XDpYDyBjwh.mX[i]){return true;}}return false;}
#include "pm_std.h"
typedef struct ssc_sli_k2T1gEFX2_d4ZuI1Q_M1kw{size_t
ssc_sli_FPVB1VKrX_h8hmXFAx1z0H;size_t ssc_core_F3PjN_oDrpK0_ThkfqVg1d;size_t
mNumModes;size_t mNumOutputs;size_t ssc_sli__KrYlKhSdSOXXeT8d_3Kmo;size_t
mNumRanges;size_t mNumSamples;size_t mNumMassMatrixNzMax;size_t
mNumLinJacobianNzMax;size_t ssc_sli_VJ8SrpAMHKxmYL9Q3pA_A4;size_t
mNumTrimResiduals;size_t ssc_sli_kvfFJtWMgTxfi9k3xvvF62;size_t
ssc_sli_FkmLIiLc7CGWaPgysl5AJO;size_t mNumSwitchingCoefficients;size_t
mNumJacobianElements;boolean_T ssc_sli_Vp5HPyLroL0k_DUEAnUzoy;boolean_T
ssc_sli_VVPQB49wTEh4gXWM_xNirR;boolean_T ssc_sli_VPy35XeH1H_Ic5S5a75SOn;
boolean_T mIsMConstant;boolean_T mIsMRuntimeScaled;boolean_T
ssc_sli__arpT5XMu5t8YXkNe8wbMn;boolean_T mIsDae;boolean_T
ssc_sli_kQ9NLJnej_07gaKiLdXsC7;PmIntVector const*mNumInputs;PmBoolVector const
*mDirectFeedthrough;}ssc_sli_V95QTHcsdJWsceYUUIcaiZ;typedef struct
ssc_sli_FddFlqLbGs8Ec9cKizRnDH{size_t ssc_sli_kdbZHDJZystegu4mC2KxAD;char const
*ssc_sli_kfIUe_GyyUxNXP9R1Bzclf;char const*ssc_sli__CyZTkoYGzl7XaQhQFTWx1;}
ssc_sli_F33sTio252OSWDmfgFnBLU;typedef struct ssc_sli_VksJFOy6ztKWayuIvJC3vL{
ssc_sli_F33sTio252OSWDmfgFnBLU*ssc_sli_FAG8fdoVes_ic5rWxjy6NT;size_t
ssc_sli_kRTHQV6aVROXgXhhhLkvwE;}ssc_sli_FFsg1hWl9wdl_y_KxzGjIe;typedef enum
ssc_sli_kBNdZWiqPRKIYu1awz4kXx{ssc_sli_kbCIOzV5Z7CAfDR9BoZ7rH= -1,
ssc_sli__RiZc_WhuMSXYLxqycSSFc,ssc_sli_kvrVP8dK_YxdXT10arv4EW,
ssc_sli_VGxILroHbgtWiTFBYYNAXm,ssc_sli_FQL0hKTqv8Sie55gV0Y8cx,
ssc_sli__GCna4k_OrxVX9kSHDDXAK,ssc_sli_kP_7DeXUvbC5e9vpE9iOIT,
ssc_sli_F6P1FaANFippVajVLK2D_T,ssc_sli__CszVq_qJvldeXSY5iS6VL,
ssc_sli__mpohBd6Qp_vYyECv_lFRd,ssc_sli_Vipfdl4tnpGrjDCNh84ogK,
ssc_sli_VUy8x1u_Igd6imXZ9DEYho,ssc_sli_kyWSQenTs_8_Zi6Jcsix3G,
ssc_sli__LrXJSNsYmtVcyVzcNYi59,ssc_sli_Vn6CJo_YVN8OcP8nn1whv6,
ssc_sli_VoSYfpN1uFKlcPezC9ncVd,ssc_sli_V98MZzJMKq0gg5WhkoMwu1,
ssc_sli__nZdFLhYWdSfgTHqWj7syJ,ssc_sli_kApiqH0m_LhDi1Il30PsjP,
ssc_sli__bj8LviD_7SAa9h0Y93_l4,ssc_sli__O4lYRI3DZGge9bI6pIk6_,
ssc_sli__nDPNUqGxXOxfT_z5oMDRA}ssc_sli_VFwLXd9iXnKCc5B9U7TnKW;typedef struct
ssc_sli__XES3TASJmKShiLbwE_pro ssc_sli_kM_sIcp_r7pug543dTUIIr;typedef struct
ssc_sli_FgbqL7C2VQGsYPXNX9ttqk ssc_sli__ZioeTVESJGpeTrFjaf6zj;typedef enum
ssc_sli__CWP_5tK7QC0jie9CMmAkg{ssc_sli__H_8csAriglmWDalIx_Jr9= -1,
ssc_sli_FHeSjK10tG_GhuRp0IXZBS}ssc_sli__8c7dMQOS04JcqlXE55xkL;typedef
ssc_sli__8c7dMQOS04JcqlXE55xkL(*ssc_sli_FeZ1lmnch4dBbqwEnNlvCL)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*,
NeuDiagnosticManager*);typedef void(*ssc_sli_kqbwhVT7n1K_jHgv1wcKZP)(void*);
typedef void(*ssc_sli__gsXzOfgna_jX98M26bmMn)(void*);struct
ssc_sli__XES3TASJmKShiLbwE_pro{ssc_sli__ZioeTVESJGpeTrFjaf6zj*
ssc_sli__X9HoYTA6GhUZPkX6FMtmN;ssc_sli_FeZ1lmnch4dBbqwEnNlvCL mMethods[
ssc_sli__nDPNUqGxXOxfT_z5oMDRA];ssc_sli_V95QTHcsdJWsceYUUIcaiZ(*mSizes)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);void(*ssc_sli_kI7uP4YIZw8pW16U7gwAco)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli__N_2P1psnRxPfLDTTyJSvb)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli_VbhYHtP_w5KncDt2d365fm)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,PmRealVector*
ssc_sli_VIrgfYjjo5hWjLkZEUNImr,PmRealVector*ssc_sli_F4Dzn5SAupC7jPCs01xBuJ);
ssc_sli__8c7dMQOS04JcqlXE55xkL(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,NeModelParameters const*mp,
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z,
ssc_sli_kqbwhVT7n1K_jHgv1wcKZP mc_Fyss_XM3F_C4dm6IKoDw4G,
ssc_sli__gsXzOfgna_jX98M26bmMn mc_Vs6xonQX17Krc5vXv8T_zq,void*
ssc_sli_V0_YXRZgCwhpfXYneT6RGZ);ssc_sli_FfCmiDUlTHWdhTaGeWWmuy const*(*
ssc_sli__fA9Mq6IS2xIV5WAVknKiS)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);
SLMatrices const**(*ssc_sli__fpSjGZmQx4lXe__BBu7Lj)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);ssc_sli__8c7dMQOS04JcqlXE55xkL(*
ssc_sli_V3vxMRQq8gCQeHUFA6N8LD)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,
ssc_sli_VW_ogzaTyo0kXql81JaM_l const*ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,void*
mc_FvxKbdtfPKOYaymjtthQ0G,NeuDiagnosticManager*);NeStiffness*
ssc_sli_k7O4VJD_GfWTiueS_WbVpj;void(*ssc_sli_k38RFN7EiQlTfHNlMviDub)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,IterationsLogCore*
ssc_sli_kFG1cmkvYqxhhXEyS95YdT);ssc_sli__8c7dMQOS04JcqlXE55xkL(*
ssc_sli_k2IVLe_gJolxZ5lBGBeXYp)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*
ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,double*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mDestroy)(ssc_sli_kM_sIcp_r7pug543dTUIIr*);NeCustomData*(*
ssc_sli__lOEzNzI75d6fuOcayiCxx)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*);
ssc_sli__8c7dMQOS04JcqlXE55xkL(*ssc_sli__ZfgolV2w_8cVmgW1DQ1Wi)(NeCustomData
const*,ssc_sli_kM_sIcp_r7pug543dTUIIr const*,NeuDiagnosticManager*);NeZCData
const*mZCData;NeRange const*mRanges;NeParameterInfo mParameterInfo;void(*
mSetParameters)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*,NeParameterBundle const*
);};PMF_DEPLOY_STATIC ssc_sli__8c7dMQOS04JcqlXE55xkL
ssc_sli_VyboOwUKgZhScDgGLfXkIQ(ssc_sli_kM_sIcp_r7pug543dTUIIr const*
ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,ssc_sli_VFwLXd9iXnKCc5B9U7TnKW
ssc_sli_kwhduxmN0MGLbibTtE1dsV,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z){return ssc_sli_F9ORBrZw_TS4eeOz_jH6FW->mMethods[
ssc_sli_kwhduxmN0MGLbibTtE1dsV](ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,pm_st_kPInN_8SRA_iYeTvYVKl3z);}typedef struct
ssc_sli_VZuNChGiiAGAYH2qBjaeOb ssc_sli_VR5KyEQ4cqhSdu3_mivtjm;typedef struct
ssc_sli_k5oTlTjw3B4FealapdTq0o ssc_sli__MwrrfYP_Utdce6lk15F_w;typedef void(*
ssc_sli__m7_DD1WSE_8iDiss0OZ24)(void*);typedef void(*
ssc_sli__ruDSvt7RVCvXa_F7eQMcr)(void*);struct ssc_sli_VZuNChGiiAGAYH2qBjaeOb{
size_t mNumInputs;size_t mNumStates;size_t mNumOutputs;size_t
ssc_sli_FkmLIiLc7CGWaPgysl5AJO;double ssc_sli__BzytCIJqpK6X9hlBST23v;
NeParameterInfo const*mParameterInfo;ssc_sli__MwrrfYP_Utdce6lk15F_w*mData;
PmSizeVector const*ssc_sli_VoAqpPI1wGlSd9G9Pvkz1u;void(*
ssc_sli__N_2P1psnRxPfLDTTyJSvb)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli_FqbH9qSYJs0xdXvTtIQe5G)(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,boolean_T
ssc_sli_FNnVz906Ccx2humxdqRIHf);boolean_T(*ssc_sli_k0d9xwJv_7dOX9x2cJmSYP)(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);
boolean_T(*mSetParameters)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeParameterBundle const*
ssc_core__wmTd2KKOKd7YPG6_QANiL);boolean_T(*mStart)(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);NeDynamicSystemInput(
*ssc_sli__h7bfQNxXbWfeerDEb8eHt)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,PmRealVector const*
ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time);void(*
ssc_sli_FkOnu54reaGRbeQmmTIPpX)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc);boolean_T(*
mSolve)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
PmRealVector const*ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,PmRealVector const*
ssc_sli_FIhpJ2B309KpaHh5HnJcyt,real_T time,void*mc_FvxKbdtfPKOYaymjtthQ0G,
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z,boolean_T
ssc_sli__Q7Ma2_YOStTje8AA4bkl7);boolean_T(*mCheck)(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
PmRealVector const*ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time,NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*s,ssc_sli__m7_DD1WSE_8iDiss0OZ24
mc_Fyss_XM3F_C4dm6IKoDw4G,ssc_sli__ruDSvt7RVCvXa_F7eQMcr
mc_Vs6xonQX17Krc5vXv8T_zq,void*ssc_sli_V0_YXRZgCwhpfXYneT6RGZ);void(*mPushInfo
)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*s,IterationsLogCore*
ssc_sli_kFG1cmkvYqxhhXEyS95YdT);mc_F9HbKNDZMeOehmlKWGUdea const*(*
ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*s);
NeStiffness*(*ssc_sli_V3vxMRQq8gCQeHUFA6N8LD)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm
const*s);void(*mDestroy)(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);};ssc_sli_VR5KyEQ4cqhSdu3_mivtjm*
simulator_create(ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM,
NeSolverParameters const ssc_core_kv7GnpbgsfSGjTKLxq5SvA,
McLinearAlgebraFactory const*la,NeVariableData const*
ssc_sli_V9H8SF3Spx4_hTWq9esS4U,NeVariableData const*
ssc_sli_VJMsZXAvFiOUeybWeDvKJF,NeModeData const*ssc_sli_kOXHZ_J3y__Bja8l9kYwoQ
,NeObservableData const*ssc_sli__Z20ybDrHThEf9sHnWmhcw,size_t const
ssc_sli_VJqInTdu468cVaIYe876ey,ssc_core_VMObUicZgDGkXuH3R8jgeY const
ssc_core_VkEZfX8sDrW2fPxW5Ht5d2);ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
rtp_manager_create(ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "ne_std.h"
struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G{ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh;};static void ssc_sli__TSE8VIBEoOSdurS4nM9Zn(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*manager){PmAllocator*a=pm_default_allocator();{
void*const ssc_sli__nXet41dE8_kZelZPVMcOT=(manager->
ssc_sli__X9HoYTA6GhUZPkX6FMtmN);PmAllocator*const
ssc_sli_Frm9k6MhgTdp_qVSQABULF=(a);if(ssc_sli__nXet41dE8_kZelZPVMcOT){(
ssc_sli_Frm9k6MhgTdp_qVSQABULF)->mFreeFcn(ssc_sli_Frm9k6MhgTdp_qVSQABULF,
ssc_sli__nXet41dE8_kZelZPVMcOT);}};{void*const ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9=
(manager);PmAllocator*const ssc_sli_VBqGHWZ7CldnePAFp61g0Y=(a);if(
ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9){(ssc_sli_VBqGHWZ7CldnePAFp61g0Y)->mFreeFcn(
ssc_sli_VBqGHWZ7CldnePAFp61g0Y,ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9);}};}static
NeParameterInfo ssc_sli_k2sIBoVJK1hofeCgH72a6B(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A
const*manager){return*(manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh->mParameterInfo);}static boolean_T
ssc_sli_VoO9Gu6VfPCHWqO_Tv5CXD(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*manager,
double time,NeParameterBundle const*ssc_core__wmTd2KKOKd7YPG6_QANiL,
NeuDiagnosticManager*ssc_core_kDh9Sdqtd1dhZLBqs4W1eB){(void)(time);(void)(
ssc_core_kDh9Sdqtd1dhZLBqs4W1eB);return(manager->
ssc_sli__X9HoYTA6GhUZPkX6FMtmN->ssc_sli_FwPr_01lCZ_TeivYoKB7Mh)->
mSetParameters((manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh),(ssc_core__wmTd2KKOKd7YPG6_QANiL));}
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*rtp_manager_create(
ssc_sli_VR5KyEQ4cqhSdu3_mivtjm const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2){
PmAllocator*a=pm_default_allocator();ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A))));ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli_k51CpyBIqopkVTskBXuCpi=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli_kqioa3Wq9idS_X_JDQovlr))));ssc_sli_k51CpyBIqopkVTskBXuCpi->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh=ssc_sli__8ZNW6YU7nGkW9bWBMo_l2;
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->ssc_sli__X9HoYTA6GhUZPkX6FMtmN=
ssc_sli_k51CpyBIqopkVTskBXuCpi;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mParameterInfo=
ssc_sli_k2sIBoVJK1hofeCgH72a6B;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mSetParameters=
ssc_sli_VoO9Gu6VfPCHWqO_Tv5CXD;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mDestroy=
ssc_sli__TSE8VIBEoOSdurS4nM9Zn;return ssc_sli_ksoYuHDGUqSHXa_wqiOeKh;}
