#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(char
const*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
typedef enum ssc_core_FsdFfzfAVXO_Xia1StEklO{ssc_core_kWt32YokoLOhcuaxS6yfzx= -
2,ssc_core__Q97de9wAyd2ai1qgkC7FJ,ssc_core_krzbr94PVv0ZbeCf8B8TOo,
ssc_core_kF8uUNHtzb_HVP_tWzVLHo}ssc_core_VPCajzt28fK6eatUgrzZrl;typedef enum
ssc_core__JcefoydxW0GWq4xMUbLxI{ssc_core__0afaMKI46Kvd9u76KUzXf= -1,
ssc_core__aIDnqGzhqWcVu6dhPsWV2,ssc_core__uwax1cB6y8TfaKQr2KH_y,
ssc_core_kOw2Uegv5BGjVXro1JWJHO,ssc_core_k5b_oShgvQlNjHaf65qGgH,
ssc_core_F31_G54i4lxiea2KJi6kBi,ssc_core__XHpTEMxftlSiT4M8UKKvF}
ssc_core_VonIc63zAk4_dqgAttBCge;typedef struct ssc_core_FpYOP0TyTZhiZaeVw73BmH
ssc_core__TnsaUXKFcKxbitO58_d7o;typedef struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs
ssc_core_kIG7sD0lJlWTfaZr6Pehvz;struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs{
boolean_T(*ssc_core_kpVC1AX7p50Ja18UISsLi_)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz
const*);boolean_T(*ssc_core_F9Kq4Qr_9Z0Yjm1oicqvtn)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*);int32_T(*
ssc_core__pl1MSSO99W8WP3QqnoCib)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,real_T const
*);void(*mInitializeFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,
NeSimulationParameters);int32_T(*ssc_core_VG3e0ucOiSGjh1qwaVjeHl)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,real_T,real_T const*);void(*
ssc_core_VpAc4HLF9R4vc5lHk8ztuA)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*,size_t
,real_T,real_T*,real_T*);void(*ssc_core_kosGVqM5sQxa_ilVRRQVR_)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,PmAllocator*);NeCustomData*(*
mGetCustomDataFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*);int32_T(*
mSetCustomDataFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,NeCustomData const*);
ssc_core__TnsaUXKFcKxbitO58_d7o*mData;};ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_VvMTiJ4aNWS9XLZDSLRpBj(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,real_T
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_F4kcadj_4cKHg1ezX_zsql(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,size_t ssc_core__ParkdIrhYxeXmPALk_GF9,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void ssc_core__iidYZ4BYP_PjX5JZknJVI(
real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,
real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core_FrSEQFBq28SaWiGfpVZwav(real_T
ssc_core__J04yncaH90DXHzyG0hSm2,real_T ssc_core_V1YgAr3atRObWulPGeoQrC,real_T
ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core__6TSrGdfXtxLbXc3mviqDL(real_T
ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T
ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(real_T
ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T
ssc_core_kxEENIdWfPSaZDyic0CcaO,real_T ssc_core__Hi10z5HjzpmfeY11NOEhD,real_T
ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);typedef struct ssc_core_VtY6X81GcTK0bqT290UMP7
ssc_core_VwbF2prDlG_nWi2eq_IWPE;struct ssc_core_VtY6X81GcTK0bqT290UMP7{real_T*
mc__d1alWYexptL_X5HTFhbNK;ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_FTf2iFFdsgK3hewKsMgEx4;};static ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_Vn5XuP9HJA0pj5UuXb_7E9(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,size_t
ssc_core__ParkdIrhYxeXmPALk_GF9){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kozcyYkxMvOHfeg9l7McOP=(ssc_core_VwbF2prDlG_nWi2eq_IWPE*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
ssc_core_VwbF2prDlG_nWi2eq_IWPE)),(1))));ssc_core_kozcyYkxMvOHfeg9l7McOP->
mc__d1alWYexptL_X5HTFhbNK=(real_T*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(real_T)),(ssc_core__ParkdIrhYxeXmPALk_GF9))
));ssc_core_kozcyYkxMvOHfeg9l7McOP->ssc_core_FTf2iFFdsgK3hewKsMgEx4=NULL;
return ssc_core_kozcyYkxMvOHfeg9l7McOP;}static void
ssc_core_VktmBtsnDZh3WL_5MgKBfv(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_kozcyYkxMvOHfeg9l7McOP){if(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){{void*const
ssc_core_FxwVSg9vwzG8eLtQskT9KX=(ssc_core_kozcyYkxMvOHfeg9l7McOP->
mc__d1alWYexptL_X5HTFhbNK);PmAllocator*const ssc_core__QcrDUEx64pIcLN2CBuiTs=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(ssc_core_FxwVSg9vwzG8eLtQskT9KX){(
ssc_core__QcrDUEx64pIcLN2CBuiTs)->mFreeFcn(ssc_core__QcrDUEx64pIcLN2CBuiTs,
ssc_core_FxwVSg9vwzG8eLtQskT9KX);}};}{void*const
ssc_core__C_AVFcEZZG0Y1__2oLk7e=(ssc_core_kozcyYkxMvOHfeg9l7McOP);PmAllocator*
const ssc_core__mQHnqOFwQGrb5Ykgr_uAL=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core__C_AVFcEZZG0Y1__2oLk7e){(ssc_core__mQHnqOFwQGrb5Ykgr_uAL)->mFreeFcn(
ssc_core__mQHnqOFwQGrb5Ykgr_uAL,ssc_core__C_AVFcEZZG0Y1__2oLk7e);}};}typedef
struct ssc_core__O0ccrbwinGtZXg5rlKfPs ssc_core__3jAYGRNM_0vZ1_f3K3L68;struct
ssc_core__O0ccrbwinGtZXg5rlKfPs{real_T ssc_core_Vc8UlnXwWF0_aL2KTzQdoU;size_t
ssc_core__ParkdIrhYxeXmPALk_GF9;ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_Vz1qOwNhpDtia9165RAqXH;};static ssc_core__3jAYGRNM_0vZ1_f3K3L68
ssc_core__AanNsDwooWtiyayYiR0pB(size_t ssc_core__ParkdIrhYxeXmPALk_GF9){
ssc_core__3jAYGRNM_0vZ1_f3K3L68 buffer;buffer.ssc_core_Vc8UlnXwWF0_aL2KTzQdoU=
-1.0;buffer.ssc_core__ParkdIrhYxeXmPALk_GF9=ssc_core__ParkdIrhYxeXmPALk_GF9;
buffer.ssc_core_Vz1qOwNhpDtia9165RAqXH=NULL;return buffer;}static void
ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer){size_t ssc_core__ParkdIrhYxeXmPALk_GF9
=buffer->ssc_core__ParkdIrhYxeXmPALk_GF9;ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH;
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_krDVsFAiZgCMb9NNivdA_W=
ssc_core_Vn5XuP9HJA0pj5UuXb_7E9(pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core__ParkdIrhYxeXmPALk_GF9);buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH=
ssc_core_krDVsFAiZgCMb9NNivdA_W;ssc_core_krDVsFAiZgCMb9NNivdA_W->
ssc_core_FTf2iFFdsgK3hewKsMgEx4=ssc_core_kozcyYkxMvOHfeg9l7McOP;}static void
ssc_core_VAscH6T1zTlHhuux1atWp5(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn=ssc_core_kozcyYkxMvOHfeg9l7McOP;
ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;ssc_core_VktmBtsnDZh3WL_5MgKBfv(
pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core_Fk2O4u6vQUpibmbv8Kjgnn);}buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH=NULL;}static size_t
ssc_core_kzlWqj4pNG_gW56PhCRMGw(ssc_core__3jAYGRNM_0vZ1_f3K3L68 const*buffer){
return(buffer->ssc_core__ParkdIrhYxeXmPALk_GF9)*sizeof(real_T);}static void
ssc_core_VWkS7fZR3H8Xa9CY_1wp_q(ssc_core__3jAYGRNM_0vZ1_f3K3L68*value,
ssc_core__3jAYGRNM_0vZ1_f3K3L68 const*time,real_T
ssc_core_F1aDw7ykDz_jjyvLiJdK_V,size_t*ssc_core_FNt92uaclVCyYXOJ4ykVyd,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kmU1yeVjxg_1iTZdf84A3T=value->ssc_core_Vz1qOwNhpDtia9165RAqXH;
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core__tFRtjv9fWKsiTRQyGa9Qa=time->
ssc_core_Vz1qOwNhpDtia9165RAqXH;real_T ssc_core_Vc8UlnXwWF0_aL2KTzQdoU=value->
ssc_core_Vc8UlnXwWF0_aL2KTzQdoU;(void)0;while((ssc_core__tFRtjv9fWKsiTRQyGa9Qa
->mc__d1alWYexptL_X5HTFhbNK[0]>ssc_core_F1aDw7ykDz_jjyvLiJdK_V-
ssc_core_Vc8UlnXwWF0_aL2KTzQdoU)&&(ssc_core_kmU1yeVjxg_1iTZdf84A3T->
ssc_core_FTf2iFFdsgK3hewKsMgEx4!=NULL)){(void)0;
ssc_core_kmU1yeVjxg_1iTZdf84A3T=ssc_core_kmU1yeVjxg_1iTZdf84A3T->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;ssc_core__tFRtjv9fWKsiTRQyGa9Qa=
ssc_core__tFRtjv9fWKsiTRQyGa9Qa->ssc_core_FTf2iFFdsgK3hewKsMgEx4;}{
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_k08OnAArgvx5dDXp_0Jkw_=
ssc_core_kmU1yeVjxg_1iTZdf84A3T;ssc_core_kmU1yeVjxg_1iTZdf84A3T=
ssc_core_kmU1yeVjxg_1iTZdf84A3T->ssc_core_FTf2iFFdsgK3hewKsMgEx4;while(
ssc_core_kmU1yeVjxg_1iTZdf84A3T!=NULL){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn=ssc_core_kmU1yeVjxg_1iTZdf84A3T->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;ssc_core_VktmBtsnDZh3WL_5MgKBfv(
pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core_kmU1yeVjxg_1iTZdf84A3T);
ssc_core_kmU1yeVjxg_1iTZdf84A3T=ssc_core_Fk2O4u6vQUpibmbv8Kjgnn;(*
ssc_core_FNt92uaclVCyYXOJ4ykVyd)+=ssc_core_kzlWqj4pNG_gW56PhCRMGw(value);}
ssc_core_k08OnAArgvx5dDXp_0Jkw_->ssc_core_FTf2iFFdsgK3hewKsMgEx4=NULL;}}static
int32_T ssc_core_FgTceQhIDhCcgPeVOM1CZU(ssc_core__3jAYGRNM_0vZ1_f3K3L68*
ssc_core_VcvT_hfFUEKucL1CkuGGDZ,ssc_core__3jAYGRNM_0vZ1_f3K3L68*
ssc_core_V1rLE_iMx9Cx_yTvxpjIho,size_t const ssc_core_kgD5Z0Aj8ElKaD6YrtYu0_,
size_t const ssc_core__K0_v7xZPoOLfHFOqAdCLP,real_T const
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T const*const
ssc_core_k4y8mv5uXzheZimBIk_n7I,size_t*ssc_core_FwcMuQh6w44jgmVmh5bq4X,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){int32_T ssc_core_k4M7bSEmThKJbirXUDQgS6
=ssc_core__aIDnqGzhqWcVu6dhPsWV2;size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd= *
ssc_core_FwcMuQh6w44jgmVmh5bq4X;size_t ssc_core__ParkdIrhYxeXmPALk_GF9=
ssc_core_VcvT_hfFUEKucL1CkuGGDZ->ssc_core__ParkdIrhYxeXmPALk_GF9;size_t i;(
void)0;if(ssc_core__K0_v7xZPoOLfHFOqAdCLP==0){ssc_core_k4M7bSEmThKJbirXUDQgS6=
ssc_core__aIDnqGzhqWcVu6dhPsWV2;}else if(ssc_core__K0_v7xZPoOLfHFOqAdCLP%
ssc_core__ParkdIrhYxeXmPALk_GF9==0){if(ssc_core_FNt92uaclVCyYXOJ4ykVyd<
ssc_core_kzlWqj4pNG_gW56PhCRMGw(ssc_core_V1rLE_iMx9Cx_yTvxpjIho)*
ssc_core_kgD5Z0Aj8ElKaD6YrtYu0_+ssc_core_kzlWqj4pNG_gW56PhCRMGw(
ssc_core_VcvT_hfFUEKucL1CkuGGDZ)){ssc_core_k4M7bSEmThKJbirXUDQgS6=
ssc_core_k5b_oShgvQlNjHaf65qGgH;}else{ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(
pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core_VcvT_hfFUEKucL1CkuGGDZ);
ssc_core_FNt92uaclVCyYXOJ4ykVyd-=ssc_core_kzlWqj4pNG_gW56PhCRMGw(
ssc_core_VcvT_hfFUEKucL1CkuGGDZ);for(i=0;i<ssc_core_kgD5Z0Aj8ElKaD6YrtYu0_;++i
){(void)0;ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
ssc_core_V1rLE_iMx9Cx_yTvxpjIho[i]));ssc_core_FNt92uaclVCyYXOJ4ykVyd-=
ssc_core_kzlWqj4pNG_gW56PhCRMGw(&(ssc_core_V1rLE_iMx9Cx_yTvxpjIho[i]));}
ssc_core_k4M7bSEmThKJbirXUDQgS6=ssc_core__aIDnqGzhqWcVu6dhPsWV2;}}if(
ssc_core_k4M7bSEmThKJbirXUDQgS6==ssc_core__aIDnqGzhqWcVu6dhPsWV2){
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_kPBSxzOtA14b_y_cuzlDQY=
ssc_core_VcvT_hfFUEKucL1CkuGGDZ->ssc_core_Vz1qOwNhpDtia9165RAqXH;size_t
ssc_core_VpvAVJM2uR0Vj9cndwz6UE=ssc_core__K0_v7xZPoOLfHFOqAdCLP%
ssc_core__ParkdIrhYxeXmPALk_GF9;ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_VpvAVJM2uR0Vj9cndwz6UE]=
ssc_core__1eAP9V6_J_NYm_1gTIm7A;for(i=0;i<ssc_core_kgD5Z0Aj8ElKaD6YrtYu0_;++i)
{ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_V1M2zmo6CuGp_TY3XJ0qPV=
ssc_core_V1rLE_iMx9Cx_yTvxpjIho[i].ssc_core_Vz1qOwNhpDtia9165RAqXH;
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_VpvAVJM2uR0Vj9cndwz6UE]=ssc_core_k4y8mv5uXzheZimBIk_n7I[i];}*
ssc_core_FwcMuQh6w44jgmVmh5bq4X=ssc_core_FNt92uaclVCyYXOJ4ykVyd;}return
ssc_core_k4M7bSEmThKJbirXUDQgS6;}static ssc_core_VPCajzt28fK6eatUgrzZrl
ssc_core_VJjzeg2lHXKq_y_Wta2PM6(ssc_core__3jAYGRNM_0vZ1_f3K3L68 time,
ssc_core__3jAYGRNM_0vZ1_f3K3L68 value,size_t ssc_core___6udXZYOhlzcy3nvCqtF3,
real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kPBSxzOtA14b_y_cuzlDQY=time.ssc_core_Vz1qOwNhpDtia9165RAqXH;
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_V1M2zmo6CuGp_TY3XJ0qPV=value.
ssc_core_Vz1qOwNhpDtia9165RAqXH;size_t const ssc_core__ParkdIrhYxeXmPALk_GF9=
time.ssc_core__ParkdIrhYxeXmPALk_GF9;size_t const
ssc_core__CNtDMT0gG_CWavNCAeKqL=ssc_core__ParkdIrhYxeXmPALk_GF9-1;size_t
ssc_core_kRulqmDih10_ZennjcVP0K=(ssc_core___6udXZYOhlzcy3nvCqtF3-1)%
ssc_core__ParkdIrhYxeXmPALk_GF9;(void)0;(void)0;if(pmf_is_nan(
ssc_core__1eAP9V6_J_NYm_1gTIm7A)){*v=pmf_get_nan();*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=pmf_get_nan();return
ssc_core_krzbr94PVv0ZbeCf8B8TOo;}if(ssc_core__1eAP9V6_J_NYm_1gTIm7A>=
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_kRulqmDih10_ZennjcVP0K]){if(ssc_core_kRulqmDih10_ZennjcVP0K>0){
ssc_core_FrSEQFBq28SaWiGfpVZwav(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_kRulqmDih10_ZennjcVP0K-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_kRulqmDih10_ZennjcVP0K-1],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_kRulqmDih10_ZennjcVP0K],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_kRulqmDih10_ZennjcVP0K],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else if(ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
ssc_core_FTf2iFFdsgK3hewKsMgEx4!=NULL){ssc_core_FrSEQFBq28SaWiGfpVZwav(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__iidYZ4BYP_PjX5JZknJVI(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}return ssc_core_kF8uUNHtzb_HVP_tWzVLHo;}if((
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0]<=
ssc_core__1eAP9V6_J_NYm_1gTIm7A)&&(ssc_core__1eAP9V6_J_NYm_1gTIm7A<=
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_kRulqmDih10_ZennjcVP0K])){size_t ssc_core_V_B84QSCqtdSiyDNn4nO_W=0;
size_t ssc_core_FU3UMXmcGLCXVLlotSHjSr=ssc_core_kRulqmDih10_ZennjcVP0K;while(
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1!=ssc_core_FU3UMXmcGLCXVLlotSHjSr){size_t
ssc_core_Fnnz2f591gdyfLGSeX__XR=(ssc_core_V_B84QSCqtdSiyDNn4nO_W+
ssc_core_FU3UMXmcGLCXVLlotSHjSr)/2;if(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_Fnnz2f591gdyfLGSeX__XR]<=
ssc_core__1eAP9V6_J_NYm_1gTIm7A){ssc_core_V_B84QSCqtdSiyDNn4nO_W=
ssc_core_Fnnz2f591gdyfLGSeX__XR;}else{ssc_core_FU3UMXmcGLCXVLlotSHjSr=
ssc_core_Fnnz2f591gdyfLGSeX__XR;}}{(void)0;if(ssc_core__1eAP9V6_J_NYm_1gTIm7A
==ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W]){if(ssc_core_V_B84QSCqtdSiyDNn4nO_W>0){
ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W-1],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else if(ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
ssc_core_FTf2iFFdsgK3hewKsMgEx4!=NULL){ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__6TSrGdfXtxLbXc3mviqDL(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}else{ssc_core__6TSrGdfXtxLbXc3mviqDL(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}return
ssc_core_krzbr94PVv0ZbeCf8B8TOo;}while(true){if(
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4==NULL){if(
ssc_core___6udXZYOhlzcy3nvCqtF3>1){ssc_core_FrSEQFBq28SaWiGfpVZwav(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[1],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__iidYZ4BYP_PjX5JZknJVI(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}return ssc_core__Q97de9wAyd2ai1qgkC7FJ;}if((
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__CNtDMT0gG_CWavNCAeKqL]<=
ssc_core__1eAP9V6_J_NYm_1gTIm7A)&&(ssc_core__1eAP9V6_J_NYm_1gTIm7A<
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0])){if(
ssc_core__1eAP9V6_J_NYm_1gTIm7A==ssc_core_kPBSxzOtA14b_y_cuzlDQY->
ssc_core_FTf2iFFdsgK3hewKsMgEx4->mc__d1alWYexptL_X5HTFhbNK[
ssc_core__CNtDMT0gG_CWavNCAeKqL]){(void)0;ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__CNtDMT0gG_CWavNCAeKqL-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__CNtDMT0gG_CWavNCAeKqL-1],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__CNtDMT0gG_CWavNCAeKqL],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__CNtDMT0gG_CWavNCAeKqL],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[0],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__6TSrGdfXtxLbXc3mviqDL(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
ssc_core_FTf2iFFdsgK3hewKsMgEx4->mc__d1alWYexptL_X5HTFhbNK[
ssc_core__CNtDMT0gG_CWavNCAeKqL],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
ssc_core_FTf2iFFdsgK3hewKsMgEx4->mc__d1alWYexptL_X5HTFhbNK[
ssc_core__CNtDMT0gG_CWavNCAeKqL],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[0],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}return ssc_core_krzbr94PVv0ZbeCf8B8TOo;}
ssc_core_kPBSxzOtA14b_y_cuzlDQY=ssc_core_kPBSxzOtA14b_y_cuzlDQY->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;ssc_core_V1M2zmo6CuGp_TY3XJ0qPV=
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4;if((
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[0]<=
ssc_core__1eAP9V6_J_NYm_1gTIm7A)&&(ssc_core__1eAP9V6_J_NYm_1gTIm7A<=
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core__CNtDMT0gG_CWavNCAeKqL])){size_t ssc_core_V_B84QSCqtdSiyDNn4nO_W=0;
size_t ssc_core_FU3UMXmcGLCXVLlotSHjSr=ssc_core__CNtDMT0gG_CWavNCAeKqL;while(
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1!=ssc_core_FU3UMXmcGLCXVLlotSHjSr){size_t
ssc_core_Fnnz2f591gdyfLGSeX__XR=(ssc_core_V_B84QSCqtdSiyDNn4nO_W+
ssc_core_FU3UMXmcGLCXVLlotSHjSr)/2;if(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_Fnnz2f591gdyfLGSeX__XR]<=
ssc_core__1eAP9V6_J_NYm_1gTIm7A){ssc_core_V_B84QSCqtdSiyDNn4nO_W=
ssc_core_Fnnz2f591gdyfLGSeX__XR;}else{ssc_core_FU3UMXmcGLCXVLlotSHjSr=
ssc_core_Fnnz2f591gdyfLGSeX__XR;}}{if(ssc_core__1eAP9V6_J_NYm_1gTIm7A==
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W]){if(ssc_core_V_B84QSCqtdSiyDNn4nO_W>0){
ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W-1],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else if(ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
ssc_core_FTf2iFFdsgK3hewKsMgEx4!=NULL){ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->ssc_core_FTf2iFFdsgK3hewKsMgEx4->
mc__d1alWYexptL_X5HTFhbNK[ssc_core__ParkdIrhYxeXmPALk_GF9-1],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__6TSrGdfXtxLbXc3mviqDL(ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_kPBSxzOtA14b_y_cuzlDQY->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}else{ssc_core__6TSrGdfXtxLbXc3mviqDL(
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W],
ssc_core_kPBSxzOtA14b_y_cuzlDQY->mc__d1alWYexptL_X5HTFhbNK[
ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],ssc_core_V1M2zmo6CuGp_TY3XJ0qPV->
mc__d1alWYexptL_X5HTFhbNK[ssc_core_V_B84QSCqtdSiyDNn4nO_W+1],
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}return
ssc_core_krzbr94PVv0ZbeCf8B8TOo;}}(void)0;return
ssc_core_kWt32YokoLOhcuaxS6yfzx;}struct ssc_core_FpYOP0TyTZhiZaeVw73BmH{size_t
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t ssc_core_kjVMEKO_Gg8beattYY_YXT;
boolean_T ssc_core___Yx8SrZeg4iVqulP_D4Fs;size_t
ssc_core__fwQoFPwhn4V_5mnuVti9m;ssc_core__3jAYGRNM_0vZ1_f3K3L68 time;
ssc_core__3jAYGRNM_0vZ1_f3K3L68*mc_kVkvrfpzuVduaPTr5FLF8K;PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY;};static ssc_core__TnsaUXKFcKxbitO58_d7o*
ssc_core_FPENxS4RNQ8T_Dpq_5vgtb(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,size_t ssc_core__ParkdIrhYxeXmPALk_GF9,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){size_t i;
ssc_core__TnsaUXKFcKxbitO58_d7o*result=(ssc_core__TnsaUXKFcKxbitO58_d7o*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
ssc_core__TnsaUXKFcKxbitO58_d7o)),(1))));result->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4=ssc_core_V8uoyu0_YA0beyMVkKylrC;result->
ssc_core_kjVMEKO_Gg8beattYY_YXT=ssc_core_FNt92uaclVCyYXOJ4ykVyd;result->
ssc_core___Yx8SrZeg4iVqulP_D4Fs=false;result->ssc_core__fwQoFPwhn4V_5mnuVti9m=
0;(void)0;result->mc_kVkvrfpzuVduaPTr5FLF8K=((pm_FbYb_iLqY2hwZTVlVaiqJY)->
mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(ssc_core_V8uoyu0_YA0beyMVkKylrC),(
sizeof(ssc_core__3jAYGRNM_0vZ1_f3K3L68))));for(i=0;i<
ssc_core_V8uoyu0_YA0beyMVkKylrC;i++){result->mc_kVkvrfpzuVduaPTr5FLF8K[i]=
ssc_core__AanNsDwooWtiyayYiR0pB(ssc_core__ParkdIrhYxeXmPALk_GF9);}result->time
=ssc_core__AanNsDwooWtiyayYiR0pB(ssc_core__ParkdIrhYxeXmPALk_GF9);result->
pm_FbYb_iLqY2hwZTVlVaiqJY=pm_FbYb_iLqY2hwZTVlVaiqJY;return result;}static
boolean_T ssc_core_knzRHl4KHw_Ff9qkPqkDfK(ssc_core__TnsaUXKFcKxbitO58_d7o const
*mc__d1alWYexptL_X5HTFhbNK){return mc__d1alWYexptL_X5HTFhbNK->
ssc_core___Yx8SrZeg4iVqulP_D4Fs;}static boolean_T
ssc_core_kTG_5_cRDW8Tc5IgaIX_GH(ssc_core__TnsaUXKFcKxbitO58_d7o const*
mc__d1alWYexptL_X5HTFhbNK){return(ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
mc__d1alWYexptL_X5HTFhbNK)&&mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m>0);}static int32_T
ssc_core_kRBrlSqklIlNh1qpUnj_l4(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK){size_t i;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT;size_t
ssc_core__ParkdIrhYxeXmPALk_GF9=mc__d1alWYexptL_X5HTFhbNK->time.
ssc_core__ParkdIrhYxeXmPALk_GF9;size_t ssc_core_FMvX4vsdl_GqXu5CoNeRfI=(
ssc_core_F5sR7BGiOQO9jq888pvXvp+1)*ssc_core__ParkdIrhYxeXmPALk_GF9;size_t
ssc_core_F1QynWb_wstnYuW53um7MG=ssc_core_FMvX4vsdl_GqXu5CoNeRfI*sizeof(real_T)
;if(ssc_core_F1QynWb_wstnYuW53um7MG>ssc_core_FNt92uaclVCyYXOJ4ykVyd){return
ssc_core_kOw2Uegv5BGjVXro1JWJHO;}ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->time));for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){(void)0;ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i]));}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT-=ssc_core_F1QynWb_wstnYuW53um7MG;
mc__d1alWYexptL_X5HTFhbNK->ssc_core___Yx8SrZeg4iVqulP_D4Fs=true;(void)0;return
ssc_core__aIDnqGzhqWcVu6dhPsWV2;}static void ssc_core__Z4HfJeRyKhDVuUR83JXa2(
ssc_core__TnsaUXKFcKxbitO58_d7o*mc__d1alWYexptL_X5HTFhbNK){PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY
;size_t i;if(!ssc_core_knzRHl4KHw_Ff9qkPqkDfK(mc__d1alWYexptL_X5HTFhbNK)){
return;}(void)0;{ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer= &
mc__d1alWYexptL_X5HTFhbNK->time;ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn=ssc_core_kozcyYkxMvOHfeg9l7McOP;
ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;ssc_core_VktmBtsnDZh3WL_5MgKBfv(
pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core_Fk2O4u6vQUpibmbv8Kjgnn);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT+=
ssc_core_kzlWqj4pNG_gW56PhCRMGw(buffer);}buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH=NULL;}for(i=0;i<mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;i++){ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer= &
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K[i];
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH;while(ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_Fk2O4u6vQUpibmbv8Kjgnn=
ssc_core_kozcyYkxMvOHfeg9l7McOP;ssc_core_kozcyYkxMvOHfeg9l7McOP=
ssc_core_kozcyYkxMvOHfeg9l7McOP->ssc_core_FTf2iFFdsgK3hewKsMgEx4;
ssc_core_VktmBtsnDZh3WL_5MgKBfv(pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT+=ssc_core_kzlWqj4pNG_gW56PhCRMGw(buffer);}
buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH=NULL;}{size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT;size_t
ssc_core__ParkdIrhYxeXmPALk_GF9=mc__d1alWYexptL_X5HTFhbNK->time.
ssc_core__ParkdIrhYxeXmPALk_GF9;size_t ssc_core_FMvX4vsdl_GqXu5CoNeRfI=(
ssc_core_F5sR7BGiOQO9jq888pvXvp+1)*ssc_core__ParkdIrhYxeXmPALk_GF9;size_t
ssc_core_F1QynWb_wstnYuW53um7MG=ssc_core_FMvX4vsdl_GqXu5CoNeRfI*sizeof(real_T)
;(void)ssc_core_FNt92uaclVCyYXOJ4ykVyd;(void)0;ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb
(pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->time));for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){(void)0;ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i]));}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT-=ssc_core_F1QynWb_wstnYuW53um7MG;}
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m=0;}static void
ssc_core__0BJ4HcCvPSqgy0OBF9T7J(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t i;ssc_core_VAscH6T1zTlHhuux1atWp5(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->time));for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){ssc_core_VAscH6T1zTlHhuux1atWp5(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i]));}{void*const ssc_core_Vk2CigkiJ0Wih92zCjwUcs=(
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K);PmAllocator*const
ssc_core_FlmOTB3DZL_Aj1STyS619t=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_Vk2CigkiJ0Wih92zCjwUcs){(ssc_core_FlmOTB3DZL_Aj1STyS619t)->mFreeFcn(
ssc_core_FlmOTB3DZL_Aj1STyS619t,ssc_core_Vk2CigkiJ0Wih92zCjwUcs);}};{void*
const ssc_core_Fm5WW10U2_SaZLwFiRmah1=(mc__d1alWYexptL_X5HTFhbNK);PmAllocator*
const ssc_core_F1D1S7ALhyWn_XiPSieyMb=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_Fm5WW10U2_SaZLwFiRmah1){(ssc_core_F1D1S7ALhyWn_XiPSieyMb)->mFreeFcn(
ssc_core_F1D1S7ALhyWn_XiPSieyMb,ssc_core_Fm5WW10U2_SaZLwFiRmah1);}};}static
int32_T ssc_core_F4ay3mU2KmpqZ1iah9APGb(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T const*
pm_kpzAtHMD4_WnheH0UiioSE){int32_T ssc_core_k4M7bSEmThKJbirXUDQgS6=
ssc_core__aIDnqGzhqWcVu6dhPsWV2;size_t*ssc_core_FNt92uaclVCyYXOJ4ykVyd= &(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT);PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY
;size_t ssc_core__K0_v7xZPoOLfHFOqAdCLP=mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m;size_t i;(void)0;{size_t
ssc_core__ParkdIrhYxeXmPALk_GF9=mc__d1alWYexptL_X5HTFhbNK->time.
ssc_core__ParkdIrhYxeXmPALk_GF9;if((ssc_core__K0_v7xZPoOLfHFOqAdCLP>0)&&(
ssc_core__K0_v7xZPoOLfHFOqAdCLP%ssc_core__ParkdIrhYxeXmPALk_GF9==0)){for(i=0;i
<mc__d1alWYexptL_X5HTFhbNK->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;i++){
ssc_core_VWkS7fZR3H8Xa9CY_1wp_q(&(mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i]),&(mc__d1alWYexptL_X5HTFhbNK->time),
ssc_core__1eAP9V6_J_NYm_1gTIm7A,ssc_core_FNt92uaclVCyYXOJ4ykVyd,
pm_FbYb_iLqY2hwZTVlVaiqJY);}ssc_core_VWkS7fZR3H8Xa9CY_1wp_q(&(
mc__d1alWYexptL_X5HTFhbNK->time),&(mc__d1alWYexptL_X5HTFhbNK->time),
ssc_core__1eAP9V6_J_NYm_1gTIm7A,ssc_core_FNt92uaclVCyYXOJ4ykVyd,
pm_FbYb_iLqY2hwZTVlVaiqJY);}}ssc_core_k4M7bSEmThKJbirXUDQgS6=
ssc_core_FgTceQhIDhCcgPeVOM1CZU(&(mc__d1alWYexptL_X5HTFhbNK->time),
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K,mc__d1alWYexptL_X5HTFhbNK
->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4,ssc_core__K0_v7xZPoOLfHFOqAdCLP,
ssc_core__1eAP9V6_J_NYm_1gTIm7A,pm_kpzAtHMD4_WnheH0UiioSE,
ssc_core_FNt92uaclVCyYXOJ4ykVyd,pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_k4M7bSEmThKJbirXUDQgS6!=ssc_core__aIDnqGzhqWcVu6dhPsWV2){return
ssc_core_k4M7bSEmThKJbirXUDQgS6;}(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m)++;return ssc_core__aIDnqGzhqWcVu6dhPsWV2;}
static ssc_core_VPCajzt28fK6eatUgrzZrl ssc_core_FufBpOwN0D4CX1YpppLxRH(
ssc_core__TnsaUXKFcKxbitO58_d7o const*mc__d1alWYexptL_X5HTFhbNK,size_t
ssc_core_V17P9xH_Q9hBeeuhligsAZ,real_T ssc_core_VER4IpDoghhAb5UJpdofQJ,real_T*
v,real_T*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){(void)0;return
ssc_core_VJjzeg2lHXKq_y_Wta2PM6(mc__d1alWYexptL_X5HTFhbNK->time,
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K[
ssc_core_V17P9xH_Q9hBeeuhligsAZ],mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m,ssc_core_VER4IpDoghhAb5UJpdofQJ,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}static boolean_T
ssc_core_FWah5VbJL4tQWa6gnNeubQ(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*
ssc_core_V_m2gViqqexRZXIgiYbrwb){return ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static boolean_T
ssc_core__FgOEMjRWf4ciaK2461HcD(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*
ssc_core_V_m2gViqqexRZXIgiYbrwb){return ssc_core_kTG_5_cRDW8Tc5IgaIX_GH(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static int32_T
ssc_core_V3fTQ14IVxhccqMgvZZYXL(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,real_T const*ssc_core__4PrJ1yDxRxoiyf8WHxOxf){
(void)0;{ssc_core__TnsaUXKFcKxbitO58_d7o*mc__d1alWYexptL_X5HTFhbNK=
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData;real_T ssc_core_krJ5fXyQ8V_1_iH_zEXS9k=
0.0;size_t ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t i;for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i].ssc_core_Vc8UlnXwWF0_aL2KTzQdoU=
ssc_core__4PrJ1yDxRxoiyf8WHxOxf[i];ssc_core_krJ5fXyQ8V_1_iH_zEXS9k=(
ssc_core_krJ5fXyQ8V_1_iH_zEXS9k>ssc_core__4PrJ1yDxRxoiyf8WHxOxf[i]?
ssc_core_krJ5fXyQ8V_1_iH_zEXS9k:ssc_core__4PrJ1yDxRxoiyf8WHxOxf[i]);}
mc__d1alWYexptL_X5HTFhbNK->time.ssc_core_Vc8UlnXwWF0_aL2KTzQdoU=
ssc_core_krJ5fXyQ8V_1_iH_zEXS9k;}return ssc_core_kRBrlSqklIlNh1qpUnj_l4(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static void
ssc_core_VcSv7dn_lp4jjXFvJO3xqP(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,NeSimulationParameters
ssc_core_k_mRxeK4vft_iezHjHn6V7){(void)ssc_core_k_mRxeK4vft_iezHjHn6V7;(void)0
;ssc_core__Z4HfJeRyKhDVuUR83JXa2(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}
static int32_T ssc_core__d_0_fGk2cKPZ1CHClSpQm(ssc_core_kIG7sD0lJlWTfaZr6Pehvz
*ssc_core_V_m2gViqqexRZXIgiYbrwb,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T
const*pm_kpzAtHMD4_WnheH0UiioSE){(void)0;return ssc_core_F4ay3mU2KmpqZ1iah9APGb
(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData,ssc_core__1eAP9V6_J_NYm_1gTIm7A,
pm_kpzAtHMD4_WnheH0UiioSE);}static void ssc_core_FTXP2PPa0idWeaJ7BESTZK(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*ssc_core_V_m2gViqqexRZXIgiYbrwb,size_t
ssc_core_kh3C5f6ZAPlGWXfJykpWPn,real_T ssc_core_VER4IpDoghhAb5UJpdofQJ,real_T*
pm_kpzAtHMD4_WnheH0UiioSE,real_T*ssc_core__UXEfLq_c3__YDAWn2ItxA){(void)0;
ssc_core_FufBpOwN0D4CX1YpppLxRH(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData,
ssc_core_kh3C5f6ZAPlGWXfJykpWPn,ssc_core_VER4IpDoghhAb5UJpdofQJ,
pm_kpzAtHMD4_WnheH0UiioSE,ssc_core__UXEfLq_c3__YDAWn2ItxA);}static void
ssc_core__HAxhQtFA0Omja30JlUhlG(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){if(
ssc_core_V_m2gViqqexRZXIgiYbrwb!=NULL){ssc_core__0BJ4HcCvPSqgy0OBF9T7J(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);{void*const
ssc_core_VM1gwU5yiESzcDMEI7JzzY=(ssc_core_V_m2gViqqexRZXIgiYbrwb);PmAllocator*
const ssc_core_k52nOWQB85GsXeqOyqT9Lf=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_VM1gwU5yiESzcDMEI7JzzY){(ssc_core_k52nOWQB85GsXeqOyqT9Lf)->mFreeFcn(
ssc_core_k52nOWQB85GsXeqOyqT9Lf,ssc_core_VM1gwU5yiESzcDMEI7JzzY);}};}}enum
ssc_core_kV19LutbO7dNcHVxGL4NX4{ssc_core_Vr59wrVYWmSwYDdUfsuZK9= -1,
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4,ssc_core_kjVMEKO_Gg8beattYY_YXT,
ssc_core___Yx8SrZeg4iVqulP_D4Fs,ssc_core__fwQoFPwhn4V_5mnuVti9m,
ssc_core_khIwJz5TXXx6hXgLq38HlW};static void ssc_core_kgCV4xwmtdGJj18_86V2_5(
ssc_core__3jAYGRNM_0vZ1_f3K3L68 buffer,int32_T**
ssc_core_kZ7d78M3pHpeXefOwkRS3v,double**ssc_core_VDHis3O_uC4WXH2UwsQcYx){
ssc_core_VwbF2prDlG_nWi2eq_IWPE const*ssc_core_kozcyYkxMvOHfeg9l7McOP=NULL;
size_t ssc_core_kAatoTKT__tTdTEfHrJ7VK;size_t k;
ssc_core_kAatoTKT__tTdTEfHrJ7VK=0;ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer.
ssc_core_Vz1qOwNhpDtia9165RAqXH;while(ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){
ssc_core_kAatoTKT__tTdTEfHrJ7VK++;ssc_core_kozcyYkxMvOHfeg9l7McOP=
ssc_core_kozcyYkxMvOHfeg9l7McOP->ssc_core_FTf2iFFdsgK3hewKsMgEx4;}*((*
ssc_core_kZ7d78M3pHpeXefOwkRS3v)++)=(int32_T)(buffer.
ssc_core__ParkdIrhYxeXmPALk_GF9);*((*ssc_core_kZ7d78M3pHpeXefOwkRS3v)++)=(
int32_T)(ssc_core_kAatoTKT__tTdTEfHrJ7VK);*((*ssc_core_VDHis3O_uC4WXH2UwsQcYx)
++)=(double)(buffer.ssc_core_Vc8UlnXwWF0_aL2KTzQdoU);
ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer.ssc_core_Vz1qOwNhpDtia9165RAqXH;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){for(k=0;k<buffer.
ssc_core__ParkdIrhYxeXmPALk_GF9;k++){*((*ssc_core_VDHis3O_uC4WXH2UwsQcYx)++)=(
double)(ssc_core_kozcyYkxMvOHfeg9l7McOP->mc__d1alWYexptL_X5HTFhbNK[k]);}
ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;}}static int32_T
ssc_core___44TrDwSOlujqUAZynl3T(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer,int32_T**
ssc_core_kZ7d78M3pHpeXefOwkRS3v,double**ssc_core_VDHis3O_uC4WXH2UwsQcYx){
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_kozcyYkxMvOHfeg9l7McOP=NULL;size_t
ssc_core_kAatoTKT__tTdTEfHrJ7VK;size_t ssc_core_VkCuyAX_xvWRb1K8kFEdD3;size_t i
;(ssc_core_VkCuyAX_xvWRb1K8kFEdD3)=(size_t)(*((*
ssc_core_kZ7d78M3pHpeXefOwkRS3v)++));(ssc_core_kAatoTKT__tTdTEfHrJ7VK)=(size_t
)(*((*ssc_core_kZ7d78M3pHpeXefOwkRS3v)++));(void)0;while(buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH->ssc_core_FTf2iFFdsgK3hewKsMgEx4!=NULL){
ssc_core_VwbF2prDlG_nWi2eq_IWPE*ssc_core_Fk2O4u6vQUpibmbv8Kjgnn=buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH->ssc_core_FTf2iFFdsgK3hewKsMgEx4;buffer->
ssc_core_Vz1qOwNhpDtia9165RAqXH->ssc_core_FTf2iFFdsgK3hewKsMgEx4=
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn->ssc_core_FTf2iFFdsgK3hewKsMgEx4;
ssc_core_VktmBtsnDZh3WL_5MgKBfv(pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core_Fk2O4u6vQUpibmbv8Kjgnn);}if(buffer->ssc_core__ParkdIrhYxeXmPALk_GF9!=
ssc_core_VkCuyAX_xvWRb1K8kFEdD3){return ssc_core__XHpTEMxftlSiT4M8UKKvF;}for(i
=1;i<ssc_core_kAatoTKT__tTdTEfHrJ7VK;i++){ssc_core_V2O3Sr7MNSKa_1OHJ2LuNb(
pm_FbYb_iLqY2hwZTVlVaiqJY,buffer);}(buffer->ssc_core_Vc8UlnXwWF0_aL2KTzQdoU)=(
double)(*((*ssc_core_VDHis3O_uC4WXH2UwsQcYx)++));
ssc_core_kozcyYkxMvOHfeg9l7McOP=buffer->ssc_core_Vz1qOwNhpDtia9165RAqXH;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){for(i=0;i<
ssc_core_VkCuyAX_xvWRb1K8kFEdD3;i++){(ssc_core_kozcyYkxMvOHfeg9l7McOP->
mc__d1alWYexptL_X5HTFhbNK[i])=(double)(*((*ssc_core_VDHis3O_uC4WXH2UwsQcYx)++)
);}ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;}return ssc_core__aIDnqGzhqWcVu6dhPsWV2;}
static NeCustomData*ssc_core_k7AmPER00TKheTljklWhJP(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*ssc_core_V_m2gViqqexRZXIgiYbrwb){
NeCustomDataSize mc__0REJ38_cKO_bunM1JCRT_;NeCustomData*
ssc_core_FuIvge0ANAGVYLeQL84M_L;ssc_core__TnsaUXKFcKxbitO58_d7o const*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_V_m2gViqqexRZXIgiYbrwb->mData;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;ssc_core_VwbF2prDlG_nWi2eq_IWPE*
ssc_core_kozcyYkxMvOHfeg9l7McOP=NULL;size_t ssc_core_VkCuyAX_xvWRb1K8kFEdD3=0;
size_t i;mc__0REJ38_cKO_bunM1JCRT_.ssc_core_kAKxIvM1NQGM_TY96YysC5=
ssc_core_khIwJz5TXXx6hXgLq38HlW+2*(ssc_core_F5sR7BGiOQO9jq888pvXvp+1);
mc__0REJ38_cKO_bunM1JCRT_.ssc_core_VOAPNvYIRPGzhDXn1iCcKS=0;
mc__0REJ38_cKO_bunM1JCRT_.ssc_core_VOAPNvYIRPGzhDXn1iCcKS++;
ssc_core_kozcyYkxMvOHfeg9l7McOP=mc__d1alWYexptL_X5HTFhbNK->time.
ssc_core_Vz1qOwNhpDtia9165RAqXH;ssc_core_VkCuyAX_xvWRb1K8kFEdD3=
mc__d1alWYexptL_X5HTFhbNK->time.ssc_core__ParkdIrhYxeXmPALk_GF9;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){mc__0REJ38_cKO_bunM1JCRT_.
ssc_core_VOAPNvYIRPGzhDXn1iCcKS+=ssc_core_VkCuyAX_xvWRb1K8kFEdD3;
ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;}for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i++
){mc__0REJ38_cKO_bunM1JCRT_.ssc_core_VOAPNvYIRPGzhDXn1iCcKS++;
ssc_core_kozcyYkxMvOHfeg9l7McOP=mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i].ssc_core_Vz1qOwNhpDtia9165RAqXH;
ssc_core_VkCuyAX_xvWRb1K8kFEdD3=mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i].ssc_core__ParkdIrhYxeXmPALk_GF9;while(
ssc_core_kozcyYkxMvOHfeg9l7McOP!=NULL){mc__0REJ38_cKO_bunM1JCRT_.
ssc_core_VOAPNvYIRPGzhDXn1iCcKS+=ssc_core_VkCuyAX_xvWRb1K8kFEdD3;
ssc_core_kozcyYkxMvOHfeg9l7McOP=ssc_core_kozcyYkxMvOHfeg9l7McOP->
ssc_core_FTf2iFFdsgK3hewKsMgEx4;}}ssc_core_FuIvge0ANAGVYLeQL84M_L=
ssc_core_VFzWBz_s8FW9_qamuHujnl(mc__0REJ38_cKO_bunM1JCRT_);
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4]=(int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_kjVMEKO_Gg8beattYY_YXT]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT);
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core___Yx8SrZeg4iVqulP_D4Fs]=(int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core___Yx8SrZeg4iVqulP_D4Fs);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core__fwQoFPwhn4V_5mnuVti9m]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m);;{int32_T*
ssc_core_VRrHuXf_WqlrfeFcNlBk_f= &(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_khIwJz5TXXx6hXgLq38HlW]);double*
ssc_core_FugWaISXKrOfeaVgIj_xYQ= &(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_VOMV27LEztpmd59gF8yJO0[0]);ssc_core_kgCV4xwmtdGJj18_86V2_5(
mc__d1alWYexptL_X5HTFhbNK->time,&ssc_core_VRrHuXf_WqlrfeFcNlBk_f,&
ssc_core_FugWaISXKrOfeaVgIj_xYQ);for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i++
){ssc_core_kgCV4xwmtdGJj18_86V2_5(mc__d1alWYexptL_X5HTFhbNK->
mc_kVkvrfpzuVduaPTr5FLF8K[i],&ssc_core_VRrHuXf_WqlrfeFcNlBk_f,&
ssc_core_FugWaISXKrOfeaVgIj_xYQ);}(void)0;(void)0;}return
ssc_core_FuIvge0ANAGVYLeQL84M_L;}static int32_T ssc_core_kNyjs6UzG0SmfXL0SL5SHm
(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*ssc_core_V_m2gViqqexRZXIgiYbrwb,NeCustomData
const*ssc_core_FuIvge0ANAGVYLeQL84M_L){ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_V_m2gViqqexRZXIgiYbrwb->mData;PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY
;size_t ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t i;boolean_T
ssc_core__DaIj7x5_zWKcT6nncDdGo=(boolean_T)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core___Yx8SrZeg4iVqulP_D4Fs]);boolean_T
ssc_core_Fl0x66IGGaxFVqzqQN1IA8=ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
mc__d1alWYexptL_X5HTFhbNK);if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4)!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_k7BUQ6_0kj8_cm39ZbqKv4]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(ssc_core__DaIj7x5_zWKcT6nncDdGo){if(
ssc_core_Fl0x66IGGaxFVqzqQN1IA8==false){int32_T ssc_core_Fbnx9FOLhnW0X1Wd233Ai7
=ssc_core_kRBrlSqklIlNh1qpUnj_l4(mc__d1alWYexptL_X5HTFhbNK);if(
ssc_core_Fbnx9FOLhnW0X1Wd233Ai7!=ssc_core__aIDnqGzhqWcVu6dhPsWV2){return
ssc_core_Fbnx9FOLhnW0X1Wd233Ai7;}}if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core___Yx8SrZeg4iVqulP_D4Fs)!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core___Yx8SrZeg4iVqulP_D4Fs]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_kjVMEKO_Gg8beattYY_YXT]);;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m=(size_t)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]);;{int32_T*ssc_core_VRrHuXf_WqlrfeFcNlBk_f= &
(ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_khIwJz5TXXx6hXgLq38HlW]);double*ssc_core_FugWaISXKrOfeaVgIj_xYQ= &(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[0]);
ssc_core___44TrDwSOlujqUAZynl3T(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->time),&ssc_core_VRrHuXf_WqlrfeFcNlBk_f,&
ssc_core_FugWaISXKrOfeaVgIj_xYQ);for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i++
){ssc_core___44TrDwSOlujqUAZynl3T(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K[i]),&
ssc_core_VRrHuXf_WqlrfeFcNlBk_f,&ssc_core_FugWaISXKrOfeaVgIj_xYQ);}(void)0;(
void)0;}}else{if(ssc_core_Fl0x66IGGaxFVqzqQN1IA8){
ssc_core_VAscH6T1zTlHhuux1atWp5(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->time));for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i
++){ssc_core_VAscH6T1zTlHhuux1atWp5(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->mc_kVkvrfpzuVduaPTr5FLF8K[i]));}
mc__d1alWYexptL_X5HTFhbNK->ssc_core___Yx8SrZeg4iVqulP_D4Fs=(boolean_T)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core___Yx8SrZeg4iVqulP_D4Fs]);;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_kjVMEKO_Gg8beattYY_YXT]);;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m=(size_t)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]);;(void)0;}}if((int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core___Yx8SrZeg4iVqulP_D4Fs)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core___Yx8SrZeg4iVqulP_D4Fs]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(
(int32_T)(mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_kjVMEKO_Gg8beattYY_YXT]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(
(int32_T)(mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};
return ssc_core__aIDnqGzhqWcVu6dhPsWV2;}ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_F4kcadj_4cKHg1ezX_zsql(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,size_t ssc_core__ParkdIrhYxeXmPALk_GF9,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){ssc_core_kIG7sD0lJlWTfaZr6Pehvz*result=
(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(ssc_core_kIG7sD0lJlWTfaZr6Pehvz)),(1))));
result->ssc_core_kpVC1AX7p50Ja18UISsLi_=ssc_core_FWah5VbJL4tQWa6gnNeubQ;result
->ssc_core_F9Kq4Qr_9Z0Yjm1oicqvtn=ssc_core__FgOEMjRWf4ciaK2461HcD;result->
mInitializeFcn=ssc_core_VcSv7dn_lp4jjXFvJO3xqP;result->
ssc_core__pl1MSSO99W8WP3QqnoCib=ssc_core_V3fTQ14IVxhccqMgvZZYXL;result->
ssc_core_VG3e0ucOiSGjh1qwaVjeHl=ssc_core__d_0_fGk2cKPZ1CHClSpQm;result->
ssc_core_VpAc4HLF9R4vc5lHk8ztuA=ssc_core_FTXP2PPa0idWeaJ7BESTZK;result->
ssc_core_kosGVqM5sQxa_ilVRRQVR_=ssc_core__HAxhQtFA0Omja30JlUhlG;result->
mGetCustomDataFcn=ssc_core_k7AmPER00TKheTljklWhJP;result->mSetCustomDataFcn=
ssc_core_kNyjs6UzG0SmfXL0SL5SHm;result->mData=ssc_core_FPENxS4RNQ8T_Dpq_5vgtb(
ssc_core_V8uoyu0_YA0beyMVkKylrC,ssc_core_FNt92uaclVCyYXOJ4ykVyd,
ssc_core__ParkdIrhYxeXmPALk_GF9,pm_FbYb_iLqY2hwZTVlVaiqJY);(void)0;return
result;}
