#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_Fj_dFIC8mwWzaLFg5PWymM ssc_core_FWI1vmgxdR8me9ofVTzx6T
;typedef struct ssc_core_kzD2duJROPp_feaAjCFfnI ssc_core_VdNJjnSb6_lVXTG3JCLKal
;struct ssc_core_kzD2duJROPp_feaAjCFfnI{PmfMessageId(*
mc_kj_oOGqml_xqaXiiWNvUfG)(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;PmfMessageId(*mCheck)(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;void(*mDestroy)(ssc_core_VdNJjnSb6_lVXTG3JCLKal*);
ssc_core_FWI1vmgxdR8me9ofVTzx6T*mData;};
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_kSq7vcYEzBSPh1_HmyvGuS,ssc_sli_FzfaJd8s_hCXWy3yxi1stW,
ssc_sli___mb2h47wN4ihPznc5zDZu,ssc_sli_VQPqsGKP5uGObDJbh_eFMB,
ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,ssc_sli__rEZqtXugN_fa5vYYYzGYc,
ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,
ssc_sli__puwPfKA1_C_XXKoAacuHL,ssc_sli__0DRn7XIvolbdPgJc8imWd,
ssc_sli__GinY4faV6x5fXRGGHiXOx,ssc_sli_k70mjUuFMQSz_irEsv6NXV,
ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,ssc_sli__OWNEM8w1KGFbaOP6K0YSM,
ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,ssc_sli__5Jlt976LTdQhme97vzhLz,
ssc_sli_FE7q2LVg_Cx6geTARRhW19,ssc_sli__cezSCdpHN4lgqD73r5pEK,
ssc_sli_kWziByYnTjSrjiEO0gFijq,ssc_sli_VCODxytNt54LYecqLGV9fH,
ssc_sli_FsuU2v1dzu0zguh8hxcIjr,ssc_sli_kcFJMg4RQe4laPBX1LMdGM,
ssc_sli_FV_e38q0Djt6eynPV7_Ny6,ssc_sli_FQTNkFa6paKoWyb_h7lF4p,
ssc_sli_kHan416AsF0SVX35Jc3ZUl,ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,
ssc_sli__AaIKqtCr_pwYX1HS4ht1q,ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,
ssc_sli_VbUGQovAbg0NXH9ywH5nXC,ssc_sli__szAKcwWzAGWXe6ZxiNqLy,
ssc_sli_FDke0C5lVb4aiu949gwwFS,ssc_sli_knnAZr_MyDhGaqCPi5fnDE,
ssc_sli_k48eOppTiHpzaP3Bk4LY0j,ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,
ssc_sli_VHuz88szqGKgjTt1PdGvzW,ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,
ssc_sli_kTmLAygbBbCecHMi0uMPAy,ssc_sli_FHVxyfshp6KgVaq6SphqIh,
ssc_sli__mVVJdecb3d__PkepHFMpg,ssc_sli_FkVgnEqViixCfumgJMCM_e,
ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,ssc_sli_k_a_p_5ozClahq0TR72sc5,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_Fr8tyhA6bhOu_T5U6JG49B,
ssc_sli_kO7B69a_Lrhhha86IyU_GA,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli_kpGiBTt5RbdhZuvwoqsVtr,ssc_sli_Fh9oEC3tNb41gqXZYE_FUG,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector mOBS_ACT;PmRealVector
mOBS_EXP;PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;
PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector
mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;
PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;
PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector mICR_IM;PmBoolVector mICR_IL
;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;PmRealVector mICR;
PmSparsityPattern mDXICR_P;PmRealVector mDXICR;PmSparsityPattern mDDICR_P;
PmRealVector mDDICR;PmSparsityPattern mICRM_P;PmRealVector mICRM;
PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;PmSparsityPattern mDDICRM_P;
PmRealVector mDDICRM;PmRealVector mEQ_TOL;PmIntVector mDP_L;PmIntVector mDP_I;
PmIntVector mDP_J;PmRealVector mDP_R;PmRealVector mIMIN;PmRealVector mIMAX;
PmRealVector mDIMIN;PmRealVector mDIMAX;PmBoolVector mVDF;PmBoolVector mVMF;
PmBoolVector mVMM;PmBoolVector mSLF;PmBoolVector mLV;PmBoolVector mNLDV;
PmRealVector mLOG;PmRealVector mJACOB;PmRealVector mSTATE;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmRealVector*
ssc_sli_VU_2QwnChmGVgqMm5Sr7Z7;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmRealVector*ssc_sli_Ft6MItjvPuONWT3V3OKBBu;PmSparsityPattern*
ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;PmRealVector*ssc_sli_F_osIpSL94xCdqURiUvIz_;
PmSparsityPattern*ssc_sli_Vd1e_JCWeyptimGJ3TpS_h;};struct
ssc_sli_FwOCwa_vjXx9haWvTfh5mO{ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[
ssc_sli__Udg2iOsHnplYyGCps5u_2];ssc_sli_kQALV9CmL9diceRAXQ_cn_
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t
ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t
ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t
ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t
ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t
ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t
ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t
ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t
ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t
ssc_sli_kRBQlHbYYD4Egm1QxQJNGZ;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;NeAssertData const*mAssertData;size_t mNumAssertRanges;NeRange
const*mAssertRanges;size_t mNumInitialAsserts;NeAssertData const*
mInitialAssertData;size_t mNumInitialAssertRanges;NeRange const*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_V2edm5XULi4bhDK_5PJPZ7*ssc_sli_VjXisdXgW_hWheKa6_ZxQl;
NeDynamicSystemInput*ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeModelParameters const*const mp,
NeSolverParameters const*const ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*
ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli__6gTFXBv2i84fanvoJsVjr)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli__Qs092x10UtZ_eE_eC7Xz0)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_sli_kl9YKZTIwnlGdySFA8pHdf(const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli_FCwZLBnFKkp2b5_z2A2lil,const size_t
ssc_sli__LUTDtJud8K4_PqqE22fA8,const NeCERData*ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,
boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t
ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_sli_Vq1UMqIpC0ttVytX_hyOlE(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
boolean_T ssc_sli_kvYdEBImn2CCdeuS6ty1i1,real_T mc_FfDTppU8N_tOWuLK37x_08,
size_t ssc_core_F4tlqGoz8dpsjmIIo_HrZB,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
boolean_T ssc_sli__vLGn5snyBGCc9MqkwvzyK(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,NeDynamicSystemInput const*
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,size_t ssc_core_FKySES0vPzxeVPkVt80QKX,
PmSparsityPattern const*ssc_sli_F4abcJKsDhWhdLzsF0QXFJ,boolean_T
ssc_sli_kzBcD1zVPWKLj5FRuDlc3c);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_kjCgkKdgjf_B_e_hraPYjI(McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,
PmBoolVector*mc__zB_qJZo0IluZ9L_7brV_8,PmBoolVector*mc__kGOISkZ94x2fHWVVKuIS5,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc__Lbf28Vmk3xMWaMWf4YhQ0(McMatrixFunction*mc_kXwHswK956KEimdoHimdrb,
PmBoolVector*mc_VlZMmzn2z2dpZyy2834RK6,PmBoolVector*mc__d0bLF53CvGmj1ZBgVfH1i,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc_FzXHxaC_zhO_j9ob7zq7Cu(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);
McMatrixFunction*mc_FvfmwR5Z4udFdmA89MySHd(McMatrixFunction*
mc_kEQ7ZkhePUp8eHqnX6lLap,McMatrixFunction*mc_VRqcAPiI_zWzcaWghAD8Ra,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc__4fFDnwFhbSuaLZ4NJB06a(PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,void const*
mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc_Vl4aaEoJK_KwYaROiytCdQ(PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,void const*
mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc_keWxvg6kivCmgu_AS8haey(PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*mc_kVkvrfpzuVduaPTr5FLF8K,
McMatrixFunction*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_kjBl5aSCPqK8_T48OOvhEj(
McMatrixFunction*mc_ky0WCncALplbXL_SNbJkvW,size_t mc_Fxvltms7Im4baT5ZPxj7f2,
size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
#include "mc_std_fwd.h"
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core__iWz_v8nE_W4Zudun77ppE(McRealFunction
*ssc_core_FFZbGh27ya8eem_J_hUtAZ,McMatrixFunction*mc_VoTkdAz8Qxd2iDKiMSyIbK,
boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t
ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
#include "mc_std_fwd.h"
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core_V2b5WBjkcPlsb9dufPuJOH(McRealFunction
*ssc_core_FFZbGh27ya8eem_J_hUtAZ,McMatrixFunction*mc_VoTkdAz8Qxd2iDKiMSyIbK,
boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t
ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
#include "mc_std_fwd.h"
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core_VFv9ctmy6xC9Y5nC__XZlU(McRealFunction
*ssc_core_FFZbGh27ya8eem_J_hUtAZ,McMatrixFunction*
ssc_core_VriVbeGXVySZhmo4IqByQ6,McMatrixFunction*y,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,boolean_T ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,
real_T mc_FfDTppU8N_tOWuLK37x_08,size_t ssc_core_FhbD3RsEbmlPa1L52gsu55,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_core_Fml092VdhNSIcaKdB4FldR(PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
#include "mc_std_fwd.h"
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core_VCAwjquo7vCVdyRTBC0d7e(McRealFunction
*ssc_core_koVEIOVQ7YKpgLI1DDze9g,McMatrixFunction*
ssc_core__s2Li0w3ytS9bTdqzsL3yT,McMatrixFunction*
ssc_core__ZFWXFEjLlS7Z9rB2YJqNY,boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
boolean_T ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,real_T mc_FfDTppU8N_tOWuLK37x_08,
size_t ssc_core_FhbD3RsEbmlPa1L52gsu55,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_kv3fXx6PfXt7cekeoT00mk mc_kgKqfPHHGatO_9OUxR4PRK;struct
mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;void(*mc_FapEct1OXaSugDZ6N_u_kA)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH);void(*mc_FVdv01I3SEC4hD41rxmnRM)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,real_T mc__d1alWYexptL_X5HTFhbNK);void(*
mc_kPHJTxMUjl8Oi1EQSHes2Q)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector
const*mc__d1alWYexptL_X5HTFhbNK);void(*mc__WEKdqi2uo0m_Dm8w8T_ZO)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);};typedef struct
mc__nZqLQp3m1lFaHyLAzyG2a mc__39VLhR7TBCGYH016BQq8W;typedef struct
mc__UzXDLpnAvdw_eUt0mYuul mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct
mc__sr5lnPbYjO_Wyo_mmPUmd mc_Fw_IO5LchthA_LoeiSceRf;struct
mc__sr5lnPbYjO_Wyo_mmPUmd{mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;
void(*mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};McRealFunction*ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McRealFunction*ssc_sli_FGH9xESnQESJZ5rrZGPWdT(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McIntFunction*ssc_sli_kZrc6L3r4_xaX1bSkV57Yd(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli_FNYHSvltK9CtZu3Uutc_pv(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
NeDynamicSystemInput ssc_sli__W_AnWQ747WB_a7wEezy5_(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,NeSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_VYZbxd6QDPKAY5EdNNnxvo ssc_core_FTQiFug__ySeca8XLOZvsP
;typedef struct ssc_core__96yahfzEI_rZTPZ9_F__R ssc_core_FdxXK8OYjaSyde1dks8fo6
;struct ssc_core__96yahfzEI_rZTPZ9_F__R{void(*mc_F8jYh1XJ10K_emvBxS7m6z)(
ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k);void(*mc_VrNsQKHIiLOFaL3PHRFxZL
)(ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z);
NeSystemInputSizes(*ssc_core_k12HeDepc7deXD9LUZ_NTV)(
ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*
mDestroy)(ssc_core_FdxXK8OYjaSyde1dks8fo6*);boolean_T mHasConstraints;
boolean_T ssc_core_FiExqWFTEah9jHJ0SH1HNW;PmSparsityPattern const*
ssc_core_FF_1tT6hvsWRWDPOW_Lf9p;PmRealVector const*
ssc_core_VNr5R_tseV8GZ9MEkaP0iI;PmSparsityPattern const*
ssc_core_F8ct2g4u30Cd_eVBM1fmme;PmRealVector const*
ssc_core_VYZTZNi4zntdY96IiRebWs;PmBoolVector const*
ssc_core_kmBetGuEoz8wi9ZOF3VWFZ;PmBoolVector const*
ssc_core_Vr0_Hh6W3aK_geLt8t_w5s;PmSparsityPattern const*
ssc_core_VroU7Vctp3hnfXBuzbTcMf;PmRealVector const*
ssc_core_VKjPDXGkelWFairK7M4e7w;PmSparsityPattern const*
ssc_core_F_IPhSinY6K8eTISPitBTp;PmRealVector const*
ssc_core_kFjGshRebZdxbPE1qJHCAI;ssc_core_FTQiFug__ySeca8XLOZvsP*mData;};
McMatrixFunction*ssc_sli_VvFvQWKlzndA_uICETZCBj(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*,PmAllocator*);McRealFunction*ssc_sli__UrK3rytxHCfVXpTq182GL(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli__QonMhVfyKxdg5cfn4U8Jp(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_VpA8MeBTbz4vfeehXz_6ss(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McRealFunction*
ssc_sli_FguaPp8zXiO1VLb8KoL2eG(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli_FO5r0OGVFOdAcPhW2GWnW1(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_km3ERy3JxHO6_u4Kr1_1mz(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli_V4rVN29HRbWXfyoy1Rm7o9(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);ssc_sli_V2edm5XULi4bhDK_5PJPZ7*ssc_sli_FywFPN2hnBhka5OlyA_ZYy(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,NeSolverParameters const*,size_t,
boolean_T,ssc_core_FdxXK8OYjaSyde1dks8fo6 const*,PmAllocator*);void
ssc_sli__K_PX_hcHbSBdqT1N1HqJX(ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_Fwiw7skPygOpXi8qQorrTL);static void ssc_sli_kTknElplLHtccL3X647xvY(
PmBoolVector**ssc_sli_FyKzMIZlv5_ZhLyOYO6l71,PmBoolVector**
ssc_sli_kxEyXlk_fCxNjugVeKhXua,ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){size_t n
=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[NE_DYNAMIC_SYSTEM_INPUT_ID_X];
NeDynamicSystemInput*ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd=
neu_create_dynamic_system_input(ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes,
pm_FbYb_iLqY2hwZTVlVaiqJY);PmBoolVector*ssc_sli_kSOKc5GXtKh2ZD31JqLnAa=
pm__jbisDMumXdocXANx5LhhY(n,pm_FbYb_iLqY2hwZTVlVaiqJY);PmBoolVector*
ssc_sli_kl5LS8HZoPCFd9PEamS0tt=pm__jbisDMumXdocXANx5LhhY(n,
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*ssc_sli__3m9za6AQ781ci367S8iNU=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,
pm_FbYb_iLqY2hwZTVlVaiqJY);PmBoolVector*ssc_sli__sA_bYyZ6WKyiLww7QsIct=
pm__jbisDMumXdocXANx5LhhY(n,pm_FbYb_iLqY2hwZTVlVaiqJY);PmBoolVector*
ssc_sli_kSftJjstgk4Oj1dQT6JSzo=pm__jbisDMumXdocXANx5LhhY(n,
pm_FbYb_iLqY2hwZTVlVaiqJY);PmBoolVector*ssc_sli_kUYA31gmLcx3dHl9ZsbR_f=
pm__jbisDMumXdocXANx5LhhY(n,pm_FbYb_iLqY2hwZTVlVaiqJY);size_t i=0,
ssc_sli__BwCbGCDlrx2gDK5rof3H8=0;ssc_sli_kF79J1yovOdS_uDIzPgJXv
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;mc__pFtu1g17h8ZaaZK4PpTkb(
ssc_sli__sA_bYyZ6WKyiLww7QsIct,ssc_sli__3m9za6AQ781ci367S8iNU->
mc_kjWUPQN_Ui4d_enzFJIsF_);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mVMF= *
ssc_sli_kSftJjstgk4Oj1dQT6JSzo;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mSLF= *ssc_sli_kUYA31gmLcx3dHl9ZsbR_f;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli__J5DR8iwtetKhiPtMB9tI5](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);mc_VWloU5QD6gpaXeK8lmytFA(
ssc_sli_kSOKc5GXtKh2ZD31JqLnAa);mc_VWloU5QD6gpaXeK8lmytFA(
ssc_sli_kl5LS8HZoPCFd9PEamS0tt);for(i=0;i<n;i++){if(
ssc_sli_kUYA31gmLcx3dHl9ZsbR_f->mX[i]||(!ssc_sli__sA_bYyZ6WKyiLww7QsIct->mX[i]
&&!ssc_sli_kSftJjstgk4Oj1dQT6JSzo->mX[i])){ssc_sli_kSOKc5GXtKh2ZD31JqLnAa->mX[
i]=true;}ssc_sli_kl5LS8HZoPCFd9PEamS0tt->mX[i]=ssc_sli_kSOKc5GXtKh2ZD31JqLnAa
->mX[i]&&ssc_sli_kUYA31gmLcx3dHl9ZsbR_f->mX[i];}(
ssc_sli__3m9za6AQ781ci367S8iNU)->mDestroy(ssc_sli__3m9za6AQ781ci367S8iNU);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli__sA_bYyZ6WKyiLww7QsIct,
pm_FbYb_iLqY2hwZTVlVaiqJY);pm_VuaGyqV_9K0Ia9Qgn65rsj(
ssc_sli_kSftJjstgk4Oj1dQT6JSzo,pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_kUYA31gmLcx3dHl9ZsbR_f,
pm_FbYb_iLqY2hwZTVlVaiqJY);neu_destroy_dynamic_system_input(
ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,pm_FbYb_iLqY2hwZTVlVaiqJY);*
ssc_sli_FyKzMIZlv5_ZhLyOYO6l71=ssc_sli_kSOKc5GXtKh2ZD31JqLnAa;*
ssc_sli_kxEyXlk_fCxNjugVeKhXua=ssc_sli_kl5LS8HZoPCFd9PEamS0tt;}static
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_sli_V3IvKUBgJj8EjHudwb3Lz1(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli_FCwZLBnFKkp2b5_z2A2lil,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,boolean_T ssc_sli_Vd8egxYRexpOemSPFvvJei,
boolean_T ssc_sli_kvYdEBImn2CCdeuS6ty1i1,real_T mc_FfDTppU8N_tOWuLK37x_08,
size_t ssc_core_F4tlqGoz8dpsjmIIo_HrZB,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){
McRealFunction*ssc_core_FFZbGh27ya8eem_J_hUtAZ=ssc_sli__UrK3rytxHCfVXpTq182GL(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_core_VriVbeGXVySZhmo4IqByQ6=ssc_sli__QonMhVfyKxdg5cfn4U8Jp(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*tm=
NULL;if(ssc_sli_Vd8egxYRexpOemSPFvvJei){McMatrixFunction*
mc_VLHhnPUiNQpve5VIL9P3O9=ssc_sli_VvFvQWKlzndA_uICETZCBj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_core_VB53fXegNkCQcXjkCLRtVG=ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);PmBoolVector*
ssc_sli_VaDcshETvyxXeLIP5NMivY=NULL;PmBoolVector*
ssc_sli_kl5LS8HZoPCFd9PEamS0tt=NULL;McMatrixFunction*
ssc_core__1eAP9V6_J_NYm_1gTIm7A=NULL;ssc_sli_kTknElplLHtccL3X647xvY(&
ssc_sli_VaDcshETvyxXeLIP5NMivY,&ssc_sli_kl5LS8HZoPCFd9PEamS0tt,
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);
mc_kUD9LJQRjT0FayfqpQrhnP(ssc_sli_kl5LS8HZoPCFd9PEamS0tt);
ssc_core__1eAP9V6_J_NYm_1gTIm7A=mc__Lbf28Vmk3xMWaMWf4YhQ0(
ssc_core_VB53fXegNkCQcXjkCLRtVG,ssc_sli_VaDcshETvyxXeLIP5NMivY,
ssc_sli_kl5LS8HZoPCFd9PEamS0tt,mc_FZx3iFiX1YW7j5eEojoAPc);tm=
mc_FvfmwR5Z4udFdmA89MySHd(ssc_core__1eAP9V6_J_NYm_1gTIm7A,
mc_VLHhnPUiNQpve5VIL9P3O9,mc_FZx3iFiX1YW7j5eEojoAPc);}else{PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ=pm_create_sparsity_pattern(0,
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[NE_DYNAMIC_SYSTEM_INPUT_ID_X],
ssc_core_F4tlqGoz8dpsjmIIo_HrZB,mc_FZx3iFiX1YW7j5eEojoAPc);PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K=pm_create_real_vector(0,mc_FZx3iFiX1YW7j5eEojoAPc);
tm=mc_Vl4aaEoJK_KwYaROiytCdQ(mc__srK5LmyWw42ZyPnbOWDWJ,
mc_kVkvrfpzuVduaPTr5FLF8K,(NeSystemInput const*)((
ssc_core_FFZbGh27ya8eem_J_hUtAZ)->mc_FXz9GdGvpOKnh5e2dYstBe((
ssc_core_FFZbGh27ya8eem_J_hUtAZ))),mc_FZx3iFiX1YW7j5eEojoAPc);}return
ssc_core_VCAwjquo7vCVdyRTBC0d7e(ssc_core_FFZbGh27ya8eem_J_hUtAZ,
ssc_core_VriVbeGXVySZhmo4IqByQ6,tm,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_sli_kvYdEBImn2CCdeuS6ty1i1,mc_FfDTppU8N_tOWuLK37x_08,
ssc_core_F4tlqGoz8dpsjmIIo_HrZB,mc_FZx3iFiX1YW7j5eEojoAPc);}
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_sli_Vq1UMqIpC0ttVytX_hyOlE(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli_FCwZLBnFKkp2b5_z2A2lil,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,boolean_T ssc_sli_kvYdEBImn2CCdeuS6ty1i1,
real_T mc_FfDTppU8N_tOWuLK37x_08,size_t ssc_core_F4tlqGoz8dpsjmIIo_HrZB,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){size_t const
ssc_sli_VHK9AVam1qpFjLFQC_JToi=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[
NE_DYNAMIC_SYSTEM_INPUT_ID_X];size_t const mc_Fxl4i6XHkE8cY9kYmlJixt=
ssc_core_F4tlqGoz8dpsjmIIo_HrZB;size_t const ssc_sli_k7G_R2S7iIOLditRzSZy_A=
ssc_sli_VHK9AVam1qpFjLFQC_JToi-mc_Fxl4i6XHkE8cY9kYmlJixt;NeDynamicSystemInput*
ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd=neu_create_dynamic_system_input(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes,mc_FZx3iFiX1YW7j5eEojoAPc);
ssc_sli_kF79J1yovOdS_uDIzPgJXv ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;PmBoolVector*
ssc_sli_kzi9beWw69_JYDWqr_7hnk=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_VHK9AVam1qpFjLFQC_JToi,mc_FZx3iFiX1YW7j5eEojoAPc);PmBoolVector*
ssc_sli_kdd24RcsXK4hjXPJnCgxPO=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_VHK9AVam1qpFjLFQC_JToi,mc_FZx3iFiX1YW7j5eEojoAPc);PmBoolVector*
ssc_sli_kIEgOgA4iTGCePyxIAQAhr=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->ssc_sli_kRBQlHbYYD4Egm1QxQJNGZ,
mc_FZx3iFiX1YW7j5eEojoAPc);boolean_T ssc_sli_Vd8egxYRexpOemSPFvvJei=false;
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mLV= *ssc_sli_kzi9beWw69_JYDWqr_7hnk;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_Fr8tyhA6bhOu_T5U6JG49B](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mVMM= *
ssc_sli_kIEgOgA4iTGCePyxIAQAhr;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli__CpBn4DTIb4zbyG0hxjNf2](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_sli_Vd8egxYRexpOemSPFvvJei=(mc_FLTxr_Wc1PKSeTxwfrcl5B(
ssc_sli_kIEgOgA4iTGCePyxIAQAhr)==0);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mNLDV= *
ssc_sli_kdd24RcsXK4hjXPJnCgxPO;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_kO7B69a_Lrhhha86IyU_GA](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
neu_destroy_dynamic_system_input(ssc_sli_Fi3xeEdWn9dpaPj32ZDRPd,
mc_FZx3iFiX1YW7j5eEojoAPc);if(ssc_sli_Vd8egxYRexpOemSPFvvJei&&
mc_FLTxr_Wc1PKSeTxwfrcl5B(ssc_sli_kdd24RcsXK4hjXPJnCgxPO)==0){McRealFunction*
ssc_core_FFZbGh27ya8eem_J_hUtAZ=ssc_sli__UrK3rytxHCfVXpTq182GL(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_sli_kQlQoPz6R_tAXmvINarRY8=ssc_sli__QonMhVfyKxdg5cfn4U8Jp(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_core_VriVbeGXVySZhmo4IqByQ6=mc_kjBl5aSCPqK8_T48OOvhEj(
ssc_sli_kQlQoPz6R_tAXmvINarRY8,0,ssc_sli_VHK9AVam1qpFjLFQC_JToi,0,
mc_Fxl4i6XHkE8cY9kYmlJixt,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
mc_VLHhnPUiNQpve5VIL9P3O9=ssc_sli_VvFvQWKlzndA_uICETZCBj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_sli__NQzZKFWEchAj5kN5LQygE=mc_kjBl5aSCPqK8_T48OOvhEj(
mc_VLHhnPUiNQpve5VIL9P3O9,0,mc_Fxl4i6XHkE8cY9kYmlJixt,0,
mc_Fxl4i6XHkE8cY9kYmlJixt,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_sli_FVIQgrGUy1CbhifFSYQZLh=mc_FzXHxaC_zhO_j9ob7zq7Cu(
ssc_sli__NQzZKFWEchAj5kN5LQygE);McMatrixFunction*
ssc_sli_FiR44P6ABy0MZeFPxSvWak=ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_sli__ClXZCn6RECUd1BcYVTRbB=ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*
ssc_sli_F2mOihgIDAl_XDu2BTwIDf=mc_kjBl5aSCPqK8_T48OOvhEj(
ssc_sli_FiR44P6ABy0MZeFPxSvWak,0,mc_Fxl4i6XHkE8cY9kYmlJixt,
mc_Fxl4i6XHkE8cY9kYmlJixt,ssc_sli_VHK9AVam1qpFjLFQC_JToi,
mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*ssc_sli_kNMl7z10JKp9im0NwWsblj=
mc_kjBl5aSCPqK8_T48OOvhEj(ssc_sli__ClXZCn6RECUd1BcYVTRbB,
mc_Fxl4i6XHkE8cY9kYmlJixt,ssc_sli_VHK9AVam1qpFjLFQC_JToi,
mc_Fxl4i6XHkE8cY9kYmlJixt,ssc_sli_VHK9AVam1qpFjLFQC_JToi,
mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*ssc_sli_F3nVSXkoDK8VeeL5OmY0_B=
NULL;McMatrixFunction*ssc_sli_Fmeca4Tw7VxMimRGIZ0RCs=NULL;McMatrixFunction*y=
NULL;PmBoolVector*ssc_sli_Fmfiwgsssgd2byBBXsI7Dy=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_k7G_R2S7iIOLditRzSZy_A,mc_FZx3iFiX1YW7j5eEojoAPc);PmBoolVector*
ssc_sli_VInYINErPJSQfDLK7Iseeb=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_k7G_R2S7iIOLditRzSZy_A,mc_FZx3iFiX1YW7j5eEojoAPc);
mc_k1sxUtEClkOZVuHMQ91JqD(ssc_sli_VInYINErPJSQfDLK7Iseeb,true);{size_t
ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_;for(ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_=0;
ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_<ssc_sli_Fmfiwgsssgd2byBBXsI7Dy->mN;++
ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_){ssc_sli_Fmfiwgsssgd2byBBXsI7Dy->mX[
ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_]=ssc_sli_kzi9beWw69_JYDWqr_7hnk->mX[
ssc_sli_FEa9HpQub3K9X1Fkj0Fvl_+mc_Fxl4i6XHkE8cY9kYmlJixt];}}
ssc_sli_F3nVSXkoDK8VeeL5OmY0_B=mc_kjCgkKdgjf_B_e_hraPYjI(
ssc_sli_kNMl7z10JKp9im0NwWsblj,ssc_sli_VInYINErPJSQfDLK7Iseeb,
ssc_sli_Fmfiwgsssgd2byBBXsI7Dy,mc_FZx3iFiX1YW7j5eEojoAPc);
ssc_sli_Fmeca4Tw7VxMimRGIZ0RCs=mc_FvfmwR5Z4udFdmA89MySHd(
ssc_sli_F2mOihgIDAl_XDu2BTwIDf,ssc_sli_F3nVSXkoDK8VeeL5OmY0_B,
mc_FZx3iFiX1YW7j5eEojoAPc);y=mc_FvfmwR5Z4udFdmA89MySHd(
ssc_sli_FVIQgrGUy1CbhifFSYQZLh,ssc_sli_Fmeca4Tw7VxMimRGIZ0RCs,
mc_FZx3iFiX1YW7j5eEojoAPc);pm_VuaGyqV_9K0Ia9Qgn65rsj(
ssc_sli_kzi9beWw69_JYDWqr_7hnk,mc_FZx3iFiX1YW7j5eEojoAPc);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_kdd24RcsXK4hjXPJnCgxPO,
mc_FZx3iFiX1YW7j5eEojoAPc);pm_VuaGyqV_9K0Ia9Qgn65rsj(
ssc_sli_kIEgOgA4iTGCePyxIAQAhr,mc_FZx3iFiX1YW7j5eEojoAPc);return
ssc_core_VFv9ctmy6xC9Y5nC__XZlU(ssc_core_FFZbGh27ya8eem_J_hUtAZ,
ssc_core_VriVbeGXVySZhmo4IqByQ6,y,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_sli_kvYdEBImn2CCdeuS6ty1i1,mc_FfDTppU8N_tOWuLK37x_08,
ssc_core_F4tlqGoz8dpsjmIIo_HrZB,mc_FZx3iFiX1YW7j5eEojoAPc);}else{
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_kzi9beWw69_JYDWqr_7hnk,
mc_FZx3iFiX1YW7j5eEojoAPc);pm_VuaGyqV_9K0Ia9Qgn65rsj(
ssc_sli_kdd24RcsXK4hjXPJnCgxPO,mc_FZx3iFiX1YW7j5eEojoAPc);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_kIEgOgA4iTGCePyxIAQAhr,
mc_FZx3iFiX1YW7j5eEojoAPc);return ssc_sli_V3IvKUBgJj8EjHudwb3Lz1(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_sli_Vd8egxYRexpOemSPFvvJei,ssc_sli_kvYdEBImn2CCdeuS6ty1i1,
mc_FfDTppU8N_tOWuLK37x_08,ssc_core_F4tlqGoz8dpsjmIIo_HrZB,
mc_FZx3iFiX1YW7j5eEojoAPc);}}static ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_sli_kibvD6MCr40gZT4yp6iHJM(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,
boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t
ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_core__u7SkOaBUGdCdLyqO2X23S=NULL;if(ssc_sli__LUTDtJud8K4_PqqE22fA8>0){
McRealFunction*ssc_core_FyZkX4cpKZ8YVH5EKfcqLt=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__z5LXIdNga07WqTouQ7yCi,
mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*ssc_core_VB5XLoala8W0VPgYyUV04u=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_FTtfNfzSNBpAWuyfv7HADR,ssc_sli__yONDaHWSO0Y_H0PIYQgl_,
mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_core__iWz_v8nE_W4Zudun77ppE(ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,
ssc_core_VB5XLoala8W0VPgYyUV04u,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_core_VRPaLnG8nfCj_X7coRuJlC,ssc_core_FxVx8bRexTl3hDBcGo5O3w,
mc_FZx3iFiX1YW7j5eEojoAPc);}else{ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_core_Fml092VdhNSIcaKdB4FldR(mc_FZx3iFiX1YW7j5eEojoAPc);}return
ssc_core__u7SkOaBUGdCdLyqO2X23S;}static ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_sli_FBRNPYCXzcC7fHVC8iJOfd(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,
boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t
ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_core__u7SkOaBUGdCdLyqO2X23S=NULL;if(ssc_sli__LUTDtJud8K4_PqqE22fA8>0){
McRealFunction*ssc_core_FyZkX4cpKZ8YVH5EKfcqLt=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__z5LXIdNga07WqTouQ7yCi,
mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*ssc_core_VB5XLoala8W0VPgYyUV04u=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_FTtfNfzSNBpAWuyfv7HADR,ssc_sli__yONDaHWSO0Y_H0PIYQgl_,
mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_core_V2b5WBjkcPlsb9dufPuJOH(ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,
ssc_core_VB5XLoala8W0VPgYyUV04u,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_core_VRPaLnG8nfCj_X7coRuJlC,ssc_core_FxVx8bRexTl3hDBcGo5O3w,
mc_FZx3iFiX1YW7j5eEojoAPc);}else{ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_core_Fml092VdhNSIcaKdB4FldR(mc_FZx3iFiX1YW7j5eEojoAPc);}return
ssc_core__u7SkOaBUGdCdLyqO2X23S;}ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_sli_kl9YKZTIwnlGdySFA8pHdf(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,
NeCERData const*ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,size_t ssc_core_VRPaLnG8nfCj_X7coRuJlC,real_T
ssc_core_FxVx8bRexTl3hDBcGo5O3w,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core__u7SkOaBUGdCdLyqO2X23S=NULL;boolean_T
ssc_sli_kJIiJj4ft2pWbasDqubJP_=false;size_t i;for(i=0;i<
ssc_sli__LUTDtJud8K4_PqqE22fA8;++i){if(ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy[i].
mIsLinear){continue;}ssc_sli_kJIiJj4ft2pWbasDqubJP_=true;break;}if(
ssc_sli_kJIiJj4ft2pWbasDqubJP_){ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_sli_kibvD6MCr40gZT4yp6iHJM(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli__LUTDtJud8K4_PqqE22fA8,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_core_VRPaLnG8nfCj_X7coRuJlC,ssc_core_FxVx8bRexTl3hDBcGo5O3w,
mc_FZx3iFiX1YW7j5eEojoAPc);}else{ssc_core__u7SkOaBUGdCdLyqO2X23S=
ssc_sli_FBRNPYCXzcC7fHVC8iJOfd(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli__LUTDtJud8K4_PqqE22fA8,ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
ssc_core_VRPaLnG8nfCj_X7coRuJlC,ssc_core_FxVx8bRexTl3hDBcGo5O3w,
mc_FZx3iFiX1YW7j5eEojoAPc);}return ssc_core__u7SkOaBUGdCdLyqO2X23S;}boolean_T
ssc_sli__vLGn5snyBGCc9MqkwvzyK(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,NeDynamicSystemInput const*
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,size_t ssc_core_FKySES0vPzxeVPkVt80QKX,
PmSparsityPattern const*ssc_sli_F4abcJKsDhWhdLzsF0QXFJ,boolean_T
ssc_sli_kzBcD1zVPWKLj5FRuDlc3c){PmAllocator*a=pm_default_allocator();
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_kF79J1yovOdS_uDIzPgJXv ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;
NeDynamicSystemInput*ssc_sli_Fi_du5uFlgGne5wvGXKElE=
neu_create_dynamic_system_input(neu_get_dynamic_system_input_sizes(
ssc_sli__OzP6GQ7QKhuWTGGHKSszk),a);size_t ssc_sli_Fbny_rhS6i0kVaFCw9Jm_Z=
ssc_sli_F4abcJKsDhWhdLzsF0QXFJ->mNumRow;PmBoolVector*
ssc_sli_FePcjEiDh0t3auUIIUWZTu=pm__jbisDMumXdocXANx5LhhY(
ssc_sli_Fbny_rhS6i0kVaFCw9Jm_Z,a);PmBoolVector*ssc_sli_kIEgOgA4iTGCePyxIAQAhr=
pm__jbisDMumXdocXANx5LhhY(ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->
ssc_sli_kRBQlHbYYD4Egm1QxQJNGZ,a);PmBoolVector*ssc_sli_V0ktiyKeQRKKcmPJGHHEME=
pm__jbisDMumXdocXANx5LhhY(ssc_sli_Fbny_rhS6i0kVaFCw9Jm_Z,a);boolean_T
ssc_sli_kGIQ9DCh6PWGd5NSVaHdRc;boolean_T ssc_sli_VOoqZlp0_1dBca5U9gp4_u;
boolean_T ssc_sli___mDmNq4k10bdiwJPbdXVD;boolean_T
ssc_sli_FsyV3_j6dptwiqObcclF0W;mc__pFtu1g17h8ZaaZK4PpTkb(
ssc_sli_V0ktiyKeQRKKcmPJGHHEME,ssc_sli_F4abcJKsDhWhdLzsF0QXFJ);
ssc_sli_kGIQ9DCh6PWGd5NSVaHdRc=(mc_FyLahU0kjICfba8O7mWi8Z(
ssc_sli_V0ktiyKeQRKKcmPJGHHEME)==0);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mVMF= *
ssc_sli_FePcjEiDh0t3auUIIUWZTu;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_sli_VOoqZlp0_1dBca5U9gp4_u=(mc_FyLahU0kjICfba8O7mWi8Z(
ssc_sli_FePcjEiDh0t3auUIIUWZTu)==0);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mVMM= *
ssc_sli_kIEgOgA4iTGCePyxIAQAhr;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli__CpBn4DTIb4zbyG0hxjNf2](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
ssc_sli___mDmNq4k10bdiwJPbdXVD=(mc_FLTxr_Wc1PKSeTxwfrcl5B(
ssc_sli_kIEgOgA4iTGCePyxIAQAhr)==0)&&!ssc_sli_kzBcD1zVPWKLj5FRuDlc3c;
ssc_sli_FsyV3_j6dptwiqObcclF0W=(ssc_core_FKySES0vPzxeVPkVt80QKX==0);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_kIEgOgA4iTGCePyxIAQAhr,a);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_FePcjEiDh0t3auUIIUWZTu,a);
pm_VuaGyqV_9K0Ia9Qgn65rsj(ssc_sli_V0ktiyKeQRKKcmPJGHHEME,a);
neu_destroy_dynamic_system_input(ssc_sli_Fi_du5uFlgGne5wvGXKElE,a);return
ssc_sli_kGIQ9DCh6PWGd5NSVaHdRc&&ssc_sli_VOoqZlp0_1dBca5U9gp4_u&&
ssc_sli___mDmNq4k10bdiwJPbdXVD&&ssc_sli_FsyV3_j6dptwiqObcclF0W;}
