#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "ne_std_fwd.h"
#include "ssc_dae_fwd.h"
typedef struct ssc_core_kn2fkwOG390ucqMrkmBlTh ssc_core__vkZ3rfXeilTgHxrnS_l_7
;
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_V7Yb3L2rBXxKauSoS4qh7D ssc_core_k0aosL__P0OEg5ySbRV6Mk
;typedef struct ssc_core_F6pmwUwiAPCebDFOuTSllW ssc_core_kKt2emv_zM_Aii1i4Nu04i
;struct ssc_core_F6pmwUwiAPCebDFOuTSllW{PmfMessageId(*
ssc_core_kKv6Xx1worSoj9CnhS5Dnh)(ssc_core_kKt2emv_zM_Aii1i4Nu04i const*
ssc_core_VJgtn_cGgzdoceadTmm3t6,boolean_T*changed,NeSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k);void(*mDestroy)(ssc_core_kKt2emv_zM_Aii1i4Nu04i*);
void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_core_kKt2emv_zM_Aii1i4Nu04i const*);
ssc_core_k0aosL__P0OEg5ySbRV6Mk*mData;};ssc_core_kKt2emv_zM_Aii1i4Nu04i*
ssc_core__tHBYx2mzptjcixXUqAXGT(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_FJOfgRbEhUGyXLNLRImNAG,McRealFunction*ssc_core_kPDE4W0_1vdFjmGv1Hd7Up
,McRealFunction*ssc_core_VAvzygWXd_Cf_azHot_63D,PmAllocator*
mc_FZx3iFiX1YW7j5eEojoAPc);
#include "limits.h"
#include "math.h"
#include "string.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
PmSparsityPattern*mc_kAZzxJsz9tloc11S9uThaF(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_klSR73f0rO4LhXVlV6gmb7(real_T*mc_FkvBQdfnWOCY_uJC_r4riI,PmSparsityPattern
const*mc__z_znac6SDtIeyvo_HaL8F,real_T const*A,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI);PmSparsityPattern*mc__OkC5ssIRclKeDF7PdRNWG(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_VgJ42P0i5f4Hby5_Ow7gtm(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm);PmSparsityPattern*mc__tKZgLZup1pKXLQCAtP8rU(PmSparsityPattern const
*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kpAmYrZzcKGOgq9qpxzj07(real_T*
mc__nB0POFEJkOOXDZjc8BZu5,PmSparsityPattern const*mc__G8DEE_sSylod1iLuXNmpS,
real_T const*A,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmIntVector
const*perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc_FXA9yTEpI9pfhyLrn8ZGts(PmSparsityPattern*mc_VO4ezo9C6qdUWq1Fln4EVt,
PmRealVector*mc_kfuTzKNJF8C9XawgZFM5k9);PmSparsityPattern*
mc_k1ExSbm6DSOkWaNSiEvE3g(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_kWtyrGt18oGOXysCOa_B4x,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_V_3Bm28Cx08dj9ZMdrwaJg(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*
mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*
mc__qAqv2Z2m7K0VPPGKiCpwD(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,PmBoolVector const*
mc_F50LHIM89Xpj_mZvqqCQnH,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__mBVa3_c658wjuT_cJe_Qy(PmSparsityPattern const*b,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*
mc_VCVhWy_VaDhraHrlfFWxBa,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);void
mc_Fv2sZggivbSOc5zulDbRra(PmRealVector const*mc_k5z61obNZCWCbyygZn_fdK,real_T
const*mc__uV9GcaXWFlx_5jfPip5Mo,PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmBoolVector const*mc_FIRQmUoZ8GOih5Os6NY5A_,
PmBoolVector const*mc_F50LHIM89Xpj_mZvqqCQnH);PmSparsityPattern*
mc__JB9jUvbb10FaTie1cmY8_(PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,
size_t mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*mc_VINzQey3e2GxYDxzr7cOY_(
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_Fzylow9cnZxIhyL1O9nM0I(PmRealVector const*
mc_VIutEr_JmfWNeDyKonnHVk,PmRealVector const*mc_VW_HqYZElHCjWHwd6Iv4ON,
PmSparsityPattern const*pm__HVqeFmd5gKdguw04VZTsk,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1);void
mc_FY8ifnDZsXphdqo3UGrtOk(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,size_t n
);void mc_kNxwVTI76g4kj9P52yKhA5(PmSparsityPattern*mc_V_ku0ZO8TOxhc9438tlsBI,
size_t n);PmSparsityPattern*mc_kNYMmfXA1XtHcmiWCr7l_C(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc_VJlBwQnSeLpciXVTLb_llB(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*mc__5C6m_ZyP9_NYekcJCEULM(PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc__8x7kz_627_gXDli_FJo22(
PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*
mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*
mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,
PmRealVector const*mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*
mc_kyCwDjPxmBGRiTH73vrjJL(PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc__tyTSVoY7fpafmg4sUl1P3(PmRealVector const*
mc_kuYGZlr6GiOSeqresCsPcM,PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,
PmRealVector const*mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*
mc_V_ku0ZO8TOxhc9438tlsBI,PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,
PmSparsityPattern const*mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*
mc_krOJvR5Qa1KQZu3eEsQtEU);PmSparsityPattern*mc_kAJ3geuq0o8ebTsVAocwxT(
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
mc__Z9st0ivzkt_c5ayYUNbbq(PmRealVector const*mc_kuYGZlr6GiOSeqresCsPcM,
PmSparsityPattern const*mc__ILFYYSbi7hW_uYs_eHsRR,PmRealVector const*
mc_FmeGGSq6P2_Kg9j7twxwci,PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,
PmRealVector const*mc_FQSQWg_QFOKIWm9DWdLQR6,PmSparsityPattern const*
mc_VLr_Ia18P_8icXM9WFOfYI,PmRealVector const*mc_k0iOHO6BSf8IgTo550ELD8,
PmIntVector const*mc_kQx8tFCixwhfgiAY_Pi8wJ,int const mc___aedK39Pax6Ziebprhh0i
);PmSparsityPattern*mc_VI58f6RQKXS_Y5sclnoOPT(PmSparsityPattern const*a,
PmSparsityPattern const*b,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_FvfmwR5Z4udFdmA89MySHd(McMatrixFunction*mc_kEQ7ZkhePUp8eHqnX6lLap,
McMatrixFunction*mc_VRqcAPiI_zWzcaWghAD8Ra,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_kjBl5aSCPqK8_T48OOvhEj(
McMatrixFunction*mc_ky0WCncALplbXL_SNbJkvW,size_t mc_Fxvltms7Im4baT5ZPxj7f2,
size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t mc_VGPLyQQmjMlldLbUiddSkc,size_t
mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);typedef struct
mc_knhZCtHxFBxXg5tgJuUCEK mc_kZbwbT_kvDGzcDUgumpykL;typedef struct
mc_FBH8iD7u05pSXm_5ubaK2V mc_FdKBw8fvqLW3Y5joYOEBEt;struct
mc_FBH8iD7u05pSXm_5ubaK2V{mc_kZbwbT_kvDGzcDUgumpykL*mData;void(*mEvaluate)(
mc_FdKBw8fvqLW3Y5joYOEBEt const*mc__3hSkv0Wz8pGW5lmLxQaXM,void const*
mc_kDRphcAfRHSbf1ZLKEDW9k);McMatrixFunction*(*mc_FBMgSgsPcuhAfqqbis_q6w)(
mc_FdKBw8fvqLW3Y5joYOEBEt const*mc__3hSkv0Wz8pGW5lmLxQaXM);void(*mDestroy)(
mc_FdKBw8fvqLW3Y5joYOEBEt*mc__3hSkv0Wz8pGW5lmLxQaXM);};
mc_FdKBw8fvqLW3Y5joYOEBEt*mc_V7lAu3dITJGBeukLWd4htI(McMatrixFunction*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*mc_F41vm5CeApOpiPIy1rZa2m(McMatrixFunction*
mc_kXwHswK956KEimdoHimdrb,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "ne_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
#include "ne_std_fwd.h"
#include "ne_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "pm_log.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(char
const*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
typedef struct ssc_core__BFX2_i0QV8o_P5c_HM1dw ssc_core_VopF3OxFxrWebHOMVbPioB
;typedef union ssc_core_kGvI4ZFg3wpdda1nNtmEzB{PmSparsityPattern mM_P;
PmRealVector mM;PmSparsityPattern ssc_core_V2LRImwNDRhw_P09Sh1j_5;PmRealVector
ssc_core_F5cZro_aISlmYmA6qqasW5;PmSparsityPattern mDXM_P;PmRealVector mDXM;
PmSparsityPattern mDDM_P;PmRealVector mDDM;PmSparsityPattern mDUM_P;
PmRealVector mDUM;PmSparsityPattern mDPM_P;PmRealVector mDPM;PmSparsityPattern
mDTM_P;PmRealVector mDTM;PmRealVector mF;PmBoolVector mVDF;PmBoolVector mVMF;
PmBoolVector mVMM;PmBoolVector mVPF;PmBoolVector mVSF;PmBoolVector
ssc_core_FNZJop80BLhoh9Lle6JmlY;PmBoolVector ssc_core__bufeOd0__SrhLS9ckCttw;
PmBoolVector mSLF;PmBoolVector mSLF0;PmSparsityPattern mDXF_P;PmRealVector mDXF
;PmSparsityPattern ssc_core__42Iyv77wKKJ_Tevz4wZYX;PmRealVector
ssc_core__uXkUPNCvEGG_PkbtccVgX;PmSparsityPattern mDPDXF_P;PmRealVector mDPDXF
;PmSparsityPattern mTDXF_P;PmSparsityPattern mDUF_P;PmRealVector mDUF;
PmSparsityPattern mTDUF_P;PmSparsityPattern mDTF_P;PmRealVector mDTF;
PmSparsityPattern mDNF_P;PmRealVector mDNF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmRealVector mY;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mMDXY_P;PmSparsityPattern mTDXY_P;PmSparsityPattern mDUY_P;
PmRealVector mDUY;PmSparsityPattern mMDUY_P;PmSparsityPattern mTDUY_P;
PmSparsityPattern mDTY_P;PmRealVector mDTY;PmRealVector
ssc_core__A2epjO2_6d6fy8ysWexEB;PmSparsityPattern
ssc_core_keHWgCjDA6_eeu7s3KIFqa;PmRealVector ssc_core_FOr_DmeGA8drfybA5lUQuu;
PmSparsityPattern ssc_core__2xFrdyqWTd0VmiBdcgt9s;PmRealVector
ssc_core_kCmd3Iq7t5S_WP1ScroCKa;PmRealVector mCER;PmSparsityPattern mDXCER_P;
PmRealVector mDXCER;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;
PmRealVector mIC;PmRealVector mICR;PmSparsityPattern mDXICR_P;PmRealVector
mDXICR;PmSparsityPattern mDDICR_P;PmRealVector mDDICR;PmSparsityPattern
mTDUICR_P;PmIntVector mICR_IM;PmBoolVector mICR_ID;PmBoolVector mICR_IL;
PmSparsityPattern mICRM_P;PmRealVector mICRM;PmSparsityPattern mDXICRM_P;
PmRealVector mDXICRM;PmSparsityPattern mDDICRM_P;PmRealVector mDDICRM;
PmRealVector mFREQS;PmRealVector mSOLVERHITS;PmRealVector mZC;PmIntVector mMODE
;PmIntVector mUDOT_REQ;PmBoolVector mDXF_V_X;PmBoolVector mDUF_V_X;
PmBoolVector ssc_core__LvZb6o15d0CgeTD_o3fzZ;PmBoolVector mDNF_V_X;
PmRealVector mSO;PmRealVector mSP;PmBoolVector mLV;PmBoolVector mSLV;
PmBoolVector mNLDV;PmBoolVector mSCLV;PmRealVector mQX;PmSparsityPattern mQX_P
;PmRealVector mQU;PmSparsityPattern mQU_P;PmRealVector mQT;PmSparsityPattern
mQT_P;PmRealVector mQ1;PmSparsityPattern mQ1_P;PmIntVector mASSERT;PmIntVector
mPASSERT;PmIntVector mIASSERT;PmRealVector mDELAYS;PmRealVector mOBS_EXP;
PmRealVector mOBS_ACT;PmBoolVector mOBS_IL;PmRealVector mVAR_TOL;PmRealVector
mEQ_TOL;PmRealVector mIMIN;PmRealVector mIMAX;PmRealVector mDIMIN;PmRealVector
mDIMAX;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;PmBoolVector mLOCK2_R;
PmBoolVector mLOCK2_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector
mUPDATE_R;PmIntVector mUPDATE_I;PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I
;PmRealVector mJACOB;PmRealVector mSTATE;}ssc_core__TeZPMOq8dp9XmQn6UtKJ2;
typedef enum ssc_core__in5MsQCmel7aiixModbYl{ssc_core__lbQk03jRopaXe9vMviYGW= -
1,ssc_core_FMqA5v57mtWOhil5sMGjL7,ssc_core_Vn7tJfsyRZpPcPa7tryEQs,
ssc_core_VRRCroPl0HpTfy6N_IrOWr,ssc_core_kc04mq7y9khQfetMyuviYs,
ssc_core_Fw6PJbJnvod8eHJMxIFb8O,ssc_core_FbR9PdsU5U01YmfVH8ygQ2,
ssc_core__Jnoc_bEf8OMhH3dVF2Mn1,ssc_core__EoTC53fSeKzXPzFFNY31y,
ssc_core_kBe8Cgnfq1t_ZeUU4Yq0Jy,ssc_core_Fk89NpAOMw0Gdilzq_CBGU,
ssc_core__usiW0JiQEC5aLUzar8PHJ,ssc_core_FfnvETgi4Ehgf1whoIaLPu,
ssc_core__fMMPZg2NMtdfqRZ4qI77y,ssc_core_kRH1up8daAltZPZHVgaxHP,
ssc_core_FHixxHSiLQ_iX5HsQ_SKOw,ssc_core_FSTW9FqsAdOscLJbipRpuR,
ssc_core_VeV2_YWfxGGLWq1pRmDjxF,ssc_core_F3B1H_zKTHWIY9wyyPAb1O,
ssc_core__Qs_mB4S_94tVmYHzBggFr,ssc_core_F2lOqN2lFwlzYqfN1sto02,
ssc_core_F3YHEAQYs9tqjeSK5B0H1_,ssc_core_VaNcxDTwi9KkcuV3D8eiBz,
ssc_core_kjjM6qylFU0CXDthh6k7Yb,ssc_core_FT_SHIGuGxKwbiIWKmLzfp,
ssc_core__Rlum1L7jb8aWLqEHtuPwY,ssc_core_kPNjSqFZzp8Yiicm70fL3X,
ssc_core_V2sZUCpc8zlsbepSxDGyVO,ssc_core_kujBrewfrsGbYuAAwQ1xaC,
ssc_core_FsnHkzdO_I8FgLMSaW7rwP,ssc_core_k5ZBtziTx0K_eiK4_hmf9l,
ssc_core_k0U_hfj1VU4li9TWlOOVVv,ssc_core_kCYNBjxA4_OYWq36i4CQ_e,
ssc_core_VaT1OMrCUZCdXHE_S8JmWn,ssc_core_F9uy7iaCo_8ljTyZalHPgi,
ssc_core_FJ_gK8YlzO_3ieSeK7frie,ssc_core__4Bki1d07Ix8YDiy1pUEhy,
ssc_core_Fns9Ha4R97WMjuh0bWEQzK,ssc_core_FTxLvwd8_GCWfiQyi6_AMv,
ssc_core_FwJnnH9_cpSxV5V0dj19Qo,ssc_core_VMWJ81tB1dlGXuelBnRIfI,
ssc_core_FTmaJ_2smaxGgutT_OLwPX,ssc_core_kdnih69QGPxV_ymIPvA_OI,
ssc_core_FIKBzI7h7JtVYaUWh0l8FL,ssc_core_VQm8Bjj78l8scXo54laWSP,
ssc_core_k8uLW0TtfB_zZDVse7JtRL,ssc_core_FWa_jHec2bKSjPfQPBLFdx,
ssc_core_FNDX5dUHnm_wc1fzhUOQR1,ssc_core_VOqY16_eWmSGaqu25Xi027,
ssc_core_kbJAKx1ometdbyGMtvT7pq,ssc_core__DQqSoECJ8CYhD2ZvdOG6_,
ssc_core_FGe_bzXeBl8EbmwSVzf3l_,ssc_core_F1R3HoSYxntd_XHznDeIAI,
ssc_core_F_TQ5A7_604L_X0Mw5MF6Q,ssc_core_Vg_OPZTKqYG6dqX7QAEhIf,
ssc_core_FbbpOJuDdxdtbyZ3_fzhHv,ssc_core_keKSvlwac3l4aip1GWQVrr,
ssc_core_ksrrMVbs1lKpZigpAv4Nxe,ssc_core__rIoqqW41yCXcHWqRoN9X_,
ssc_core__GcYe5NxiWx5iTGKavwX_l,ssc_core_F79zCDnKsFSfaHXItZpins,
ssc_core_FHXiNrQJ3uxfgy2qe76alX,ssc_core_V_ungodJcqKQbDow4VhpNJ,
ssc_core_Fou13S_cMLlTcXKpzIeC0_,ssc_core_VKCWQTpaii_BVub0fdSwuW,
ssc_core_FbaO98Zir9K_Z1wDaxjW6h,ssc_core_VwdrGCcgJ0h_cD7CiiYWCI,
ssc_core_Vk8zIrIGWx_QZLIDZdUBVW,ssc_core_ke_tw_ny09OFgagsD_okzr,
ssc_core__ilJ5MzrD9KShD4VTk_mjA,ssc_core_kS7IbG7A9aGoZX46uEPj3w,
ssc_core__s_eUQh1wLKtYupzAs1zyA,ssc_core_kPq4r8e2tLK7XynGcJJnDJ,
ssc_core_Fvn7zqTWjEtO_iGFQertmW,ssc_core_V5kbpHOxAoKoiuKv3MrUS7,
ssc_core_k2NsmflOaJ0JjmfDWmRxTx,ssc_core_kRS_JoBwGe4McunuHx47xa,
ssc_core_VI8ZvDNHtW0fguSrZKN10S,ssc_core__NAgJP5DrB0gbiOsTU_FwQ,
ssc_core_kW67z8CtTOOtgPPiutT8OF,ssc_core_VpgHwsBwIylwcqaJF5D1Kl,
ssc_core_FzfKNVc4jQ4QaHoHh_xFru,ssc_core__j2NAClSX88Wi1_sFtGSjA,
ssc_core_F_c050LJClpKeydlnheRdg,ssc_core__USsX8hQ2BODaXQuOKOjM_,
ssc_core_F6lLOA6_JM4cd9HVqhCgha,ssc_core_F_Tgu_ROavx6ZmECsFKf3F,
ssc_core_FWOffzRazS8icaLEoHtheY,ssc_core__BJLFD6ZUZGIY5_eIs_bst,
ssc_core_F1giDMmnqZ4dbed4AQPIUW,ssc_core_kvZwufOdQ38mcilZy7Gp4x,
ssc_core_FnEGNvPN9it5h5Qwq_UjEd,ssc_core_FpcbC9cWWUlLXH1yXZWXN9,
ssc_core__QnbCkIcXHOoXH4eRvKcfo,ssc_core_Flh4LMfC49pseDv8Y3FwFu,
ssc_core_VUCbUbBdMDKkfied_ZCQFp,ssc_core_FL0_7LMdYuOVe9WQ6_L9bk,
ssc_core_FE9Z7C8kJAdpVXGuwk1WJY,ssc_core__qdig_XOtUd7WPsu1wZK2j,
ssc_core_kMfzDNBqCT8dji4ReVJ_Hi,ssc_core_VKalPPiew1GiWT8ZVYDqI9,
ssc_core_FuF4aqv8wZpf_53HpnuXCX,ssc_core_FG9NX_DYk5daceojB1CoNZ,
ssc_core_kLvdxk5qciKuiXldCEAEer,ssc_core_kW_Jq1qKAWKmjHJx8n4m_9,
ssc_core_FdA_fMXZXRCohD9lrLnmOw,ssc_core__gBPQQITzMlNYyB2Chhblz,
ssc_core__ypTVvacc2Sza9RVzw0ZAT,ssc_core_kFznQjTd16xldyq1Pca2ME,
ssc_core__SSfsMQN6c4OjLgCTZ_NYK,ssc_core_FQl0PR0amVSHh5wOZRVymI,
ssc_core_kg2r820DrGxXeLc6d_2FdV,ssc_core__HTna744Xth1d9cpYaS9T2,
ssc_core_k3hIBjt33OtXiuW9e5OfvV,ssc_core_FpWA1YgvkJWJ_TpWDJUjiG,
ssc_core_VJgsWQKAuw4C_H4AOe1DsM,ssc_core_FnjTCvm6_mOjb5gJOcTWuM,
ssc_core_FEWOncAxYHtPjPGn9asTra,ssc_core__7UXRcmUpDWLYT0xePYlQZ,
ssc_core_VPFzmbrVmTd2cuQq9MOSKY,ssc_core_kRkdzaGR_WWhjeHlmIpm_7,
ssc_core__Iyw9r7yT889fXo8SHURML,ssc_core__F_kUHVEywxOgiQYjdYQff,
ssc_core_F7uJQq_pYRt_bD1d_IPkDy,ssc_core_V_dJKR9vHwh2aDLOlvHrrs,
ssc_core__JWeWgh02bhdVDhPk33TBZ,ssc_core_kmIX6MKE_exDaLxoAPSg_m}
ssc_core_VGsErlwHEVtbbHCadOG87L;typedef enum ssc_core_Fzeiyvg_UHtqVie47gplfh{
ssc_core_VFypg8X5p1KAeeWCMOqYwP= -1,ssc_core_V_zR__KoVX8ueDtyLUsTUT,
ssc_core_FLHvYzIRwLdiWq_TEDTGGZ,ssc_core_kqsdvq2nWat8YaSGPvsB8l,
ssc_core_k2aeqL11wCCwZu46fnIUqC}ssc_core_FvUqHBlhup_UW5zf9NfVM6;typedef int32_T
(*ssc_core_kXdj0qB2ZFhZcqi5ARlG6_)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeSystemInput const*,ssc_core__TeZPMOq8dp9XmQn6UtKJ2*);typedef
ssc_core__TeZPMOq8dp9XmQn6UtKJ2*(*ssc_core_kDU7FEZ6zVdGbmnpzQaUnu)(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,PmAllocator*);typedef void(*
ssc_core__bjS2fbVF_twW1jq3u9x9y)(ssc_core__TeZPMOq8dp9XmQn6UtKJ2*,PmAllocator*
);typedef ssc_core__TeZPMOq8dp9XmQn6UtKJ2*(*ssc_core_kxx_nBt5xVKHW5dGBFnbbB)(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,NeSystemInput const*,PmAllocator*,
ssc_core_VGsErlwHEVtbbHCadOG87L);typedef int32_T(*
ssc_core_kNiwvAWLuit9iiucYO9aRY)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeSystemInput const*);typedef ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*(*
ssc_core_V8Ee96YvR3dX_yy1YolRGr)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
boolean_T);typedef void(*ssc_core_FPsY_NJe3d0MiTCYpeJRxQ)(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_VfIOAX3QKB4eaq9E5oHpmK,
NeSystemInput const*ssc_core_FV2blfCgUMl1g1X4GL7gwU,NeSystemInput const*
ssc_core__JEDb8bF9IKTcTw4Br97id,boolean_T ssc_core_FNqGPDlHZaWmjLvokz6jWi);
typedef void(*ssc_core__V3DPXtALe8khLFJI5dF5Y)(ssc_core__vkZ3rfXeilTgHxrnS_l_7
const*ssc_core_Fz_8_oSTis44XHuynjCUn6,NeSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);
typedef void(*ssc_core_VxtrQiSqXz8zc9TWnQoxiJ)(ssc_core__vkZ3rfXeilTgHxrnS_l_7
*,PmAllocator*);typedef void(*ssc_core_V__di6hD_tdeZ1kY7NdIKq)(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,NeLoggerBuilder*);typedef int32_T(*
ssc_core_Fi6feB9tEKW_bXsgmp3tXX)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeSystemInput const*,PmRealVector*);typedef void(*
ssc_core__D58xAG7k0_tfXQ6aLMTin)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeParameterBundle const*);typedef NeParameterBundle*(*
ssc_core_k3Yq5WD1lq8kWq2K_PkSya)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*);
typedef void(*ssc_core_FidnqSHQJ_0oemuCj6kIoe)(ssc_core__vkZ3rfXeilTgHxrnS_l_7
const*,NeSystemInput const*,size_t,boolean_T);typedef void(*
ssc_core_FA5ZKLzW6U8zZDzOw5Yqv6)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeSystemInput const*,boolean_T,boolean_T,int16_T);typedef void(*
ssc_core_V36PUq1Gw9WgXisqoMbgkL)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,size_t
);struct ssc_core_kn2fkwOG390ucqMrkmBlTh{size_t mRefCount;size_t mNumStates;
size_t mNumEquations;size_t ssc_core__oDWakF7Bxxh_9PylKwnyz;size_t mNumInputs;
size_t mNumOutputs;size_t ssc_core_F3PjN_oDrpK0_ThkfqVg1d;size_t mNumModes;
size_t mNumMajorModes;size_t mNumRealCache;size_t mNumIntCache;size_t mNumZcs;
size_t mNumAsserts;size_t mNumParamAsserts;size_t mNumInitialAsserts;size_t
mNumRanges;size_t mNumEquationRanges;size_t mNumCERRanges;size_t mNumICRRanges
;size_t mNumAssertRanges;size_t mNumParamAssertRanges;size_t
mNumInitialAssertRanges;size_t mNumSamples;size_t mNumCEResiduals;size_t
mNumICResiduals;size_t mNumFreqs;size_t mNumSolverHits;size_t mNumDelays;
size_t ssc_core_VeMaOhBdXx4weinqgEeV_W;size_t ssc_core_kywGOFaOjLlBYePf5nqmpT;
size_t mNumDxfNzMax;size_t ssc_core_FE8OWBPwV8hpXPYNI9I0pk;size_t
ssc_core__G3mZetE_hlHZemzBo4ffz;size_t mNumDufNzMax;size_t
ssc_core_VCPH8IZr9Llmamiai0bRDz;size_t mNumDtfNzMax;size_t
ssc_core_VM5ae4LCmpl5X5UhTjVim6;size_t ssc_core_F_2foAK_12hldH5_FWQPsG;size_t
ssc_core_k5Wq9llZvK_jVLljdrSY8N;size_t ssc_core_FjBEYpy0DG4Nhqg_PJanUh;size_t
mNumDxyNzMax;size_t ssc_core_kIyxM7hxEUSVXuEfhwaq90;size_t
ssc_core__yKNPDEEb3pMcq_OuN5rJ2;size_t mNumDuyNzMax;size_t
ssc_core_F__rCks9GmOEdy8jTvdBtt;size_t mNumTDuyNzMax;size_t mNumDtyNzMax;
size_t ssc_core_F6LqhYbo4oxriXmeTwH7T_;size_t ssc_core_Ffph1Dxli0Kej54O_kavpm;
size_t ssc_core_FL6ogbS_3NKHXHqj01uEIz;size_t ssc_core__EN4JmYjqxlR_5KoaLUvBf;
size_t ssc_core_FExXePsad1toX5FNKNsYLW;size_t ssc_core___4LXQ0pAB4U_qhfm8UvPE;
size_t ssc_core_kNRutnVHE_dbaLQ3nxjDH9;size_t ssc_core_FFwbr6cg5sKQgefweXBpQw;
size_t ssc_core_kBV_CB_QdldJY9ynG1Yy8k;size_t ssc_core_kvihOV3867dlbPxpAJ5VF_;
size_t mNumDxmNzMax;size_t mNumDumNzMax;size_t ssc_core_kFFa6_OVyDSKVLNbZmXndb
;size_t ssc_core__kVB70_cGexYai_oYX9WCn;size_t ssc_core_kPoTeeo_mdOiaLQKfgCBXy
;size_t ssc_core_VIqk791HcnW8ZXoi79EcYJ;size_t ssc_core_khE7cQ7aLzSUdaaMKGYjXT
;size_t ssc_core_FiJMHW7l9tWqVaKaG8OGtn;size_t ssc_core_Fvi4czgEYCSsVis5JTEBUV
;size_t mNumObservables;size_t mNumObservableElements;size_t
mNumSwitchingCoeffs;size_t mNumJacobianElems;size_t mNumSwitchingEquations;
size_t mNumSwitchingStates;boolean_T mIsYLinear;boolean_T
ssc_core_V_Yb_DjiZVG_cDKov0aX2a;boolean_T mIsMConstant;boolean_T
mIsMRuntimeScaled;boolean_T mIsMPwConstant;boolean_T
ssc_core_kv_qBdp3KfhVXTZs_uMB6x;boolean_T mHasConstraints;boolean_T
ssc_core_FiExqWFTEah9jHJ0SH1HNW;boolean_T mHasConstraintEquations;boolean_T
ssc_core_kekZGaaK5QxIhui7wXJn4S;boolean_T ssc_core_k891FEnFCdx7euT7ojWAvy;
boolean_T ssc_core_VqmLdt0i9U4hfe0QzfDRx7;NeVariableData*mVariableData;
NeObservableData*mObservableData;NeVariableData*mDiscreteData;NeZCData*mZCData
;NeModeData*mMajorModeData;NeEquationData*mEquationData;NeICRData*mICRData;
NeSwitchingCoeffsData*mSwitchingCoeffsData;NeJacobianElemsData*
mJacobianElemsData;NeSwitchingStatesData*mSwitchingStatesData;NeAssertData*
mAssertData;NeAssertData*mParamAssertData;NeAssertData*mInitialAssertData;
NeRange*mRanges;NeRange*mEquationRanges;NeRange*mICRRanges;NeRange*
mAssertRanges;NeRange*mParamAssertRanges;NeRange*mInitialAssertRanges;
NeCERData*mCERData;NeRange*mCERRanges;size_t*mSwitchingEquationsData;
NeParameterInfo mParameterInfo;size_t mNumIo[NUM_IO_TYPES];SscIoInfo const*mIo
[NUM_IO_TYPES];NeChecksum*mChecksum;ssc_core_kXdj0qB2ZFhZcqi5ARlG6_ mMethods[
ssc_core_kmIX6MKE_exDaLxoAPSg_m];ssc_core_kDU7FEZ6zVdGbmnpzQaUnu mMakeOutput[
ssc_core_kmIX6MKE_exDaLxoAPSg_m];ssc_core__bjS2fbVF_twW1jq3u9x9y mFreeOutput[
ssc_core_kmIX6MKE_exDaLxoAPSg_m];ssc_core_kxx_nBt5xVKHW5dGBFnbbB
ssc_core_ktZ_VgXj6ypYgmo3JmGBu8;ssc_core_kNiwvAWLuit9iiucYO9aRY mSolves[
ssc_core_k2aeqL11wCCwZu46fnIUqC];ssc_core__D58xAG7k0_tfXQ6aLMTin mSetParameters
;ssc_core_k3Yq5WD1lq8kWq2K_PkSya ssc_core_VOZVCSGMYgt9iHHikCMn8w;void(*
ssc_core__cBg4VjzR5KSYuoHs3BEAX)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*);
ssc_core_VxtrQiSqXz8zc9TWnQoxiJ ssc_core_kosGVqM5sQxa_ilVRRQVR_;
ssc_core__vkZ3rfXeilTgHxrnS_l_7*(*mCloneFcn)(ssc_core__vkZ3rfXeilTgHxrnS_l_7
const*);PmfMessageId(*mInitializeFcn)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,
NeSimulationParameters,NeuDiagnosticManager*);ssc_core_V8Ee96YvR3dX_yy1YolRGr
ssc_core_F3_Zg7QzPr_fe5wFKaoI7D;ssc_core_FPsY_NJe3d0MiTCYpeJRxQ
ssc_core_kh5VZ4JHusdwfyEBSXiXox;ssc_core__V3DPXtALe8khLFJI5dF5Y
ssc_core_FIdFRrqUoJlaVXr8Tmeoy4;ssc_core_V__di6hD_tdeZ1kY7NdIKq mSetupLoggerFcn
;ssc_core_Fi6feB9tEKW_bXsgmp3tXX mLogFcn;void(*mGenerateFcn)(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*,NeCgParams const*,NeCgResults*);
NeCustomData*(*mGetCustomDataFcn)(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*);
int32_T(*mSetCustomDataFcn)(NeCustomData const*,
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*);ssc_core_VopF3OxFxrWebHOMVbPioB*
ssc_core__aeMj4HGLhxwhebRt0eOOa;ssc_core_FidnqSHQJ_0oemuCj6kIoe
ssc_core_Vh2YL8U0kj_kgHY91Sc5UE;ssc_core_FA5ZKLzW6U8zZDzOw5Yqv6
ssc_core_FLsL2KzVDm86biVm9CPZ2O;ssc_core_V36PUq1Gw9WgXisqoMbgkL mPushInfo;};
PMF_DEPLOY_STATIC int32_T ssc_core__mUtFzhIPKl6bLjH8hrAN8(const
ssc_core__vkZ3rfXeilTgHxrnS_l_7*ssc_core_VeN_GVnH6xOJcqlpqWSg8m,
ssc_core_VGsErlwHEVtbbHCadOG87L id,const NeSystemInput*
mc_kDRphcAfRHSbf1ZLKEDW9k,ssc_core__TeZPMOq8dp9XmQn6UtKJ2*
mc_VgqbsB_3R4GTjLQeEYi1Qc){(void)0;;return ssc_core_VeN_GVnH6xOJcqlpqWSg8m->
mMethods[id](ssc_core_VeN_GVnH6xOJcqlpqWSg8m,mc_kDRphcAfRHSbf1ZLKEDW9k,
mc_VgqbsB_3R4GTjLQeEYi1Qc);}PMF_DEPLOY_STATIC ssc_core__TeZPMOq8dp9XmQn6UtKJ2*
ssc_core__87W9_KqQxdT_a6Qo5vF8k(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,ssc_core_VGsErlwHEVtbbHCadOG87L id,PmAllocator
*pm_FbYb_iLqY2hwZTVlVaiqJY){return ssc_core_VeN_GVnH6xOJcqlpqWSg8m->
mMakeOutput[id](ssc_core_VeN_GVnH6xOJcqlpqWSg8m,pm_FbYb_iLqY2hwZTVlVaiqJY);}
PMF_DEPLOY_STATIC void ssc_core_VQatmoXBi5_FZL_C_VdNiX(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_VeN_GVnH6xOJcqlpqWSg8m,
ssc_core__TeZPMOq8dp9XmQn6UtKJ2*mc_VgqbsB_3R4GTjLQeEYi1Qc,
ssc_core_VGsErlwHEVtbbHCadOG87L id,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mFreeOutput[id](mc_VgqbsB_3R4GTjLQeEYi1Qc,
pm_FbYb_iLqY2hwZTVlVaiqJY);}PMF_DEPLOY_STATIC ssc_core__TeZPMOq8dp9XmQn6UtKJ2*
ssc_core_FQIQvqOK3btE_an2yZdPr2(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core_VGsErlwHEVtbbHCadOG87L id){
return ssc_core_VeN_GVnH6xOJcqlpqWSg8m->ssc_core_ktZ_VgXj6ypYgmo3JmGBu8(
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,mc_kDRphcAfRHSbf1ZLKEDW9k,
pm_FbYb_iLqY2hwZTVlVaiqJY,id);}PMF_DEPLOY_STATIC int32_T
ssc_core_kmGws0IhfzSXf5CzL0ZfJi(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,ssc_core_FvUqHBlhup_UW5zf9NfVM6 id,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k){(void)0;;return
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mSolves[id](ssc_core_VeN_GVnH6xOJcqlpqWSg8m,
mc_kDRphcAfRHSbf1ZLKEDW9k);}PMF_DEPLOY_STATIC NeSystemInputSizes
ssc_core_VqVhmbkSXkC4YyK4PjIXiK(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_VeN_GVnH6xOJcqlpqWSg8m){NeSystemInputSizes sizes;sizes.mSizes[
NE_SYSTEM_INPUT_ID_Q]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumMajorModes;sizes.
mSizes[NE_SYSTEM_INPUT_ID_M]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumModes;sizes.
mSizes[NE_SYSTEM_INPUT_ID_T]=1;sizes.mSizes[NE_SYSTEM_INPUT_ID_U]=
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumInputs;sizes.mSizes[NE_SYSTEM_INPUT_ID_V]
=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumInputs;sizes.mSizes[NE_SYSTEM_INPUT_ID_X
]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumStates;sizes.mSizes[
NE_SYSTEM_INPUT_ID_D]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->
ssc_core_F3PjN_oDrpK0_ThkfqVg1d;sizes.mSizes[NE_SYSTEM_INPUT_ID_E]=
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumSamples;sizes.mSizes[
NE_SYSTEM_INPUT_ID_CR]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumRealCache;sizes.
mSizes[NE_SYSTEM_INPUT_ID_CI]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumIntCache;
sizes.mSizes[NE_SYSTEM_INPUT_ID_A]=ssc_core_VeN_GVnH6xOJcqlpqWSg8m->
mNumSwitchingCoeffs;sizes.mSizes[NE_SYSTEM_INPUT_ID_J]=
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mNumJacobianElems;return sizes;}
PMF_DEPLOY_STATIC void ssc_core_kdW17LXrMY43iun6DX485a(
ssc_core__vkZ3rfXeilTgHxrnS_l_7*ssc_core_VeN_GVnH6xOJcqlpqWSg8m){++(
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mRefCount);}PMF_DEPLOY_STATIC void
ssc_core_V19L3_DKUYtl_m6VGpFlSg(ssc_core__vkZ3rfXeilTgHxrnS_l_7*
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){(void)0
;;if(--(ssc_core_VeN_GVnH6xOJcqlpqWSg8m->mRefCount)==0){
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->ssc_core_kosGVqM5sQxa_ilVRRQVR_(
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,pm_FbYb_iLqY2hwZTVlVaiqJY);}}PMF_DEPLOY_STATIC
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_kFWUeoTOqtGGdeUr5_TxZS(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_VeN_GVnH6xOJcqlpqWSg8m,
boolean_T ssc_core_FNqGPDlHZaWmjLvokz6jWi){return
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->ssc_core_F3_Zg7QzPr_fe5wFKaoI7D(
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,ssc_core_FNqGPDlHZaWmjLvokz6jWi);}
PMF_DEPLOY_STATIC void ssc_core_k6_7ZMVir9p8_14K8oU3dN(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_VeN_GVnH6xOJcqlpqWSg8m,
NeSystemInput const*ssc_core_VvRyyjAI7WtOV5wPFrKrhy,NeSystemInput const*
ssc_core_VBYl1JFlaSpwYyWK_u1_hF,boolean_T ssc_core_FNqGPDlHZaWmjLvokz6jWi){
ssc_core_VeN_GVnH6xOJcqlpqWSg8m->ssc_core_kh5VZ4JHusdwfyEBSXiXox(
ssc_core_VeN_GVnH6xOJcqlpqWSg8m,ssc_core_VvRyyjAI7WtOV5wPFrKrhy,
ssc_core_VBYl1JFlaSpwYyWK_u1_hF,ssc_core_FNqGPDlHZaWmjLvokz6jWi);}
PMF_DEPLOY_STATIC void ssc_core_FslPXJldo_dIVmfDRb7EJb(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_Fz_8_oSTis44XHuynjCUn6,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VlnhKi82gfCLgumIqeduOq){ssc_core_Fz_8_oSTis44XHuynjCUn6->
ssc_core_FIdFRrqUoJlaVXr8Tmeoy4(ssc_core_Fz_8_oSTis44XHuynjCUn6,
mc_kDRphcAfRHSbf1ZLKEDW9k,mc_VlnhKi82gfCLgumIqeduOq);}PMF_DEPLOY_STATIC void
ssc_core__qeYSM3hU3hsdebNeXiYTN(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_Fz_8_oSTis44XHuynjCUn6,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,
size_t ssc_core__lEVjiBdO94nWPd1DTZuBt,boolean_T
ssc_core_kJqxcBm86v_efifQJtjyb5){ssc_core_Fz_8_oSTis44XHuynjCUn6->
ssc_core_Vh2YL8U0kj_kgHY91Sc5UE(ssc_core_Fz_8_oSTis44XHuynjCUn6,
mc_kDRphcAfRHSbf1ZLKEDW9k,ssc_core__lEVjiBdO94nWPd1DTZuBt,
ssc_core_kJqxcBm86v_efifQJtjyb5);}PMF_DEPLOY_STATIC void
ssc_core_FvEqIEZKEpOPe9EfeEWttS(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_Fz_8_oSTis44XHuynjCUn6,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,
boolean_T ssc_core__8JcQ8Vtuuh_iXzdbML_Yc,boolean_T
ssc_core_kJqxcBm86v_efifQJtjyb5,int16_T ssc_core_FQ7VXQGcxAWQhi22ldg8Cy){
ssc_core_Fz_8_oSTis44XHuynjCUn6->ssc_core_FLsL2KzVDm86biVm9CPZ2O(
ssc_core_Fz_8_oSTis44XHuynjCUn6,mc_kDRphcAfRHSbf1ZLKEDW9k,
ssc_core__8JcQ8Vtuuh_iXzdbML_Yc,ssc_core_kJqxcBm86v_efifQJtjyb5,
ssc_core_FQ7VXQGcxAWQhi22ldg8Cy);}PMF_DEPLOY_STATIC void
ssc_core_kzRJ3IB_hrGhWPGYiinFgu(ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*
ssc_core_Fz_8_oSTis44XHuynjCUn6,size_t ssc_core__lEVjiBdO94nWPd1DTZuBt){
ssc_core_Fz_8_oSTis44XHuynjCUn6->mPushInfo(ssc_core_Fz_8_oSTis44XHuynjCUn6,
ssc_core__lEVjiBdO94nWPd1DTZuBt);}
#include "ne_std.h"
typedef struct ssc_core_V3scVTYpjYthiPB7SQIxc_ ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8
;typedef struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm ssc_core__SHoBDzmLMOwaLvvD5hSet
;struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm{boolean_T(*
ssc_core_FBsF3SW3Cyp_j5Pu5wPhdl)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;void(*mc_VrNsQKHIiLOFaL3PHRFxZL)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G);void(*mDestroy)(
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core_FeUzPe0YQn4rca7KjD_v4G);
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*mData;};ssc_core__SHoBDzmLMOwaLvvD5hSet*
ssc_core_VlRDyoY8Z4C2Vy6qnfIfjk(NeSystemInputSizes sizes,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,boolean_T ssc_core__5hVjWGkxohgVTAjSVMW3a,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct
ssc_core_k5L61vkRxRKWWqL0W_umgn ssc_core_FUrzptc0wiWfjXU2e3QfOz;struct
ssc_core_k5L61vkRxRKWWqL0W_umgn{boolean_T ssc_core__LCAJ2JayW0r_qEhA8Hiyd;
real_T ssc_core_k7TZ2UlpSuxfZTHVp9D7p3;};ssc_core_FUrzptc0wiWfjXU2e3QfOz const
*ssc_core_kK894Ak9rbKpaaeUTYrSok(void);void ssc_core_kmRcS5q4_lWXhqHF3yAv3O(
ssc_core_FUrzptc0wiWfjXU2e3QfOz const*ssc_core_kv7GnpbgsfSGjTKLxq5SvA);struct
ssc_core_kesYKdRukKtCYLfoQ0YRJ5{struct{struct{struct{char const*
ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*ssc_core__qEXoys3NqhTc5aGZjoM0i;}
ssc_core_kvZlvqC1JqdoYahhfIqkPq;struct{char const*
ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*ssc_core__qEXoys3NqhTc5aGZjoM0i;}
ssc_core__CmZebP7mNptWDMef1TTIl;}ssc_core_V01A11djsUSPhydgdGoEM8;struct{struct
{char const*ssc_core__EXYd0BpsApngXjCLU66Qq;char const*
ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;}ssc_core_F0zPq17YGsWWY9f__3XLFE;struct{char
const*ssc_core__EXYd0BpsApngXjCLU66Qq;char const*
ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;char const*ssc_core_V_r1xwjDx7lwguJ2YCpUai;}
ssc_core__YmatZ07z0_k_ulppGYT3M;}ssc_core_kCihPvTAZxpx_H5ihyr_kC;struct{char
const*ssc_core_kpMuDXM8W__FWaXECbGWgq;char const*
ssc_core_kZL4P0QovRSWiqHRt1WIC6;}ssc_core_VWYj_r5wXZ0gbi3aGkkirz;}
ssc_core_VNb3dQocUud1ieYKQWZKSY;struct{struct{char const*
ssc_core_V63i95p2LLdg_5IdB06gkx;char const*ssc_core_VxPQol5LzB_eaDZ9jfsvgc;}
ssc_core__aT2sx0pgFCPiP8nk_pRK_;}ssc_core_VJgtn_cGgzdoceadTmm3t6;struct{struct
{char const*ssc_core_kTdqak9AqCGKcHj5IXmfZe;char const*
ssc_core__ZW8YII_QJ4wiHEnAMUOgB;char const*ssc_core__MNSKfpi3jteauByrrb2q7;}
ssc_core_kdx8eT3TLLtTjLxaVSammf;}ssc_core_Vb8i6ka6Ps0zj9AYvH4Qsj;};extern
struct ssc_core_kesYKdRukKtCYLfoQ0YRJ5 ssc_core_VrvQtlpclEKjVTpcoDIr6q;typedef
int(*ssc_core_Vnw7iL6EY50i_9_d5lwF1E)(double*,size_t,size_t,size_t,size_t*,
size_t*,size_t*,size_t*,double*);static int ssc_core__klbbhBKv8Ot_PEUst6Euh(
double*A,size_t k,size_t ssc_core_VND14ejye_86WmozrNaSGJ,size_t
ssc_core_VeBcpk3j08STguq_GqXn7U,size_t*ssc_core_VYCTO0OcYBG6WayE_bxS2Q,size_t*
ssc_core__rgsdHlFSL4HWiqv_yjfwN,size_t*mc_VlnhKi82gfCLgumIqeduOq,size_t*
ssc_core__Va0dX9V1VtPjiO2AwCaVW,double*ssc_core__OF2VP1uAJSieTAQNOVsV7){size_t
ssc_core__hwvPt2osBlpeHoaeAfgp9=ssc_core_VND14ejye_86WmozrNaSGJ;size_t
ssc_core_FNgDKS0RD9tSdPQ6uT4fWE=ssc_core_VeBcpk3j08STguq_GqXn7U;double
ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b=0.0;size_t i;size_t j;for(i=k;i<
ssc_core_VND14ejye_86WmozrNaSGJ;++i){for(j=k;j<ssc_core_VeBcpk3j08STguq_GqXn7U
;++j){double const ssc_core__fkcTxi8dDlyaPtMtxgicL=fabs(A[
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+ssc_core__rgsdHlFSL4HWiqv_yjfwN[j]*
ssc_core_VND14ejye_86WmozrNaSGJ]);if(ssc_core__fkcTxi8dDlyaPtMtxgicL>
ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b){ssc_core__hwvPt2osBlpeHoaeAfgp9=i;
ssc_core_FNgDKS0RD9tSdPQ6uT4fWE=j;ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b=
ssc_core__fkcTxi8dDlyaPtMtxgicL;}}}if((ssc_core__hwvPt2osBlpeHoaeAfgp9==
ssc_core_VND14ejye_86WmozrNaSGJ)||(ssc_core_FNgDKS0RD9tSdPQ6uT4fWE==
ssc_core_VeBcpk3j08STguq_GqXn7U)){return-1;}*mc_VlnhKi82gfCLgumIqeduOq=
ssc_core__hwvPt2osBlpeHoaeAfgp9;*ssc_core__Va0dX9V1VtPjiO2AwCaVW=
ssc_core_FNgDKS0RD9tSdPQ6uT4fWE;*ssc_core__OF2VP1uAJSieTAQNOVsV7=
ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b;return 0;}static int
ssc_core_VMBPqg7Im3lfiiXR0d98gi(double*A,size_t k,size_t
ssc_core_VND14ejye_86WmozrNaSGJ,size_t ssc_core_VeBcpk3j08STguq_GqXn7U,size_t*
ssc_core_VYCTO0OcYBG6WayE_bxS2Q,size_t*ssc_core__rgsdHlFSL4HWiqv_yjfwN,size_t*
mc_VlnhKi82gfCLgumIqeduOq,size_t*ssc_core__Va0dX9V1VtPjiO2AwCaVW,double*
ssc_core__OF2VP1uAJSieTAQNOVsV7){size_t ssc_core__hwvPt2osBlpeHoaeAfgp9=
ssc_core_VND14ejye_86WmozrNaSGJ;size_t ssc_core_FNgDKS0RD9tSdPQ6uT4fWE=
ssc_core_VeBcpk3j08STguq_GqXn7U;double ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b=0.0;
size_t i;size_t j;for(i=k;i<ssc_core_VND14ejye_86WmozrNaSGJ;++i){double const
ssc_core_kiPRze5K9GKPgDS_XueXeg=fabs(A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]*ssc_core_VND14ejye_86WmozrNaSGJ]);if(
ssc_core_kiPRze5K9GKPgDS_XueXeg>ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b){
ssc_core__hwvPt2osBlpeHoaeAfgp9=i;ssc_core_FNgDKS0RD9tSdPQ6uT4fWE=k;
ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b=ssc_core_kiPRze5K9GKPgDS_XueXeg;}}for(j=k;j<
ssc_core_VeBcpk3j08STguq_GqXn7U;++j){double const
ssc_core_kN1rL1sloqWVbqQCzW_QLA=fabs(A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[j]*ssc_core_VND14ejye_86WmozrNaSGJ]);if(
ssc_core_kN1rL1sloqWVbqQCzW_QLA>ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b){
ssc_core__hwvPt2osBlpeHoaeAfgp9=k;ssc_core_FNgDKS0RD9tSdPQ6uT4fWE=j;
ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b=ssc_core_kN1rL1sloqWVbqQCzW_QLA;}}if((
ssc_core__hwvPt2osBlpeHoaeAfgp9==ssc_core_VND14ejye_86WmozrNaSGJ)||(
ssc_core_FNgDKS0RD9tSdPQ6uT4fWE==ssc_core_VeBcpk3j08STguq_GqXn7U)){return-1;}*
mc_VlnhKi82gfCLgumIqeduOq=ssc_core__hwvPt2osBlpeHoaeAfgp9;*
ssc_core__Va0dX9V1VtPjiO2AwCaVW=ssc_core_FNgDKS0RD9tSdPQ6uT4fWE;*
ssc_core__OF2VP1uAJSieTAQNOVsV7=ssc_core_Fr1eJsaQ1SdXY5bLPjPQ7b;return 0;}
static int ssc_core_FoJeIw1kkyOPWTqpRBEHH2(ssc_core_Vnw7iL6EY50i_9_d5lwF1E
ssc_core__awPXfPIF6dZVTKxrMvecB,double ssc_core_kAqC_XivnI4FVXW3Q5Ht_f,double*
A,size_t ssc_core_VND14ejye_86WmozrNaSGJ,size_t ssc_core_VeBcpk3j08STguq_GqXn7U
,size_t*ssc_core_VYCTO0OcYBG6WayE_bxS2Q,size_t*ssc_core__rgsdHlFSL4HWiqv_yjfwN
){int ssc_core_k4M7bSEmThKJbirXUDQgS6=0;size_t k;size_t i;size_t j;size_t
mc_VlnhKi82gfCLgumIqeduOq;size_t ssc_core__Va0dX9V1VtPjiO2AwCaVW;double
ssc_core__OF2VP1uAJSieTAQNOVsV7;double ssc_core_k97WT8CIJTOle9SypTHhfj;(void)0
;;for(k=0;k<ssc_core_VND14ejye_86WmozrNaSGJ;++k){
ssc_core_k97WT8CIJTOle9SypTHhfj=A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]*ssc_core_VND14ejye_86WmozrNaSGJ];
ssc_core_k4M7bSEmThKJbirXUDQgS6=ssc_core__awPXfPIF6dZVTKxrMvecB(A,k,
ssc_core_VND14ejye_86WmozrNaSGJ,ssc_core_VeBcpk3j08STguq_GqXn7U,
ssc_core_VYCTO0OcYBG6WayE_bxS2Q,ssc_core__rgsdHlFSL4HWiqv_yjfwN,&
mc_VlnhKi82gfCLgumIqeduOq,&ssc_core__Va0dX9V1VtPjiO2AwCaVW,&
ssc_core__OF2VP1uAJSieTAQNOVsV7);if(ssc_core_k4M7bSEmThKJbirXUDQgS6!=0){return
ssc_core_k4M7bSEmThKJbirXUDQgS6;}if(ssc_core__OF2VP1uAJSieTAQNOVsV7>
ssc_core_kAqC_XivnI4FVXW3Q5Ht_f*fabs(ssc_core_k97WT8CIJTOle9SypTHhfj)){size_t
ssc_core_V5XnIQ0HZCxrbPmX4D3LbT;ssc_core_V5XnIQ0HZCxrbPmX4D3LbT=
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k];ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k]=
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[mc_VlnhKi82gfCLgumIqeduOq];
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[mc_VlnhKi82gfCLgumIqeduOq]=
ssc_core_V5XnIQ0HZCxrbPmX4D3LbT;ssc_core_V5XnIQ0HZCxrbPmX4D3LbT=
ssc_core__rgsdHlFSL4HWiqv_yjfwN[k];ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]=
ssc_core__rgsdHlFSL4HWiqv_yjfwN[ssc_core__Va0dX9V1VtPjiO2AwCaVW];
ssc_core__rgsdHlFSL4HWiqv_yjfwN[ssc_core__Va0dX9V1VtPjiO2AwCaVW]=
ssc_core_V5XnIQ0HZCxrbPmX4D3LbT;ssc_core_k97WT8CIJTOle9SypTHhfj=A[
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k]+ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]*
ssc_core_VND14ejye_86WmozrNaSGJ];}(void)0;;for(i=k+1;i<
ssc_core_VND14ejye_86WmozrNaSGJ;++i){double const
ssc_core_kiPRze5K9GKPgDS_XueXeg=A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]*ssc_core_VND14ejye_86WmozrNaSGJ];if(
ssc_core_kiPRze5K9GKPgDS_XueXeg!=0.0){double const mc_kHfMSiCBJRSoju34wwOKOx=
ssc_core_kiPRze5K9GKPgDS_XueXeg/ssc_core_k97WT8CIJTOle9SypTHhfj;A[
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+ssc_core__rgsdHlFSL4HWiqv_yjfwN[k]*
ssc_core_VND14ejye_86WmozrNaSGJ]=0.0;for(j=k+1;j<
ssc_core_VeBcpk3j08STguq_GqXn7U;++j){double const
ssc_core__fkcTxi8dDlyaPtMtxgicL=A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[j]*ssc_core_VND14ejye_86WmozrNaSGJ];double
const ssc_core_kN1rL1sloqWVbqQCzW_QLA=A[ssc_core_VYCTO0OcYBG6WayE_bxS2Q[k]+
ssc_core__rgsdHlFSL4HWiqv_yjfwN[j]*ssc_core_VND14ejye_86WmozrNaSGJ];A[
ssc_core_VYCTO0OcYBG6WayE_bxS2Q[i]+ssc_core__rgsdHlFSL4HWiqv_yjfwN[j]*
ssc_core_VND14ejye_86WmozrNaSGJ]=ssc_core__fkcTxi8dDlyaPtMtxgicL-
mc_kHfMSiCBJRSoju34wwOKOx*ssc_core_kN1rL1sloqWVbqQCzW_QLA;}}}}return
ssc_core_k4M7bSEmThKJbirXUDQgS6;}typedef struct ssc_core_k4miXYejsztdg96AkXJLM6
ssc_core_k9TWKm2UWsClZaVdViejm2;struct ssc_core_k4miXYejsztdg96AkXJLM6{size_t
ssc_core__BV_jtW7GJSt_iEIcHNo3Q;size_t mNumStates;size_t
ssc_core__HRD3bo_2jCEZ1I9eGjo1i;size_t mCoeffIndex;int32_T*mA;size_t
mJacobIndex;double*mJ;size_t*ssc_core_kZi8n8seMbxAau321Kq9DH;size_t*
ssc_core__Cul_b4NU149fLMIUlmUXa;size_t*ssc_core__jyKnjOECBxhayGXTlX4rr;size_t*
ssc_core_FLmWux70Ky8xcexlLZRpHj;};struct ssc_core_V7Yb3L2rBXxKauSoS4qh7D{
size_t mNumSwitchingStates;ssc_core_k9TWKm2UWsClZaVdViejm2*
ssc_core_VZ5nXAahs8pqYLNQM7m2MP;ssc_core_Vnw7iL6EY50i_9_d5lwF1E
ssc_core_FE2ge1bEeZ_2ZDqM7Z1TNw;double ssc_core_ka00frrUybduhyy6GggbN1;
PmRealVector*mJ;size_t*ssc_core__1VayNZdut_1i9Bnea6mQS;PmRealVector*
mc_VXjHmhUsq2xwV5rMn9UIPa;PmSizeVector*mS;McRealFunction*
ssc_core_VnZz7PwP15O6WPjaS9R3Q0;McRealFunction*ssc_core_kyvoLlA18PpXXmqmiCtuyf
;PmAllocator*ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;};static PmfMessageId
ssc_core_VYrURvaOJ4GLZaszVv8u6c(ssc_core_kKt2emv_zM_Aii1i4Nu04i const*
ssc_core_VJgtn_cGgzdoceadTmm3t6,boolean_T*changed,NeSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k){ssc_core_k0aosL__P0OEg5ySbRV6Mk*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_VJgtn_cGgzdoceadTmm3t6->mData;PmRealVector
const*mc_F6RwpxHXSXp7gDlfFRloPz= &mc_kDRphcAfRHSbf1ZLKEDW9k->mX;PmIntVector
const*ssc_core_kdQwK8qcHgtmZuC1u6r7FU= &mc_kDRphcAfRHSbf1ZLKEDW9k->mA;
PmRealVector const*ssc_core_V08Ht59RhOhOj9R_BMeDYs= &mc_kDRphcAfRHSbf1ZLKEDW9k
->mJ;PmfMessageId id=NULL;size_t i;*changed=false;(*((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VnZz7PwP15O6WPjaS9R3Q0)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
ssc_core_V08Ht59RhOhOj9R_BMeDYs),((mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VnZz7PwP15O6WPjaS9R3Q0)->mc_ko6_hiERTRldgDROOJBQCH));memcpy(
mc__d1alWYexptL_X5HTFhbNK->mJ->mX,ssc_core_V08Ht59RhOhOj9R_BMeDYs->mX,
ssc_core_V08Ht59RhOhOj9R_BMeDYs->mN*sizeof(double));for(i=0;i!=
mc__d1alWYexptL_X5HTFhbNK->mNumSwitchingStates;++i){
ssc_core_k9TWKm2UWsClZaVdViejm2*ssc_core_VSXz_TRM5aW8gHE1oqZL8U= &
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VZ5nXAahs8pqYLNQM7m2MP[i];size_t const
ssc_core_VeBcpk3j08STguq_GqXn7U=ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__BV_jtW7GJSt_iEIcHNo3Q;size_t const ssc_core__3SMUKEqzApti1xrhtRNex=
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mNumStates;size_t const
mc_Fxl4i6XHkE8cY9kYmlJixt=ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__HRD3bo_2jCEZ1I9eGjo1i;size_t j;int ssc_core_k4M7bSEmThKJbirXUDQgS6;
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mA=ssc_core_kdQwK8qcHgtmZuC1u6r7FU->mX+
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mCoeffIndex;for(j=0;j!=
mc_Fxl4i6XHkE8cY9kYmlJixt;++j){ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core_kZi8n8seMbxAau321Kq9DH[j]=j;}for(j=0;j!=
ssc_core_VeBcpk3j08STguq_GqXn7U;++j){ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__Cul_b4NU149fLMIUlmUXa[j]=j;}ssc_core_k4M7bSEmThKJbirXUDQgS6=
ssc_core_FoJeIw1kkyOPWTqpRBEHH2(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FE2ge1bEeZ_2ZDqM7Z1TNw,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_ka00frrUybduhyy6GggbN1,ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mJ,
mc_Fxl4i6XHkE8cY9kYmlJixt,ssc_core_VeBcpk3j08STguq_GqXn7U,
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core_kZi8n8seMbxAau321Kq9DH,
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core__Cul_b4NU149fLMIUlmUXa);if(
ssc_core_k4M7bSEmThKJbirXUDQgS6==0){memset(ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__jyKnjOECBxhayGXTlX4rr,0,ssc_core_VeBcpk3j08STguq_GqXn7U*sizeof(
size_t));for(j=mc_Fxl4i6XHkE8cY9kYmlJixt;j<ssc_core_VeBcpk3j08STguq_GqXn7U;++j
){ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core__jyKnjOECBxhayGXTlX4rr[
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core__Cul_b4NU149fLMIUlmUXa[j]]=1U;}if(
memcmp(ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core__jyKnjOECBxhayGXTlX4rr,
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core_FLmWux70Ky8xcexlLZRpHj,
ssc_core_VeBcpk3j08STguq_GqXn7U*sizeof(size_t))!=0){size_t i=0;size_t j;memset
(ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mA,0,ssc_core__3SMUKEqzApti1xrhtRNex*
ssc_core_VeBcpk3j08STguq_GqXn7U*sizeof(int32_T));for(j=0;j<
ssc_core_VeBcpk3j08STguq_GqXn7U;++j){if(ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__jyKnjOECBxhayGXTlX4rr[j]==1U){ssc_core_VSXz_TRM5aW8gHE1oqZL8U->mA[i+
j*ssc_core__3SMUKEqzApti1xrhtRNex]=1;++i;}}memcpy(
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core_FLmWux70Ky8xcexlLZRpHj,
ssc_core_VSXz_TRM5aW8gHE1oqZL8U->ssc_core__jyKnjOECBxhayGXTlX4rr,
ssc_core_VeBcpk3j08STguq_GqXn7U*sizeof(size_t));*changed=true;}}else{if(
ssc_core_k4M7bSEmThKJbirXUDQgS6== -1){id=ssc_core_VrvQtlpclEKjVTpcoDIr6q.
ssc_core_VJgtn_cGgzdoceadTmm3t6 .ssc_core__aT2sx0pgFCPiP8nk_pRK_.
ssc_core_VxPQol5LzB_eaDZ9jfsvgc;}else{id=ssc_core_VrvQtlpclEKjVTpcoDIr6q.
ssc_core_VJgtn_cGgzdoceadTmm3t6 .ssc_core__aT2sx0pgFCPiP8nk_pRK_.
ssc_core_V63i95p2LLdg_5IdB06gkx;}break;}}if(*changed){(*((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kyvoLlA18PpXXmqmiCtuyf)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
mc__d1alWYexptL_X5HTFhbNK->mc_VXjHmhUsq2xwV5rMn9UIPa),((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kyvoLlA18PpXXmqmiCtuyf)->
mc_ko6_hiERTRldgDROOJBQCH));mc_kAamy8ZxNZSIa9FrfB2mHE(
mc_F6RwpxHXSXp7gDlfFRloPz,mc__d1alWYexptL_X5HTFhbNK->mS,
mc__d1alWYexptL_X5HTFhbNK->mc_VXjHmhUsq2xwV5rMn9UIPa);}return id;}static void
ssc_core_FfWeeZBmfcp_b9gjJnTg9g(ssc_core_kKt2emv_zM_Aii1i4Nu04i const*
ssc_core_VJgtn_cGgzdoceadTmm3t6){ssc_core_k0aosL__P0OEg5ySbRV6Mk*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_VJgtn_cGgzdoceadTmm3t6->mData;size_t i;for(
i=0;i!=mc__d1alWYexptL_X5HTFhbNK->mNumSwitchingStates;++i){
ssc_core_k9TWKm2UWsClZaVdViejm2*ssc_core_VSXz_TRM5aW8gHE1oqZL8U= &
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VZ5nXAahs8pqYLNQM7m2MP[i];size_t const
ssc_core_VeBcpk3j08STguq_GqXn7U=ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core__BV_jtW7GJSt_iEIcHNo3Q;size_t j;for(j=0;j!=
ssc_core_VeBcpk3j08STguq_GqXn7U;++j){ssc_core_VSXz_TRM5aW8gHE1oqZL8U->
ssc_core_FLmWux70Ky8xcexlLZRpHj[j]=ssc_core_VeBcpk3j08STguq_GqXn7U;}}}static
void ssc_core__A_WoR_2h2hNjTFmnkKFbS(ssc_core_kKt2emv_zM_Aii1i4Nu04i*
pm__lqjegyKuwStj56WZLiC_e){ssc_core_k0aosL__P0OEg5ySbRV6Mk*d=
pm__lqjegyKuwStj56WZLiC_e->mData;PmAllocator*a=d->
ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;{void*const ssc_core_kevZJ_Fy4Cd9WyDErs5lCb=(d
->ssc_core_VZ5nXAahs8pqYLNQM7m2MP);PmAllocator*const
ssc_core__88bXLP0p1lnc1mH7kGBo6=(a);if(ssc_core_kevZJ_Fy4Cd9WyDErs5lCb){(
ssc_core__88bXLP0p1lnc1mH7kGBo6)->mFreeFcn(ssc_core__88bXLP0p1lnc1mH7kGBo6,
ssc_core_kevZJ_Fy4Cd9WyDErs5lCb);}};pm_destroy_real_vector(d->mJ,a);
pm_destroy_real_vector(d->mc_VXjHmhUsq2xwV5rMn9UIPa,a);
pm_kWBi8ZqmeopPhmEU9I2aNH(d->mS,a);{void*const ssc_core__j111Igr_iKuYLKF_1dvYl
=(d->ssc_core__1VayNZdut_1i9Bnea6mQS);PmAllocator*const
ssc_core_kijv_4l2ot0bbyhreknlPp=(a);if(ssc_core__j111Igr_iKuYLKF_1dvYl){(
ssc_core_kijv_4l2ot0bbyhreknlPp)->mFreeFcn(ssc_core_kijv_4l2ot0bbyhreknlPp,
ssc_core__j111Igr_iKuYLKF_1dvYl);}};(d->ssc_core_VnZz7PwP15O6WPjaS9R3Q0)->
mDestroy(d->ssc_core_VnZz7PwP15O6WPjaS9R3Q0);(d->
ssc_core_kyvoLlA18PpXXmqmiCtuyf)->mDestroy(d->ssc_core_kyvoLlA18PpXXmqmiCtuyf)
;{void*const ssc_core_FU5fiqU4DfhSf9inTCIYb0=(d);PmAllocator*const
ssc_core_kjXGJ59X6GlwYq8j2lDUYi=(a);if(ssc_core_FU5fiqU4DfhSf9inTCIYb0){(
ssc_core_kjXGJ59X6GlwYq8j2lDUYi)->mFreeFcn(ssc_core_kjXGJ59X6GlwYq8j2lDUYi,
ssc_core_FU5fiqU4DfhSf9inTCIYb0);}};{void*const ssc_core_kieV4hdIsA0BYqYaxunMcG
=(pm__lqjegyKuwStj56WZLiC_e);PmAllocator*const ssc_core_FJ0mr3rxCRpXVH9OwvWyGA
=(a);if(ssc_core_kieV4hdIsA0BYqYaxunMcG){(ssc_core_FJ0mr3rxCRpXVH9OwvWyGA)->
mFreeFcn(ssc_core_FJ0mr3rxCRpXVH9OwvWyGA,ssc_core_kieV4hdIsA0BYqYaxunMcG);}};}
ssc_core_kKt2emv_zM_Aii1i4Nu04i*ssc_core__tHBYx2mzptjcixXUqAXGT(
ssc_core__vkZ3rfXeilTgHxrnS_l_7 const*ssc_core_FJOfgRbEhUGyXLNLRImNAG,
McRealFunction*ssc_core_kPDE4W0_1vdFjmGv1Hd7Up,McRealFunction*
ssc_core_VAvzygWXd_Cf_azHot_63D,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){
ssc_core_kKt2emv_zM_Aii1i4Nu04i*ssc_core_VJgtn_cGgzdoceadTmm3t6;
ssc_core_k0aosL__P0OEg5ySbRV6Mk*mc__d1alWYexptL_X5HTFhbNK;PmRealVector*
ssc_core__vm3OM7apTGKj9igW_mnRp;PmRealVector*ssc_core_FDYqt01oCUt7VmJpXy9spj;
size_t*ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;PmSizeVector*
ssc_core_VbCwLux3tAhjgXAwKlCUzM;ssc_core_k9TWKm2UWsClZaVdViejm2*
ssc_core_VSXz_TRM5aW8gHE1oqZL8U;size_t i;boolean_T const
ssc_core__rcBMCQNLjhQ_LcS_Gff7_=ssc_core_kK894Ak9rbKpaaeUTYrSok()->
ssc_core__LCAJ2JayW0r_qEhA8Hiyd;double const ssc_core_kAqC_XivnI4FVXW3Q5Ht_f=
ssc_core_kK894Ak9rbKpaaeUTYrSok()->ssc_core_k7TZ2UlpSuxfZTHVp9D7p3;size_t
ssc_core_VynOck_LWXSQhHmFuoUkrz=0;size_t ssc_core_VUxwaVOGjuGGaXBoB23_p5=0;
ssc_core_VJgtn_cGgzdoceadTmm3t6=(ssc_core_kKt2emv_zM_Aii1i4Nu04i*)(((
mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(
ssc_core_kKt2emv_zM_Aii1i4Nu04i)),(1))));mc__d1alWYexptL_X5HTFhbNK=(
ssc_core_k0aosL__P0OEg5ySbRV6Mk*)(((mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((
mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(ssc_core_k0aosL__P0OEg5ySbRV6Mk)),(1))));
ssc_core_VSXz_TRM5aW8gHE1oqZL8U=(ssc_core_k9TWKm2UWsClZaVdViejm2*)(((
mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(
ssc_core_k9TWKm2UWsClZaVdViejm2)),(ssc_core_FJOfgRbEhUGyXLNLRImNAG->
mNumSwitchingStates))));mc__d1alWYexptL_X5HTFhbNK->mNumSwitchingStates=
ssc_core_FJOfgRbEhUGyXLNLRImNAG->mNumSwitchingStates;mc__d1alWYexptL_X5HTFhbNK
->ssc_core_VZ5nXAahs8pqYLNQM7m2MP=ssc_core_VSXz_TRM5aW8gHE1oqZL8U;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa=
mc_FZx3iFiX1YW7j5eEojoAPc;for(i=0;i!=ssc_core_FJOfgRbEhUGyXLNLRImNAG->
mNumSwitchingStates;++i){NeSwitchingStatesData const*const
ssc_core_k1w6gB30OohHePkWtWR5Ot= &ssc_core_FJOfgRbEhUGyXLNLRImNAG->
mSwitchingStatesData[i];size_t const mc_Fxl4i6XHkE8cY9kYmlJixt=
ssc_core_k1w6gB30OohHePkWtWR5Ot->mJacobRows;size_t const
ssc_core_VeBcpk3j08STguq_GqXn7U=ssc_core_k1w6gB30OohHePkWtWR5Ot->mJacobCols;
size_t const ssc_core__3SMUKEqzApti1xrhtRNex=ssc_core_k1w6gB30OohHePkWtWR5Ot->
mCoeffRows;ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].ssc_core__BV_jtW7GJSt_iEIcHNo3Q=
ssc_core_VeBcpk3j08STguq_GqXn7U;ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].mNumStates=
ssc_core__3SMUKEqzApti1xrhtRNex;ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].
ssc_core__HRD3bo_2jCEZ1I9eGjo1i=mc_Fxl4i6XHkE8cY9kYmlJixt;
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].mCoeffIndex=ssc_core_k1w6gB30OohHePkWtWR5Ot
->mCoeffIndex;ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].mJacobIndex=
ssc_core_k1w6gB30OohHePkWtWR5Ot->mJacobIndex;ssc_core_VynOck_LWXSQhHmFuoUkrz+=
mc_Fxl4i6XHkE8cY9kYmlJixt*ssc_core_VeBcpk3j08STguq_GqXn7U;
ssc_core_VUxwaVOGjuGGaXBoB23_p5+=mc_Fxl4i6XHkE8cY9kYmlJixt+3*
ssc_core_VeBcpk3j08STguq_GqXn7U;}ssc_core__vm3OM7apTGKj9igW_mnRp=
pm_create_real_vector(ssc_core_FJOfgRbEhUGyXLNLRImNAG->mNumSwitchingEquations,
mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core_FDYqt01oCUt7VmJpXy9spj=
pm_create_real_vector(ssc_core_VynOck_LWXSQhHmFuoUkrz,
mc_FZx3iFiX1YW7j5eEojoAPc);ssc_core_VbCwLux3tAhjgXAwKlCUzM=
pm_FZch3YyGWrOM_PQNdo7b2c(ssc_core_FJOfgRbEhUGyXLNLRImNAG->
mNumSwitchingEquations,mc_FZx3iFiX1YW7j5eEojoAPc);
ssc_core_FNmPzSsUEaCrVHr1mF5Nxp=(size_t*)(((mc_FZx3iFiX1YW7j5eEojoAPc)->
mCallocFcn((mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(size_t)),(
ssc_core_VUxwaVOGjuGGaXBoB23_p5))));mc__d1alWYexptL_X5HTFhbNK->mJ=
ssc_core_FDYqt01oCUt7VmJpXy9spj;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__1VayNZdut_1i9Bnea6mQS=ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;
mc__d1alWYexptL_X5HTFhbNK->mc_VXjHmhUsq2xwV5rMn9UIPa=
ssc_core__vm3OM7apTGKj9igW_mnRp;mc__d1alWYexptL_X5HTFhbNK->mS=
ssc_core_VbCwLux3tAhjgXAwKlCUzM;memcpy(ssc_core_VbCwLux3tAhjgXAwKlCUzM->mX,
ssc_core_FJOfgRbEhUGyXLNLRImNAG->mSwitchingEquationsData,
ssc_core_FJOfgRbEhUGyXLNLRImNAG->mNumSwitchingEquations*sizeof(size_t));for(i=
0;i!=ssc_core_FJOfgRbEhUGyXLNLRImNAG->mNumSwitchingStates;++i){size_t const
ssc_core_VeBcpk3j08STguq_GqXn7U=ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].
ssc_core__BV_jtW7GJSt_iEIcHNo3Q;size_t const mc_Fxl4i6XHkE8cY9kYmlJixt=
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].ssc_core__HRD3bo_2jCEZ1I9eGjo1i;
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].mJ=ssc_core_FDYqt01oCUt7VmJpXy9spj->mX+
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].mJacobIndex;ssc_core_VSXz_TRM5aW8gHE1oqZL8U
[i].ssc_core_kZi8n8seMbxAau321Kq9DH=ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;
ssc_core_FNmPzSsUEaCrVHr1mF5Nxp+=mc_Fxl4i6XHkE8cY9kYmlJixt;
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].ssc_core__Cul_b4NU149fLMIUlmUXa=
ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;ssc_core_FNmPzSsUEaCrVHr1mF5Nxp+=
ssc_core_VeBcpk3j08STguq_GqXn7U;ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].
ssc_core__jyKnjOECBxhayGXTlX4rr=ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;
ssc_core_FNmPzSsUEaCrVHr1mF5Nxp+=ssc_core_VeBcpk3j08STguq_GqXn7U;
ssc_core_VSXz_TRM5aW8gHE1oqZL8U[i].ssc_core_FLmWux70Ky8xcexlLZRpHj=
ssc_core_FNmPzSsUEaCrVHr1mF5Nxp;ssc_core_FNmPzSsUEaCrVHr1mF5Nxp+=
ssc_core_VeBcpk3j08STguq_GqXn7U;}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FE2ge1bEeZ_2ZDqM7Z1TNw=ssc_core__rcBMCQNLjhQ_LcS_Gff7_?
ssc_core__klbbhBKv8Ot_PEUst6Euh:ssc_core_VMBPqg7Im3lfiiXR0d98gi;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_ka00frrUybduhyy6GggbN1=
ssc_core_kAqC_XivnI4FVXW3Q5Ht_f;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VnZz7PwP15O6WPjaS9R3Q0=ssc_core_kPDE4W0_1vdFjmGv1Hd7Up;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kyvoLlA18PpXXmqmiCtuyf=
ssc_core_VAvzygWXd_Cf_azHot_63D;ssc_core_VJgtn_cGgzdoceadTmm3t6->
ssc_core_kKv6Xx1worSoj9CnhS5Dnh=ssc_core_VYrURvaOJ4GLZaszVv8u6c;
ssc_core_VJgtn_cGgzdoceadTmm3t6->mc_k0h0NPxQNyl2XD95RLG6Hy=
ssc_core_FfWeeZBmfcp_b9gjJnTg9g;ssc_core_VJgtn_cGgzdoceadTmm3t6->mDestroy=
ssc_core__A_WoR_2h2hNjTFmnkKFbS;ssc_core_VJgtn_cGgzdoceadTmm3t6->mData=
mc__d1alWYexptL_X5HTFhbNK;return ssc_core_VJgtn_cGgzdoceadTmm3t6;}
