#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "mc_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ssc_dae.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_VYZbxd6QDPKAY5EdNNnxvo ssc_core_FTQiFug__ySeca8XLOZvsP
;typedef struct ssc_core__96yahfzEI_rZTPZ9_F__R ssc_core_FdxXK8OYjaSyde1dks8fo6
;struct ssc_core__96yahfzEI_rZTPZ9_F__R{void(*mc_F8jYh1XJ10K_emvBxS7m6z)(
ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k);void(*mc_VrNsQKHIiLOFaL3PHRFxZL
)(ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z);
NeSystemInputSizes(*ssc_core_k12HeDepc7deXD9LUZ_NTV)(
ssc_core_FdxXK8OYjaSyde1dks8fo6 const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*
mDestroy)(ssc_core_FdxXK8OYjaSyde1dks8fo6*);boolean_T mHasConstraints;
boolean_T ssc_core_FiExqWFTEah9jHJ0SH1HNW;PmSparsityPattern const*
ssc_core_FF_1tT6hvsWRWDPOW_Lf9p;PmRealVector const*
ssc_core_VNr5R_tseV8GZ9MEkaP0iI;PmSparsityPattern const*
ssc_core_F8ct2g4u30Cd_eVBM1fmme;PmRealVector const*
ssc_core_VYZTZNi4zntdY96IiRebWs;PmBoolVector const*
ssc_core_kmBetGuEoz8wi9ZOF3VWFZ;PmBoolVector const*
ssc_core_Vr0_Hh6W3aK_geLt8t_w5s;PmSparsityPattern const*
ssc_core_VroU7Vctp3hnfXBuzbTcMf;PmRealVector const*
ssc_core_VKjPDXGkelWFairK7M4e7w;PmSparsityPattern const*
ssc_core_F_IPhSinY6K8eTISPitBTp;PmRealVector const*
ssc_core_kFjGshRebZdxbPE1qJHCAI;ssc_core_FTQiFug__ySeca8XLOZvsP*mData;};
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_kv3fXx6PfXt7cekeoT00mk
mc_kgKqfPHHGatO_9OUxR4PRK;struct mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;
void(*mc_FapEct1OXaSugDZ6N_u_kA)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH);void(*
mc_FVdv01I3SEC4hD41rxmnRM)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,real_T
mc__d1alWYexptL_X5HTFhbNK);void(*mc_kPHJTxMUjl8Oi1EQSHes2Q)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);void(*
mc__WEKdqi2uo0m_Dm8w8T_ZO)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc__d1alWYexptL_X5HTFhbNK);};typedef struct mc__nZqLQp3m1lFaHyLAzyG2a
mc__39VLhR7TBCGYH016BQq8W;typedef struct mc__UzXDLpnAvdw_eUt0mYuul
mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct mc__sr5lnPbYjO_Wyo_mmPUmd
mc_Fw_IO5LchthA_LoeiSceRf;struct mc__sr5lnPbYjO_Wyo_mmPUmd{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};
#include "ne_std.h"
typedef struct ssc_core_Fd3FGkpCS2lhYThVpSV0kq ssc_core_VRw4xIuayc87h10CIYab_d
;typedef struct ssc_core_k1oWXtPHE_xydLoGE_SLjv ssc_core__cqeoq_N8axBWHaE78_gdI
;struct ssc_core_k1oWXtPHE_xydLoGE_SLjv{mc__3nzW_mY1qOqgXk2FmdyDG const*
ssc_core_VM7BxQGhXaKueLTlYnjv9x;PmBoolVector const*
ssc_core_VMZE4Bri2eO_f1fez5gp7L;PmRealVector const*
ssc_core__KFnMWfvZ7_FjylWw_6f82;PmRealVector const*
ssc_core__YBHEbaNs784duVk_OMx7f;ssc_core_VRw4xIuayc87h10CIYab_d*mPrivateData;
void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_core__cqeoq_N8axBWHaE78_gdI const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_klXC4aNpb9GwZu6_HluAlj)(ssc_core__cqeoq_N8axBWHaE78_gdI const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector const*ssc_core_FBNduJ2xtv0UjTuX5_iN4m,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);NeSystemInputSizes(*mSizes)(
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_kpyeXH2RWcWG_DVSgKEG_O);
mc_F3czdn9EwuxfaaYWgN0vfZ(*ssc_core_kOw3W_1IrxSe_5HOqgvUlK)(
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_kpyeXH2RWcWG_DVSgKEG_O,
mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core_Fy4dLy8_QEOmhuIT5Fg3wh);void(*mDestroy)(
ssc_core__cqeoq_N8axBWHaE78_gdI*);};typedef struct
ssc_core__PWwrOfdEpWRXDbczq38F0 ssc_core__uDVmtdsiy0D_yCTEmgRcK;typedef struct
ssc_core_FYaVeWjobnOncaAFHOiTZt ssc_core__XvzTXJcADdQhPSJjzuq_2;struct
ssc_core_FYaVeWjobnOncaAFHOiTZt{ssc_core__uDVmtdsiy0D_yCTEmgRcK*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(ssc_core__XvzTXJcADdQhPSJjzuq_2 const*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(ssc_core__XvzTXJcADdQhPSJjzuq_2 const*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
ssc_core__XvzTXJcADdQhPSJjzuq_2 const*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
ssc_core__XvzTXJcADdQhPSJjzuq_2 const*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*
mDestroy)(ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);};
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_F7zBQipNH88gfa_9A256_e(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__WuYgVAkb6lGaLEOrHsdum(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__LKVUa50d7OBWPOR9PJtdt(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_kSq7vcYEzBSPh1_HmyvGuS,ssc_sli_FzfaJd8s_hCXWy3yxi1stW,
ssc_sli___mb2h47wN4ihPznc5zDZu,ssc_sli_VQPqsGKP5uGObDJbh_eFMB,
ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,ssc_sli__rEZqtXugN_fa5vYYYzGYc,
ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,
ssc_sli__puwPfKA1_C_XXKoAacuHL,ssc_sli__0DRn7XIvolbdPgJc8imWd,
ssc_sli__GinY4faV6x5fXRGGHiXOx,ssc_sli_k70mjUuFMQSz_irEsv6NXV,
ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,ssc_sli__OWNEM8w1KGFbaOP6K0YSM,
ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,ssc_sli__5Jlt976LTdQhme97vzhLz,
ssc_sli_FE7q2LVg_Cx6geTARRhW19,ssc_sli__cezSCdpHN4lgqD73r5pEK,
ssc_sli_kWziByYnTjSrjiEO0gFijq,ssc_sli_VCODxytNt54LYecqLGV9fH,
ssc_sli_FsuU2v1dzu0zguh8hxcIjr,ssc_sli_kcFJMg4RQe4laPBX1LMdGM,
ssc_sli_FV_e38q0Djt6eynPV7_Ny6,ssc_sli_FQTNkFa6paKoWyb_h7lF4p,
ssc_sli_kHan416AsF0SVX35Jc3ZUl,ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,
ssc_sli__AaIKqtCr_pwYX1HS4ht1q,ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,
ssc_sli_VbUGQovAbg0NXH9ywH5nXC,ssc_sli__szAKcwWzAGWXe6ZxiNqLy,
ssc_sli_FDke0C5lVb4aiu949gwwFS,ssc_sli_knnAZr_MyDhGaqCPi5fnDE,
ssc_sli_k48eOppTiHpzaP3Bk4LY0j,ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,
ssc_sli_VHuz88szqGKgjTt1PdGvzW,ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,
ssc_sli_kTmLAygbBbCecHMi0uMPAy,ssc_sli_FHVxyfshp6KgVaq6SphqIh,
ssc_sli__mVVJdecb3d__PkepHFMpg,ssc_sli_FkVgnEqViixCfumgJMCM_e,
ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,ssc_sli_k_a_p_5ozClahq0TR72sc5,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_Fr8tyhA6bhOu_T5U6JG49B,
ssc_sli_kO7B69a_Lrhhha86IyU_GA,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli_kpGiBTt5RbdhZuvwoqsVtr,ssc_sli_Fh9oEC3tNb41gqXZYE_FUG,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector mOBS_ACT;PmRealVector
mOBS_EXP;PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;
PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector
mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;
PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;
PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector mICR_IM;PmBoolVector mICR_IL
;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;PmRealVector mICR;
PmSparsityPattern mDXICR_P;PmRealVector mDXICR;PmSparsityPattern mDDICR_P;
PmRealVector mDDICR;PmSparsityPattern mICRM_P;PmRealVector mICRM;
PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;PmSparsityPattern mDDICRM_P;
PmRealVector mDDICRM;PmRealVector mEQ_TOL;PmIntVector mDP_L;PmIntVector mDP_I;
PmIntVector mDP_J;PmRealVector mDP_R;PmRealVector mIMIN;PmRealVector mIMAX;
PmRealVector mDIMIN;PmRealVector mDIMAX;PmBoolVector mVDF;PmBoolVector mVMF;
PmBoolVector mVMM;PmBoolVector mSLF;PmBoolVector mLV;PmBoolVector mNLDV;
PmRealVector mLOG;PmRealVector mJACOB;PmRealVector mSTATE;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmRealVector*
ssc_sli_VU_2QwnChmGVgqMm5Sr7Z7;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmRealVector*ssc_sli_Ft6MItjvPuONWT3V3OKBBu;PmSparsityPattern*
ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;PmRealVector*ssc_sli_F_osIpSL94xCdqURiUvIz_;
PmSparsityPattern*ssc_sli_Vd1e_JCWeyptimGJ3TpS_h;};struct
ssc_sli_FwOCwa_vjXx9haWvTfh5mO{ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[
ssc_sli__Udg2iOsHnplYyGCps5u_2];ssc_sli_kQALV9CmL9diceRAXQ_cn_
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t
ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t
ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t
ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t
ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t
ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t
ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t
ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t
ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t
ssc_sli_kRBQlHbYYD4Egm1QxQJNGZ;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;NeAssertData const*mAssertData;size_t mNumAssertRanges;NeRange
const*mAssertRanges;size_t mNumInitialAsserts;NeAssertData const*
mInitialAssertData;size_t mNumInitialAssertRanges;NeRange const*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_V2edm5XULi4bhDK_5PJPZ7*ssc_sli_VjXisdXgW_hWheKa6_ZxQl;
NeDynamicSystemInput*ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeModelParameters const*const mp,
NeSolverParameters const*const ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*
ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli__6gTFXBv2i84fanvoJsVjr)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli__Qs092x10UtZ_eE_eC7Xz0)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};typedef
struct ssc_sli_F_vP0jc6imdggybhDorHBu{NeInitMode ssc_sli_FzYEFclEENWbai7WMvLo2t
[NE_INIT_MODE_NUM];NeInitMode ssc_sli_Fh4Kzu_H_gW1i9HasZBNtT[NE_INIT_MODE_NUM]
;NeInitMode ssc_sli_Vfn_24nd2nOrZyqPq6SPkS[NE_INIT_MODE_NUM];}
ssc_sli_kowpXkg3O1xEVetTVS23aT;ssc_core__cqeoq_N8axBWHaE78_gdI*
ssc_sli_kGWVMal0vixSji9mCld1X6(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,NeDynamicSystemInput const*
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,ssc_core_FdxXK8OYjaSyde1dks8fo6 const*
ssc_sli__NVQQK5kaIW5cuwdj3ICGD,NeCERData const*ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,
size_t ssc_sli__LUTDtJud8K4_PqqE22fA8,size_t ssc_sli_V_ya37s60_SvbX0govvyGN,
double mc_FfDTppU8N_tOWuLK37x_08,PmIntVector*ssc_core__FL_3zWgtZO8bunUoshkt_,
PmIntVector*ssc_core__Wsccr5SV4lneHu1c48wqw,PmIntVector*
ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,boolean_T ssc_sli__p3kKFb4zHxxf9moWUPWZL,
boolean_T ssc_sli___mDmNq4k10bdiwJPbdXVD,size_t ssc_core_F4tlqGoz8dpsjmIIo_HrZB
);ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_sli__Df4nvb2Vh0XjqsebV8GwG(size_t
ssc_sli_kNAdXxObD3dmjy4Cd1xTJZ,size_t ssc_sli__usAOidwpAxfaaBUmyG_Wc,
NeSolverParameters const*ssc_core_kH7c9UGCUNOFXqT6Omambe,
ssc_core__cqeoq_N8axBWHaE78_gdI*ssc_core_FGW_LNPjvUWPjT2uiRMTEf);void
ssc_sli_VAZlN0IkJcOggTBnFt6iC6(PmfMessageId*ssc_sli_k4M7bSEmThKJbirXUDQgS6,
boolean_T ssc_sli_FbXFA8Xx5gGCaLVvOMx5Hu,McLinearAlgebraFactory const*
ssc_sli_FXGCQ_kYY_poWPf4tMmp3E,ssc_core__cqeoq_N8axBWHaE78_gdI*
ssc_sli__PBbET7yf_tSbyUIdDNzkr,NeDynamicSystemInput*
ssc_sli_k9R1mrW343CNi5YS7y0tBD);PmIntVector*ssc_sli__sGkwL9nHl8ceLVO9ChQMM(
NeVariableData const*ssc_core_Vng7nXLBKc4WginpFwCvE1,size_t
ssc_core_VMKB5bhU7slcjmqJOJScaf,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "pm_std.h"
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef struct mc_VJ95jMweiZWSVLsSPpLjbI mc__w8slDeOjOCYX5XtAOAaVQ;struct
McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*mc_ko6_hiERTRldgDROOJBQCH;
mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McRealFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_VqsYk672m3G9YuweR9VjuM mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{
mc_Vfjzfv7SnSWthXl7BAncu7*mc_ko6_hiERTRldgDROOJBQCH;void(*
mc_VAvAkWmhpT_WWme_3E1U91)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector
const*mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_Vfjzfv7SnSWthXl7BAncu7*
mc__d1alWYexptL_X5HTFhbNK);void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(
McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McIntFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_kIf5GUUnTAOChauG3_6hhe
mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag{mc_k3jb_ssG91tZa9bwLjlWEj
*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*mc_kjWUPQN_Ui4d_enzFJIsF_;
void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,
PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_k3jb_ssG91tZa9bwLjlWEj*
mc__d1alWYexptL_X5HTFhbNK);void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(
McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(
McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};
#include "mc_std.h"
McLinearAlgebraFactory const*mc_get_csparse_rect_la(void);
#include "mc_std.h"
McLinearAlgebraFactory const*mc_V8hcGoGUqVCbYm6_XzatbE(void);
mc_VLJsdw7KrQK_jqGzFmjnuT*mc__PhB7k0aq_Gde1cr0yF0Mc(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FlXY_094_dtxdqxSsR6BQE,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_VLJsdw7KrQK_jqGzFmjnuT*mc_kwP2VKNJqIxYePRpmXmFiZ(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FlXY_094_dtxdqxSsR6BQE,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__0IlPKOEsWprdXBQNHyYFL(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc_FN7xLc4h1wtoW9h_uAsJ11,PmRealVector const*mc_FgkSoAqE75lsVqCT0s070P,
PmRealVector const*mc_kH3bO_YJW98YWa3J39Vj1I);
#include "mc_std.h"
#include "mc_std_fwd.h"
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__XkRYQ9TVkCscmjB33oVx5(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,McLinearAlgebraFactory const*
mc_Fiqi8a6cvxOLX1oR_MTbxh,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_F_FkJXxKCcG0fTwCI3XAqt,boolean_T mc_kw6NOvmP0mtTgTawDfvetp,boolean_T
mc_FDZq9eTGbfpXb97L46FmHM,int mc_VxCDFadJbxxYXXYcTgCg8q,real_T
mc_FudFwNllWjdidLu5FKlWqd,real_T mc_Fk38a0_1AB8q_HD9kGLbGx);
mc_kKrwrwNLgB_NYDY0UUZRVA*mc__3QXiu7ZX9pkeexY6PSlvR(PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY,McLinearAlgebraFactory const*
mc_Fiqi8a6cvxOLX1oR_MTbxh,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_F_FkJXxKCcG0fTwCI3XAqt,size_t mc_V0jiAH2gCJ_zYedoHqBU86,boolean_T
mc_kw6NOvmP0mtTgTawDfvetp,boolean_T mc_FDZq9eTGbfpXb97L46FmHM,int
mc_VxCDFadJbxxYXXYcTgCg8q,real_T mc_FudFwNllWjdidLu5FKlWqd,real_T
mc_Fk38a0_1AB8q_HD9kGLbGx);mc_kKrwrwNLgB_NYDY0UUZRVA*mc_FrttlftKZApYZPlsTFuMrS
(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,McLinearAlgebraFactory const*
mc_Fiqi8a6cvxOLX1oR_MTbxh,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_F_FkJXxKCcG0fTwCI3XAqt,size_t mc_VNsIi0F3TL_aeqk8IaSBnl,boolean_T
mc_kw6NOvmP0mtTgTawDfvetp,boolean_T mc_FDZq9eTGbfpXb97L46FmHM,int
mc_VxCDFadJbxxYXXYcTgCg8q,real_T mc_FudFwNllWjdidLu5FKlWqd,real_T
mc_Fk38a0_1AB8q_HD9kGLbGx);mc_kKrwrwNLgB_NYDY0UUZRVA*mc_Vla0Xo0KtCOgj9nUAxBHKz
(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,McLinearAlgebraFactory const*
mc_Fiqi8a6cvxOLX1oR_MTbxh,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_F_FkJXxKCcG0fTwCI3XAqt,boolean_T mc_FDZq9eTGbfpXb97L46FmHM,int
mc_VxCDFadJbxxYXXYcTgCg8q,real_T mc_FudFwNllWjdidLu5FKlWqd,real_T
mc_Fk38a0_1AB8q_HD9kGLbGx,IterationsLogCore*mc_FBc2dbX9MXKAd5WCw_3i1l);void
mc_kkqzb7EMLYWrdyRinsR_5h(char const*name,McMatrixFunction const*
mc_Fe6copTTRcKEayCm87ABO_);
#include "pm_inline.h"
#include "pm_std.h"
typedef struct pm_V1heuUPdFYSBhXSTZrzev1{size_t mNumRow;size_t mNumCol;real_T*
mX;}pm_FMSUHHOOKD8acuFWLEq4lL;pm_FMSUHHOOKD8acuFWLEq4lL*
pm__IzxUodah3x2_u_ENKAuGk(size_t pm__6bYkkT4Shd0e1DZPlpqqb,size_t
pm__g5DiU2QzFtUiL4XoU6SMs,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_FMSUHHOOKD8acuFWLEq4lL*pm__vffvPR7IsS2XyyCPqmNPs(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm__sjTRWOMR4WzZisVeB2fYm,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
pm__uc9LGWqLf03gLt6Sr9mtw(pm_FMSUHHOOKD8acuFWLEq4lL*pm_k5aqR5haGY_ZXuGDU2ua60,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VuZ05R76dw4R_5mH59xUl3(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60);size_t
pm_kXhhlZLW3c8yiTFYZWcurB(pm_FMSUHHOOKD8acuFWLEq4lL const*
pm_k5aqR5haGY_ZXuGDU2ua60);PMF_DEPLOY_STATIC real_T pm_VWoHHtf6OqO6YXA_khGhQm(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t
pm_kplAJmOlA30feiNcOzi7oj,size_t pm_Fr_bHKkQKFWbfi50VWd5Pw){return
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow];}
PMF_DEPLOY_STATIC void pm_kzEZvMeJLvOmgX1qMXsT0P(pm_FMSUHHOOKD8acuFWLEq4lL
const*pm_k5aqR5haGY_ZXuGDU2ua60,size_t pm_kplAJmOlA30feiNcOzi7oj,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,real_T pm_kpzAtHMD4_WnheH0UiioSE){
pm_k5aqR5haGY_ZXuGDU2ua60->mX[pm_kplAJmOlA30feiNcOzi7oj+
pm_Fr_bHKkQKFWbfi50VWd5Pw*pm_k5aqR5haGY_ZXuGDU2ua60->mNumRow]=
pm_kpzAtHMD4_WnheH0UiioSE;}void pm_kqNP_VNVXgWGcLsAqt8n_A(
pm_FMSUHHOOKD8acuFWLEq4lL const*pm_kUO9H2UqXf8k_y6THPribZ,PmRealVector const*
pm_V9BoL4F3KMGcYqNc2RhxW_,PmSparsityPattern const*pm_FbpiqbN30g8sY9B6YI6RUP);
void pm_kRraI4tqfotp_aUXOIifb6(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,
pm_FMSUHHOOKD8acuFWLEq4lL const*src);boolean_T pm__DD6QRkN3jGod5UZotcfi8(
pm_FMSUHHOOKD8acuFWLEq4lL const*dst,pm_FMSUHHOOKD8acuFWLEq4lL const*src);
boolean_T pm__Wj7kGLfa8_wfmNCNFVchb(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);void
pm_VL4rp2NEaF8Tcu2gE6TeeU(pm_FMSUHHOOKD8acuFWLEq4lL const*dst,size_t
pm_kFiZgJyKzlhBjiAGyCdzxA,pm_FMSUHHOOKD8acuFWLEq4lL const*src,size_t
pm_VLyT3I17Hm8phLoGoAFHeg,size_t pm__dZ3R3yisKSMd19Osaf1CO);
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
mc__QFp_Gwyen4pg5YWQYpO3H(char const*mc__U8NYtiFyNpCjuJN65HCEo,PmRealVector
const*mc__LA_p_vKNdOf_an832S3i6,PmSparsityPattern const*
mc_FEnmBOZ5cfxL_y4SmwvqMI);void mc___0fsWZwiwCeiHr99h_pdS(char const*
mc__U8NYtiFyNpCjuJN65HCEo,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_kPF7K9YwQrlqYyhOzVDc9F);void mc_VVlY03tEyt8Te1_JAhPeqb(char const*
mc__U8NYtiFyNpCjuJN65HCEo,pm_FMSUHHOOKD8acuFWLEq4lL const*
pm_k5aqR5haGY_ZXuGDU2ua60);void mc_F_aDZE5jsQtShDKMpxPeT4(char const*
mc__U8NYtiFyNpCjuJN65HCEo,PmRealVector const*mc_kQcHGEyhefpmWPPKUJsLBB);void
mc_VrrTkw_etgSPcyaUfEsd2F(char const*mc__U8NYtiFyNpCjuJN65HCEo,PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd);void mc__OI_HwmeBECxi15PsgBd55(char const*
mc__U8NYtiFyNpCjuJN65HCEo,PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH);void
mc_VL29uTrWwttHayl9VA84sd(char const*mc__U8NYtiFyNpCjuJN65HCEo,double value);
#include "mc_std.h"
#include "ne_std_fwd.h"
#include "ne_std_fwd.h"
#include "ssc_dae_fwd.h"
typedef struct ssc_core_kn2fkwOG390ucqMrkmBlTh ssc_core__vkZ3rfXeilTgHxrnS_l_7
;typedef enum ssc_core__SA3uQv5q1Gdiqt9NZ8nUr{ssc_core_VAvrS3sgX38dW1TK_6kaj_,
ssc_core_FWJtCOkwvdtfhHBcuZfkso,ssc_core_kLvA7xejjr_QgPtJEt_TMj,
ssc_core_kfPcirvViAlFXDztrNfx1g,ssc_core_k6E5_LFEFh_UXeAVbM3A2m}
ssc_core__wvqa1NsiQxtcyBzy2mKio;ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_F_KwLJ0mWNOFhTXpD8BCKG(NeSolverParameters const*
ssc_core_kH7c9UGCUNOFXqT6Omambe,ssc_core__cqeoq_N8axBWHaE78_gdI const*
ssc_core_FGW_LNPjvUWPjT2uiRMTEf,boolean_T ssc_core__6gTHc63VIWQbeDvSHksxF,
size_t ssc_core_kbGnKCSxws0fYXvQUcV8T8,size_t ssc_core_Fe_BSDjMNWx2_DMFC2qefm,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core__xfZz87_uW_IdyGFE8P6lI(NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,ssc_core__cqeoq_N8axBWHaE78_gdI const*
ssc_core_k_piHYKSpOtmbLTg9Ol1J5,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,ssc_core__wvqa1NsiQxtcyBzy2mKio
ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_VVWIJMeUM_pjdTaeXm2JCd(
NeSolverParameters const*ssc_core_F9hWo1tj7uSuViXynXXv5y,
ssc_core__cqeoq_N8axBWHaE78_gdI const*ssc_core_k_piHYKSpOtmbLTg9Ol1J5,
McLinearAlgebraFactory const*ssc_core__cs_l0pvGGWCXDgz1TCAlt,
ssc_core__wvqa1NsiQxtcyBzy2mKio ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_F_SwKOBJ20t_aDtxzgaxGL(NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,ssc_core__cqeoq_N8axBWHaE78_gdI const*
ssc_core_k_piHYKSpOtmbLTg9Ol1J5,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__tRxnE45q2p8WuXITqJAv7(
NeSolverParameters const*ssc_core_F9hWo1tj7uSuViXynXXv5y,
ssc_core__cqeoq_N8axBWHaE78_gdI const*ssc_core_k_piHYKSpOtmbLTg9Ol1J5,
McLinearAlgebraFactory const*ssc_core__cs_l0pvGGWCXDgz1TCAlt,
ssc_core__wvqa1NsiQxtcyBzy2mKio ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_FweIktsohBSygP_GuPNZZA(NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,ssc_core__cqeoq_N8axBWHaE78_gdI const*
ssc_core_k_piHYKSpOtmbLTg9Ol1J5,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,ssc_core__wvqa1NsiQxtcyBzy2mKio
ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_VKuD3ejyLmxDeybdRf7YG2(
NeSolverParameters const*ssc_core_F9hWo1tj7uSuViXynXXv5y,
ssc_core__cqeoq_N8axBWHaE78_gdI const*ssc_core_k_piHYKSpOtmbLTg9Ol1J5,
McLinearAlgebraFactory const*ssc_core__cs_l0pvGGWCXDgz1TCAlt,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core__XvzTXJcADdQhPSJjzuq_2*
ssc_core_k68olxaDTeCBZT_KDjZ8UG(ssc_core__cqeoq_N8axBWHaE78_gdI const*
ssc_core_k_piHYKSpOtmbLTg9Ol1J5,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_kOvos_YnH5dfhLgsDkxTkD(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,ssc_core__wvqa1NsiQxtcyBzy2mKio
ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_FEsLMHg4gLl5aHqHyO5Yjj(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,ssc_core__wvqa1NsiQxtcyBzy2mKio
ssc_core__E5jcSPd8u_9XPAwf_qv1q,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_kZEYHYrpTc4wgLcRc14EqO(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_FOUg25i4dcxy_9VmyW9Kq5(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,size_t mc_kF77yGs8Y4pbZunORy8X8l,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_core_kgJB4xOjNwKfgPnpfPFKha(NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_V0jiAH2gCJ_zYedoHqBU86,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core__irO8ZXa8e8ZYL4OfAV2_y(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*
ssc_core__cs_l0pvGGWCXDgz1TCAlt,size_t mc_kF77yGs8Y4pbZunORy8X8l,size_t
mc_VNsIi0F3TL_aeqk8IaSBnl,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_VS8nVrgnc5SMgqTmyJNjsZ(NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y,McLinearAlgebraFactory const*la,
ssc_core__wvqa1NsiQxtcyBzy2mKio ssc_core__E5jcSPd8u_9XPAwf_qv1q,boolean_T
ssc_core_FQGARrqpMOxJcPEe9_81zY,size_t mc_kF77yGs8Y4pbZunORy8X8l,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);struct ssc_sli_kesYKdRukKtCYLfoQ0YRJ5{struct{char
const*ssc_sli_V7qkys9O80ShjaUIHbAAei;}ssc_sli_kPcTn2ohlNOm_1o8g8PPHq;struct{
char const*ssc_sli_VzaQ5Qbex9hMb9_Q_2EG0u;char const*
ssc_sli_kkppsM8Zi9pPiuuFXziY02;char const*ssc_sli__zJUBcxUbYh8cXXGBoVSdx;char
const*ssc_sli_VK6W_CYqut_9duBNpo_NW_;char const*ssc_sli_k_RtH7x8yop2f12RH7hXi2
;char const*ssc_sli_VJ5Ejyvd5AOng9VcQKGenn;char const*
ssc_sli_F8vzSvsWvJt4Y9mcFrhG03;char const*ssc_sli_FF81li8wPV__iL8OOfuhwB;char
const*ssc_sli_VK_ssLxeZB8jYuWvMbihTn;char const*ssc_sli_V6K3EGDXGI4VXmGfne1n56
;char const*ssc_sli__c_9G8hkI0SwXHvNjdIDoT;char const*
ssc_sli__Bh8L4iqdX0_gLkWHYCQN7;char const*ssc_sli_kdWyvurcxiWehyP0izpTrD;char
const*ssc_sli___bbo2W2ZdSPb5Kw22wVfO;}ssc_sli_FJynBFsFIwxriaPMzBML7u;};extern
struct ssc_sli_kesYKdRukKtCYLfoQ0YRJ5 ssc_sli_Vacz9FHeIdKsdLygkEbC_A;typedef
int32_T(*ssc_sli_FiGpvUYYF3_2gqRDeUS37U)(const void*,const PmRealVector*,const
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*);typedef int32_T(*
ssc_sli_kZhcJl5nKU0_g9IRjs_BoU)(void const*,PmRealVector const*,
PmSparsityPattern*,ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*);McRealFunction*
ssc_sli_FfOhPkGpecpCb171mvRXie(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_sli_FiGpvUYYF3_2gqRDeUS37U const
ssc_sli_FHYCSZTG0vl9b9VGL0KGKq,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_Fcb76GJfIO83g1S6lfaicv(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*dae,ssc_sli_kZhcJl5nKU0_g9IRjs_BoU const ssc_sli_V90Y6s0k0G4HWytbHubrHy,
size_t ssc_sli_kNgcOktCtQxdYedrGvFn5i,size_t pm_FW8nEXbTFjdJhTIKepsgFT,size_t
pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_kitr6RhcJnOOfPPehhVy_k(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_VAE5DdVFdRGTV9fAs2IqDk(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli__NEUFEqHHF_qiPSUslCI5p(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
McMatrixFunction*ssc_sli_V2RVycuO3XWzgmSrJNXGsU(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*dae,ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_core_V_DRESe0gNtOfHGOtCHo2g,
PmSparsityPattern const*ssc_sli_FMIqOpRQtFtLg9cdvAIg6W,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);PmSparsityPattern*ssc_sli_V2_ErJUMF9KnWmpEYOxqOS(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY
);McRealFunction*ssc_sli_kRhdbfXAHi_8havz7KIYoj(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McRealFunction*ssc_sli_FGH9xESnQESJZ5rrZGPWdT(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McIntFunction*ssc_sli_kZrc6L3r4_xaX1bSkV57Yd(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli__yJMA3iYg0OIYazayPoQxR,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_sli__HUN_nc5YqSrXH2UOcQvGY,ssc_sli__XG4dW9jg8K5aqSVlFCEPx
ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_FNYHSvltK9CtZu3Uutc_pv(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*dae,ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_sli__HUN_nc5YqSrXH2UOcQvGY,
ssc_sli__XG4dW9jg8K5aqSVlFCEPx ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);NeDynamicSystemInput ssc_sli__W_AnWQ747WB_a7wEezy5_
(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*dae,NeSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "ne_std.h"
ssc_core__cqeoq_N8axBWHaE78_gdI*ssc_sli_kef3mYiPeV4Khq48Vn0Hji(PmIntVector*
ssc_core__FL_3zWgtZO8bunUoshkt_,PmRealVector*ssc_core_VOWKumMlbtW4VXce4H_wn2,
PmIntVector*ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,PmRealVector*
ssc_core_koKjwdMe5Vdteq6adeee9v,McIntFunction*mc_V45upKVqFMGjWmb_LkY2NN,
McRealFunction*mc_Fe6copTTRcKEayCm87ABO_,McMatrixFunction*
ssc_core_VB53fXegNkCQcXjkCLRtVG,McMatrixFunction*
ssc_core_kRLzd2SzrBl_jTgvf56_z4,PmBoolVector*ssc_core__rSkuJjxftlwduYiuUd9rW,
McMatrixFunction*mc_VLHhnPUiNQpve5VIL9P3O9,McMatrixFunction*
ssc_core_Vjf_IpltRHCfhPwQq3C_IY,McMatrixFunction*
ssc_core_VYgEVLOTSaxPVTUp295uAH,boolean_T ssc_core_kqY6_4RKFYdpf9V29d8AI8,
McRealFunction*ssc_core_FFZbGh27ya8eem_J_hUtAZ,McMatrixFunction*
ssc_core_VriVbeGXVySZhmo4IqByQ6,McMatrixFunction*
ssc_core_khnxU_g3zxlubHIUGDCLIb,boolean_T ssc_core__xtYtzCzfulz_9EMwws7jR,
McRealFunction*ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,McMatrixFunction*
ssc_core_VB5XLoala8W0VPgYyUV04u,McMatrixFunction*
ssc_core_k8xI_4CVG6Kme1FhXXiyE_,PmBoolVector*ssc_core_kSszp6ydq7pbcL7ojlKh1U,
PmIntVector*ssc_core__Wsccr5SV4lneHu1c48wqw,McRealFunction*
ssc_core_kH9J5Bq5WXtuYahcoaktju,PmBoolVector*ssc_core__CNhzpx_HmdVVmev_ZDlJy,
McMatrixFunction*ssc_core_kECuv8qDlA_GeDuBxE4osn,McMatrixFunction*
ssc_core__11LqlhMpopue950Op3gHT,McMatrixFunction*
ssc_core_FQvSyZB5nvWchH_h_XqWV6,McMatrixFunction*
ssc_core__K_4_9VU7wGGgaWB05q4SN,McMatrixFunction*
ssc_core_FGGFID_AEV06Yag1yd_X9c,McRealFunction*ssc_core_kMgeiJyALdWk_qIpaBzpUY
,double mc_FfDTppU8N_tOWuLK37x_08,size_t ssc_core__akQWQ4rjgWrgD7mVPq1Bq,
McRealFunction*mc_FgkSoAqE75lsVqCT0s070P,McRealFunction*
mc_kH3bO_YJW98YWa3J39Vj1I,McRealFunction*ssc_core__AV_js14TdCSVTL47qwXS2,
McRealFunction*ssc_core_kiBL1YkUNVG1VyHm3DftAw);
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "ne_std.h"
ssc_core__cqeoq_N8axBWHaE78_gdI*ssc_sli_VQ7AHOZWjE_ZZuZD9eHpxL(PmIntVector*
ssc_core__FL_3zWgtZO8bunUoshkt_,PmRealVector*ssc_core_VOWKumMlbtW4VXce4H_wn2,
PmIntVector*ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,PmRealVector*
ssc_core_koKjwdMe5Vdteq6adeee9v,McIntFunction*mc_V45upKVqFMGjWmb_LkY2NN,
McRealFunction*mc_Fe6copTTRcKEayCm87ABO_,McMatrixFunction*
ssc_core_VB53fXegNkCQcXjkCLRtVG,McMatrixFunction*
ssc_core_kRLzd2SzrBl_jTgvf56_z4,PmBoolVector*ssc_core__rSkuJjxftlwduYiuUd9rW,
McMatrixFunction*mc_VLHhnPUiNQpve5VIL9P3O9,McMatrixFunction*
ssc_core_Vjf_IpltRHCfhPwQq3C_IY,McMatrixFunction*
ssc_core_VYgEVLOTSaxPVTUp295uAH,boolean_T ssc_core_kqY6_4RKFYdpf9V29d8AI8,
McRealFunction*ssc_core_FFZbGh27ya8eem_J_hUtAZ,McMatrixFunction*
ssc_core_VriVbeGXVySZhmo4IqByQ6,McMatrixFunction*
ssc_core_khnxU_g3zxlubHIUGDCLIb,boolean_T ssc_core__xtYtzCzfulz_9EMwws7jR,
McRealFunction*ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,McMatrixFunction*
ssc_core_VB5XLoala8W0VPgYyUV04u,McMatrixFunction*
ssc_core_k8xI_4CVG6Kme1FhXXiyE_,PmBoolVector*ssc_core_kSszp6ydq7pbcL7ojlKh1U,
PmIntVector*ssc_core__Wsccr5SV4lneHu1c48wqw,McRealFunction*
ssc_core_kH9J5Bq5WXtuYahcoaktju,PmBoolVector*ssc_core__CNhzpx_HmdVVmev_ZDlJy,
McMatrixFunction*ssc_core_kECuv8qDlA_GeDuBxE4osn,McMatrixFunction*
ssc_core__11LqlhMpopue950Op3gHT,McMatrixFunction*
ssc_core_FQvSyZB5nvWchH_h_XqWV6,McMatrixFunction*
ssc_core__K_4_9VU7wGGgaWB05q4SN,McMatrixFunction*
ssc_core_FGGFID_AEV06Yag1yd_X9c,McRealFunction*ssc_core_kMgeiJyALdWk_qIpaBzpUY
,double mc_FfDTppU8N_tOWuLK37x_08,size_t ssc_core__akQWQ4rjgWrgD7mVPq1Bq,
McRealFunction*mc_FgkSoAqE75lsVqCT0s070P,McRealFunction*
mc_kH3bO_YJW98YWa3J39Vj1I,McRealFunction*ssc_core__AV_js14TdCSVTL47qwXS2,
McRealFunction*ssc_core_kiBL1YkUNVG1VyHm3DftAw);McMatrixFunction*
ssc_sli_VvFvQWKlzndA_uICETZCBj(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McRealFunction*ssc_sli__UrK3rytxHCfVXpTq182GL(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli__QonMhVfyKxdg5cfn4U8Jp(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_VpA8MeBTbz4vfeehXz_6ss(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McRealFunction*
ssc_sli_FguaPp8zXiO1VLb8KoL2eG(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli_FO5r0OGVFOdAcPhW2GWnW1(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);McMatrixFunction*ssc_sli_km3ERy3JxHO6_u4Kr1_1mz(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,PmAllocator*);McMatrixFunction*
ssc_sli_V4rVN29HRbWXfyoy1Rm7o9(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,
PmAllocator*);ssc_sli_V2edm5XULi4bhDK_5PJPZ7*ssc_sli_FywFPN2hnBhka5OlyA_ZYy(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*,NeSolverParameters const*,size_t,
boolean_T,ssc_core_FdxXK8OYjaSyde1dks8fo6 const*,PmAllocator*);void
ssc_sli__K_PX_hcHbSBdqT1N1HqJX(ssc_sli_V2edm5XULi4bhDK_5PJPZ7*
ssc_sli_Fwiw7skPygOpXi8qQorrTL);static PmBoolVector*
ssc_sli_kjQNxgQPUXS0VyLovwKvMR(NeDynamicSystemInput const*
ssc_sli_Fi_du5uFlgGne5wvGXKElE,ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,PmAllocator*a,size_t const
ssc_sli_VLHP8aIsJwGVfL5S40M5HW){PmBoolVector*ssc_sli_kU_M8ptY2CpSYDp2zvEcjg=
pm__jbisDMumXdocXANx5LhhY(ssc_sli_VLHP8aIsJwGVfL5S40M5HW,a);
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_kWziByYnTjSrjiEO0gFijq](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli_Fi_du5uFlgGne5wvGXKElE,(
ssc_sli_kF79J1yovOdS_uDIzPgJXv*)ssc_sli_kU_M8ptY2CpSYDp2zvEcjg);return
ssc_sli_kU_M8ptY2CpSYDp2zvEcjg;}static PmBoolVector*
ssc_sli_FwiGZoF7i8OzdiLDqI5_up(size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,
NeCERData const*const ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy){PmAllocator*a=
pm_default_allocator();PmBoolVector*mc_FleGJLV78MSFf5qx1JOm0Z=
pm__jbisDMumXdocXANx5LhhY(ssc_sli__LUTDtJud8K4_PqqE22fA8,a);size_t i;for(i=0;i
<ssc_sli__LUTDtJud8K4_PqqE22fA8;++i){mc_FleGJLV78MSFf5qx1JOm0Z->mX[i]=
ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy[i].mIsLinear;}return mc_FleGJLV78MSFf5qx1JOm0Z;
}static int32_T ssc_sli_F705zccsoEGrjihUxxGqjk(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli_FCwZLBnFKkp2b5_z2A2lil){(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;(void)mc_VgqbsB_3R4GTjLQeEYi1Qc;(void)
ssc_sli_FCwZLBnFKkp2b5_z2A2lil;return mc_FFaaXY_gkbSTcyLBvtfrzS;}static int32_T
ssc_sli_kLeNP2i_LgxPZm3vzWfObU(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,
PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil){size_t const ssc_sli_kVbJiKiJNOGFdqSSJIWgzn=
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[NE_DYNAMIC_SYSTEM_INPUT_ID_X];
PmAllocator*a=pm_default_allocator();PmSparsityPattern*
ssc_sli_kWoHTxtcf2WscinriFq8th=pm_create_sparsity_pattern(0,
ssc_sli_kVbJiKiJNOGFdqSSJIWgzn,ssc_sli_kVbJiKiJNOGFdqSSJIWgzn,a);PmRealVector*
ssc_sli__D3Ty3lBunC0Z5eN__gKcp=pm_create_real_vector(0,a);(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;pm_kTFq3qlgTulWiT6pafkmmT(mc__srK5LmyWw42ZyPnbOWDWJ,
ssc_sli_kWoHTxtcf2WscinriFq8th);pm_rv_equals_rv(mc_VgqbsB_3R4GTjLQeEYi1Qc,
ssc_sli__D3Ty3lBunC0Z5eN__gKcp);pm_VYooJBURCwKrVu6RXzQZ_5(
ssc_sli_kWoHTxtcf2WscinriFq8th,a);pm_destroy_real_vector(
ssc_sli__D3Ty3lBunC0Z5eN__gKcp,a);return mc_FFaaXY_gkbSTcyLBvtfrzS;}static
int32_T ssc_sli__TedvFeHFAhreDSfrI7xV3(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,
PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,PmSparsityPattern*
mc__srK5LmyWw42ZyPnbOWDWJ,ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli_FCwZLBnFKkp2b5_z2A2lil){size_t const ssc_sli_kVbJiKiJNOGFdqSSJIWgzn=
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[NE_DYNAMIC_SYSTEM_INPUT_ID_X];
size_t const ssc_sli_F_KzfNGwrktAVXAEQLJldg=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->
mSizes.mSizes[NE_DYNAMIC_SYSTEM_INPUT_ID_D];PmAllocator*a=pm_default_allocator
();PmSparsityPattern*ssc_sli_kWoHTxtcf2WscinriFq8th=pm_create_sparsity_pattern
(0,ssc_sli_kVbJiKiJNOGFdqSSJIWgzn,ssc_sli_F_KzfNGwrktAVXAEQLJldg,a);
PmRealVector*ssc_sli__D3Ty3lBunC0Z5eN__gKcp=pm_create_real_vector(0,a);(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;pm_kTFq3qlgTulWiT6pafkmmT(mc__srK5LmyWw42ZyPnbOWDWJ,
ssc_sli_kWoHTxtcf2WscinriFq8th);pm_rv_equals_rv(mc_VgqbsB_3R4GTjLQeEYi1Qc,
ssc_sli__D3Ty3lBunC0Z5eN__gKcp);pm_VYooJBURCwKrVu6RXzQZ_5(
ssc_sli_kWoHTxtcf2WscinriFq8th,a);pm_destroy_real_vector(
ssc_sli__D3Ty3lBunC0Z5eN__gKcp,a);return mc_FFaaXY_gkbSTcyLBvtfrzS;}static
PmBoolVector*ssc_sli_kY3UicIqYl_BeT0_RDb6mS(ssc_sli_VmZk8hTl6VheWiwMDRQsyS
const*ssc_sli_FCwZLBnFKkp2b5_z2A2lil,NeDynamicSystemInput const*
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,ssc_core_FdxXK8OYjaSyde1dks8fo6 const*
ssc_sli__NVQQK5kaIW5cuwdj3ICGD,McMatrixFunction*ssc_sli__3m9za6AQ781ci367S8iNU
){PmAllocator*a=pm_default_allocator();ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_kF79J1yovOdS_uDIzPgJXv
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;NeDynamicSystemInput*
ssc_sli_Fi_du5uFlgGne5wvGXKElE=neu_create_dynamic_system_input(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes,a);PmBoolVector*
ssc_core__rSkuJjxftlwduYiuUd9rW=pm__jbisDMumXdocXANx5LhhY(
ssc_sli__3m9za6AQ781ci367S8iNU->mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,a);
PmBoolVector*ssc_sli_FePcjEiDh0t3auUIIUWZTu=pm__jbisDMumXdocXANx5LhhY(
ssc_sli__3m9za6AQ781ci367S8iNU->mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,a);
PmBoolVector const*ssc_sli_k3vOCj_aUAOBjiTl7ZoYud=
ssc_sli__NVQQK5kaIW5cuwdj3ICGD->ssc_core_Vr0_Hh6W3aK_geLt8t_w5s;
mc__pFtu1g17h8ZaaZK4PpTkb(ssc_core__rSkuJjxftlwduYiuUd9rW,
ssc_sli__3m9za6AQ781ci367S8iNU->mc_kjWUPQN_Ui4d_enzFJIsF_);if(
ssc_sli__NVQQK5kaIW5cuwdj3ICGD->ssc_core_FiExqWFTEah9jHJ0SH1HNW){
mc__uq8ZXcr_B_zgDxjibJDSi(ssc_core__rSkuJjxftlwduYiuUd9rW,
ssc_sli_k3vOCj_aUAOBjiTl7ZoYud);}ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mVMF= *
ssc_sli_FePcjEiDh0t3auUIIUWZTu;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
mc__uq8ZXcr_B_zgDxjibJDSi(ssc_core__rSkuJjxftlwduYiuUd9rW,
ssc_sli_FePcjEiDh0t3auUIIUWZTu);mc_kUD9LJQRjT0FayfqpQrhnP(
ssc_core__rSkuJjxftlwduYiuUd9rW);pm_VuaGyqV_9K0Ia9Qgn65rsj(
ssc_sli_FePcjEiDh0t3auUIIUWZTu,a);neu_destroy_dynamic_system_input(
ssc_sli_Fi_du5uFlgGne5wvGXKElE,a);(ssc_sli__3m9za6AQ781ci367S8iNU)->mDestroy((
ssc_sli__3m9za6AQ781ci367S8iNU));return ssc_core__rSkuJjxftlwduYiuUd9rW;}
ssc_core__cqeoq_N8axBWHaE78_gdI*ssc_sli_kGWVMal0vixSji9mCld1X6(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
NeDynamicSystemInput const*ssc_sli__OzP6GQ7QKhuWTGGHKSszk,
ssc_core_FdxXK8OYjaSyde1dks8fo6 const*ssc_sli__NVQQK5kaIW5cuwdj3ICGD,NeCERData
const*ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,size_t ssc_sli__LUTDtJud8K4_PqqE22fA8,
size_t ssc_sli_V_ya37s60_SvbX0govvyGN,double mc_FfDTppU8N_tOWuLK37x_08,
PmIntVector*ssc_core__FL_3zWgtZO8bunUoshkt_,PmIntVector*
ssc_core__Wsccr5SV4lneHu1c48wqw,PmIntVector*ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,
boolean_T ssc_sli__p3kKFb4zHxxf9moWUPWZL,boolean_T
ssc_sli___mDmNq4k10bdiwJPbdXVD,size_t ssc_core_F4tlqGoz8dpsjmIIo_HrZB){
PmAllocator*a=pm_default_allocator();ssc_sli__vLsdRWt9o_uhqT7KXX2wx*
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc=ssc_sli_FCwZLBnFKkp2b5_z2A2lil->
ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;ssc_sli_kF79J1yovOdS_uDIzPgJXv
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM;McRealFunction*mc_Fe6copTTRcKEayCm87ABO_;
McMatrixFunction*ssc_core_VB53fXegNkCQcXjkCLRtVG;McMatrixFunction*
ssc_core_kRLzd2SzrBl_jTgvf56_z4;McMatrixFunction*mc_VLHhnPUiNQpve5VIL9P3O9;
McMatrixFunction*ssc_core_Vjf_IpltRHCfhPwQq3C_IY;McMatrixFunction*
ssc_core_VYgEVLOTSaxPVTUp295uAH;McRealFunction*ssc_core_FFZbGh27ya8eem_J_hUtAZ
;McMatrixFunction*ssc_core_VriVbeGXVySZhmo4IqByQ6;McMatrixFunction*
ssc_core_khnxU_g3zxlubHIUGDCLIb;McIntFunction*mc_V45upKVqFMGjWmb_LkY2NN=
ssc_sli_kZrc6L3r4_xaX1bSkV57Yd(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,a);McRealFunction*
ssc_core_FyZkX4cpKZ8YVH5EKfcqLt=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__z5LXIdNga07WqTouQ7yCi,a);
McMatrixFunction*ssc_core_VB5XLoala8W0VPgYyUV04u=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_FTtfNfzSNBpAWuyfv7HADR,ssc_sli__yONDaHWSO0Y_H0PIYQgl_,a);
McMatrixFunction*ssc_core_k8xI_4CVG6Kme1FhXXiyE_=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_FsuU2v1dzu0zguh8hxcIjr,ssc_sli_VCODxytNt54LYecqLGV9fH,a);
McRealFunction*ssc_core_kH9J5Bq5WXtuYahcoaktju=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_kcFJMg4RQe4laPBX1LMdGM,a);
McMatrixFunction*ssc_core_kECuv8qDlA_GeDuBxE4osn=
ssc_sli_FVCIxD_gjctkdDyaZwHaP7(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_FQTNkFa6paKoWyb_h7lF4p,ssc_sli_FV_e38q0Djt6eynPV7_Ny6,a);
McMatrixFunction*ssc_sli_kMtKewpuyZ_z_9WLYdicfp=ssc_sli_FVCIxD_gjctkdDyaZwHaP7
(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,
ssc_sli_kHan416AsF0SVX35Jc3ZUl,a);McMatrixFunction*
ssc_core_FQvSyZB5nvWchH_h_XqWV6=ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,
ssc_sli__AaIKqtCr_pwYX1HS4ht1q,a);McMatrixFunction*
ssc_core__K_4_9VU7wGGgaWB05q4SN=ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__szAKcwWzAGWXe6ZxiNqLy,
ssc_sli_VbUGQovAbg0NXH9ywH5nXC,a);McMatrixFunction*
ssc_core_FGGFID_AEV06Yag1yd_X9c=ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_knnAZr_MyDhGaqCPi5fnDE,
ssc_sli_FDke0C5lVb4aiu949gwwFS,a);McRealFunction*
ssc_core_kMgeiJyALdWk_qIpaBzpUY=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_k48eOppTiHpzaP3Bk4LY0j,a);
McRealFunction*ssc_sli_Fa35fYhbZA03ZipctuX5h1=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_FHVxyfshp6KgVaq6SphqIh,a);
McRealFunction*ssc_sli__NbjXUeO_bdXjLOXjp08yZ=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__mVVJdecb3d__PkepHFMpg,a);
McRealFunction*ssc_sli_k_htxnzxqplvaX2Tbe_gpF=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_FkVgnEqViixCfumgJMCM_e,a);
McRealFunction*ssc_sli_Fq0LlZmYKHSVYer1pL54Cv=ssc_sli_kRhdbfXAHi_8havz7KIYoj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,a);PmRealVector*
ssc_core_VOWKumMlbtW4VXce4H_wn2=pm_create_real_vector(
ssc_sli__OzP6GQ7QKhuWTGGHKSszk->mX.mN,a);PmRealVector*
ssc_core_koKjwdMe5Vdteq6adeee9v=pm_create_real_vector(
ssc_sli__OzP6GQ7QKhuWTGGHKSszk->mD.mN,a);McMatrixFunction*
ssc_sli__3m9za6AQ781ci367S8iNU=ssc_sli_FVCIxD_gjctkdDyaZwHaP7(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,a);if(!ssc_sli__NVQQK5kaIW5cuwdj3ICGD->
mHasConstraints){mc_Fe6copTTRcKEayCm87ABO_=ssc_sli_FGH9xESnQESJZ5rrZGPWdT(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,a);
ssc_core_VB53fXegNkCQcXjkCLRtVG=ssc_sli_VAE5DdVFdRGTV9fAs2IqDk(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);ssc_core_kRLzd2SzrBl_jTgvf56_z4=
ssc_sli_FNYHSvltK9CtZu3Uutc_pv(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli__5pEFw2qPJC8cL_hguGK9T,ssc_sli__hBbOcyt8q_K_i_O1ylN50,a);if(
ssc_sli___mDmNq4k10bdiwJPbdXVD){mc_VLHhnPUiNQpve5VIL9P3O9=
ssc_sli_kitr6RhcJnOOfPPehhVy_k(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);}else{
mc_VLHhnPUiNQpve5VIL9P3O9=ssc_sli__NEUFEqHHF_qiPSUslCI5p(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);}ssc_core_Vjf_IpltRHCfhPwQq3C_IY=
ssc_sli_V2RVycuO3XWzgmSrJNXGsU(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
mc_VLHhnPUiNQpve5VIL9P3O9->mc_kjWUPQN_Ui4d_enzFJIsF_,a);
ssc_core_VYgEVLOTSaxPVTUp295uAH=ssc_sli_V2RVycuO3XWzgmSrJNXGsU(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,
ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,mc_VLHhnPUiNQpve5VIL9P3O9->
mc_kjWUPQN_Ui4d_enzFJIsF_,a);ssc_core_FFZbGh27ya8eem_J_hUtAZ=
ssc_sli_FfOhPkGpecpCb171mvRXie(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,&
ssc_sli_F705zccsoEGrjihUxxGqjk,a);ssc_core_VriVbeGXVySZhmo4IqByQ6=
ssc_sli_Fcb76GJfIO83g1S6lfaicv(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,&
ssc_sli_kLeNP2i_LgxPZm3vzWfObU,0,ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes
[NE_DYNAMIC_SYSTEM_INPUT_ID_X],ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[
NE_DYNAMIC_SYSTEM_INPUT_ID_X],a);ssc_core_khnxU_g3zxlubHIUGDCLIb=
ssc_sli_Fcb76GJfIO83g1S6lfaicv(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,&
ssc_sli__TedvFeHFAhreDSfrI7xV3,0,ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes
[NE_DYNAMIC_SYSTEM_INPUT_ID_X],ssc_sli_FCwZLBnFKkp2b5_z2A2lil->mSizes.mSizes[
NE_DYNAMIC_SYSTEM_INPUT_ID_D],a);}else{(void)0;mc_Fe6copTTRcKEayCm87ABO_=
ssc_sli_FguaPp8zXiO1VLb8KoL2eG(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);
ssc_core_VB53fXegNkCQcXjkCLRtVG=ssc_sli_V75nrXicnjdi_mzSciOmCo(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);ssc_core_kRLzd2SzrBl_jTgvf56_z4=
ssc_sli_FO5r0OGVFOdAcPhW2GWnW1(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);
mc_VLHhnPUiNQpve5VIL9P3O9=ssc_sli_VvFvQWKlzndA_uICETZCBj(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);ssc_core_Vjf_IpltRHCfhPwQq3C_IY=
ssc_sli_km3ERy3JxHO6_u4Kr1_1mz(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);
ssc_core_VYgEVLOTSaxPVTUp295uAH=ssc_sli_V4rVN29HRbWXfyoy1Rm7o9(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);ssc_core_FFZbGh27ya8eem_J_hUtAZ=
ssc_sli__UrK3rytxHCfVXpTq182GL(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);
ssc_core_VriVbeGXVySZhmo4IqByQ6=ssc_sli__QonMhVfyKxdg5cfn4U8Jp(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);ssc_core_khnxU_g3zxlubHIUGDCLIb=
ssc_sli_VpA8MeBTbz4vfeehXz_6ss(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,a);}
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mIC= *ssc_core_VOWKumMlbtW4VXce4H_wn2;
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mIC.mN=ssc_sli__OzP6GQ7QKhuWTGGHKSszk->mX.mN;
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods[ssc_sli_FE7q2LVg_Cx6geTARRhW19](
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,ssc_sli__OzP6GQ7QKhuWTGGHKSszk,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mINIT_R= *
ssc_core_koKjwdMe5Vdteq6adeee9v;ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mINIT_R.mN=
ssc_sli__OzP6GQ7QKhuWTGGHKSszk->mD.mN;ssc_sli_ktcdMpjvBzOSaXg_F3VqCc->mMethods
[ssc_sli_k6Bgpzq7VLOIWDidw0wbuu](ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,&ssc_sli_FmhQXjq8EL0S_aFuxGK2fM);
pm_rv_equals_rv(ssc_core_koKjwdMe5Vdteq6adeee9v,&
ssc_sli_FmhQXjq8EL0S_aFuxGK2fM.mINIT_R);if(ssc_sli__p3kKFb4zHxxf9moWUPWZL){
return ssc_sli_VQ7AHOZWjE_ZZuZD9eHpxL(ssc_core__FL_3zWgtZO8bunUoshkt_,
ssc_core_VOWKumMlbtW4VXce4H_wn2,ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,
ssc_core_koKjwdMe5Vdteq6adeee9v,mc_V45upKVqFMGjWmb_LkY2NN,
mc_Fe6copTTRcKEayCm87ABO_,ssc_core_VB53fXegNkCQcXjkCLRtVG,
ssc_core_kRLzd2SzrBl_jTgvf56_z4,ssc_sli_kY3UicIqYl_BeT0_RDb6mS(
ssc_sli_FCwZLBnFKkp2b5_z2A2lil,ssc_sli__OzP6GQ7QKhuWTGGHKSszk,
ssc_sli__NVQQK5kaIW5cuwdj3ICGD,ssc_sli__3m9za6AQ781ci367S8iNU),
mc_VLHhnPUiNQpve5VIL9P3O9,ssc_core_Vjf_IpltRHCfhPwQq3C_IY,
ssc_core_VYgEVLOTSaxPVTUp295uAH,ssc_sli___mDmNq4k10bdiwJPbdXVD&&!
ssc_sli__NVQQK5kaIW5cuwdj3ICGD->ssc_core_FiExqWFTEah9jHJ0SH1HNW,
ssc_core_FFZbGh27ya8eem_J_hUtAZ,ssc_core_VriVbeGXVySZhmo4IqByQ6,
ssc_core_khnxU_g3zxlubHIUGDCLIb,!ssc_sli__NVQQK5kaIW5cuwdj3ICGD->
ssc_core_FiExqWFTEah9jHJ0SH1HNW,ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,
ssc_core_VB5XLoala8W0VPgYyUV04u,ssc_core_k8xI_4CVG6Kme1FhXXiyE_,
ssc_sli_FwiGZoF7i8OzdiLDqI5_up(ssc_sli__LUTDtJud8K4_PqqE22fA8,
ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy),ssc_core__Wsccr5SV4lneHu1c48wqw,
ssc_core_kH9J5Bq5WXtuYahcoaktju,ssc_sli_kjQNxgQPUXS0VyLovwKvMR(
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,a,
ssc_sli_V_ya37s60_SvbX0govvyGN),ssc_core_kECuv8qDlA_GeDuBxE4osn,
ssc_sli_kMtKewpuyZ_z_9WLYdicfp,ssc_core_FQvSyZB5nvWchH_h_XqWV6,
ssc_core__K_4_9VU7wGGgaWB05q4SN,ssc_core_FGGFID_AEV06Yag1yd_X9c,
ssc_core_kMgeiJyALdWk_qIpaBzpUY,mc_FfDTppU8N_tOWuLK37x_08,
ssc_core_F4tlqGoz8dpsjmIIo_HrZB,ssc_sli_Fa35fYhbZA03ZipctuX5h1,
ssc_sli__NbjXUeO_bdXjLOXjp08yZ,ssc_sli_k_htxnzxqplvaX2Tbe_gpF,
ssc_sli_Fq0LlZmYKHSVYer1pL54Cv);}else{return ssc_sli_kef3mYiPeV4Khq48Vn0Hji(
ssc_core__FL_3zWgtZO8bunUoshkt_,ssc_core_VOWKumMlbtW4VXce4H_wn2,
ssc_core_Ve6NBMLaOZ4KY5KthnAYhe,ssc_core_koKjwdMe5Vdteq6adeee9v,
mc_V45upKVqFMGjWmb_LkY2NN,mc_Fe6copTTRcKEayCm87ABO_,
ssc_core_VB53fXegNkCQcXjkCLRtVG,ssc_core_kRLzd2SzrBl_jTgvf56_z4,
ssc_sli_kY3UicIqYl_BeT0_RDb6mS(ssc_sli_FCwZLBnFKkp2b5_z2A2lil,
ssc_sli__OzP6GQ7QKhuWTGGHKSszk,ssc_sli__NVQQK5kaIW5cuwdj3ICGD,
ssc_sli__3m9za6AQ781ci367S8iNU),mc_VLHhnPUiNQpve5VIL9P3O9,
ssc_core_Vjf_IpltRHCfhPwQq3C_IY,ssc_core_VYgEVLOTSaxPVTUp295uAH,
ssc_sli___mDmNq4k10bdiwJPbdXVD&&!ssc_sli__NVQQK5kaIW5cuwdj3ICGD->
ssc_core_FiExqWFTEah9jHJ0SH1HNW,ssc_core_FFZbGh27ya8eem_J_hUtAZ,
ssc_core_VriVbeGXVySZhmo4IqByQ6,ssc_core_khnxU_g3zxlubHIUGDCLIb,!
ssc_sli__NVQQK5kaIW5cuwdj3ICGD->ssc_core_FiExqWFTEah9jHJ0SH1HNW,
ssc_core_FyZkX4cpKZ8YVH5EKfcqLt,ssc_core_VB5XLoala8W0VPgYyUV04u,
ssc_core_k8xI_4CVG6Kme1FhXXiyE_,ssc_sli_FwiGZoF7i8OzdiLDqI5_up(
ssc_sli__LUTDtJud8K4_PqqE22fA8,ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy),
ssc_core__Wsccr5SV4lneHu1c48wqw,ssc_core_kH9J5Bq5WXtuYahcoaktju,
ssc_sli_kjQNxgQPUXS0VyLovwKvMR(ssc_sli__OzP6GQ7QKhuWTGGHKSszk,
ssc_sli_ktcdMpjvBzOSaXg_F3VqCc,a,ssc_sli_V_ya37s60_SvbX0govvyGN),
ssc_core_kECuv8qDlA_GeDuBxE4osn,ssc_sli_kMtKewpuyZ_z_9WLYdicfp,
ssc_core_FQvSyZB5nvWchH_h_XqWV6,ssc_core__K_4_9VU7wGGgaWB05q4SN,
ssc_core_FGGFID_AEV06Yag1yd_X9c,ssc_core_kMgeiJyALdWk_qIpaBzpUY,
mc_FfDTppU8N_tOWuLK37x_08,ssc_core_F4tlqGoz8dpsjmIIo_HrZB,
ssc_sli_Fa35fYhbZA03ZipctuX5h1,ssc_sli__NbjXUeO_bdXjLOXjp08yZ,
ssc_sli_k_htxnzxqplvaX2Tbe_gpF,ssc_sli_Fq0LlZmYKHSVYer1pL54Cv);}}
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_sli__Df4nvb2Vh0XjqsebV8GwG(size_t
ssc_sli_kNAdXxObD3dmjy4Cd1xTJZ,size_t ssc_sli__usAOidwpAxfaaBUmyG_Wc,
NeSolverParameters const*ssc_core_kH7c9UGCUNOFXqT6Omambe,
ssc_core__cqeoq_N8axBWHaE78_gdI*ssc_core_FGW_LNPjvUWPjT2uiRMTEf){size_t
ssc_core_kbGnKCSxws0fYXvQUcV8T8=2*ssc_sli_kNAdXxObD3dmjy4Cd1xTJZ+
ssc_sli__usAOidwpAxfaaBUmyG_Wc;size_t ssc_core_Fe_BSDjMNWx2_DMFC2qefm=
ssc_sli_kNAdXxObD3dmjy4Cd1xTJZ+ssc_sli__usAOidwpAxfaaBUmyG_Wc;boolean_T
ssc_core__6gTHc63VIWQbeDvSHksxF=ssc_core_FGW_LNPjvUWPjT2uiRMTEf->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPattern->mNumCol==
ssc_core_kbGnKCSxws0fYXvQUcV8T8;ssc_core__XvzTXJcADdQhPSJjzuq_2*result;result=
ssc_core_F_KwLJ0mWNOFhTXpD8BCKG(ssc_core_kH7c9UGCUNOFXqT6Omambe,
ssc_core_FGW_LNPjvUWPjT2uiRMTEf,ssc_core__6gTHc63VIWQbeDvSHksxF,
ssc_core_kbGnKCSxws0fYXvQUcV8T8,ssc_core_Fe_BSDjMNWx2_DMFC2qefm,
pm_default_allocator());return result;}void ssc_sli_VAZlN0IkJcOggTBnFt6iC6(
PmfMessageId*ssc_sli_k4M7bSEmThKJbirXUDQgS6,boolean_T
ssc_sli_FbXFA8Xx5gGCaLVvOMx5Hu,McLinearAlgebraFactory const*
ssc_sli_FXGCQ_kYY_poWPf4tMmp3E,ssc_core__cqeoq_N8axBWHaE78_gdI*
ssc_sli__PBbET7yf_tSbyUIdDNzkr,NeDynamicSystemInput*
ssc_sli_k9R1mrW343CNi5YS7y0tBD){PmAllocator*pm__8zlSpb2Hixod149p2zadR=
pm_default_allocator();if(*ssc_sli_k4M7bSEmThKJbirXUDQgS6==NULL){PmRealVector*
ssc_sli_V2yCe22tgLW6iHfuJkGXPn=pm_V_q_QnwoVVl6fHS_0pLvYo(&(
ssc_sli_k9R1mrW343CNi5YS7y0tBD->mX),pm__8zlSpb2Hixod149p2zadR);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_sli_VVMKaGdGCYlHdT4GWkrX68=
ssc_core_k68olxaDTeCBZT_KDjZ8UG(ssc_sli__PBbET7yf_tSbyUIdDNzkr,
ssc_sli_FXGCQ_kYY_poWPf4tMmp3E,pm__8zlSpb2Hixod149p2zadR);
mc_kQtOKCqS08dIbumyDnHNDL ssc_sli_VDml9ZinbW08Wez66ymdXC=(
ssc_sli_VVMKaGdGCYlHdT4GWkrX68)->mSolve((ssc_sli_VVMKaGdGCYlHdT4GWkrX68),((
NeSystemInput*)ssc_sli_k9R1mrW343CNi5YS7y0tBD));pm_rv_equals_rv(&(
ssc_sli_k9R1mrW343CNi5YS7y0tBD->mX),ssc_sli_V2yCe22tgLW6iHfuJkGXPn);
pm_destroy_real_vector(ssc_sli_V2yCe22tgLW6iHfuJkGXPn,
pm__8zlSpb2Hixod149p2zadR);(ssc_sli_VVMKaGdGCYlHdT4GWkrX68)->mDestroy(
ssc_sli_VVMKaGdGCYlHdT4GWkrX68);if(ssc_sli_VDml9ZinbW08Wez66ymdXC!=
mc_FFaaXY_gkbSTcyLBvtfrzS){if(!ssc_sli_FbXFA8Xx5gGCaLVvOMx5Hu){*
ssc_sli_k4M7bSEmThKJbirXUDQgS6=ssc_sli_Vacz9FHeIdKsdLygkEbC_A.
ssc_sli_FJynBFsFIwxriaPMzBML7u.ssc_sli_k_RtH7x8yop2f12RH7hXi2;}else{*
ssc_sli_k4M7bSEmThKJbirXUDQgS6=ssc_sli_Vacz9FHeIdKsdLygkEbC_A.
ssc_sli_FJynBFsFIwxriaPMzBML7u.ssc_sli_VK6W_CYqut_9duBNpo_NW_;}}}}PmIntVector*
ssc_sli__sGkwL9nHl8ceLVO9ChQMM(NeVariableData const*
ssc_core_Vng7nXLBKc4WginpFwCvE1,size_t ssc_core_VMKB5bhU7slcjmqJOJScaf,
PmAllocator*pm__8zlSpb2Hixod149p2zadR){PmIntVector*result=pm_create_int_vector
(ssc_core_VMKB5bhU7slcjmqJOJScaf,pm__8zlSpb2Hixod149p2zadR);size_t
ssc_sli_kh3C5f6ZAPlGWXfJykpWPn=0;for(ssc_sli_kh3C5f6ZAPlGWXfJykpWPn=0;
ssc_sli_kh3C5f6ZAPlGWXfJykpWPn<ssc_core_VMKB5bhU7slcjmqJOJScaf;
ssc_sli_kh3C5f6ZAPlGWXfJykpWPn++){result->mX[ssc_sli_kh3C5f6ZAPlGWXfJykpWPn]=(
int32_T)ssc_core_Vng7nXLBKc4WginpFwCvE1[ssc_sli_kh3C5f6ZAPlGWXfJykpWPn].
mInitMode;}return result;}
