#include "multibody_model_macros.h"
#include "pm_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
#include "pm_std.h"
#include "stdarg.h"
typedef NeuDiagnosticTree*pm_st_FjUEd5ZQJA0Ej1IosTlZ5E;typedef struct
pm_st__0atO_17n_Ci_qYhoCxFUV pm_st_F04yXT_zz14zgHdLildPgK;struct
NeuDiagnosticManagerTag{pm_st_F04yXT_zz14zgHdLildPgK*mPrivateData;
pm_st_FjUEd5ZQJA0Ej1IosTlZ5E(*pm_st_VESUSzIzeRWSV1xYVr5zH5)(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*
pm_st__RtuwtEn2c_yh1OySiqODN)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st__YxE_N42_idoWyreGeTz9t)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,va_list args);void(*
pm_st_kAPwXpB5miCGVLsko_7ONE)(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE);void(*pm_st__u9riBfE3RK3ZXQpAXjZW_)(
NeuDiagnosticManager const*pm_st_FgQH451kC4lOZ5A2coatZe,NeuDiagnosticManager
const*src);NeuDiagnosticTree const*(*pm_st_kqsZroyTBbpjb1za_BT1dv)(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mDestroy)(
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z);};PmfMessageId
pm_st_Fj4pG1CbqChThqCdYV3xux(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_FqMmOIGGjkpTZ58Esd_XuA(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st_F5XP0Is_HAWucugpsjE8XK(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,...);PmfMessageId
pm_st__w8As0Yf6B8Ji9iMi5WOGi(NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z,pm_st_FjUEd5ZQJA0Ej1IosTlZ5E
pm_st_k3bA0_SocS_baqMdimEffE,NeuDiagnosticLevel pm_st_FlRsyRMpiRpNY9kP14dKKM,
PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,char const*
pm_st_kvsOBKjJwlx5dTxrw7qAwS);PmfMessageId pm_st__xrkslL_b0pOemBxsxBQx0(
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z,NeuDiagnosticLevel
pm_st_FlRsyRMpiRpNY9kP14dKKM,PmfMessageId pm_st__C0ajRzPQzOpeHB7hy4YXo,char
const*pm_st_kvsOBKjJwlx5dTxrw7qAwS);NeuDiagnosticManager*
neu_create_diagnostic_manager(PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
neu_destroy_diagnostic_manager(NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z);
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0 ssc_sli__9m1LfQ2DwC_cXa8Cjj28A;
typedef struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G ssc_sli_kqioa3Wq9idS_X_JDQovlr;
struct ssc_sli_VOZYd8vNMhp_hepDNbmZN0{ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli__X9HoYTA6GhUZPkX6FMtmN;void(*mDestroy)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
);NeParameterInfo(*mParameterInfo)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*);
boolean_T(*mSetParameters)(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*,double,
NeParameterBundle const*,NeuDiagnosticManager*);};
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef enum{ssc_core__ioOg4ScKX0EZDRCgs08_8= -1,
ssc_core_VUvhZChBwCxhcDNbwou1aT,ssc_core__QYxQXlKud8zbLGuiUNTmv,
ssc_core_VNLm8DNiLLxzVDGeWBpIJV,ssc_core_V36UEe9kiR_Qcm5dDei5__}
ssc_core_VMObUicZgDGkXuH3R8jgeY;
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_sli_FwOCwa_vjXx9haWvTfh5mO ssc_sli__vLsdRWt9o_uhqT7KXX2wx;
typedef struct ssc_sli_Vja1AfrZCvlheiavhSpdVF ssc_sli_kQALV9CmL9diceRAXQ_cn_;
typedef enum ssc_sli_FE5N1K4heIdccDsy_EmpHE{ssc_sli_VFn7lNfhEQtvWmhsK0f7iQ= -1
,ssc_sli__SbSoLGkCb0VYetIHyypdx,ssc_sli_kOTXWtFmR5hVf9BCWYJcdj,
ssc_sli_FsBy7VJnW4t0e9Aa9fqsVi,ssc_sli_V5sGOLM4tI4YgHiz_gPRep,
ssc_sli_kT9odGnh23pr_L1CRbInlf,ssc_sli_FLDlJzliB9SMiy_qVX_4q6,
ssc_sli_V_YsXbMUCDCBcyyCkkOqBq,ssc_sli__AEiHOXsuN8Kcy8XGVngBx,
ssc_sli_FFcVx8SadQ8GY1voDUS_jp,ssc_sli__BA3_ZqWIe8PZLLDIe9qXu,
ssc_sli_FIzQw5SYZbSeVDQX7ebQ15,ssc_sli__qUOIfC9uZ8WhiT4S2CcWp,
ssc_sli_km99tSEvYx0sbeG39MyEXT,ssc_sli_FaxfxAH4rHWBb5BUak2ZLA,
ssc_sli_Vufu1ZXw2SKE_qySmGRnm_,ssc_sli_kJ7p6FmVpVxVa1EfAHUFDF,
ssc_sli__I4XhuqlnQ0ecXFfaJnVtA,ssc_sli__z5LXIdNga07WqTouQ7yCi,
ssc_sli__yONDaHWSO0Y_H0PIYQgl_,ssc_sli_FTtfNfzSNBpAWuyfv7HADR,
ssc_sli_F6maP3dAiZKe_HJRrU4ih_,ssc_sli_VcQ_SCRTc3OCc9xlLxlhM2,
ssc_sli__H_Jz_zALMlldLCpBR_NQV,ssc_sli__b04q4JhYdl6dq2J3mLqiu,
ssc_sli__hBbOcyt8q_K_i_O1ylN50,ssc_sli__5pEFw2qPJC8cL_hguGK9T,
ssc_sli_FI1U_phgAwhsVPW73Ev3BX,ssc_sli_k_m7DOTs2khciPPzpB23Dp,
ssc_sli_V64qJi8ItWOwXicna6wdf9,ssc_sli__VnKQww0jJpNhi7w803Pqz,
ssc_sli__i90ZwB8v5tfdyUD8usaF5,ssc_sli_kTD52GIdaC4AZiD3_SgboV,
ssc_sli__pnglHvV_wCCZ9tsPjcAj_,ssc_sli_kyVFwkwRUudebDZ8fv0Mqu,
ssc_sli_VyiC_rHiNAxfeXN9t8Z46p,ssc_sli__Ck6F7jCfqKgeahVO7BD0P,
ssc_sli_kSq7vcYEzBSPh1_HmyvGuS,ssc_sli_FzfaJd8s_hCXWy3yxi1stW,
ssc_sli___mb2h47wN4ihPznc5zDZu,ssc_sli_VQPqsGKP5uGObDJbh_eFMB,
ssc_sli_k6Bgpzq7VLOIWDidw0wbuu,ssc_sli__rEZqtXugN_fa5vYYYzGYc,
ssc_sli_V3nBzlNjt48rYL7Wv7cFq7,ssc_sli_VoQ3EqrSwP8_bHycV_ZM_Y,
ssc_sli__puwPfKA1_C_XXKoAacuHL,ssc_sli__0DRn7XIvolbdPgJc8imWd,
ssc_sli__GinY4faV6x5fXRGGHiXOx,ssc_sli_k70mjUuFMQSz_irEsv6NXV,
ssc_sli_V8Sp15ZCPk4jiL9EQsoNyb,ssc_sli__OWNEM8w1KGFbaOP6K0YSM,
ssc_sli_V7cFtvzq5v0Ica9n7ZY32s,ssc_sli__5Jlt976LTdQhme97vzhLz,
ssc_sli_FE7q2LVg_Cx6geTARRhW19,ssc_sli__cezSCdpHN4lgqD73r5pEK,
ssc_sli_kWziByYnTjSrjiEO0gFijq,ssc_sli_VCODxytNt54LYecqLGV9fH,
ssc_sli_FsuU2v1dzu0zguh8hxcIjr,ssc_sli_kcFJMg4RQe4laPBX1LMdGM,
ssc_sli_FV_e38q0Djt6eynPV7_Ny6,ssc_sli_FQTNkFa6paKoWyb_h7lF4p,
ssc_sli_kHan416AsF0SVX35Jc3ZUl,ssc_sli_VkPOkxGyh8h2ZHn6VM4FlF,
ssc_sli__AaIKqtCr_pwYX1HS4ht1q,ssc_sli_kPLJtaHw3MS_VLkU2lSQRq,
ssc_sli_VbUGQovAbg0NXH9ywH5nXC,ssc_sli__szAKcwWzAGWXe6ZxiNqLy,
ssc_sli_FDke0C5lVb4aiu949gwwFS,ssc_sli_knnAZr_MyDhGaqCPi5fnDE,
ssc_sli_k48eOppTiHpzaP3Bk4LY0j,ssc_sli_Vh7M4IOwZgdYdiu1n7C8t0,
ssc_sli_VHuz88szqGKgjTt1PdGvzW,ssc_sli_kNZ4tFFUHVluZiz8DsHlCO,
ssc_sli_kTmLAygbBbCecHMi0uMPAy,ssc_sli_FHVxyfshp6KgVaq6SphqIh,
ssc_sli__mVVJdecb3d__PkepHFMpg,ssc_sli_FkVgnEqViixCfumgJMCM_e,
ssc_sli_Vge_nrKxO_O9eD_Fd91nEn,ssc_sli_k_a_p_5ozClahq0TR72sc5,
ssc_sli_VoAl0EnYNmtgYXk1SJDWYK,ssc_sli__CpBn4DTIb4zbyG0hxjNf2,
ssc_sli__J5DR8iwtetKhiPtMB9tI5,ssc_sli_Fr8tyhA6bhOu_T5U6JG49B,
ssc_sli_kO7B69a_Lrhhha86IyU_GA,ssc_sli_kgIxcr5ydSlcd5cK039dgi,
ssc_sli_kpGiBTt5RbdhZuvwoqsVtr,ssc_sli_Fh9oEC3tNb41gqXZYE_FUG,
ssc_sli__Udg2iOsHnplYyGCps5u_2}ssc_sli__XG4dW9jg8K5aqSVlFCEPx;typedef union
ssc_sli__g7Rnp_ZaZdWjHBJH25aLG{PmSparsityPattern mMCON_P;PmRealVector mMCON;
PmSparsityPattern mMPAR_P;PmRealVector mMPAR;PmSparsityPattern mMNL_P;
PmRealVector mMNL;PmSparsityPattern ssc_sli__ovpY6KnH6dQfP8xdfUDc1;
PmRealVector ssc_sli_F_HUzkCmpOSggXuMGEWGT_;PmSparsityPattern
ssc_sli__N9N869oEI85YTjN2q1on1;PmRealVector ssc_sli__7bH_a1nF7lLZXfikHEybp;
PmSparsityPattern ssc_sli__bu_B_0YfB0YZaJNCv1HDf;PmRealVector
ssc_sli_FI6yp2TwSaCubX2niJDZUc;PmRealVector mDXM;PmSparsityPattern mDXM_P;
PmRealVector mDDM;PmSparsityPattern mDDM_P;PmRealVector mF;PmRealVector mCER;
PmSparsityPattern mDXCER_P;PmRealVector mDXCER;PmIntVector mMODE;PmRealVector
mY;PmSparsityPattern mDUF_P;PmRealVector mDUF;PmSparsityPattern mDDF_P;
PmRealVector mDDF;PmSparsityPattern mDTF_P;PmRealVector mDTF;PmRealVector
ssc_sli_F66CfR4KHnKTdDSCFJVRA9;PmRealVector ssc_sli_koF8rp4sVUhsfa789D7mOs;
PmRealVector ssc_sli_VWsha__IqNGYfayonvvJ52;PmRealVector
ssc_sli_VN47afO0cOKIii03g9IO50;PmSparsityPattern mDXY_P;PmRealVector mDXY;
PmSparsityPattern mDUY_P;PmRealVector mDUY;PmRealVector mOBS_ACT;PmRealVector
mOBS_EXP;PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;
PmIntVector mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector
mUPDATE_R;PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;
PmRealVector mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;
PmBoolVector mLOCK2_I;PmRealVector mIC;PmIntVector mICR_IM;PmBoolVector mICR_IL
;PmSparsityPattern mDDCER_P;PmRealVector mDDCER;PmRealVector mICR;
PmSparsityPattern mDXICR_P;PmRealVector mDXICR;PmSparsityPattern mDDICR_P;
PmRealVector mDDICR;PmSparsityPattern mICRM_P;PmRealVector mICRM;
PmSparsityPattern mDXICRM_P;PmRealVector mDXICRM;PmSparsityPattern mDDICRM_P;
PmRealVector mDDICRM;PmRealVector mEQ_TOL;PmIntVector mDP_L;PmIntVector mDP_I;
PmIntVector mDP_J;PmRealVector mDP_R;PmRealVector mIMIN;PmRealVector mIMAX;
PmRealVector mDIMIN;PmRealVector mDIMAX;PmBoolVector mVDF;PmBoolVector mVMF;
PmBoolVector mVMM;PmBoolVector mSLF;PmBoolVector mLV;PmBoolVector mNLDV;
PmRealVector mLOG;PmRealVector mJACOB;PmRealVector mSTATE;}
ssc_sli_kF79J1yovOdS_uDIzPgJXv;typedef int32_T(*ssc_sli_FzWzEHJ0zkxraeyYpIfGuy
)(ssc_sli__vLsdRWt9o_uhqT7KXX2wx const*,NeDynamicSystemInput const*,
ssc_sli_kF79J1yovOdS_uDIzPgJXv*);typedef enum ssc_sli_Fi6dICMEryhlhHsqFF1Glm{
ssc_sli_VrW2BTigS4GAZ1rUN4iH39= -1,ssc_sli_k3o9uZCQechhVih4dUr47D,
ssc_sli_k0kLWpXMhRGfgLcPi7Fisp,ssc_sli_FWYGLerJdq_1c5_i_yeER2}
ssc_sli_FJ_RXAqUrzWEZDw2SwxbIY;struct ssc_sli_Vja1AfrZCvlheiavhSpdVF{
PmRealVector*ssc_sli_F3YBMnlPap4lhLNi_9Ia6y;PmRealVector*
ssc_sli_VU_2QwnChmGVgqMm5Sr7Z7;PmSparsityPattern*
ssc_sli_FhRAq2ytvVK_aXmUKt_zmt;PmRealVector*ssc_sli__YRQX_L6Cl0a_LNO7JjE1O;
PmRealVector*ssc_sli_Ft6MItjvPuONWT3V3OKBBu;PmSparsityPattern*
ssc_sli_kFvlHYIJ4O46YueTUwLqcd;PmSparsityPattern*
ssc_sli__4jnpo1eUu_FYPG8boGTjO;PmRealVector*ssc_sli_F_osIpSL94xCdqURiUvIz_;
PmSparsityPattern*ssc_sli_Vd1e_JCWeyptimGJ3TpS_h;};struct
ssc_sli_FwOCwa_vjXx9haWvTfh5mO{ssc_sli_FzWzEHJ0zkxraeyYpIfGuy mMethods[
ssc_sli__Udg2iOsHnplYyGCps5u_2];ssc_sli_kQALV9CmL9diceRAXQ_cn_
ssc_sli__A9ExPHJ98lvhaKKVhSSjN[ssc_sli_FWYGLerJdq_1c5_i_yeER2];size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_VEeWPhRa2n_8jenUxYBk2R;size_t
ssc_sli_ktQ6DdDzqUSdaXznnc9fp3;size_t ssc_sli_VfxYoGxtCxWOe5CIpZEpgR;size_t
ssc_sli_Vqze4nWRq5S2hLxe1l9Xt6;size_t ssc_sli_FQ0W8NnTLcCMX5CkdMXBql;size_t
ssc_sli__xynZR2gV1K1VLm2neoI3N;size_t ssc_sli_kroPKLd25g4hc1eNzsO5QT;size_t
ssc_sli__JdS4RqKrWSnZyqLPmT_Z6;size_t ssc_sli_VKz26iZ4db8yf1LIqY5mUN;size_t
ssc_sli_kYzaD1Lit1SSjLkdiqP1OV;size_t ssc_sli_kElTq4DVnE8HZmeAigHPwt;size_t
ssc_sli_VNEvEsK8LlCNf1A3s6hbTP;size_t ssc_sli__oB_jUpLTy8EViR7WWaQwH;size_t
ssc_sli_FbAYOXktHVSs_DAgk5v7MD;size_t ssc_sli_kq_WEvLf5mdwV1L3h9nPtn;size_t
ssc_sli_FF7CcO01674qYqGO2HmRs2;size_t ssc_sli_Ft_B7NFN50prZ901dibEp3;size_t
ssc_sli_kRBQlHbYYD4Egm1QxQJNGZ;size_t mNumDelays;size_t
ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t ssc_sli_VXUVpYvb2UONieN5d_4zj_;size_t
ssc_sli_kJ3ldNqAyU_j_HtRTM2zRM;size_t ssc_sli__ABlmQCTuWSnXL25ScOMaB;size_t
ssc_sli_F_HT1PU_764UVerkGAoJea;size_t ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t
mNumAsserts;NeAssertData const*mAssertData;size_t mNumAssertRanges;NeRange
const*mAssertRanges;size_t mNumInitialAsserts;NeAssertData const*
mInitialAssertData;size_t mNumInitialAssertRanges;NeRange const*
mInitialAssertRanges;NeParameterInfo mParameterInfo;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;PmIntVector*ssc_sli__IRxq1x60pW_c50ZYXet9_;
PmIntVector*ssc_sli_VK0mZPdkSZ0AeL2A9O_fqg;PmRealVector*
ssc_sli_kq_4_2qQj_K_iXwR96F3Z0;PmSparsityPattern*
ssc_sli_FMHWnd6hS2Ohe5h6WHoJk7;boolean_T ssc_sli_kVFXI80kGBW_Z9MUWAEJa_;
PmRealVector*ssc_sli_VkANUOZhDiS3WPP0Zls80v;};typedef struct
ssc_sli_FoZkm_5qOEKfcH3QbkEcVB ssc_sli_V2edm5XULi4bhDK_5PJPZ7;typedef struct
ssc_sli_VPhVVeWKwIKoVaX7WXrfxf ssc_sli_VBKvh6DiD0tgcq_RIzRALP;typedef struct
ssc_sli__zGf_s_hkhW4XuR69xE5su ssc_sli_VmZk8hTl6VheWiwMDRQsyS;struct
ssc_sli__zGf_s_hkhW4XuR69xE5su{NeDynamicSystemInputSizes mSizes;
ssc_sli__vLsdRWt9o_uhqT7KXX2wx*ssc_sli_FUA8D5ImF_4aiT9qVHs5oX;
ssc_sli_V2edm5XULi4bhDK_5PJPZ7*ssc_sli_VjXisdXgW_hWheKa6_ZxQl;
NeDynamicSystemInput*ssc_sli__9cODvEKbYO8XThLttQhJI;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;void(*
mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeModelParameters const*const mp,
NeSolverParameters const*const ssc_core_kH7c9UGCUNOFXqT6Omambe);int32_T(*
ssc_sli_V3VUbDwWgtdHXe8MDjtoZN)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli__6gTFXBv2i84fanvoJsVjr)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup);void(*mDestroy)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli_kXbRX_Jm9MSS_DN_XK6gAs)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR,NeDynamicSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);void(*ssc_sli_kBSiVedNuQCHj9PHy4DbI_)(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*ssc_sli__yJMA3iYg0OIYazayPoQxR);void(*
ssc_sli__Qs092x10UtZ_eE_eC7Xz0)(ssc_sli_VmZk8hTl6VheWiwMDRQsyS const*
ssc_sli__yJMA3iYg0OIYazayPoQxR);ssc_sli_VBKvh6DiD0tgcq_RIzRALP*mData;};
#include "pm_std.h"
#include "ne_std.h"
typedef void(*ssc_sli_VLHLirPkN8tkXeqFGHjU2i)(void*,PmCharVector);typedef void
(*ssc_sli_kbiAFAvTXQx_bDxj3uVstA)(void*,PmRealVector const*,PmIntVector const*
,PmCharVector);typedef struct ssc_sli_kMpO1n_UBd47YuQ9jzZuzr{void*
ssc_sli_k634Dqj5Scpifm9Ki1eHhL;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli_FRiVh68ViPKEg9hf4_Ug13;ssc_sli_VLHLirPkN8tkXeqFGHjU2i
ssc_sli__FAyTG0BYYdgZPwbJfkwqb;void(*ssc_sli_knp9t1hx76OXeqA2TA61cp)(void*,
NeDynamicSystemInput const*ssc_sli__OzP6GQ7QKhuWTGGHKSszk);}
ssc_sli__fVrcqbYF9WBimPMxPRd4Y;
#include "pm_inline.h"
#include "mc_std.h"
#include "ne_std_fwd.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ssc_dae.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(char
const*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
#include "ne_stiffness_fwd.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef
struct ssc_sli_VFWQkwsWjFO3YXl_MNZJDP ssc_sli_FfCmiDUlTHWdhTaGeWWmuy;struct
ssc_sli_VFWQkwsWjFO3YXl_MNZJDP{PmRealVector*ssc_sli__umAQFI5A7lxePExgO_arY;
mc__mbv8xxcLWlA_qjxkZ_Zr3 ssc_sli_FXYJKQreD2_Tf14HXZftwA;
mc__mbv8xxcLWlA_qjxkZ_Zr3 ssc_sli__yB5r2Ovvv_1d1pc4UbomW;PmRealVector
ssc_sli__sojpoqyGKxKi1MJAukVny;boolean_T ssc_sli_kOMlZk7NTpxXgLpfPXk1fc;
boolean_T ssc_sli_Vin1htMvvV0qiD156ttlEy;};
#include "pm_inline.h"
typedef struct ssc_sli_kZxrCUA8tO0phPexWrtzmM ssc_sli_VW_ogzaTyo0kXql81JaM_l;
typedef struct ssc_sli_VzcAkZJ6ELtRge9892ouV5 ssc_sli__9vNmB0C9GK1W1pRr15dLc;
struct ssc_sli_kZxrCUA8tO0phPexWrtzmM{PmRealVector*(*
ssc_sli_FvPt29eXWrtnaywnAkTTzE)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli__JaMZNWAa__QbXiCKJnXnC)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*ssc_sli__V2GsKfXhY_p_mlJLOS6A6)
(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_k8tMlkuYj_Sih11Pcpr3ne)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmIntVector*(*ssc_sli__5_UeKPn6E8yZ5FYsZA0Qi)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli_F4k7ST_risKBWmkiDYmsGi
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*
ssc_sli_VOZQl3ssDr0hhyaiwOy11c)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_F9Xs5gc0nAGDbX3AbwXh5D)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli_FXYJKQreD2_Tf14HXZftwA
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_FbaMgAuDQXtkd5RShI3o7C)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_FamvhohjbzCm_umircxMjq)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_core_FyOwljf5rtGFdmq18I_hmE)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmSparsityPattern*(*mM_P)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*
(*ssc_sli__0tB_km2jUKvXPhyTmThux)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmSparsityPattern*(*ssc_sli_kU1IKNSGg4dpha8WaWkPZ_)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli__WXl5FgRW90TjX0RRwUEci
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmSparsityPattern*(*
ssc_sli__2DhE5J_fFWhbadILLrm1L)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli__UQIrcKp8d8UbLqyvXnQyv)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*ssc_sli__8inMtesCR0FgXaTeArkt_
)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmRealVector*(*
ssc_sli_FUpUzGnPnv0m_qSXZnwv4E)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
PmRealVector*(*ssc_sli_VvtT_los6httV9uBdX1mPJ)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);PmIntVector*(*ssc_sli_Vpna_7I4l94jjTxsYGOBlk)
(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli__djxsoGTYk8_WHFWI6CE2e)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_kTgaWou2ePGi_T83eVmFB4)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli__aK6RhIri2lsiPw9024AWm)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_VnYSekQWhpOYYPjDWhTOod)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_VfTUkRE7gRtXfXDqOCNgGn)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli_kjeAwr4pAFloZ9ZzA_nG8M)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_kdrm8_CkIRdyZLDWuc4lOV)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_ka77aS1n6yCxcerEl7v1wG)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli__Hq42Wk_zm0tf57HHJNb8K)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*
ssc_sli_F2GpUH_z4lKcYyKqirODC3)(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);
boolean_T*(*ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh)(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);boolean_T*(*ssc_sli_VdyOM3ac9ktjgT8rdrPUIH)(
const ssc_sli_VW_ogzaTyo0kXql81JaM_l*);void(*mDestroy)(
ssc_sli_VW_ogzaTyo0kXql81JaM_l*);ssc_sli__9vNmB0C9GK1W1pRr15dLc*mData;};
PMF_DEPLOY_STATIC PmRealVector ssc_sli_FbNDE2Rr_DtMXHgwY7qW3A(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FvPt29eXWrtnaywnAkTTzE(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_Fj6FoMj5Dl0q_a_prqq3bR(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__JaMZNWAa__QbXiCKJnXnC(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_FSjcBIED8tKmiay_NyK7zQ(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__V2GsKfXhY_p_mlJLOS6A6(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kOWE0zHM8m0wY93asHJwLe(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_k8tMlkuYj_Sih11Pcpr3ne(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_kxY1noz2O7pcb1hLLo5nhR(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__5_UeKPn6E8yZ5FYsZA0Qi(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kqV3lDja_PhgfDmC9KZQTj(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_F4k7ST_risKBWmkiDYmsGi(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli_kqLQwTUQI3CnaLR7ld3n7Q(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VOZQl3ssDr0hhyaiwOy11c(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_FzWdjDQLk9WW_ujd7Jcybq(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_F9Xs5gc0nAGDbX3AbwXh5D(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli__XqvlNMriUSFgmk2jTZSu6(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FXYJKQreD2_Tf14HXZftwA(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli__MpM_ZZQhot7Vml7PvXRok(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_FbaMgAuDQXtkd5RShI3o7C(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kOSTk1s82US5aDFQKpH067(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FamvhohjbzCm_umircxMjq(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_F_0yf_qMGxxjZHpE9HfXPe(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_core_FyOwljf5rtGFdmq18I_hmE(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmSparsityPattern ssc_sli_kZDsMQqCvulggHj1JCoqJb(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->mM_P(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_VlhTWAbwxnGkeXPRc_CIBs(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__0tB_km2jUKvXPhyTmThux(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmSparsityPattern
ssc_sli_kDea3SpoCkl1ciMKcHlJ41(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kU1IKNSGg4dpha8WaWkPZ_(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kYjn6kSV9TGZWirFUKegIj(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__WXl5FgRW90TjX0RRwUEci(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmSparsityPattern
ssc_sli_k9NjcG39_i80hPvHCeLl6v(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__2DhE5J_fFWhbadILLrm1L(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_kXzjAyYPzYhQf5GxACFOOR(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli__UQIrcKp8d8UbLqyvXnQyv(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kg2z3WNMy9xU_mlnYjkP15(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__8inMtesCR0FgXaTeArkt_(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmRealVector ssc_sli_FrV7CfQG67dTeuOwvsv9fy(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_FUpUzGnPnv0m_qSXZnwv4E(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC PmRealVector
ssc_sli_kpox7sctNc8Xbaocx9zi8G(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VvtT_los6httV9uBdX1mPJ(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC PmIntVector ssc_sli__zK4QBKRV14lcyf_S2N3Gf(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_Vpna_7I4l94jjTxsYGOBlk(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli__JosVOTFU_tPgaLZK_6MIS(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__djxsoGTYk8_WHFWI6CE2e(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_Fu3sYKZIuVhWVqwSrNMy2f(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kTgaWou2ePGi_T83eVmFB4(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kE4ggXPRuoKbg9HQdpE4D9(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__aK6RhIri2lsiPw9024AWm(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_kZtJNvHqhaC2YXYlEWrh3k(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VnYSekQWhpOYYPjDWhTOod(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kwuFB_guvCORXTdOY4UzOM(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VfTUkRE7gRtXfXDqOCNgGn(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli__JqOJzB0KxdqgXfjaKtWIa(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kjeAwr4pAFloZ9ZzA_nG8M(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_VUg_nT8OzmSqY5SEaTPMyk(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kdrm8_CkIRdyZLDWuc4lOV(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_VBMd0tXODmxLda_dFV9uP8(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_ka77aS1n6yCxcerEl7v1wG(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC boolean_T
ssc_sli_k3bobvwthx8Ziu2mn2F0GJ(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli__Hq42Wk_zm0tf57HHJNb8K(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli__NyFjOIc89hGfaOX6LZHDS(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_F2GpUH_z4lKcYyKqirODC3(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}PMF_DEPLOY_STATIC void
ssc_sli_kqN8aEQ2NgxN_D8dwZHHbj(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB,boolean_T value){*(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB))=value;}PMF_DEPLOY_STATIC boolean_T
ssc_sli_kCobpMmYSpxPdTEetzTICi(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_kLL_DEKSew8ZX9_3s_H0Kh(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC void ssc_sli_F8IwhpQUksl7XmkQJ97tWd(const
ssc_sli_VW_ogzaTyo0kXql81JaM_l*ssc_sli_VItvg5KmEMhxWDP6EQKkBB,boolean_T value)
{*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->ssc_sli_VdyOM3ac9ktjgT8rdrPUIH(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB))=value;}PMF_DEPLOY_STATIC boolean_T
ssc_sli__fZq__Q0E2xqfiI3oL4jo1(const ssc_sli_VW_ogzaTyo0kXql81JaM_l*
ssc_sli_VItvg5KmEMhxWDP6EQKkBB){return*(ssc_sli_VItvg5KmEMhxWDP6EQKkBB->
ssc_sli_VdyOM3ac9ktjgT8rdrPUIH(ssc_sli_VItvg5KmEMhxWDP6EQKkBB));}
PMF_DEPLOY_STATIC boolean_T ssc_sli_kosjTda6DbKpcPl1wp4aRa(
ssc_sli_VW_ogzaTyo0kXql81JaM_l const*ssc_sli_VItvg5KmEMhxWDP6EQKkBB){size_t i;
PmIntVector ssc_sli__WLSFXXyRPp_XDpYDyBjwh=ssc_sli_kqLQwTUQI3CnaLR7ld3n7Q(
ssc_sli_VItvg5KmEMhxWDP6EQKkBB);for(i=0;i<ssc_sli__WLSFXXyRPp_XDpYDyBjwh.mN;i
++){if(ssc_sli__WLSFXXyRPp_XDpYDyBjwh.mX[i]){return true;}}return false;}
#include "pm_std.h"
typedef struct ssc_sli_k2T1gEFX2_d4ZuI1Q_M1kw{size_t
ssc_sli_FPVB1VKrX_h8hmXFAx1z0H;size_t ssc_core_F3PjN_oDrpK0_ThkfqVg1d;size_t
mNumModes;size_t mNumOutputs;size_t ssc_sli__KrYlKhSdSOXXeT8d_3Kmo;size_t
mNumRanges;size_t mNumSamples;size_t mNumMassMatrixNzMax;size_t
mNumLinJacobianNzMax;size_t ssc_sli_VJ8SrpAMHKxmYL9Q3pA_A4;size_t
mNumTrimResiduals;size_t ssc_sli_kvfFJtWMgTxfi9k3xvvF62;size_t
ssc_sli_FkmLIiLc7CGWaPgysl5AJO;size_t mNumSwitchingCoefficients;size_t
mNumJacobianElements;boolean_T ssc_sli_Vp5HPyLroL0k_DUEAnUzoy;boolean_T
ssc_sli_VVPQB49wTEh4gXWM_xNirR;boolean_T ssc_sli_VPy35XeH1H_Ic5S5a75SOn;
boolean_T mIsMConstant;boolean_T mIsMRuntimeScaled;boolean_T
ssc_sli__arpT5XMu5t8YXkNe8wbMn;boolean_T mIsDae;boolean_T
ssc_sli_kQ9NLJnej_07gaKiLdXsC7;PmIntVector const*mNumInputs;PmBoolVector const
*mDirectFeedthrough;}ssc_sli_V95QTHcsdJWsceYUUIcaiZ;typedef struct
ssc_sli_FddFlqLbGs8Ec9cKizRnDH{size_t ssc_sli_kdbZHDJZystegu4mC2KxAD;char const
*ssc_sli_kfIUe_GyyUxNXP9R1Bzclf;char const*ssc_sli__CyZTkoYGzl7XaQhQFTWx1;}
ssc_sli_F33sTio252OSWDmfgFnBLU;typedef struct ssc_sli_VksJFOy6ztKWayuIvJC3vL{
ssc_sli_F33sTio252OSWDmfgFnBLU*ssc_sli_FAG8fdoVes_ic5rWxjy6NT;size_t
ssc_sli_kRTHQV6aVROXgXhhhLkvwE;}ssc_sli_FFsg1hWl9wdl_y_KxzGjIe;typedef enum
ssc_sli_kBNdZWiqPRKIYu1awz4kXx{ssc_sli_kbCIOzV5Z7CAfDR9BoZ7rH= -1,
ssc_sli__RiZc_WhuMSXYLxqycSSFc,ssc_sli_kvrVP8dK_YxdXT10arv4EW,
ssc_sli_VGxILroHbgtWiTFBYYNAXm,ssc_sli_FQL0hKTqv8Sie55gV0Y8cx,
ssc_sli__GCna4k_OrxVX9kSHDDXAK,ssc_sli_kP_7DeXUvbC5e9vpE9iOIT,
ssc_sli_F6P1FaANFippVajVLK2D_T,ssc_sli__CszVq_qJvldeXSY5iS6VL,
ssc_sli__mpohBd6Qp_vYyECv_lFRd,ssc_sli_Vipfdl4tnpGrjDCNh84ogK,
ssc_sli_VUy8x1u_Igd6imXZ9DEYho,ssc_sli_kyWSQenTs_8_Zi6Jcsix3G,
ssc_sli__LrXJSNsYmtVcyVzcNYi59,ssc_sli_Vn6CJo_YVN8OcP8nn1whv6,
ssc_sli_VoSYfpN1uFKlcPezC9ncVd,ssc_sli_V98MZzJMKq0gg5WhkoMwu1,
ssc_sli__nZdFLhYWdSfgTHqWj7syJ,ssc_sli_kApiqH0m_LhDi1Il30PsjP,
ssc_sli__bj8LviD_7SAa9h0Y93_l4,ssc_sli__O4lYRI3DZGge9bI6pIk6_,
ssc_sli__nDPNUqGxXOxfT_z5oMDRA}ssc_sli_VFwLXd9iXnKCc5B9U7TnKW;typedef struct
ssc_sli__XES3TASJmKShiLbwE_pro ssc_sli_kM_sIcp_r7pug543dTUIIr;typedef struct
ssc_sli_FgbqL7C2VQGsYPXNX9ttqk ssc_sli__ZioeTVESJGpeTrFjaf6zj;typedef enum
ssc_sli__CWP_5tK7QC0jie9CMmAkg{ssc_sli__H_8csAriglmWDalIx_Jr9= -1,
ssc_sli_FHeSjK10tG_GhuRp0IXZBS}ssc_sli__8c7dMQOS04JcqlXE55xkL;typedef
ssc_sli__8c7dMQOS04JcqlXE55xkL(*ssc_sli_FeZ1lmnch4dBbqwEnNlvCL)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*,
NeuDiagnosticManager*);typedef void(*ssc_sli_kqbwhVT7n1K_jHgv1wcKZP)(void*);
typedef void(*ssc_sli__gsXzOfgna_jX98M26bmMn)(void*);struct
ssc_sli__XES3TASJmKShiLbwE_pro{ssc_sli__ZioeTVESJGpeTrFjaf6zj*
ssc_sli__X9HoYTA6GhUZPkX6FMtmN;ssc_sli_FeZ1lmnch4dBbqwEnNlvCL mMethods[
ssc_sli__nDPNUqGxXOxfT_z5oMDRA];ssc_sli_V95QTHcsdJWsceYUUIcaiZ(*mSizes)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);void(*ssc_sli_kI7uP4YIZw8pW16U7gwAco)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli__N_2P1psnRxPfLDTTyJSvb)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli_VbhYHtP_w5KncDt2d365fm)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,PmRealVector*
ssc_sli_VIrgfYjjo5hWjLkZEUNImr,PmRealVector*ssc_sli_F4Dzn5SAupC7jPCs01xBuJ);
ssc_sli__8c7dMQOS04JcqlXE55xkL(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,NeModelParameters const*mp,
NeuDiagnosticManager*pm_st_kPInN_8SRA_iYeTvYVKl3z,
ssc_sli_kqbwhVT7n1K_jHgv1wcKZP mc_Fyss_XM3F_C4dm6IKoDw4G,
ssc_sli__gsXzOfgna_jX98M26bmMn mc_Vs6xonQX17Krc5vXv8T_zq,void*
ssc_sli_V0_YXRZgCwhpfXYneT6RGZ);ssc_sli_FfCmiDUlTHWdhTaGeWWmuy const*(*
ssc_sli__fA9Mq6IS2xIV5WAVknKiS)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);
SLMatrices const**(*ssc_sli__fpSjGZmQx4lXe__BBu7Lj)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s);ssc_sli__8c7dMQOS04JcqlXE55xkL(*
ssc_sli_V3vxMRQq8gCQeHUFA6N8LD)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,
ssc_sli_VW_ogzaTyo0kXql81JaM_l const*ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,void*
mc_FvxKbdtfPKOYaymjtthQ0G,NeuDiagnosticManager*);NeStiffness*
ssc_sli_k7O4VJD_GfWTiueS_WbVpj;void(*ssc_sli_k38RFN7EiQlTfHNlMviDub)(
ssc_sli_kM_sIcp_r7pug543dTUIIr const*s,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,IterationsLogCore*
ssc_sli_kFG1cmkvYqxhhXEyS95YdT);ssc_sli__8c7dMQOS04JcqlXE55xkL(*
ssc_sli_k2IVLe_gJolxZ5lBGBeXYp)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*
ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,double*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mDestroy)(ssc_sli_kM_sIcp_r7pug543dTUIIr*);NeCustomData*(*
ssc_sli__lOEzNzI75d6fuOcayiCxx)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*);
ssc_sli__8c7dMQOS04JcqlXE55xkL(*ssc_sli__ZfgolV2w_8cVmgW1DQ1Wi)(NeCustomData
const*,ssc_sli_kM_sIcp_r7pug543dTUIIr const*,NeuDiagnosticManager*);NeZCData
const*mZCData;NeRange const*mRanges;NeParameterInfo mParameterInfo;void(*
mSetParameters)(ssc_sli_kM_sIcp_r7pug543dTUIIr const*,NeParameterBundle const*
);};PMF_DEPLOY_STATIC ssc_sli__8c7dMQOS04JcqlXE55xkL
ssc_sli_VyboOwUKgZhScDgGLfXkIQ(ssc_sli_kM_sIcp_r7pug543dTUIIr const*
ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,ssc_sli_VFwLXd9iXnKCc5B9U7TnKW
ssc_sli_kwhduxmN0MGLbibTtE1dsV,ssc_sli_VW_ogzaTyo0kXql81JaM_l const*
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,NeuDiagnosticManager*
pm_st_kPInN_8SRA_iYeTvYVKl3z){return ssc_sli_F9ORBrZw_TS4eeOz_jH6FW->mMethods[
ssc_sli_kwhduxmN0MGLbibTtE1dsV](ssc_sli_F9ORBrZw_TS4eeOz_jH6FW,
ssc_sli_kTR03ZFlgvKQYaMvR5JNAi,pm_st_kPInN_8SRA_iYeTvYVKl3z);}typedef struct
ssc_sli_Vuz0GhjW2WhTZDC4SVMvG7 ssc_sli_kjLv8FL1DDSYaiak95i_aG;typedef struct
ssc_sli__DkiyEWJgJ8zc1Fp45S1zC ssc_sli__YnIwbk2Zd0ydu44P69Ygf;typedef void(*
ssc_sli_FqhfXr159G88f1FdgyEvon)(void*);typedef void(*
ssc_sli_VlRyoSb503thaDFhWdahL8)(void*);struct ssc_sli_Vuz0GhjW2WhTZDC4SVMvG7{
size_t mNumInputs;size_t mNumStates;size_t mNumOutputs;size_t mNumVariables;
size_t ssc_sli_FkmLIiLc7CGWaPgysl5AJO;double ssc_sli__BzytCIJqpK6X9hlBST23v;
NeParameterInfo const*mParameterInfo;ssc_sli__YnIwbk2Zd0ydu44P69Ygf*mData;void
(*ssc_sli__N_2P1psnRxPfLDTTyJSvb)(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,ssc_sli_FFsg1hWl9wdl_y_KxzGjIe const*
ssc_sli__a5NuSO1IMdf_XJPt6pvf2);void(*ssc_sli_FqbH9qSYJs0xdXvTtIQe5G)(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,boolean_T
ssc_sli_FNnVz906Ccx2humxdqRIHf);boolean_T(*ssc_sli_k0d9xwJv_7dOX9x2cJmSYP)(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);boolean_T
(*mSetParameters)(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,NeParameterBundle const*
ssc_core__wmTd2KKOKd7YPG6_QANiL);boolean_T(*mStart)(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z);NeDynamicSystemInput(
*ssc_sli__h7bfQNxXbWfeerDEb8eHt)(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,PmRealVector const*
ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time);void(*
ssc_sli_FkOnu54reaGRbeQmmTIPpX)(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc);boolean_T(*
mSolve)(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,
PmRealVector const*ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,PmRealVector const*
ssc_sli_FIhpJ2B309KpaHh5HnJcyt,real_T time,void*mc_FvxKbdtfPKOYaymjtthQ0G,
NeuDiagnosticManager const*pm_st_kPInN_8SRA_iYeTvYVKl3z,boolean_T
ssc_sli__Q7Ma2_YOStTje8AA4bkl7,ssc_sli__fVrcqbYF9WBimPMxPRd4Y*
ssc_sli_VOIs9X47Te87iTPKtKti3R);boolean_T(*ssc_core_FaodIriazzO_eqYQvE0wWC)(
PmfMessageId*ssc_sli_k4M7bSEmThKJbirXUDQgS6,ssc_sli_kjLv8FL1DDSYaiak95i_aG
const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,NeDynamicSystemInput const*
ssc_sli_Fi_du5uFlgGne5wvGXKElE);boolean_T(*mCheck)(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2,
PmRealVector const*ssc_sli_FYJpLKluh5liZmQvV10qz_,PmRealVector const*
ssc_sli_F_LG3UJhX_KFge1D1_tDsw,PmRealVector const*
ssc_sli__03FJRdYjrGLeXD1KD8kv3,real_T time,NeuDiagnosticManager const*
pm_st_kPInN_8SRA_iYeTvYVKl3z);void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*s,ssc_sli_FqhfXr159G88f1FdgyEvon
mc_Fyss_XM3F_C4dm6IKoDw4G,ssc_sli_VlRyoSb503thaDFhWdahL8
mc_Vs6xonQX17Krc5vXv8T_zq,void*ssc_sli_V0_YXRZgCwhpfXYneT6RGZ);void(*mDestroy)
(ssc_sli_kjLv8FL1DDSYaiak95i_aG*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);};
ssc_sli_kjLv8FL1DDSYaiak95i_aG*local_dae_simulator_create(
ssc_sli_VmZk8hTl6VheWiwMDRQsyS*dae,NeSolverParameters const
ssc_core_kH7c9UGCUNOFXqT6Omambe,NeModelParameters const mp,
McLinearAlgebraFactory const*la,NeVariableData const*
ssc_sli_VN_7L42pqbCtiyaEWByaMn,NeVariableData const*
ssc_sli__K7Djg9QG80KhHk28hgZIk,NeModeData const*ssc_sli_kWGDyXyjTxt_XaIg_4K8Jp
,NeEquationData const*ssc_sli_FYF8h7Y0_VKocq7icQcbIO,NeRange const*
ssc_sli_kD4mWNBnT_0ahDKC1KT8t6,NeICRData const*ssc_sli__ItxhVqlmhdtheI_ajB_jd,
NeCERData const*ssc_sli_FPoJIEsiOy4EbmKLXeJ5Vy,size_t const
ssc_sli_V_ya37s60_SvbX0govvyGN,size_t const ssc_sli__LUTDtJud8K4_PqqE22fA8,
size_t const ssc_core_F4tlqGoz8dpsjmIIo_HrZB,size_t
ssc_sli_FfWUwxM1ofWZVyY38cZ_pg,NeSwitchingCoeffsData const*
ssc_sli__W_TX7Fo5CKLiDyMecexaW,size_t ssc_sli__uq48tY8wZWZdLNLTOGIiZ,
NeJacobianElemsData const*ssc_sli_FEcs0fFn4WdigeQh6oTl8b,size_t
ssc_sli__t_U_16iYH03gTyFvlLH3w,size_t const*ssc_sli_VTITMaurjjdxjTNwTLFTuC,
size_t ssc_sli_kucX2oAXzWGseaPyJuX1HZ,NeSwitchingStatesData const*
ssc_sli_F_87EaeRhRWgYTUiBbND1Z);ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
local_dae_rtp_manager_create(ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli__8ZNW6YU7nGkW9bWBMo_l2);
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "ne_std.h"
struct ssc_sli_Vl2TiQlVUtSTW13yNxgI6G{ssc_sli_kjLv8FL1DDSYaiak95i_aG const*
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh;};static void ssc_sli__GBQFb1P9g_nX9yezfzkGA(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*manager){PmAllocator*a=pm_default_allocator();{
void*const ssc_sli__nXet41dE8_kZelZPVMcOT=(manager->
ssc_sli__X9HoYTA6GhUZPkX6FMtmN);PmAllocator*const
ssc_sli_Frm9k6MhgTdp_qVSQABULF=(a);if(ssc_sli__nXet41dE8_kZelZPVMcOT){(
ssc_sli_Frm9k6MhgTdp_qVSQABULF)->mFreeFcn(ssc_sli_Frm9k6MhgTdp_qVSQABULF,
ssc_sli__nXet41dE8_kZelZPVMcOT);}};{void*const ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9=
(manager);PmAllocator*const ssc_sli_VBqGHWZ7CldnePAFp61g0Y=(a);if(
ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9){(ssc_sli_VBqGHWZ7CldnePAFp61g0Y)->mFreeFcn(
ssc_sli_VBqGHWZ7CldnePAFp61g0Y,ssc_sli_Vq3NNJdKzbtHfe8WeFbDg9);}};}static
NeParameterInfo ssc_sli_kEiFBbYVTBpUc5eIasBQ82(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A
const*manager){return*(manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh->mParameterInfo);}static boolean_T
ssc_sli_V_tr6RTxRnd1j5a01FYwKB(ssc_sli__9m1LfQ2DwC_cXa8Cjj28A const*manager,
double time,NeParameterBundle const*ssc_core__wmTd2KKOKd7YPG6_QANiL,
NeuDiagnosticManager*ssc_core_kDh9Sdqtd1dhZLBqs4W1eB){(void)(time);(void)(
ssc_core_kDh9Sdqtd1dhZLBqs4W1eB);return(manager->
ssc_sli__X9HoYTA6GhUZPkX6FMtmN->ssc_sli_FwPr_01lCZ_TeivYoKB7Mh)->
mSetParameters((manager->ssc_sli__X9HoYTA6GhUZPkX6FMtmN->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh),(ssc_core__wmTd2KKOKd7YPG6_QANiL));}
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*local_dae_rtp_manager_create(
ssc_sli_kjLv8FL1DDSYaiak95i_aG const*ssc_sli__8ZNW6YU7nGkW9bWBMo_l2){
PmAllocator*a=pm_default_allocator();ssc_sli__9m1LfQ2DwC_cXa8Cjj28A*
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli__9m1LfQ2DwC_cXa8Cjj28A))));ssc_sli_kqioa3Wq9idS_X_JDQovlr*
ssc_sli_k51CpyBIqopkVTskBXuCpi=((a)->mCallocFcn((a),(1),(sizeof(
ssc_sli_kqioa3Wq9idS_X_JDQovlr))));ssc_sli_k51CpyBIqopkVTskBXuCpi->
ssc_sli_FwPr_01lCZ_TeivYoKB7Mh=ssc_sli__8ZNW6YU7nGkW9bWBMo_l2;
ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->ssc_sli__X9HoYTA6GhUZPkX6FMtmN=
ssc_sli_k51CpyBIqopkVTskBXuCpi;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mParameterInfo=
ssc_sli_kEiFBbYVTBpUc5eIasBQ82;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mSetParameters=
ssc_sli_V_tr6RTxRnd1j5a01FYwKB;ssc_sli_ksoYuHDGUqSHXa_wqiOeKh->mDestroy=
ssc_sli__GBQFb1P9g_nX9yezfzkGA;return ssc_sli_ksoYuHDGUqSHXa_wqiOeKh;}
