#include "multibody_model_macros.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_kv3fXx6PfXt7cekeoT00mk
mc_kgKqfPHHGatO_9OUxR4PRK;struct mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;
void(*mc_FapEct1OXaSugDZ6N_u_kA)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH);void(*
mc_FVdv01I3SEC4hD41rxmnRM)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,real_T
mc__d1alWYexptL_X5HTFhbNK);void(*mc_kPHJTxMUjl8Oi1EQSHes2Q)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);void(*
mc__WEKdqi2uo0m_Dm8w8T_ZO)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc__d1alWYexptL_X5HTFhbNK);};typedef struct mc__nZqLQp3m1lFaHyLAzyG2a
mc__39VLhR7TBCGYH016BQq8W;typedef struct mc__UzXDLpnAvdw_eUt0mYuul
mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct mc__sr5lnPbYjO_Wyo_mmPUmd
mc_Fw_IO5LchthA_LoeiSceRf;struct mc__sr5lnPbYjO_Wyo_mmPUmd{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};
#include "ne_std.h"
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_kgrRugFNBJpseX_oy36MXV(char const*
ssc_core_FKUxmi8JO84daTOro9pI0M,mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_core_F2yFvGbtw4lXYqqnP9I3YY,NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "mc_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "ne_std_fwd.h"
typedef struct{char const*ssc_core_FEEIxTw6DLpu_yk_jGffrz;NeSolverParameters
const*ssc_core_F9hWo1tj7uSuViXynXXv5y;}ssc_core_VbDRZ724cspBXLOHnaxIyW;typedef
mc_kQtOKCqS08dIbumyDnHNDL(*ssc_core_VBdYZqyml8GvVDY5Qd4U1_)(
mc__39VLhR7TBCGYH016BQq8W const*,PmRealVector*x,PmRealVector const*
ssc_core_V6MxPEeIW3xrhDyMzumQaB,mc_kQtOKCqS08dIbumyDnHNDL
ssc_core__QM6NQSNn0h8gutSkjedYL,ssc_core_VbDRZ724cspBXLOHnaxIyW);
PMF_DEPLOY_STATIC ssc_core_VBdYZqyml8GvVDY5Qd4U1_
ssc_core__rJ2RjDMAAOC_5yCaQVwS5(void){return NULL;}struct
mc_k577Fzud3mpCe91P_z0Qf_{PmAllocator*ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_VAAiULd60jtNget6Qvf00e;char const*
ssc_core_FlYWWBMoxdWTVHRBIU6TrW;NeSolverParameters const*
ssc_core_FcpIJmczZt0BZuicXfS4A3;};struct mc_FpSYgeBscUCg_qWX4io4Kb{
mc__39VLhR7TBCGYH016BQq8W const*ssc_core_Vu8wy9IGEVWgiDu5nL3zwQ;
mc_FuB6ZnvWHlGVe5AYB_qh1v ssc_core_VPnByizXfG86dX_49PzmU_;
mc_kxnFIpkyuc0YdXbZO41ABc*ssc_core_VtTVlkFFh1Oegq3flxwZFF;};static
mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core___vJv9qjdo4mVDvm_LKzG6(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO){return(
mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF)->
mc__vHH72jqKt44cXWzB3_tSu((mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->
ssc_core_VtTVlkFFh1Oegq3flxwZFF));}static void ssc_core_knw_Jz66UfOCgLEUV3Do3k
(mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP){(mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->
ssc_core_VtTVlkFFh1Oegq3flxwZFF)->mc_FF_Aq2b8Cx_iduzooh_sWO((
mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF),(
mc_kTckK8teUpOlhm8Ippu8XP));}static void ssc_core_Vemm_S8QeGhIbyw738GxPz(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO){(
mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF)->
mc_F_be_I5uNaSddegs3UZPvG((mc_kHt1ybY5z_OofadxN4AZsO->mPrivateData->
ssc_core_VtTVlkFFh1Oegq3flxwZFF));}static mc_kQtOKCqS08dIbumyDnHNDL
ssc_core_kzJL1L79VyGaiHK64HVbmf(mc_kxnFIpkyuc0YdXbZO41ABc const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector*x){mc_kQtOKCqS08dIbumyDnHNDL
ssc_core_k4M7bSEmThKJbirXUDQgS6=mc_VUd8H_Dz0yp8cmQqTd7DxF;PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
ssc_core_VPnByizXfG86dX_49PzmU_.ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;PmRealVector*
ssc_core_VagIBJvwhjlUhTf2ZQ9s9c=pm_V_q_QnwoVVl6fHS_0pLvYo(x,
pm_FbYb_iLqY2hwZTVlVaiqJY);PmRealVector*mc_VRbT1WwZjwW6f5YGBCFuaD=
pm_V_q_QnwoVVl6fHS_0pLvYo(ssc_core_VagIBJvwhjlUhTf2ZQ9s9c,
pm_FbYb_iLqY2hwZTVlVaiqJY);(void)0;ssc_core_k4M7bSEmThKJbirXUDQgS6=(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF
)->mSolve((ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
ssc_core_VtTVlkFFh1Oegq3flxwZFF),(mc_VRbT1WwZjwW6f5YGBCFuaD));{
ssc_core_VBdYZqyml8GvVDY5Qd4U1_ const ssc_core_kHj27cgeaghOZeeUcZz4eu=
ssc_core__rJ2RjDMAAOC_5yCaQVwS5();if(ssc_core_kHj27cgeaghOZeeUcZz4eu!=NULL){
ssc_core_VbDRZ724cspBXLOHnaxIyW ssc_core_FITehoI3JIKRaHrCWSq5BK;
ssc_core_FITehoI3JIKRaHrCWSq5BK.ssc_core_FEEIxTw6DLpu_yk_jGffrz=
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core_VPnByizXfG86dX_49PzmU_
.ssc_core_FlYWWBMoxdWTVHRBIU6TrW;ssc_core_FITehoI3JIKRaHrCWSq5BK.
ssc_core_F9hWo1tj7uSuViXynXXv5y=ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData
->ssc_core_VPnByizXfG86dX_49PzmU_.ssc_core_FcpIJmczZt0BZuicXfS4A3;
pm_rv_equals_rv(x,ssc_core_VagIBJvwhjlUhTf2ZQ9s9c);
ssc_core_k4M7bSEmThKJbirXUDQgS6=ssc_core_kHj27cgeaghOZeeUcZz4eu(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core_Vu8wy9IGEVWgiDu5nL3zwQ
,x,mc_VRbT1WwZjwW6f5YGBCFuaD,ssc_core_k4M7bSEmThKJbirXUDQgS6,
ssc_core_FITehoI3JIKRaHrCWSq5BK);}}pm_destroy_real_vector(
ssc_core_VagIBJvwhjlUhTf2ZQ9s9c,pm_FbYb_iLqY2hwZTVlVaiqJY);
pm_destroy_real_vector(mc_VRbT1WwZjwW6f5YGBCFuaD,pm_FbYb_iLqY2hwZTVlVaiqJY);
return ssc_core_k4M7bSEmThKJbirXUDQgS6;}static void
ssc_core_k3V3Vc1hG2_x_Xw9XCRIB0(mc_kxnFIpkyuc0YdXbZO41ABc*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core_VPnByizXfG86dX_49PzmU_
.ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF)->mDestroy(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core_VtTVlkFFh1Oegq3flxwZFF
);{void*const ssc_core_V0GNWS8jd2CNjek_jxKpvK=(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx
->mPrivateData);PmAllocator*const ssc_core_kRJQe3tgURpNcTrXYjj8nL=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(ssc_core_V0GNWS8jd2CNjek_jxKpvK){(
ssc_core_kRJQe3tgURpNcTrXYjj8nL)->mFreeFcn(ssc_core_kRJQe3tgURpNcTrXYjj8nL,
ssc_core_V0GNWS8jd2CNjek_jxKpvK);}};{void*const ssc_core_VoOlMUHwMj8iaibcUVWG7X
=(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);PmAllocator*const
ssc_core_VrBWzS4w48pfaqdbB_msWq=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_VoOlMUHwMj8iaibcUVWG7X){(ssc_core_VrBWzS4w48pfaqdbB_msWq)->mFreeFcn(
ssc_core_VrBWzS4w48pfaqdbB_msWq,ssc_core_VoOlMUHwMj8iaibcUVWG7X);}};}static
mc_kxnFIpkyuc0YdXbZO41ABc*ssc_core_F4ov0R79RWKebudGYuVtjI(
mc_kKrwrwNLgB_NYDY0UUZRVA const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
mc__39VLhR7TBCGYH016BQq8W const*mc_VkOVRwyffyOPbanx3qI3TI){PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData->
ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;mc_kxnFIpkyuc0YdXbZO41ABc*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx=(mc_kxnFIpkyuc0YdXbZO41ABc*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
mc_kxnFIpkyuc0YdXbZO41ABc)),(1))));mc_FSKepYWjsK8mbHLmdHWO58*
ssc_core__jUbZ5TudDGfVmrpB7MnwY=(mc_FSKepYWjsK8mbHLmdHWO58*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
mc_FSKepYWjsK8mbHLmdHWO58)),(1))));mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_core_F2yFvGbtw4lXYqqnP9I3YY=ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData
->ssc_core_VAAiULd60jtNget6Qvf00e;ssc_core__jUbZ5TudDGfVmrpB7MnwY->
ssc_core_VtTVlkFFh1Oegq3flxwZFF=(ssc_core_F2yFvGbtw4lXYqqnP9I3YY)->
mc_k_hVWBJWCUlCdPNZka5iZF((ssc_core_F2yFvGbtw4lXYqqnP9I3YY),(
mc_VkOVRwyffyOPbanx3qI3TI));ssc_core__jUbZ5TudDGfVmrpB7MnwY->
ssc_core_Vu8wy9IGEVWgiDu5nL3zwQ=mc_VkOVRwyffyOPbanx3qI3TI;
ssc_core__jUbZ5TudDGfVmrpB7MnwY->ssc_core_VPnByizXfG86dX_49PzmU_= *(
ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData);ssc_core_V8a_FQ2T6YWLgu_s5UfAPx
->mPrivateData=ssc_core__jUbZ5TudDGfVmrpB7MnwY;ssc_core_V8a_FQ2T6YWLgu_s5UfAPx
->mSolve= &ssc_core_kzJL1L79VyGaiHK64HVbmf;ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
mc__vHH72jqKt44cXWzB3_tSu= &ssc_core___vJv9qjdo4mVDvm_LKzG6;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mc_FF_Aq2b8Cx_iduzooh_sWO= &
ssc_core_knw_Jz66UfOCgLEUV3Do3k;ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
mc_F_be_I5uNaSddegs3UZPvG= &ssc_core_Vemm_S8QeGhIbyw738GxPz;
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mDestroy= &ssc_core_k3V3Vc1hG2_x_Xw9XCRIB0;
return ssc_core_V8a_FQ2T6YWLgu_s5UfAPx;}static void
ssc_core_V6YOwo9Gov8i_mkf0agwBp(mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_core__RtkHrrPEelBbDRCt5cBnV){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData->ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa
;(ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData->
ssc_core_VAAiULd60jtNget6Qvf00e)->mDestroy(ssc_core__RtkHrrPEelBbDRCt5cBnV->
mPrivateData->ssc_core_VAAiULd60jtNget6Qvf00e);{void*const
ssc_core_kXqiJlet7_l7WXg7cNMPXz=(ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData
);PmAllocator*const ssc_core_FHfDIOtpwQ8AVm4XRcnAoU=(pm_FbYb_iLqY2hwZTVlVaiqJY
);if(ssc_core_kXqiJlet7_l7WXg7cNMPXz){(ssc_core_FHfDIOtpwQ8AVm4XRcnAoU)->
mFreeFcn(ssc_core_FHfDIOtpwQ8AVm4XRcnAoU,ssc_core_kXqiJlet7_l7WXg7cNMPXz);}};{
void*const ssc_core_FVh6FsKAZwtAXy_X6SZbMy=(ssc_core__RtkHrrPEelBbDRCt5cBnV);
PmAllocator*const ssc_core_VeUiO_Svs7W3XiyzgqyXIt=(pm_FbYb_iLqY2hwZTVlVaiqJY);
if(ssc_core_FVh6FsKAZwtAXy_X6SZbMy){(ssc_core_VeUiO_Svs7W3XiyzgqyXIt)->
mFreeFcn(ssc_core_VeUiO_Svs7W3XiyzgqyXIt,ssc_core_FVh6FsKAZwtAXy_X6SZbMy);}};}
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core_kgrRugFNBJpseX_oy36MXV(char const*
ssc_core_FKUxmi8JO84daTOro9pI0M,mc_kKrwrwNLgB_NYDY0UUZRVA*
ssc_core_F2yFvGbtw4lXYqqnP9I3YY,NeSolverParameters const*
ssc_core_F9hWo1tj7uSuViXynXXv5y,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){if(
ssc_core_F9hWo1tj7uSuViXynXXv5y->mUseMatlabAlgebraicSolver){
mc_kKrwrwNLgB_NYDY0UUZRVA*ssc_core__RtkHrrPEelBbDRCt5cBnV=(
mc_kKrwrwNLgB_NYDY0UUZRVA*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_kKrwrwNLgB_NYDY0UUZRVA)),(1))));
mc_FuB6ZnvWHlGVe5AYB_qh1v*ssc_core_FJ2Y0frA7_Sle9T2qXzJdY=(
mc_FuB6ZnvWHlGVe5AYB_qh1v*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_FuB6ZnvWHlGVe5AYB_qh1v)),(1))));
ssc_core_FJ2Y0frA7_Sle9T2qXzJdY->ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa=
pm_FbYb_iLqY2hwZTVlVaiqJY;ssc_core_FJ2Y0frA7_Sle9T2qXzJdY->
ssc_core_FlYWWBMoxdWTVHRBIU6TrW=ssc_core_FKUxmi8JO84daTOro9pI0M;
ssc_core_FJ2Y0frA7_Sle9T2qXzJdY->ssc_core_VAAiULd60jtNget6Qvf00e=
ssc_core_F2yFvGbtw4lXYqqnP9I3YY;ssc_core_FJ2Y0frA7_Sle9T2qXzJdY->
ssc_core_FcpIJmczZt0BZuicXfS4A3=ssc_core_F9hWo1tj7uSuViXynXXv5y;
ssc_core__RtkHrrPEelBbDRCt5cBnV->mPrivateData=ssc_core_FJ2Y0frA7_Sle9T2qXzJdY;
ssc_core__RtkHrrPEelBbDRCt5cBnV->mc_k_hVWBJWCUlCdPNZka5iZF= &
ssc_core_F4ov0R79RWKebudGYuVtjI;ssc_core__RtkHrrPEelBbDRCt5cBnV->mDestroy= &
ssc_core_V6YOwo9Gov8i_mkf0agwBp;return ssc_core__RtkHrrPEelBbDRCt5cBnV;}return
ssc_core_F2yFvGbtw4lXYqqnP9I3YY;}
