#include "multibody_model_macros.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_Fj_dFIC8mwWzaLFg5PWymM ssc_core_FWI1vmgxdR8me9ofVTzx6T
;typedef struct ssc_core_kzD2duJROPp_feaAjCFfnI ssc_core_VdNJjnSb6_lVXTG3JCLKal
;struct ssc_core_kzD2duJROPp_feaAjCFfnI{PmfMessageId(*
mc_kj_oOGqml_xqaXiiWNvUfG)(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;PmfMessageId(*mCheck)(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;void(*mDestroy)(ssc_core_VdNJjnSb6_lVXTG3JCLKal*);
ssc_core_FWI1vmgxdR8me9ofVTzx6T*mData;};ssc_core_VdNJjnSb6_lVXTG3JCLKal*
ssc_core_VCAwjquo7vCVdyRTBC0d7e(McRealFunction*ssc_core_koVEIOVQ7YKpgLI1DDze9g
,McMatrixFunction*ssc_core__s2Li0w3ytS9bTdqzsL3yT,McMatrixFunction*
ssc_core__ZFWXFEjLlS7Z9rB2YJqNY,boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
boolean_T ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,real_T mc_FfDTppU8N_tOWuLK37x_08,
size_t ssc_core_FhbD3RsEbmlPa1L52gsu55,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_kjBl5aSCPqK8_T48OOvhEj(McMatrixFunction*mc_ky0WCncALplbXL_SNbJkvW,size_t
mc_Fxvltms7Im4baT5ZPxj7f2,size_t mc_knvTkz3vM6t4a9WNgNRMzB,size_t
mc_VGPLyQQmjMlldLbUiddSkc,size_t mc_Fp_w9JW6vqt5eXL55IL0g1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
typedef struct ssc_core_V3scVTYpjYthiPB7SQIxc_ ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8
;typedef struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm ssc_core__SHoBDzmLMOwaLvvD5hSet
;struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm{boolean_T(*
ssc_core_FBsF3SW3Cyp_j5Pu5wPhdl)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;void(*mc_VrNsQKHIiLOFaL3PHRFxZL)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G);void(*mDestroy)(
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core_FeUzPe0YQn4rca7KjD_v4G);
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*mData;};ssc_core__SHoBDzmLMOwaLvvD5hSet*
ssc_core_VlRDyoY8Z4C2Vy6qnfIfjk(NeSystemInputSizes sizes,boolean_T
ssc_core_kFxS3Lt0_2dX_mARPrjLL1,boolean_T ssc_core__5hVjWGkxohgVTAjSVMW3a,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "mc_std_fwd.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_VxEVmLDkbMdz_TOnm0H9bO ssc_core__BPWbVF8WMtGgDZfIci1Sl
;typedef struct ssc_core_VieO23MegiC1gL_vCDuv4X ssc_core_VMqynAgC_yGKXm5AmUS8eA
;struct ssc_core_VieO23MegiC1gL_vCDuv4X{PmfMessageId(*mFactor)(
ssc_core_VMqynAgC_yGKXm5AmUS8eA*s,NeSystemInput const*
mc__XfQXtB6cfd9fyc_v3eEup);PmfMessageId(*mCheck)(
ssc_core_VMqynAgC_yGKXm5AmUS8eA*s,PmRealVector const*
ssc_core__2Pe_i_F4ZdhVag7TbBhYI,PmRealVector const*
ssc_core_kUQBO1dSP8_IVqRAUx4R8G);PmfMessageId(*mSolve)(
ssc_core_VMqynAgC_yGKXm5AmUS8eA*s,PmRealVector const*
ssc_core__2Pe_i_F4ZdhVag7TbBhYI,PmRealVector const*
ssc_core_kUQBO1dSP8_IVqRAUx4R8G);void(*mDestroy)(
ssc_core_VMqynAgC_yGKXm5AmUS8eA*s);ssc_core__BPWbVF8WMtGgDZfIci1Sl*mData;};
ssc_core_VMqynAgC_yGKXm5AmUS8eA*ssc_core_V3vvWaYDbTtn_yNIq_pJe8(
McMatrixFunction*a,McMatrixFunction*b,real_T ssc_core_FxVx8bRexTl3hDBcGo5O3w,
boolean_T ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);struct ssc_core_kesYKdRukKtCYLfoQ0YRJ5{struct{
struct{struct{char const*ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*
ssc_core__qEXoys3NqhTc5aGZjoM0i;}ssc_core_kvZlvqC1JqdoYahhfIqkPq;struct{char
const*ssc_core_kjdqJsJTibClVTmfkrIlFw;char const*
ssc_core__qEXoys3NqhTc5aGZjoM0i;}ssc_core__CmZebP7mNptWDMef1TTIl;}
ssc_core_V01A11djsUSPhydgdGoEM8;struct{struct{char const*
ssc_core__EXYd0BpsApngXjCLU66Qq;char const*ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;}
ssc_core_F0zPq17YGsWWY9f__3XLFE;struct{char const*
ssc_core__EXYd0BpsApngXjCLU66Qq;char const*ssc_core_kaKiE6Wj2W0xjHCgFmOiEO;
char const*ssc_core_V_r1xwjDx7lwguJ2YCpUai;}ssc_core__YmatZ07z0_k_ulppGYT3M;}
ssc_core_kCihPvTAZxpx_H5ihyr_kC;struct{char const*
ssc_core_kpMuDXM8W__FWaXECbGWgq;char const*ssc_core_kZL4P0QovRSWiqHRt1WIC6;}
ssc_core_VWYj_r5wXZ0gbi3aGkkirz;}ssc_core_VNb3dQocUud1ieYKQWZKSY;struct{struct
{char const*ssc_core_V63i95p2LLdg_5IdB06gkx;char const*
ssc_core_VxPQol5LzB_eaDZ9jfsvgc;}ssc_core__aT2sx0pgFCPiP8nk_pRK_;}
ssc_core_VJgtn_cGgzdoceadTmm3t6;struct{struct{char const*
ssc_core_kTdqak9AqCGKcHj5IXmfZe;char const*ssc_core__ZW8YII_QJ4wiHEnAMUOgB;
char const*ssc_core__MNSKfpi3jteauByrrb2q7;}ssc_core_kdx8eT3TLLtTjLxaVSammf;}
ssc_core_Vb8i6ka6Ps0zj9AYvH4Qsj;};extern struct ssc_core_kesYKdRukKtCYLfoQ0YRJ5
ssc_core_VrvQtlpclEKjVTpcoDIr6q;struct ssc_core_Fj_dFIC8mwWzaLFg5PWymM{size_t
mNumStates;size_t ssc_core__oDWakF7Bxxh_9PylKwnyz;real_T
ssc_core_kSsQH5I8Tk_lW9d8fx9Lty;boolean_T ssc_core_kYRPIC8P4o8CYXme9CRbxR;
PmRealVector*ssc_core__X7RtP_1wM02VPXS68Zx6R;McRealFunction*
ssc_core_kGyGEotwUjShe14LUofp94;PmRealVector*ssc_core__hFVQUsTpnClj99vjhFFQ6;
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core__n6jD7kSB20XdmXD3Sv0va;
ssc_core_VMqynAgC_yGKXm5AmUS8eA*ssc_core__unM5qTtoPKKjTEAMTe2A4;PmAllocator*
ssc_core_kSt9Kxk1TVO6eyrizTBhKs;};static PmfMessageId
ssc_core_VvvtjACY8xG2c9TYdEbHGA(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
{ssc_core_FWI1vmgxdR8me9ofVTzx6T*mc__d1alWYexptL_X5HTFhbNK=
ssc_core__u7SkOaBUGdCdLyqO2X23S->mData;if((mc__d1alWYexptL_X5HTFhbNK->
ssc_core__n6jD7kSB20XdmXD3Sv0va)->ssc_core_FBsF3SW3Cyp_j5Pu5wPhdl((
mc__d1alWYexptL_X5HTFhbNK->ssc_core__n6jD7kSB20XdmXD3Sv0va),(
mc_kDRphcAfRHSbf1ZLKEDW9k))){(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__unM5qTtoPKKjTEAMTe2A4)->mFactor((mc__d1alWYexptL_X5HTFhbNK->
ssc_core__unM5qTtoPKKjTEAMTe2A4),(mc_kDRphcAfRHSbf1ZLKEDW9k));}return NULL;}
static PmfMessageId ssc_core_F1ZLGgCVe4SahPgG2aztVN(
ssc_core_VdNJjnSb6_lVXTG3JCLKal const*ssc_core__u7SkOaBUGdCdLyqO2X23S,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k){ssc_core_FWI1vmgxdR8me9ofVTzx6T
*mc__d1alWYexptL_X5HTFhbNK=ssc_core__u7SkOaBUGdCdLyqO2X23S->mData;PmRealVector
const*x= &(mc_kDRphcAfRHSbf1ZLKEDW9k->mX);PmfMessageId id;(void)0;;(void)0;;id
=ssc_core_VvvtjACY8xG2c9TYdEbHGA(ssc_core__u7SkOaBUGdCdLyqO2X23S,
mc_kDRphcAfRHSbf1ZLKEDW9k);if(id!=NULL){return id;}(*((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kGyGEotwUjShe14LUofp94)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__hFVQUsTpnClj99vjhFFQ6),((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kGyGEotwUjShe14LUofp94)->
mc_ko6_hiERTRldgDROOJBQCH));if(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kYRPIC8P4o8CYXme9CRbxR||mc_F1fvRD4xlFhBdyqJtcgdmn(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__hFVQUsTpnClj99vjhFFQ6)>
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kSsQH5I8Tk_lW9d8fx9Lty){
mc__aNO1s5qwzt6fXwft5YgCz(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__X7RtP_1wM02VPXS68Zx6R);mc_VqP4HesDIf47bDn5teE2H2(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__X7RtP_1wM02VPXS68Zx6R,0,x,0,
mc__d1alWYexptL_X5HTFhbNK->ssc_core__oDWakF7Bxxh_9PylKwnyz);
mc_V7hiVZfxKK0Uj9rPai4LYw(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__hFVQUsTpnClj99vjhFFQ6,-1.0);id=(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__unM5qTtoPKKjTEAMTe2A4)->mSolve((mc__d1alWYexptL_X5HTFhbNK->
ssc_core__unM5qTtoPKKjTEAMTe2A4),(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__X7RtP_1wM02VPXS68Zx6R),(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__hFVQUsTpnClj99vjhFFQ6));if(id!=NULL){return
ssc_core_VrvQtlpclEKjVTpcoDIr6q.ssc_core_VNb3dQocUud1ieYKQWZKSY.
ssc_core_VWYj_r5wXZ0gbi3aGkkirz.ssc_core_kZL4P0QovRSWiqHRt1WIC6;}
mc_VqP4HesDIf47bDn5teE2H2(x,0,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__X7RtP_1wM02VPXS68Zx6R,0,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__oDWakF7Bxxh_9PylKwnyz);}return NULL;}static PmfMessageId
ssc_core__6dfCjZ_zBdiV5E9_8E3CG(ssc_core_VdNJjnSb6_lVXTG3JCLKal const*
ssc_core__u7SkOaBUGdCdLyqO2X23S,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
{ssc_core_FWI1vmgxdR8me9ofVTzx6T*mc__d1alWYexptL_X5HTFhbNK=
ssc_core__u7SkOaBUGdCdLyqO2X23S->mData;PmfMessageId id=
ssc_core_VvvtjACY8xG2c9TYdEbHGA(ssc_core__u7SkOaBUGdCdLyqO2X23S,
mc_kDRphcAfRHSbf1ZLKEDW9k);if(id!=NULL){return id;}(*((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kGyGEotwUjShe14LUofp94)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc_kDRphcAfRHSbf1ZLKEDW9k),(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__hFVQUsTpnClj99vjhFFQ6),((
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kGyGEotwUjShe14LUofp94)->
mc_ko6_hiERTRldgDROOJBQCH));return(mc_F1fvRD4xlFhBdyqJtcgdmn(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__hFVQUsTpnClj99vjhFFQ6)<=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kSsQH5I8Tk_lW9d8fx9Lty)?NULL:
ssc_core_VrvQtlpclEKjVTpcoDIr6q.ssc_core_VNb3dQocUud1ieYKQWZKSY.
ssc_core_VWYj_r5wXZ0gbi3aGkkirz.ssc_core_kpMuDXM8W__FWaXECbGWgq;}static void
ssc_core_FevuEParsHxyZ9TTQfC3_S(ssc_core_VdNJjnSb6_lVXTG3JCLKal*
pm__lqjegyKuwStj56WZLiC_e){ssc_core_FWI1vmgxdR8me9ofVTzx6T*d=
pm__lqjegyKuwStj56WZLiC_e->mData;PmAllocator*a=d->
ssc_core_kSt9Kxk1TVO6eyrizTBhKs;pm_destroy_real_vector(d->
ssc_core__X7RtP_1wM02VPXS68Zx6R,a);(d->ssc_core_kGyGEotwUjShe14LUofp94)->
mDestroy(d->ssc_core_kGyGEotwUjShe14LUofp94);pm_destroy_real_vector(d->
ssc_core__hFVQUsTpnClj99vjhFFQ6,a);(d->ssc_core__n6jD7kSB20XdmXD3Sv0va)->
mDestroy(d->ssc_core__n6jD7kSB20XdmXD3Sv0va);(d->
ssc_core__unM5qTtoPKKjTEAMTe2A4)->mDestroy(d->ssc_core__unM5qTtoPKKjTEAMTe2A4)
;{void*const ssc_core__2n2PSHTnMORhTaa0dlrtR=(d);PmAllocator*const
ssc_core_VRP7NPBDEFCffyu0bQU0wD=(a);if(ssc_core__2n2PSHTnMORhTaa0dlrtR){(
ssc_core_VRP7NPBDEFCffyu0bQU0wD)->mFreeFcn(ssc_core_VRP7NPBDEFCffyu0bQU0wD,
ssc_core__2n2PSHTnMORhTaa0dlrtR);}};{void*const ssc_core_F5CH8GVD174dWaUTIal3Iu
=(pm__lqjegyKuwStj56WZLiC_e);PmAllocator*const ssc_core_VRAv3A99MXOnbXfmRcb7pO
=(a);if(ssc_core_F5CH8GVD174dWaUTIal3Iu){(ssc_core_VRAv3A99MXOnbXfmRcb7pO)->
mFreeFcn(ssc_core_VRAv3A99MXOnbXfmRcb7pO,ssc_core_F5CH8GVD174dWaUTIal3Iu);}};}
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core_VCAwjquo7vCVdyRTBC0d7e(McRealFunction
*ssc_core_koVEIOVQ7YKpgLI1DDze9g,McMatrixFunction*
ssc_core__s2Li0w3ytS9bTdqzsL3yT,McMatrixFunction*
ssc_core__ZFWXFEjLlS7Z9rB2YJqNY,boolean_T ssc_core_kFxS3Lt0_2dX_mARPrjLL1,
boolean_T ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,real_T mc_FfDTppU8N_tOWuLK37x_08,
size_t ssc_core_FhbD3RsEbmlPa1L52gsu55,PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc){
ssc_core_VdNJjnSb6_lVXTG3JCLKal*ssc_core__u7SkOaBUGdCdLyqO2X23S=(
ssc_core_VdNJjnSb6_lVXTG3JCLKal*)(((mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((
mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(ssc_core_VdNJjnSb6_lVXTG3JCLKal)),(1))));
ssc_core_FWI1vmgxdR8me9ofVTzx6T*mc__d1alWYexptL_X5HTFhbNK=(
ssc_core_FWI1vmgxdR8me9ofVTzx6T*)(((mc_FZx3iFiX1YW7j5eEojoAPc)->mCallocFcn((
mc_FZx3iFiX1YW7j5eEojoAPc),(sizeof(ssc_core_FWI1vmgxdR8me9ofVTzx6T)),(1))));
size_t ssc_core_kWAFYs9e5LChXqH2wQXohB=ssc_core__s2Li0w3ytS9bTdqzsL3yT->
mc_kjWUPQN_Ui4d_enzFJIsF_->mNumCol;(void)0;;mc__d1alWYexptL_X5HTFhbNK->
mNumStates=ssc_core_kWAFYs9e5LChXqH2wQXohB;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__oDWakF7Bxxh_9PylKwnyz=ssc_core_FhbD3RsEbmlPa1L52gsu55;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kSsQH5I8Tk_lW9d8fx9Lty=
mc_FfDTppU8N_tOWuLK37x_08;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kYRPIC8P4o8CYXme9CRbxR=ssc_core_kFxS3Lt0_2dX_mARPrjLL1;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__X7RtP_1wM02VPXS68Zx6R=
pm_create_real_vector(ssc_core_FhbD3RsEbmlPa1L52gsu55,
mc_FZx3iFiX1YW7j5eEojoAPc);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kGyGEotwUjShe14LUofp94=ssc_core_koVEIOVQ7YKpgLI1DDze9g;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__hFVQUsTpnClj99vjhFFQ6=
pm_create_real_vector(ssc_core__s2Li0w3ytS9bTdqzsL3yT->
mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,mc_FZx3iFiX1YW7j5eEojoAPc);
mc__d1alWYexptL_X5HTFhbNK->ssc_core__n6jD7kSB20XdmXD3Sv0va=
ssc_core_VlRDyoY8Z4C2Vy6qnfIfjk(neu_get_system_input_sizes((NeSystemInput const
*)((ssc_core__s2Li0w3ytS9bTdqzsL3yT)->mc_FXz9GdGvpOKnh5e2dYstBe((
ssc_core__s2Li0w3ytS9bTdqzsL3yT)))),ssc_core_kFxS3Lt0_2dX_mARPrjLL1,!
ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,mc_FZx3iFiX1YW7j5eEojoAPc);{McMatrixFunction*
ssc_core_krIZILlcemKHhyc6Vtt_ax=mc_kjBl5aSCPqK8_T48OOvhEj(
ssc_core__s2Li0w3ytS9bTdqzsL3yT,0,ssc_core__s2Li0w3ytS9bTdqzsL3yT->
mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,0,ssc_core_FhbD3RsEbmlPa1L52gsu55,
mc_FZx3iFiX1YW7j5eEojoAPc);McMatrixFunction*ssc_core__Qw41bwGDN8IXqM6VY_qfZ=
mc_kjBl5aSCPqK8_T48OOvhEj(ssc_core__ZFWXFEjLlS7Z9rB2YJqNY,0,
ssc_core__ZFWXFEjLlS7Z9rB2YJqNY->mc_kjWUPQN_Ui4d_enzFJIsF_->mNumRow,0,
ssc_core_FhbD3RsEbmlPa1L52gsu55,mc_FZx3iFiX1YW7j5eEojoAPc);
mc__d1alWYexptL_X5HTFhbNK->ssc_core__unM5qTtoPKKjTEAMTe2A4=
ssc_core_V3vvWaYDbTtn_yNIq_pJe8(ssc_core_krIZILlcemKHhyc6Vtt_ax,
ssc_core__Qw41bwGDN8IXqM6VY_qfZ,mc_FfDTppU8N_tOWuLK37x_08,
ssc_core_VJb7Gs0XdZ4Lfu58z8BbCQ,mc_FZx3iFiX1YW7j5eEojoAPc);}
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kSt9Kxk1TVO6eyrizTBhKs=
mc_FZx3iFiX1YW7j5eEojoAPc;ssc_core__u7SkOaBUGdCdLyqO2X23S->
mc_kj_oOGqml_xqaXiiWNvUfG=ssc_core_F1ZLGgCVe4SahPgG2aztVN;
ssc_core__u7SkOaBUGdCdLyqO2X23S->mCheck=ssc_core__6dfCjZ_zBdiV5E9_8E3CG;
ssc_core__u7SkOaBUGdCdLyqO2X23S->mDestroy=ssc_core_FevuEParsHxyZ9TTQfC3_S;
ssc_core__u7SkOaBUGdCdLyqO2X23S->mData=mc__d1alWYexptL_X5HTFhbNK;return
ssc_core__u7SkOaBUGdCdLyqO2X23S;}
