#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VWJbTwnVZB_LVqIIM_COT0{int32_T mc_FvxKbdtfPKOYaymjtthQ0G,
mc__0REJ38_cKO_bunM1JCRT_,id;struct mc_VWJbTwnVZB_LVqIIM_COT0*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;}
mc_FSz7cV1MCGScXq_M5VT121;typedef struct mc_kjlHS2Mzxsh6gyVZ329fra{
mc_FSz7cV1MCGScXq_M5VT121*mc__a1o_SOX2HC3f9QpH_hO5s;PmIntVector*
mc__5uLb2__blGtb9EQ9Zwa2_;PmIntVector*mQ;}mc_F9HbKNDZMeOehmlKWGUdea;typedef
struct mc__fV9rOH7ci_OWykNO7xTBO{size_t mc_VLHhnPUiNQpve5VIL9P3O9,n;int32_T*
mc_FvxKbdtfPKOYaymjtthQ0G,*mc__0REJ38_cKO_bunM1JCRT_,*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;int32_T*
pm__lqjegyKuwStj56WZLiC_e,*mc__AExROh1PVWNeP7hmMWuJv;}
mc_FwUXSPCwCAC_jydGHlCZxe;PmIntVector*mc__oCV63DXBpKVZL_8tU2Wiz(
mc_FSz7cV1MCGScXq_M5VT121 const*mc_VPPSxR3RRt0pXLadx2tWo7,PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
mc__RLQweDZtv0hhLXz_f8MMi(mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt)
;mc_FSz7cV1MCGScXq_M5VT121*mc_VCdOZjcBUFORayuNvO7rtI(mc_FSz7cV1MCGScXq_M5VT121
*mc_Fxl4i6XHkE8cY9kYmlJixt);void mc_VbHMSzzYu5_WZiNG_fSW8Q(
mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt,int32_T
mc_FvxKbdtfPKOYaymjtthQ0G);int32_T mc__1AbngzPnBGnXXDldWop_b(
mc_FSz7cV1MCGScXq_M5VT121*mc_VPPSxR3RRt0pXLadx2tWo7);void
mc_VBCIjXiCCT_RXmHVT9WPVa(mc_F9HbKNDZMeOehmlKWGUdea*mc_VpSwxG2uxL4JaLmMQqUqTJ)
;mc_FwUXSPCwCAC_jydGHlCZxe*mc_F79LLfWDdKORZ1K7KKqAke(mc_F9HbKNDZMeOehmlKWGUdea
const*mc_VpSwxG2uxL4JaLmMQqUqTJ);mc_F9HbKNDZMeOehmlKWGUdea*
mc_perm_data_from_flat(mc_FwUXSPCwCAC_jydGHlCZxe const*
mc_Fw6WJxuximC4jHgRLzUSDo);void mc_Vq5AUJWyc3xVgP5Ff1_aP6(
mc_FwUXSPCwCAC_jydGHlCZxe*mc_Fw6WJxuximC4jHgRLzUSDo);
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
typedef enum{ssc_sli_kiIb5xamJm8uXPyOkLeM64= -1,ssc_sli_FRFqZTqvUYlL_1GmhnSKa9
,ssc_sli_F_n1U4dfhIKmZeTb79_bhk,ssc_sli_Vje8c4NwMs8edaUv9kAKU5,
ssc_sli_F95A2pmjwJGycuR83ALBWW,ssc_sli_FRC3ujZIQjdba9ZBxy4ztV}
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ;typedef struct ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv
ssc_sli_FTmXA5ksLdxWam9tKEDDRp;typedef union ssc_sli_V3VjUqcAjgGUfa9pjdr9Vc{
PmIntVector mMODE;PmRealVector mY;PmRealVector ssc_sli_kxq2De1a8BxzemrdMYbh_Z;
PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;PmIntVector
mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector mUPDATE_R;
PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;PmRealVector
mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector ssc_sli_VjGKBH58LAdsYPWWs6sfbL;PmRealVector mLOG;}
ssc_sli_kkoV3MWI3Olsj9ue_OTrKB;typedef enum ssc_sli__gFYpQJuFtpEfTSOOLoPeL{
ssc_sli_kcaKKN8GXoxUdyPIz9ME4P= -1,ssc_sli_VFlLQfEII_dCjPOLZCKl1h,
ssc_sli_FQmAUq5mRNGbVih2F3PCCN,ssc_sli_FHA50iTf0YOSaPrq60uYIa,
ssc_sli__d4NvF_TU8xhiPidhlSBeU,ssc_sli_kje3FEfA_VOecqlGobEPlW,
ssc_sli_V2lBgEm_1wOKgP3OF7OhA2,ssc_sli__HZXcTW2uIp1b5VW7Lmaiz,
ssc_sli__iC2umSSBnhLdaou8jCK4Q,ssc_sli__cdqw5QDTiWb_HxgGzJupf,
ssc_sli_VzRYNhOLez0fcahY6OfqAT,ssc_sli_ksyP1mhwOx_gdi_qxA1XwQ,
ssc_sli_FdbT7DDFOod_gD62wqPcy_,ssc_sli_FxDcIIX1_0WChuVyeYIziJ,
ssc_sli_km8PqndzZYCHbPN_lUtQcC,ssc_sli_Fh3EMcmCEi0cfaU6jdkIj2,
ssc_sli_k2mBp0rugDOniPAiyz8Hig,ssc_sli_FPv0_UNPp8__hPT18mmlhp,
ssc_sli_kxwvUNoEGCOiceCilpf1YD,ssc_sli__nuLYOAWg4luhub2duGQQ_,
ssc_sli_kjrjD1N2_uWBXaVD9TSx7N,ssc_sli_VLEO4HXvRlGQaqqGghTyqa,
ssc_sli__kD90nzGGZSGWTWEkw1Cis,ssc_sli_k8wcDa_7rDts_9nPV5dfjq,
ssc_sli_VujW_EuJpidTduLntgaxe6}ssc_sli_Vfu07t_igc0ehHkC_w2Ar_;typedef int32_T(
*ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5)(ssc_sli_FTmXA5ksLdxWam9tKEDDRp const*,
NeDynamicSystemInput const*,ssc_sli_kkoV3MWI3Olsj9ue_OTrKB*);struct
ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv{ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5 mMethods[
ssc_sli_VujW_EuJpidTduLntgaxe6];size_t ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t
ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t mNumAsserts;NeAssertData const*
mAssertData;size_t mNumAssertRanges;NeRange const*mAssertRanges;size_t
mNumInitialAsserts;NeAssertData const*mInitialAssertData;size_t
mNumInitialAssertRanges;NeRange const*mInitialAssertRanges;NeParameterInfo
mParameterInfo;PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;};typedef struct ssc_sli_knlRBEvE2xlTdL9XQDsraA
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO;typedef struct ssc_sli__M0yHGxYdRh6WeZsp03MsF
ssc_sli_ktYRHip3ZVhEdLZEQWORqW;typedef struct ssc_sli__C7xfBs4_wtZdybDh_1S17
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ;typedef union ssc_sli_kEJscBISiC0cW1zDnm5FFI{
PmSparsityPattern mMCON_P;PmRealVector mMCON;PmSparsityPattern mMPAR_P;
PmRealVector mMPAR;PmSparsityPattern mMNL_P;PmRealVector mMNL;
PmSparsityPattern ssc_sli__iV7cpieH5lkhLu3Lg9TbF;PmRealVector
ssc_sli_kpJ_qciQSWpsiPiK3aYpC6;PmSparsityPattern ssc_sli_FCUwBAadDl4jdTbQJs191b
;PmRealVector ssc_sli__4wk9aw_kxhdamxJBndVFp;PmSparsityPattern
ssc_sli_kpP4jzbAmSSabDQ2Rr8bL8;PmRealVector ssc_sli_kKsgUsw2JgtEYPjXL27qpf;
PmRealVector ssc_sli_FisUhCWjCaKZVHMV_vZE5q;PmRealVector mF;PmRealVector
ssc_sli__EEaI0glzV_ziunIayuQB_;PmIntVector mMODE;PmBoolVector mSLF;}
ssc_sli_Vp0c29ygDdlujTOV9DIZY0;typedef enum ssc_sli_VD2_Ev_HuH0of9gNrHze9d{
ssc_sli_VXnsMGX_7cGRb55H42tfn7= -1,ssc_sli_k_8QN9x5_k42cyQrpZzjsI,
ssc_sli_kqMvQKKxuVtEea_8OzY2TM,ssc_sli_VfTboTvpAHCDgqUBkJD5Rl,
ssc_sli_k2Owy_sJ_40uh9KZRFIdY5,ssc_sli_kmQ2_m3O6DG6euIv_XuxVg,
ssc_sli_VQO8dLIZX78oa5taxlg_vo,ssc_sli_V7DyxzVA0QGofTFR6YdqYq,
ssc_sli__DRGltAScIGfeu43CxFuG8,ssc_sli__sxV91jCfEGzYXaVBkddIG,
ssc_sli_k0IoR8Wj3MdBiLa4ZtAvTI,ssc_sli_kFNU_9_j_MOSead4baHt3T,
ssc_sli_Vx3D_PUFnUhXeH6lNfeh3d,ssc_sli__pmgH1Up57xCbH_C454qdO,
ssc_sli_kVzQQaaqlPt8bmsY4qvPjV,ssc_sli_kTfE4dqxl7OZdqxWw7pewy,
ssc_sli_VazOOCfCtUhdYPCvduXfsJ,ssc_sli__a5HvR7wGotUf9fcjCj4Zw,
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C}ssc_sli_FSls2IGSVBpdeeBJHp6ST7;typedef int32_T(
*ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT)(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*,
NeDynamicSystemInput const*,ssc_sli_Vp0c29ygDdlujTOV9DIZY0*);typedef enum
ssc_sli__I1_0bn1tlpndTZaRA_ZPl{ssc_sli_kIVETWACXbp0d94SP8_dc1= -1,
ssc_sli_F5_rBq64Lj4aWXXU0PyiUb,ssc_sli_FshPfGethuxwX9btxT6saT,
ssc_sli__uxzr382yeG7jXfsoRvs2Z}ssc_sli_V79S98fiH1S7byo5F9wnzk;typedef
PmSizeVector*ssc_sli__C96EutllrWlgykXJW4e3Y;struct
ssc_sli_koMvWW1l_F_oi5bwovAr78{PmSparsityPattern*mPattern;};struct
ssc_sli__M0yHGxYdRh6WeZsp03MsF{PmSparsityPattern*mPattern;PmRealVector*mPr;};
struct ssc_sli_knlRBEvE2xlTdL9XQDsraA{ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT mMethods[
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C];ssc_sli_ktYRHip3ZVhEdLZEQWORqW
ssc_sli_kb5sBAIsNGx3h5TSZDK2nO[ssc_sli__uxzr382yeG7jXfsoRvs2Z];
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ*ssc_sli__he79Qtc4y4abmydbMrr9d;size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_k3ro8_fNFeG3YHRPCSyK_y;size_t
ssc_sli_VimjrZhJPvSkgeFbqT7DNg;size_t ssc_sli_Vd47fO4esQxG_HpE1mPb9b;size_t
ssc_sli_F0sp_kii_WGhgeeqy_FSs6;boolean_T ssc_sli_Vq7NNhAfxIO_j9IbOG6sAS;
NeDynamicSystemInputSizes mSizes;ssc_sli__C96EutllrWlgykXJW4e3Y
ssc_sli__jDRUOD243tjgTxKYEsbsv[NE_NUM_DYNAMIC_SYSTEM_INPUT_ID];PmIntVector*
ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*ssc_sli__ysspeBWLwt9fe39xFzdmF;
PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ
ssc_sli_FA2YAvRyL2h_f9kmmok0RW;boolean_T ssc_sli_V6uMeGVfspW_ju_lkeNWOq;};
typedef struct ssc_sli__we9OgtXM80Beq3Pau0ORa ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ;
typedef union ssc_sli_kZbOKlPIFU_2ZqIJ7Wxuxt{PmSparsityPattern mM_P;
PmRealVector mM;PmRealVector mF;PmSparsityPattern
ssc_sli__aw0Y7gxbhS0_LvT4MtW1M;PmRealVector mJ;}ssc_sli_FXl61xRLPE47iP1Q_pvk2u
;typedef enum ssc_sli_V1Ph_XOAJoKRYqSqeTnmEx{ssc_sli_V3bEzwx1u0lOVPYRbuCqcW= -
1,ssc_sli_Fn41P1GumQ42i9T8pr7NwB,ssc_sli_F2Ws5ikk0qOaWyeJpDP8bj,
ssc_sli_FYPImDMfyFhqYmN4WZY0Gv,ssc_sli_kAf_QyKmY34ZVLgh19055f,
ssc_sli_kKEx7mxjxwKzZTWlJaaDbC,ssc_sli_FEtyoYrn_ttHf99kNFRkob}
ssc_sli_FD25vRYmqOCeX9QMP0Yb86;typedef int32_T(*ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW
)(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*,NeDynamicSystemInput const*,
ssc_sli_FXl61xRLPE47iP1Q_pvk2u*);struct ssc_sli__we9OgtXM80Beq3Pau0ORa{
ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW mMethods[ssc_sli_FEtyoYrn_ttHf99kNFRkob];size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;
PmIntVector*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;};typedef struct
ssc_sli_VAuysnx4S7lBcPba8gefmX ssc_sli_kTxQKABEQA__dXDaX6_8lx;struct
ssc_sli_VAuysnx4S7lBcPba8gefmX{NeDynamicSystemInputSizes mSizes;PmIntVector*
ssc_sli_FtEj7nrAMw8EX1WVETDajL;ssc_sli_FTmXA5ksLdxWam9tKEDDRp*
ssc_sli_ki5qToeyQ7tPheF11zZqgB;size_t ssc_sli__MBuKzK8US4ghTfNeJrQSZ;
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO**ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH;
ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ*ssc_sli__Rb1pGJJ50KLfagQM39h_L;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;
mc_F9HbKNDZMeOehmlKWGUdea*(*ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,size_t mc_k0zHKt3B8EloaeisOobs3u);void(*
ssc_sli_kkIk538kkH4PjT_BdbbDnq)(ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,NeDynamicSystemInput**ssc_sli_FI3oLMQhBMhqhTN_ohgA9w
);void(*mDestroy)(ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM);};
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);
#include "ne_std.h"
typedef struct ssc_sli__nZTUaqBX_8WjLa9SNF8OI ssc_sli_FzLpHYC8pbORfLs1HQ5tx8;
typedef struct ssc_sli_VM8UVTrsCYCuX54rf7azJe ssc_sli_VUa2TSfWIUlueyhCKkORiK;
struct ssc_sli_VM8UVTrsCYCuX54rf7azJe{ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*
mPrivateData;PmSparsityPattern const*mPattern;NeDynamicSystemInputSizes mSizes
;PmIntVector const*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector const*
ssc_sli__ysspeBWLwt9fe39xFzdmF;PmIntVector const*
ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector const*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector const*
ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;void(*
ssc_sli_k98doWegV6xNVLpUJF775m)(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_Vewa2aEFH2p4eyRGN0BdA4)
(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_FrnJvV2zDsWGhiwD7eB0IS)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmIntVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli__WkMCltDVadkZuQRjGYmXq)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector const*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*ssc_sli_FsX__XbkKPdEYTPBZsyQSK)(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,
NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(ssc_sli_VUa2TSfWIUlueyhCKkORiK*);};
ssc_sli_VUa2TSfWIUlueyhCKkORiK*ssc_sli__oVk_KhXeghpf5BXrX5fRj(
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*ssc_sli__IqjUOFkW8_nauH_Moi97j);
#include "pm_std.h"
#include "pm_std.h"
PmAllocator*pm_default_allocator(void);
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};McMatrixFunction
*mc_VmBCniFWwo8BYmiUfCse67(McMatrixFunction*mc_kh0AzKGHcX8tfeDoNul_TU,
McMatrixFunction*mc__Oliq0seKPWShTNRpvAarb,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc__4fFDnwFhbSuaLZ4NJB06a(
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,void const*mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_Vl4aaEoJK_KwYaROiytCdQ(
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,void const*mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_keWxvg6kivCmgu_AS8haey(
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,McMatrixFunction*pm__sjTRWOMR4WzZisVeB2fYm,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);typedef struct mc_knhZCtHxFBxXg5tgJuUCEK
mc_kZbwbT_kvDGzcDUgumpykL;typedef struct mc_FBH8iD7u05pSXm_5ubaK2V
mc_FdKBw8fvqLW3Y5joYOEBEt;struct mc_FBH8iD7u05pSXm_5ubaK2V{
mc_kZbwbT_kvDGzcDUgumpykL*mData;void(*mEvaluate)(mc_FdKBw8fvqLW3Y5joYOEBEt
const*mc__3hSkv0Wz8pGW5lmLxQaXM,void const*mc_kDRphcAfRHSbf1ZLKEDW9k);
McMatrixFunction*(*mc_FBMgSgsPcuhAfqqbis_q6w)(mc_FdKBw8fvqLW3Y5joYOEBEt const*
mc__3hSkv0Wz8pGW5lmLxQaXM);void(*mDestroy)(mc_FdKBw8fvqLW3Y5joYOEBEt*
mc__3hSkv0Wz8pGW5lmLxQaXM);};mc_FdKBw8fvqLW3Y5joYOEBEt*
mc_V7lAu3dITJGBeukLWd4htI(McMatrixFunction*mc_FVG9mW_iV00Sd5jvvtdbAo,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc_VjS2AX9knfCIa1JgE0u_Mq(McMatrixFunction*mc_ky0WCncALplbXL_SNbJkvW,
PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc__SEcNGNHbdG4d1gvLmKmKO(McMatrixFunction*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_F8fT7naL9bOcimTADCVzTC,PmIntVector*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void mc_FT3m0bbChpCrZTNz__fpXy(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmIntVector*
mc_FHEC_Zdq4o_xh1izBH8bUo,PmSparsityPattern*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_F8fT7naL9bOcimTADCVzTC,PmIntVector*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);McMatrixFunction*
ssc_sli__0xRjfYIJ4GUb92KcJDY4u(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*
ssc_sli__IqjUOFkW8_nauH_Moi97j,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_V1iOeFwioxKijmwSQumlRX(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO
const*ssc_sli__IqjUOFkW8_nauH_Moi97j,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McRealFunction*ssc_sli_kzgzBnb4bl4_eapKdiTm8H(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO
const*ssc_sli__IqjUOFkW8_nauH_Moi97j,ssc_sli_FSls2IGSVBpdeeBJHp6ST7
ssc_sli__D_acN46eH8vdLtx_ioY6M,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
McMatrixFunction*ssc_sli_V1bLIPK3dT4ziu_gYZjDKI(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO
const*ssc_sli__IqjUOFkW8_nauH_Moi97j,ssc_sli_FSls2IGSVBpdeeBJHp6ST7
ssc_sli__D_acN46eH8vdLtx_ioY6M,ssc_sli_FSls2IGSVBpdeeBJHp6ST7
ssc_core_V_DRESe0gNtOfHGOtCHo2g,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);struct
ssc_sli__nZTUaqBX_8WjLa9SNF8OI{McMatrixFunction*ssc_sli_kXSv4dTv8At6VLv5OlDCaf
;McMatrixFunction*ssc_sli_kniAJrAWeVl_hy2gsFuPcT;McMatrixFunction*mM;
McRealFunction*mF;mc_FdKBw8fvqLW3Y5joYOEBEt*mJ;PmBoolVector*
ssc_sli__mvMRZrJTMKeequEOzKRS2;PmRealVector*ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ;
PmRealVector*ssc_sli_kdl2GDLXpZl1imsJLXV_I4;PmRealVector*
ssc_sli_VD97icaQKhOjVeP8EL6yNh;PmRealVector*ssc_sli_VdUKc9M2JcK__H3HdvujQd;
PmRealVector*ssc_sli_kozZEBqdu9lJhTcWextajd;ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO
const*ssc_sli__eGKFuP4aYCGf1kIlYAYvg;};static void
ssc_sli__Ac4_9Y1itphg1cl_q6oBJ(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF){ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;(d->mJ)->mEvaluate((d->mJ),(
mc__XfQXtB6cfd9fyc_v3eEup));(*((d->ssc_sli_kXSv4dTv8At6VLv5OlDCaf)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc__XfQXtB6cfd9fyc_v3eEup),(
mc_V2mBNcV1EqCifyH9UdCbkF),((d->ssc_sli_kXSv4dTv8At6VLv5OlDCaf)->
mc_ko6_hiERTRldgDROOJBQCH));}static void ssc_sli_Vn_kP_HwAv_xhe2eirjKdP(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF){ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;(void)0;(*((d->mF)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc__XfQXtB6cfd9fyc_v3eEup),(
mc_V2mBNcV1EqCifyH9UdCbkF),((d->mF)->mc_ko6_hiERTRldgDROOJBQCH));if(((size_t)(
((d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT->mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(d->
ssc_sli_kniAJrAWeVl_hy2gsFuPcT->mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol])))>0){
size_t i,j=0;size_t ssc_core_V5LBNJCbhICNbmMG_hLaZ6=mc_V2mBNcV1EqCifyH9UdCbkF
->mN;(void)0;(void)0;for(i=0;i<ssc_core_V5LBNJCbhICNbmMG_hLaZ6;i++){if(d->
ssc_sli__mvMRZrJTMKeequEOzKRS2->mX[i]){int ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_sli_F7t5lALbnyS5i9RsYavPtr->mX[i];d->
ssc_sli_VD97icaQKhOjVeP8EL6yNh->mX[j]=mc__XfQXtB6cfd9fyc_v3eEup->mX.mX[
ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT];j++;}}(d->mJ)->mEvaluate((d->mJ),(
mc__XfQXtB6cfd9fyc_v3eEup));(*((d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT)->
mc_VAvAkWmhpT_WWme_3E1U91))((mc__XfQXtB6cfd9fyc_v3eEup),(d->
ssc_sli_VdUKc9M2JcK__H3HdvujQd),((d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT)->
mc_ko6_hiERTRldgDROOJBQCH));mc_kM_Y9u9U2F_Cf9sWAtmMMu(
mc_V2mBNcV1EqCifyH9UdCbkF,d->ssc_sli_VdUKc9M2JcK__H3HdvujQd,d->
ssc_sli_kniAJrAWeVl_hy2gsFuPcT->mc_kjWUPQN_Ui4d_enzFJIsF_,d->
ssc_sli_VD97icaQKhOjVeP8EL6yNh);}}static void ssc_sli_Vslugpw_q2dfaTtIFuEec7(
ssc_sli_VUa2TSfWIUlueyhCKkORiK const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector
const*x,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF){ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;size_t ssc_core_V5LBNJCbhICNbmMG_hLaZ6
=mc_V2mBNcV1EqCifyH9UdCbkF->mN;(void)0;(void)0;d->
ssc_sli__eGKFuP4aYCGf1kIlYAYvg->mMethods[ssc_sli__pmgH1Up57xCbH_C454qdO](d->
ssc_sli__eGKFuP4aYCGf1kIlYAYvg,mc__XfQXtB6cfd9fyc_v3eEup,(
ssc_sli_Vp0c29ygDdlujTOV9DIZY0*)d->ssc_sli_kdl2GDLXpZl1imsJLXV_I4);(*((d->mF)
->mc_VAvAkWmhpT_WWme_3E1U91))((mc__XfQXtB6cfd9fyc_v3eEup),(
mc_V2mBNcV1EqCifyH9UdCbkF),((d->mF)->mc_ko6_hiERTRldgDROOJBQCH));
mc_FGkd8Riw6p4eaDCAbwBVPv(mc_V2mBNcV1EqCifyH9UdCbkF,d->
ssc_sli_kdl2GDLXpZl1imsJLXV_I4);mc__aNO1s5qwzt6fXwft5YgCz(d->
ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ);(*((d->mM)->mc_VAvAkWmhpT_WWme_3E1U91))((
mc__XfQXtB6cfd9fyc_v3eEup),(d->ssc_sli_kozZEBqdu9lJhTcWextajd),((d->mM)->
mc_ko6_hiERTRldgDROOJBQCH));mc_kM_Y9u9U2F_Cf9sWAtmMMu(d->
ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ,d->ssc_sli_kozZEBqdu9lJhTcWextajd,d->mM->
mc_kjWUPQN_Ui4d_enzFJIsF_,x);mc__w_RD4J1MZlqcL7as8FLdk(
mc_V2mBNcV1EqCifyH9UdCbkF,d->ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ);}static void
ssc_sli_Vm7Ss_iPTMtWjmguiRW_co(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF){ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;(void)0;d->
ssc_sli__eGKFuP4aYCGf1kIlYAYvg->mMethods[ssc_sli_VazOOCfCtUhdYPCvduXfsJ](d->
ssc_sli__eGKFuP4aYCGf1kIlYAYvg,mc__XfQXtB6cfd9fyc_v3eEup,(
ssc_sli_Vp0c29ygDdlujTOV9DIZY0*)mc_V2mBNcV1EqCifyH9UdCbkF);}static void
ssc_sli_Fvi_arVpMDCSdPERTpFFde(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmRealVector const*ssc_sli_VxEnS0KgNUl5XukGjy0xQd){
ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;
size_t i;size_t ssc_core_V5LBNJCbhICNbmMG_hLaZ6=ssc_sli_VxEnS0KgNUl5XukGjy0xQd
->mN;(void)0;(void)0;for(i=0;i<ssc_core_V5LBNJCbhICNbmMG_hLaZ6;i++){if(!d->
ssc_sli__mvMRZrJTMKeequEOzKRS2->mX[i]){int ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_sli_F7t5lALbnyS5i9RsYavPtr->mX[i];
mc__XfQXtB6cfd9fyc_v3eEup->mX.mX[ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT]=
ssc_sli_VxEnS0KgNUl5XukGjy0xQd->mX[i];}}}static void
ssc_sli__B9tgkFh2cCNeTzaIqMLf7(ssc_sli_VUa2TSfWIUlueyhCKkORiK const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeDynamicSystemInput const*mc__XfQXtB6cfd9fyc_v3eEup
,PmRealVector*ssc_sli_VxEnS0KgNUl5XukGjy0xQd){ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d
=mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;size_t i;size_t
ssc_core_V5LBNJCbhICNbmMG_hLaZ6=ssc_sli_VxEnS0KgNUl5XukGjy0xQd->mN;(void)0;(
void)0;for(i=0;i<ssc_core_V5LBNJCbhICNbmMG_hLaZ6;i++){if(d->
ssc_sli__mvMRZrJTMKeequEOzKRS2->mX[i]){ssc_sli_VxEnS0KgNUl5XukGjy0xQd->mX[i]=
0.0;}else{int ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT=mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_F7t5lALbnyS5i9RsYavPtr->mX[i];ssc_sli_VxEnS0KgNUl5XukGjy0xQd->mX[i]=
mc__XfQXtB6cfd9fyc_v3eEup->mX.mX[ssc_sli_V5XnIQ0HZCxrbPmX4D3LbT];}}}static void
ssc_sli_VOTrYl7cWWOpi9jFCkUjKS(ssc_sli_VUa2TSfWIUlueyhCKkORiK*
mc_kpyeXH2RWcWG_DVSgKEG_O){PmAllocator*a=pm_default_allocator();
ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData;(d->
ssc_sli_kXSv4dTv8At6VLv5OlDCaf)->mDestroy(d->ssc_sli_kXSv4dTv8At6VLv5OlDCaf);(
d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT)->mDestroy(d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT
);(d->mF)->mDestroy(d->mF);(d->mJ)->mDestroy(d->mJ);pm_VuaGyqV_9K0Ia9Qgn65rsj(
d->ssc_sli__mvMRZrJTMKeequEOzKRS2,a);pm_destroy_real_vector(d->
ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ,a);pm_destroy_real_vector(d->
ssc_sli_kdl2GDLXpZl1imsJLXV_I4,a);pm_destroy_real_vector(d->
ssc_sli_VD97icaQKhOjVeP8EL6yNh,a);pm_destroy_real_vector(d->
ssc_sli_VdUKc9M2JcK__H3HdvujQd,a);pm_destroy_real_vector(d->
ssc_sli_kozZEBqdu9lJhTcWextajd,a);{void*const ssc_sli_V65nW_kE2ExKeew5aQPdZS=(
d);PmAllocator*const ssc_sli___8kbK45NvCwd1pTTEgIlm=(a);if(
ssc_sli_V65nW_kE2ExKeew5aQPdZS){(ssc_sli___8kbK45NvCwd1pTTEgIlm)->mFreeFcn(
ssc_sli___8kbK45NvCwd1pTTEgIlm,ssc_sli_V65nW_kE2ExKeew5aQPdZS);}};{void*const
ssc_sli_VGWWml0SFfOUVDG9LbquPO=(mc_kpyeXH2RWcWG_DVSgKEG_O);PmAllocator*const
ssc_sli_FSPlgsEEhgWXiH1vF7LwsW=(a);if(ssc_sli_VGWWml0SFfOUVDG9LbquPO){(
ssc_sli_FSPlgsEEhgWXiH1vF7LwsW)->mFreeFcn(ssc_sli_FSPlgsEEhgWXiH1vF7LwsW,
ssc_sli_VGWWml0SFfOUVDG9LbquPO);}};}ssc_sli_VUa2TSfWIUlueyhCKkORiK*
ssc_sli__oVk_KhXeghpf5BXrX5fRj(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*
ssc_sli__IqjUOFkW8_nauH_Moi97j){PmAllocator*a=pm_default_allocator();
ssc_sli_VUa2TSfWIUlueyhCKkORiK*mc_kpyeXH2RWcWG_DVSgKEG_O=(
ssc_sli_VUa2TSfWIUlueyhCKkORiK*)(((a)->mCallocFcn((a),(sizeof(
ssc_sli_VUa2TSfWIUlueyhCKkORiK)),(1))));ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*d=(
ssc_sli_FzLpHYC8pbORfLs1HQ5tx8*)(((a)->mCallocFcn((a),(sizeof(
ssc_sli_FzLpHYC8pbORfLs1HQ5tx8)),(1))));size_t ssc_core_V5LBNJCbhICNbmMG_hLaZ6
=ssc_sli__IqjUOFkW8_nauH_Moi97j->ssc_sli_F7t5lALbnyS5i9RsYavPtr->mN;d->mF=
ssc_sli_kzgzBnb4bl4_eapKdiTm8H(ssc_sli__IqjUOFkW8_nauH_Moi97j,
ssc_sli_kVzQQaaqlPt8bmsY4qvPjV,a);{PmBoolVector*mc_F8fT7naL9bOcimTADCVzTC,*
mc_VCVhWy_VaDhraHrlfFWxBa;McMatrixFunction*ssc_sli_kr54pdOF7m03iip5bybdRd,*
ssc_sli_k52KZ_57cplD_9C1ZpXEi9;d->mM=ssc_sli__0xRjfYIJ4GUb92KcJDY4u(
ssc_sli__IqjUOFkW8_nauH_Moi97j,a);d->ssc_sli_kozZEBqdu9lJhTcWextajd=
pm_create_real_vector(((size_t)(((d->mM->mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(d->
mM->mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),a);mc_F8fT7naL9bOcimTADCVzTC=
pm__jbisDMumXdocXANx5LhhY(ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);
mc_VCVhWy_VaDhraHrlfFWxBa=pm__jbisDMumXdocXANx5LhhY(
ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);mc_k1sxUtEClkOZVuHMQ91JqD(
mc_F8fT7naL9bOcimTADCVzTC,true);mc__pbFNjwg_bCPdPFSjC2Wdv(
mc_VCVhWy_VaDhraHrlfFWxBa,d->mM->mc_kjWUPQN_Ui4d_enzFJIsF_);d->
ssc_sli__mvMRZrJTMKeequEOzKRS2=pm_kpRdzyG9L_8MV5lRovACCg(
mc_VCVhWy_VaDhraHrlfFWxBa,a);d->ssc_sli__0yDm4ZTkjC7_Xfp7pZ8NQ=
pm_create_real_vector(ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);d->
ssc_sli_kdl2GDLXpZl1imsJLXV_I4=pm_create_real_vector(
ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);d->ssc_sli_VD97icaQKhOjVeP8EL6yNh=
pm_create_real_vector(mc_FyLahU0kjICfba8O7mWi8Z(mc_VCVhWy_VaDhraHrlfFWxBa),a);
ssc_sli_k52KZ_57cplD_9C1ZpXEi9=mc_VjS2AX9knfCIa1JgE0u_Mq(d->mM,
mc_F8fT7naL9bOcimTADCVzTC,mc_VCVhWy_VaDhraHrlfFWxBa,a);
ssc_sli_kr54pdOF7m03iip5bybdRd=ssc_sli_V1iOeFwioxKijmwSQumlRX(
ssc_sli__IqjUOFkW8_nauH_Moi97j,a);d->mJ=mc_V7lAu3dITJGBeukLWd4htI(
ssc_sli_kr54pdOF7m03iip5bybdRd,a);{PmBoolVector*ssc_sli_VFrhjye_NbhBXift22neEP
,*ssc_sli_FhXZAUu5rkpLh1lTaPPPfH;McMatrixFunction*
ssc_sli_kbQyf_2qufh3cuRaZEGjZA=(d->mJ)->mc_FBMgSgsPcuhAfqqbis_q6w((d->mJ));
ssc_sli_VFrhjye_NbhBXift22neEP=pm_kpRdzyG9L_8MV5lRovACCg(
mc_F8fT7naL9bOcimTADCVzTC,a);ssc_sli_FhXZAUu5rkpLh1lTaPPPfH=
pm_kpRdzyG9L_8MV5lRovACCg(mc_VCVhWy_VaDhraHrlfFWxBa,a);d->
ssc_sli_kniAJrAWeVl_hy2gsFuPcT=mc_VjS2AX9knfCIa1JgE0u_Mq(
ssc_sli_kbQyf_2qufh3cuRaZEGjZA,ssc_sli_VFrhjye_NbhBXift22neEP,
ssc_sli_FhXZAUu5rkpLh1lTaPPPfH,a);d->ssc_sli_VdUKc9M2JcK__H3HdvujQd=
pm_create_real_vector(((size_t)(((d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(d->ssc_sli_kniAJrAWeVl_hy2gsFuPcT->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),a);}{PmBoolVector*
ssc_sli_VFrhjye_NbhBXift22neEP,*ssc_sli_FhXZAUu5rkpLh1lTaPPPfH;PmIntVector*
ssc_sli_FnMKLTs1DM_Mdqn_LDfnFk,*ssc_sli__5ImMVKwRQODfHaXvRFBvg;
McMatrixFunction*ssc_sli_FKgQvsPAoSKmaHeEqqrJao,*
ssc_sli_kCGp6G6ZWpStWuOd8BU382;McMatrixFunction*ssc_sli_kbQyf_2qufh3cuRaZEGjZA
=(d->mJ)->mc_FBMgSgsPcuhAfqqbis_q6w((d->mJ));int i,j,k;
ssc_sli_VFrhjye_NbhBXift22neEP=pm_kpRdzyG9L_8MV5lRovACCg(
mc_F8fT7naL9bOcimTADCVzTC,a);ssc_sli_FhXZAUu5rkpLh1lTaPPPfH=
pm_kpRdzyG9L_8MV5lRovACCg(mc_VCVhWy_VaDhraHrlfFWxBa,a);
mc_kUD9LJQRjT0FayfqpQrhnP(ssc_sli_FhXZAUu5rkpLh1lTaPPPfH);
ssc_sli_FKgQvsPAoSKmaHeEqqrJao=mc_VjS2AX9knfCIa1JgE0u_Mq(
ssc_sli_kbQyf_2qufh3cuRaZEGjZA,ssc_sli_VFrhjye_NbhBXift22neEP,
ssc_sli_FhXZAUu5rkpLh1lTaPPPfH,a);ssc_sli_kCGp6G6ZWpStWuOd8BU382=
mc_VmBCniFWwo8BYmiUfCse67(ssc_sli_k52KZ_57cplD_9C1ZpXEi9,
ssc_sli_FKgQvsPAoSKmaHeEqqrJao,a);ssc_sli_FnMKLTs1DM_Mdqn_LDfnFk=
pm_create_int_vector(ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);
ssc_sli__5ImMVKwRQODfHaXvRFBvg=pm_create_int_vector(
ssc_core_V5LBNJCbhICNbmMG_hLaZ6,a);i=0;j=(int)d->
ssc_sli_VD97icaQKhOjVeP8EL6yNh->mN;for(k=0;k<(int)
ssc_core_V5LBNJCbhICNbmMG_hLaZ6;k++){ssc_sli_FnMKLTs1DM_Mdqn_LDfnFk->mX[k]=k;
if(d->ssc_sli__mvMRZrJTMKeequEOzKRS2->mX[k]){ssc_sli__5ImMVKwRQODfHaXvRFBvg->
mX[k]=i;i++;}else{ssc_sli__5ImMVKwRQODfHaXvRFBvg->mX[k]=j;j++;}}d->
ssc_sli_kXSv4dTv8At6VLv5OlDCaf=mc__SEcNGNHbdG4d1gvLmKmKO(
ssc_sli_kCGp6G6ZWpStWuOd8BU382,ssc_sli_FnMKLTs1DM_Mdqn_LDfnFk,
ssc_sli__5ImMVKwRQODfHaXvRFBvg,a);}}d->ssc_sli__eGKFuP4aYCGf1kIlYAYvg=
ssc_sli__IqjUOFkW8_nauH_Moi97j;mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData=d;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPattern=d->ssc_sli_kXSv4dTv8At6VLv5OlDCaf->
mc_kjWUPQN_Ui4d_enzFJIsF_;mc_kpyeXH2RWcWG_DVSgKEG_O->mSizes=
ssc_sli__IqjUOFkW8_nauH_Moi97j->mSizes;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_F7t5lALbnyS5i9RsYavPtr=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli_F7t5lALbnyS5i9RsYavPtr;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli__g89dzKHN9WyW1QK3EhGT2=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli__g89dzKHN9WyW1QK3EhGT2;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_kvN_H6GsD70dhuDSrFXI_8=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_FrT0SxUiz3lUYTPj5gvPFW=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_VJpCWpuVNmCdX55T4H0I1u=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli_VJpCWpuVNmCdX55T4H0I1u;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_FA2YAvRyL2h_f9kmmok0RW=ssc_sli__IqjUOFkW8_nauH_Moi97j->
ssc_sli_FA2YAvRyL2h_f9kmmok0RW;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_k98doWegV6xNVLpUJF775m=ssc_sli__Ac4_9Y1itphg1cl_q6oBJ;
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_sli_Vewa2aEFH2p4eyRGN0BdA4=
ssc_sli_Vn_kP_HwAv_xhe2eirjKdP;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli_FrnJvV2zDsWGhiwD7eB0IS=ssc_sli_Vslugpw_q2dfaTtIFuEec7;
mc_kpyeXH2RWcWG_DVSgKEG_O->mc_VT_CRoRmbpWajqcrcvcctF=
ssc_sli_Vm7Ss_iPTMtWjmguiRW_co;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_sli__WkMCltDVadkZuQRjGYmXq=ssc_sli_Fvi_arVpMDCSdPERTpFFde;
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_sli_FsX__XbkKPdEYTPBZsyQSK=
ssc_sli__B9tgkFh2cCNeTzaIqMLf7;mc_kpyeXH2RWcWG_DVSgKEG_O->mDestroy=
ssc_sli_VOTrYl7cWWOpi9jFCkUjKS;return mc_kpyeXH2RWcWG_DVSgKEG_O;}
