#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_VjM_t72HhIWQX1Bm59l9n0 mc__mbv8xxcLWlA_qjxkZ_Zr3;struct
mc_VjM_t72HhIWQX1Bm59l9n0{PmSparsityPattern*mPattern;PmRealVector*mPr;};
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kNHKmAODJZ_WYXTjy6yXM3(PmSparsityPattern const*
pm__6H5I5OnY3KoY5YVL6mLgG,PmRealVector const*mc_VTddUsjDkUlHXyWpbnu_X6,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void mc_FqXnLzanko_Ab94u17BqAf(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kSyG2aZimWxIhPxax8Yu0Z
(size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FHYJxAGKrzlJjylbsXle3W(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VouCmbdjpn8CXiz7xVQKz_(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__oFzjr34Rc8NYmhojkCr9E
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kV_gUolC0V8HVaDz0GYD5Z(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*a,
mc__mbv8xxcLWlA_qjxkZ_Zr3 const*b,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLaKMHroqwpzcXQaYqiA0c(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_F3GYxtOuUXStZuaKTYqPSh,size_t
mc_kdV6gi9UV7C3busQ054WhO,size_t mc_kF0899509L4BdTLCApD17a,size_t
mc_kk1VpoYYYRxBgi6A0xe6ww,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__uIK1az5Q0lU_9qiZoDp2w(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VX7DKY_ZZSSif9ozGgJwHo(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*perm,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VlrliqitUo4vbaopHr9nhF
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmIntVector const*
perm,PmAllocator*pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_kapI_G_0Yw87h9sCrfe5hw(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,size_t mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F9nGB39wn6SS_XzeIPdTIk
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FIvSpRV20s_Jcm1tm_edj6,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__fPbUii52Xh9f5vNQlUxeO(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VbJEq3duwshuZ1WJY1KN7J
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*A,mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_Vqiy96WqvuhCaXm5e_vvT0,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F6NuiNPSsu0yf1TluQ0__s(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FLVFQ6dsCKtdgmHV1uYwHn
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*
mc_F8fT7naL9bOcimTADCVzTC,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa,
PmAllocator*mc_FZx3iFiX1YW7j5eEojoAPc);mc__mbv8xxcLWlA_qjxkZ_Zr3*
mc_F1kJsdLDNlprdX40bwF9LB(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*
mc_FVG9mW_iV00Sd5jvvtdbAo,PmBoolVector const*mc_VlZMmzn2z2dpZyy2834RK6,
PmBoolVector const*mc_kYm9_Bnh90tjXTI8q_HusO,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_F_kKl1gO2gWidXfY0v7Kdt
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_kqP_Mrhf890jimFaY9LP3v(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FSgafOY1yb0YV9IeGdZxYK
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
pm_Fr_bHKkQKFWbfi50VWd5Pw,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VQxpNOmpxN43ei92Zbz5PM(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t pm_kplAJmOlA30feiNcOzi7oj,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void mc_kXL8zBVnOn4yZLHVqnqmYJ(
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc__H_R6laiZnCcXyegjjDM0e,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_VJSNkp4nxul3XLhr4R_sS6
(mc__mbv8xxcLWlA_qjxkZ_Zr3 const*mc_FVG9mW_iV00Sd5jvvtdbAo,size_t
mc_FG9ZSShR1cC8i1m0e45L1r,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
mc__mbv8xxcLWlA_qjxkZ_Zr3*mc_FA7jg_R9xsKGViqmqdtd5O(mc__mbv8xxcLWlA_qjxkZ_Zr3
const*mc__XfQXtB6cfd9fyc_v3eEup,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
typedef struct mc_VWJbTwnVZB_LVqIIM_COT0{int32_T mc_FvxKbdtfPKOYaymjtthQ0G,
mc__0REJ38_cKO_bunM1JCRT_,id;struct mc_VWJbTwnVZB_LVqIIM_COT0*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;}
mc_FSz7cV1MCGScXq_M5VT121;typedef struct mc_kjlHS2Mzxsh6gyVZ329fra{
mc_FSz7cV1MCGScXq_M5VT121*mc__a1o_SOX2HC3f9QpH_hO5s;PmIntVector*
mc__5uLb2__blGtb9EQ9Zwa2_;PmIntVector*mQ;}mc_F9HbKNDZMeOehmlKWGUdea;typedef
struct mc__fV9rOH7ci_OWykNO7xTBO{size_t mc_VLHhnPUiNQpve5VIL9P3O9,n;int32_T*
mc_FvxKbdtfPKOYaymjtthQ0G,*mc__0REJ38_cKO_bunM1JCRT_,*
mc_Vk_mYyVPAa4IZeLta2BLLG,*mc_VKkEmtOg5lC4dH7wVVnG4C;int32_T*
pm__lqjegyKuwStj56WZLiC_e,*mc__AExROh1PVWNeP7hmMWuJv;}
mc_FwUXSPCwCAC_jydGHlCZxe;PmIntVector*mc__oCV63DXBpKVZL_8tU2Wiz(
mc_FSz7cV1MCGScXq_M5VT121 const*mc_VPPSxR3RRt0pXLadx2tWo7,PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);void
mc__RLQweDZtv0hhLXz_f8MMi(mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt)
;mc_FSz7cV1MCGScXq_M5VT121*mc_VCdOZjcBUFORayuNvO7rtI(mc_FSz7cV1MCGScXq_M5VT121
*mc_Fxl4i6XHkE8cY9kYmlJixt);void mc_VbHMSzzYu5_WZiNG_fSW8Q(
mc_FSz7cV1MCGScXq_M5VT121*mc_Fxl4i6XHkE8cY9kYmlJixt,int32_T
mc_FvxKbdtfPKOYaymjtthQ0G);int32_T mc__1AbngzPnBGnXXDldWop_b(
mc_FSz7cV1MCGScXq_M5VT121*mc_VPPSxR3RRt0pXLadx2tWo7);void
mc_VBCIjXiCCT_RXmHVT9WPVa(mc_F9HbKNDZMeOehmlKWGUdea*mc_VpSwxG2uxL4JaLmMQqUqTJ)
;mc_FwUXSPCwCAC_jydGHlCZxe*mc_F79LLfWDdKORZ1K7KKqAke(mc_F9HbKNDZMeOehmlKWGUdea
const*mc_VpSwxG2uxL4JaLmMQqUqTJ);mc_F9HbKNDZMeOehmlKWGUdea*
mc_perm_data_from_flat(mc_FwUXSPCwCAC_jydGHlCZxe const*
mc_Fw6WJxuximC4jHgRLzUSDo);void mc_Vq5AUJWyc3xVgP5Ff1_aP6(
mc_FwUXSPCwCAC_jydGHlCZxe*mc_Fw6WJxuximC4jHgRLzUSDo);
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "ne_initer_fwd.h"
typedef enum{ssc_sli_kiIb5xamJm8uXPyOkLeM64= -1,ssc_sli_FRFqZTqvUYlL_1GmhnSKa9
,ssc_sli_F_n1U4dfhIKmZeTb79_bhk,ssc_sli_Vje8c4NwMs8edaUv9kAKU5,
ssc_sli_F95A2pmjwJGycuR83ALBWW,ssc_sli_FRC3ujZIQjdba9ZBxy4ztV}
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ;typedef struct ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv
ssc_sli_FTmXA5ksLdxWam9tKEDDRp;typedef union ssc_sli_V3VjUqcAjgGUfa9pjdr9Vc{
PmIntVector mMODE;PmRealVector mY;PmRealVector ssc_sli_kxq2De1a8BxzemrdMYbh_Z;
PmIntVector mASSERT;PmIntVector mIASSERT;PmRealVector mINIT_R;PmIntVector
mINIT_I;PmRealVector mCACHE_R;PmIntVector mCACHE_I;PmRealVector mUPDATE_R;
PmIntVector mUPDATE_I;PmBoolVector mLOCK_R;PmBoolVector mLOCK_I;PmRealVector
mUPDATE2_R;PmIntVector mUPDATE2_I;PmBoolVector mLOCK2_R;PmBoolVector mLOCK2_I;
PmIntVector mDP_L;PmIntVector mDP_I;PmIntVector mDP_J;PmRealVector mDP_R;
PmRealVector ssc_sli_VjGKBH58LAdsYPWWs6sfbL;PmRealVector mLOG;}
ssc_sli_kkoV3MWI3Olsj9ue_OTrKB;typedef enum ssc_sli__gFYpQJuFtpEfTSOOLoPeL{
ssc_sli_kcaKKN8GXoxUdyPIz9ME4P= -1,ssc_sli_VFlLQfEII_dCjPOLZCKl1h,
ssc_sli_FQmAUq5mRNGbVih2F3PCCN,ssc_sli_FHA50iTf0YOSaPrq60uYIa,
ssc_sli__d4NvF_TU8xhiPidhlSBeU,ssc_sli_kje3FEfA_VOecqlGobEPlW,
ssc_sli_V2lBgEm_1wOKgP3OF7OhA2,ssc_sli__HZXcTW2uIp1b5VW7Lmaiz,
ssc_sli__iC2umSSBnhLdaou8jCK4Q,ssc_sli__cdqw5QDTiWb_HxgGzJupf,
ssc_sli_VzRYNhOLez0fcahY6OfqAT,ssc_sli_ksyP1mhwOx_gdi_qxA1XwQ,
ssc_sli_FdbT7DDFOod_gD62wqPcy_,ssc_sli_FxDcIIX1_0WChuVyeYIziJ,
ssc_sli_km8PqndzZYCHbPN_lUtQcC,ssc_sli_Fh3EMcmCEi0cfaU6jdkIj2,
ssc_sli_k2mBp0rugDOniPAiyz8Hig,ssc_sli_FPv0_UNPp8__hPT18mmlhp,
ssc_sli_kxwvUNoEGCOiceCilpf1YD,ssc_sli__nuLYOAWg4luhub2duGQQ_,
ssc_sli_kjrjD1N2_uWBXaVD9TSx7N,ssc_sli_VLEO4HXvRlGQaqqGghTyqa,
ssc_sli__kD90nzGGZSGWTWEkw1Cis,ssc_sli_k8wcDa_7rDts_9nPV5dfjq,
ssc_sli_VujW_EuJpidTduLntgaxe6}ssc_sli_Vfu07t_igc0ehHkC_w2Ar_;typedef int32_T(
*ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5)(ssc_sli_FTmXA5ksLdxWam9tKEDDRp const*,
NeDynamicSystemInput const*,ssc_sli_kkoV3MWI3Olsj9ue_OTrKB*);struct
ssc_sli_Fs6RUekc_EtXgPaZ4IsGwv{ssc_sli_V5YgNLc0HyS2buQ_0Ec5M5 mMethods[
ssc_sli_VujW_EuJpidTduLntgaxe6];size_t ssc_sli__6xxO1zzzZ87ZuJDfcXI71;size_t
ssc_sli_kZS4XmJSc_lOXT_wq5w1Le;size_t mNumAsserts;NeAssertData const*
mAssertData;size_t mNumAssertRanges;NeRange const*mAssertRanges;size_t
mNumInitialAsserts;NeAssertData const*mInitialAssertData;size_t
mNumInitialAssertRanges;NeRange const*mInitialAssertRanges;NeParameterInfo
mParameterInfo;PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli__xnuR3B_dV_0jaRn6xall3;};typedef struct ssc_sli_knlRBEvE2xlTdL9XQDsraA
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO;typedef struct ssc_sli__M0yHGxYdRh6WeZsp03MsF
ssc_sli_ktYRHip3ZVhEdLZEQWORqW;typedef struct ssc_sli__C7xfBs4_wtZdybDh_1S17
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ;typedef union ssc_sli_kEJscBISiC0cW1zDnm5FFI{
PmSparsityPattern mMCON_P;PmRealVector mMCON;PmSparsityPattern mMPAR_P;
PmRealVector mMPAR;PmSparsityPattern mMNL_P;PmRealVector mMNL;
PmSparsityPattern ssc_sli__iV7cpieH5lkhLu3Lg9TbF;PmRealVector
ssc_sli_kpJ_qciQSWpsiPiK3aYpC6;PmSparsityPattern ssc_sli_FCUwBAadDl4jdTbQJs191b
;PmRealVector ssc_sli__4wk9aw_kxhdamxJBndVFp;PmSparsityPattern
ssc_sli_kpP4jzbAmSSabDQ2Rr8bL8;PmRealVector ssc_sli_kKsgUsw2JgtEYPjXL27qpf;
PmRealVector ssc_sli_FisUhCWjCaKZVHMV_vZE5q;PmRealVector mF;PmRealVector
ssc_sli__EEaI0glzV_ziunIayuQB_;PmIntVector mMODE;PmBoolVector mSLF;}
ssc_sli_Vp0c29ygDdlujTOV9DIZY0;typedef enum ssc_sli_VD2_Ev_HuH0of9gNrHze9d{
ssc_sli_VXnsMGX_7cGRb55H42tfn7= -1,ssc_sli_k_8QN9x5_k42cyQrpZzjsI,
ssc_sli_kqMvQKKxuVtEea_8OzY2TM,ssc_sli_VfTboTvpAHCDgqUBkJD5Rl,
ssc_sli_k2Owy_sJ_40uh9KZRFIdY5,ssc_sli_kmQ2_m3O6DG6euIv_XuxVg,
ssc_sli_VQO8dLIZX78oa5taxlg_vo,ssc_sli_V7DyxzVA0QGofTFR6YdqYq,
ssc_sli__DRGltAScIGfeu43CxFuG8,ssc_sli__sxV91jCfEGzYXaVBkddIG,
ssc_sli_k0IoR8Wj3MdBiLa4ZtAvTI,ssc_sli_kFNU_9_j_MOSead4baHt3T,
ssc_sli_Vx3D_PUFnUhXeH6lNfeh3d,ssc_sli__pmgH1Up57xCbH_C454qdO,
ssc_sli_kVzQQaaqlPt8bmsY4qvPjV,ssc_sli_kTfE4dqxl7OZdqxWw7pewy,
ssc_sli_VazOOCfCtUhdYPCvduXfsJ,ssc_sli__a5HvR7wGotUf9fcjCj4Zw,
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C}ssc_sli_FSls2IGSVBpdeeBJHp6ST7;typedef int32_T(
*ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT)(ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO const*,
NeDynamicSystemInput const*,ssc_sli_Vp0c29ygDdlujTOV9DIZY0*);typedef enum
ssc_sli__I1_0bn1tlpndTZaRA_ZPl{ssc_sli_kIVETWACXbp0d94SP8_dc1= -1,
ssc_sli_F5_rBq64Lj4aWXXU0PyiUb,ssc_sli_FshPfGethuxwX9btxT6saT,
ssc_sli__uxzr382yeG7jXfsoRvs2Z}ssc_sli_V79S98fiH1S7byo5F9wnzk;typedef
PmSizeVector*ssc_sli__C96EutllrWlgykXJW4e3Y;struct
ssc_sli_koMvWW1l_F_oi5bwovAr78{PmSparsityPattern*mPattern;};struct
ssc_sli__M0yHGxYdRh6WeZsp03MsF{PmSparsityPattern*mPattern;PmRealVector*mPr;};
struct ssc_sli_knlRBEvE2xlTdL9XQDsraA{ssc_sli_kHGh4wh4tjO2Z9nI8m9KtT mMethods[
ssc_sli_kTT5c5KnkrhaaHrCHJEj3C];ssc_sli_ktYRHip3ZVhEdLZEQWORqW
ssc_sli_kb5sBAIsNGx3h5TSZDK2nO[ssc_sli__uxzr382yeG7jXfsoRvs2Z];
ssc_sli_FoGz5zrtBQ0RgqipoHUSDZ*ssc_sli__he79Qtc4y4abmydbMrr9d;size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;size_t
ssc_sli__W3kBT05WSC6WPEI9Yuazr;size_t ssc_sli__4W_ICUoZ5pQb5CD_591s6;size_t
ssc_sli_VcjSlsQyP4pqf5089e6UHb;size_t ssc_sli_k3ro8_fNFeG3YHRPCSyK_y;size_t
ssc_sli_VimjrZhJPvSkgeFbqT7DNg;size_t ssc_sli_Vd47fO4esQxG_HpE1mPb9b;size_t
ssc_sli_F0sp_kii_WGhgeeqy_FSs6;boolean_T ssc_sli_Vq7NNhAfxIO_j9IbOG6sAS;
NeDynamicSystemInputSizes mSizes;ssc_sli__C96EutllrWlgykXJW4e3Y
ssc_sli__jDRUOD243tjgTxKYEsbsv[NE_NUM_DYNAMIC_SYSTEM_INPUT_ID];PmIntVector*
ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*ssc_sli__ysspeBWLwt9fe39xFzdmF;
PmIntVector*ssc_sli__g89dzKHN9WyW1QK3EhGT2;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
boolean_T ssc_sli_VJpCWpuVNmCdX55T4H0I1u;ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ
ssc_sli_FA2YAvRyL2h_f9kmmok0RW;boolean_T ssc_sli_V6uMeGVfspW_ju_lkeNWOq;};
typedef struct ssc_sli__we9OgtXM80Beq3Pau0ORa ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ;
typedef union ssc_sli_kZbOKlPIFU_2ZqIJ7Wxuxt{PmSparsityPattern mM_P;
PmRealVector mM;PmRealVector mF;PmSparsityPattern
ssc_sli__aw0Y7gxbhS0_LvT4MtW1M;PmRealVector mJ;}ssc_sli_FXl61xRLPE47iP1Q_pvk2u
;typedef enum ssc_sli_V1Ph_XOAJoKRYqSqeTnmEx{ssc_sli_V3bEzwx1u0lOVPYRbuCqcW= -
1,ssc_sli_Fn41P1GumQ42i9T8pr7NwB,ssc_sli_F2Ws5ikk0qOaWyeJpDP8bj,
ssc_sli_FYPImDMfyFhqYmN4WZY0Gv,ssc_sli_kAf_QyKmY34ZVLgh19055f,
ssc_sli_kKEx7mxjxwKzZTWlJaaDbC,ssc_sli_FEtyoYrn_ttHf99kNFRkob}
ssc_sli_FD25vRYmqOCeX9QMP0Yb86;typedef int32_T(*ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW
)(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*,NeDynamicSystemInput const*,
ssc_sli_FXl61xRLPE47iP1Q_pvk2u*);struct ssc_sli__we9OgtXM80Beq3Pau0ORa{
ssc_sli_VuZ7XkxFOEW9eDs_mLe6yW mMethods[ssc_sli_FEtyoYrn_ttHf99kNFRkob];size_t
ssc_sli_k2RLDpP2nLh8WT535aP0mU;size_t ssc_sli_kc2oIClFbFKEaLXRIl6yrm;
PmIntVector*ssc_sli_F7t5lALbnyS5i9RsYavPtr;PmIntVector*
ssc_sli_kvN_H6GsD70dhuDSrFXI_8;PmIntVector*ssc_sli_FrT0SxUiz3lUYTPj5gvPFW;
ssc_sli_VnBw0hOC0JSHb5Pg67DfPJ ssc_sli_FA2YAvRyL2h_f9kmmok0RW;};typedef struct
ssc_sli_VAuysnx4S7lBcPba8gefmX ssc_sli_kTxQKABEQA__dXDaX6_8lx;struct
ssc_sli_VAuysnx4S7lBcPba8gefmX{NeDynamicSystemInputSizes mSizes;PmIntVector*
ssc_sli_FtEj7nrAMw8EX1WVETDajL;ssc_sli_FTmXA5ksLdxWam9tKEDDRp*
ssc_sli_ki5qToeyQ7tPheF11zZqgB;size_t ssc_sli__MBuKzK8US4ghTfNeJrQSZ;
ssc_sli_V82Cz4PmAJ4Jh5NsxRSXpO**ssc_sli_kB5nTrHgNTWIZ1KFHBi8XH;
ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ*ssc_sli__Rb1pGJJ50KLfagQM39h_L;SscIniter*
ssc_sli_VR_NrzucmTGQePxxfCzXg2;SscIniter*ssc_sli__ooqAz7SMjSwaDaud6_xyI;
mc_F9HbKNDZMeOehmlKWGUdea*(*ssc_sli_FrHYG41gZrG7b9SBHEWeHM)(PmSparsityPattern
const*mc_FNLG4N0Qc3OxdmBVwutDsy,size_t mc_k0zHKt3B8EloaeisOobs3u);void(*
ssc_sli_kkIk538kkH4PjT_BdbbDnq)(ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,NeDynamicSystemInput**ssc_sli_FI3oLMQhBMhqhTN_ohgA9w
);void(*mDestroy)(ssc_sli_kTxQKABEQA__dXDaX6_8lx*mc__JuAUR_Sob8_WqDjXwmJgM);};
McMatrixFunction*ssc_sli_FlmW6nnb2dSudHNXnsL5BQ(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ
const*ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,ssc_sli_FD25vRYmqOCeX9QMP0Yb86
ssc_sli_FBXPJm0AysCEjX_wMAG2PR,ssc_sli_FD25vRYmqOCeX9QMP0Yb86
ssc_core_V_DRESe0gNtOfHGOtCHo2g,ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "pm_std.h"
int_T pm_kkW9oQAVI7Wt_9Rzuat5bx(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
size_t pm_keOJjiAyBTtFhyWf033kni,size_t pm_kJxontPsxndNYXwDXdE1iy,size_t
pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
PmSparsityPattern*pm_create_sparsity_pattern(size_t pm_keOJjiAyBTtFhyWf033kni,
size_t pm_kJxontPsxndNYXwDXdE1iy,size_t pm_kPvICtSd_wWNieTWLEBFD1,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_kTFq3qlgTulWiT6pafkmmT(PmSparsityPattern*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
boolean_T pm__ZRI70SuGwhmamUtcsoyxS(PmSparsityPattern const*
pm__56dBn4vKXWjZ1nclFRYZB,PmSparsityPattern const*pm_kAWy4EaHbpxVbT_qyApDbv);
PmSparsityPattern*pm_FQMLyYzCQ5CtgHjze1nNJP(PmSparsityPattern const*
pm__HVqeFmd5gKdguw04VZTsk,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_FvcKvutPfxG9Xe1kjs7gg0(PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void pm_VYooJBURCwKrVu6RXzQZ_5(
PmSparsityPattern*pm__6H5I5OnY3KoY5YVL6mLgG,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm__YwdRBXissh3bPWPl30Fpe(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FFniD_kRQg_JWTYc5cmjGs(size_t
pm_FW8nEXbTFjdJhTIKepsgFT,size_t pm_FsQ9LRKHRTKdgeP2xWDL07,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmSparsityPattern*pm_FhqtSrxlPotrcypQHJ9Dcq(size_t
pm__lqjegyKuwStj56WZLiC_e,size_t n,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmSparsityPattern*pm__TNI3M36rThlaTetY4tWiB(size_t n,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PMF_DEPLOY_STATIC int32_T
ssc_sli_FRsZjemx7LtueusqFACqLb(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*
ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,ssc_sli_FD25vRYmqOCeX9QMP0Yb86 id,
NeDynamicSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k,
ssc_sli_FXl61xRLPE47iP1Q_pvk2u*mc_VgqbsB_3R4GTjLQeEYi1Qc){(void)0;return
ssc_core_VkEZfX8sDrW2fPxW5Ht5d2->mMethods[id](ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,
mc_kDRphcAfRHSbf1ZLKEDW9k,mc_VgqbsB_3R4GTjLQeEYi1Qc);}struct
mc_kIf5GUUnTAOChauG3_6hhe{ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*
ssc_sli__Rb1pGJJ50KLfagQM39h_L;NeDynamicSystemInput*
ssc_sli__vXnEdflyb8o_XdLMEj7Di;ssc_sli_FD25vRYmqOCeX9QMP0Yb86
ssc_sli_FOEnDFkwDdhSf1OMrMCTWK;PmSparsityPattern*mPattern;PmAllocator*
ssc_sli_Ff9S1xA4Ip4ZXeljM4_eEa;};static void ssc_sli_VaRjgSngpulUfu51y2U0O9(
void const*inputPtr,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK){
ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ const*ssc_core_VkEZfX8sDrW2fPxW5Ht5d2=
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__Rb1pGJJ50KLfagQM39h_L;
ssc_sli_FD25vRYmqOCeX9QMP0Yb86 id=mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FOEnDFkwDdhSf1OMrMCTWK;ssc_sli_FXl61xRLPE47iP1Q_pvk2u
ssc_sli_k3GlufAHBu45fabExfkrR8;NeDynamicSystemInput const*
mc_kDRphcAfRHSbf1ZLKEDW9k=(NeDynamicSystemInput const*)(inputPtr);
ssc_sli_k3GlufAHBu45fabExfkrR8 .mM= *mc_VgqbsB_3R4GTjLQeEYi1Qc;
ssc_sli_FRsZjemx7LtueusqFACqLb(ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,id,
mc_kDRphcAfRHSbf1ZLKEDW9k,&ssc_sli_k3GlufAHBu45fabExfkrR8);}static void const*
ssc_sli_F56IDwBFWatai5TO_TaWvb(McMatrixFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ){return mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->ssc_sli__vXnEdflyb8o_XdLMEj7Di;}static void
ssc_sli__cNs_i2Mdkh1ayuwtkFlrb(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ){
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->ssc_sli_Ff9S1xA4Ip4ZXeljM4_eEa;
neu_destroy_dynamic_system_input(mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->ssc_sli__vXnEdflyb8o_XdLMEj7Di,
pm_FbYb_iLqY2hwZTVlVaiqJY);if(mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_ko6_hiERTRldgDROOJBQCH->mPattern!=NULL){pm_VYooJBURCwKrVu6RXzQZ_5(
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH->mPattern,
pm_FbYb_iLqY2hwZTVlVaiqJY);}{void*const ssc_sli_FlxuvnOdAZGbc51XrUi1Wa=(
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH);PmAllocator*const
ssc_sli_VjdCMDaJ9NlmeeRG1RiT3N=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_sli_FlxuvnOdAZGbc51XrUi1Wa){(ssc_sli_VjdCMDaJ9NlmeeRG1RiT3N)->mFreeFcn(
ssc_sli_VjdCMDaJ9NlmeeRG1RiT3N,ssc_sli_FlxuvnOdAZGbc51XrUi1Wa);}};{void*const
ssc_sli_VjA5pJZ_W0dvW5jzYmOXSy=(mc_k0CXwzVaibdnZiGUCx6PMZ);PmAllocator*const
ssc_sli__DGDsEtC87GY_ufcV9rxxQ=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_sli_VjA5pJZ_W0dvW5jzYmOXSy){(ssc_sli__DGDsEtC87GY_ufcV9rxxQ)->mFreeFcn(
ssc_sli__DGDsEtC87GY_ufcV9rxxQ,ssc_sli_VjA5pJZ_W0dvW5jzYmOXSy);}};}
McMatrixFunction*ssc_sli_FlmW6nnb2dSudHNXnsL5BQ(ssc_sli_V5VqrM0P2jd_i1Y2UNR_pQ
const*ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,ssc_sli_FD25vRYmqOCeX9QMP0Yb86
ssc_sli_FBXPJm0AysCEjX_wMAG2PR,ssc_sli_FD25vRYmqOCeX9QMP0Yb86
ssc_core_V_DRESe0gNtOfHGOtCHo2g,ssc_sli_kTxQKABEQA__dXDaX6_8lx const*
mc__JuAUR_Sob8_WqDjXwmJgM,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){
McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ=(McMatrixFunction*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
McMatrixFunction)),(1))));mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK=
(mc_k3jb_ssG91tZa9bwLjlWEj*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(mc_k3jb_ssG91tZa9bwLjlWEj)),(1))));size_t
ssc_sli_kNgcOktCtQxdYedrGvFn5i=0,ssc_sli_F9XXYvbW1X_RXP6D2uUU48=0;
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ;ssc_sli_FXl61xRLPE47iP1Q_pvk2u
ssc_sli_k3GlufAHBu45fabExfkrR8;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli__Rb1pGJJ50KLfagQM39h_L=ssc_core_VkEZfX8sDrW2fPxW5Ht5d2;
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__vXnEdflyb8o_XdLMEj7Di=
neu_create_dynamic_system_input(mc__JuAUR_Sob8_WqDjXwmJgM->mSizes,
pm_FbYb_iLqY2hwZTVlVaiqJY);mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_FOEnDFkwDdhSf1OMrMCTWK=ssc_sli_FBXPJm0AysCEjX_wMAG2PR;switch(
ssc_core_V_DRESe0gNtOfHGOtCHo2g){case ssc_sli_Fn41P1GumQ42i9T8pr7NwB:
ssc_sli_kNgcOktCtQxdYedrGvFn5i=ssc_core_VkEZfX8sDrW2fPxW5Ht5d2->
ssc_sli_k2RLDpP2nLh8WT535aP0mU;break;default:(void)0;break;}
ssc_sli_F9XXYvbW1X_RXP6D2uUU48=ssc_core_VkEZfX8sDrW2fPxW5Ht5d2->
ssc_sli_F7t5lALbnyS5i9RsYavPtr->mN;mc__srK5LmyWw42ZyPnbOWDWJ=
pm_create_sparsity_pattern(ssc_sli_kNgcOktCtQxdYedrGvFn5i,
ssc_sli_F9XXYvbW1X_RXP6D2uUU48,ssc_sli_F9XXYvbW1X_RXP6D2uUU48,
pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_sli_k3GlufAHBu45fabExfkrR8 .mM_P= *
mc__srK5LmyWw42ZyPnbOWDWJ;ssc_sli_FRsZjemx7LtueusqFACqLb(
ssc_core_VkEZfX8sDrW2fPxW5Ht5d2,ssc_core_V_DRESe0gNtOfHGOtCHo2g,
mc__d1alWYexptL_X5HTFhbNK->ssc_sli__vXnEdflyb8o_XdLMEj7Di,&
ssc_sli_k3GlufAHBu45fabExfkrR8);mc__d1alWYexptL_X5HTFhbNK->mPattern=
mc__srK5LmyWw42ZyPnbOWDWJ;mc__d1alWYexptL_X5HTFhbNK->
ssc_sli_Ff9S1xA4Ip4ZXeljM4_eEa=pm_FbYb_iLqY2hwZTVlVaiqJY;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_ko6_hiERTRldgDROOJBQCH=mc__d1alWYexptL_X5HTFhbNK
;mc_k0CXwzVaibdnZiGUCx6PMZ->mc_kjWUPQN_Ui4d_enzFJIsF_=
mc__d1alWYexptL_X5HTFhbNK->mPattern;mc_k0CXwzVaibdnZiGUCx6PMZ->
mc_VAvAkWmhpT_WWme_3E1U91= &ssc_sli_VaRjgSngpulUfu51y2U0O9;
mc_k0CXwzVaibdnZiGUCx6PMZ->mc_FXz9GdGvpOKnh5e2dYstBe= &
ssc_sli_F56IDwBFWatai5TO_TaWvb;mc_k0CXwzVaibdnZiGUCx6PMZ->mDestroy= &
ssc_sli__cNs_i2Mdkh1ayuwtkFlrb;return mc_k0CXwzVaibdnZiGUCx6PMZ;}
