#include "multibody_model_macros.h"
#include "pm_std.h"
#include "math.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ssc_dae_fwd.h"
struct NeCustomDataSizeTag{size_t ssc_core_VOAPNvYIRPGzhDXn1iCcKS;size_t
ssc_core_kAKxIvM1NQGM_TY96YysC5;};struct NeCustomDataTag{double*
ssc_core_VOMV27LEztpmd59gF8yJO0;int32_T*ssc_core_F85sNEuWe1GIjmiT6vHSvn;
NeCustomDataSize mSizes;NeCustomData*ssc_core__HGpmB64in_eWHsZP7Cb0h;};
NeCustomDataSize ssc_core_kvaTUFehmelwWDNafwUyA0(void);NeCustomData*
ssc_core_VFzWBz_s8FW9_qamuHujnl(NeCustomDataSize sizes);NeCustomData*
ssc_core__uWFHemgRS83bDIJli34aR(void);void ne_free_custom_data(NeCustomData*
ssc_core_FQj37QqwZMSgjLC3bhgfpn);size_t ne_measure_packed_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn);void ne_pack_custom_data(
NeCustomData const*ssc_core_FQj37QqwZMSgjLC3bhgfpn,char*
ssc_core_V0vDZJ8GoT_FY58vl_R6tv);NeCustomData*ne_recreate_custom_data(char
const*ssc_core_V0vDZJ8GoT_FY58vl_R6tv,size_t ssc_core__Mwijnrb0M46cT7T_bvxpH);
typedef enum ssc_core_FsdFfzfAVXO_Xia1StEklO{ssc_core_kWt32YokoLOhcuaxS6yfzx= -
2,ssc_core__Q97de9wAyd2ai1qgkC7FJ,ssc_core_krzbr94PVv0ZbeCf8B8TOo,
ssc_core_kF8uUNHtzb_HVP_tWzVLHo}ssc_core_VPCajzt28fK6eatUgrzZrl;typedef enum
ssc_core__JcefoydxW0GWq4xMUbLxI{ssc_core__0afaMKI46Kvd9u76KUzXf= -1,
ssc_core__aIDnqGzhqWcVu6dhPsWV2,ssc_core__uwax1cB6y8TfaKQr2KH_y,
ssc_core_kOw2Uegv5BGjVXro1JWJHO,ssc_core_k5b_oShgvQlNjHaf65qGgH,
ssc_core_F31_G54i4lxiea2KJi6kBi,ssc_core__XHpTEMxftlSiT4M8UKKvF}
ssc_core_VonIc63zAk4_dqgAttBCge;typedef struct ssc_core_FpYOP0TyTZhiZaeVw73BmH
ssc_core__TnsaUXKFcKxbitO58_d7o;typedef struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs
ssc_core_kIG7sD0lJlWTfaZr6Pehvz;struct ssc_core_Vbs_Wy1Vbb4dYuXR9u2Hrs{
boolean_T(*ssc_core_kpVC1AX7p50Ja18UISsLi_)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz
const*);boolean_T(*ssc_core_F9Kq4Qr_9Z0Yjm1oicqvtn)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*);int32_T(*
ssc_core__pl1MSSO99W8WP3QqnoCib)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,real_T const
*);void(*mInitializeFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,
NeSimulationParameters);int32_T(*ssc_core_VG3e0ucOiSGjh1qwaVjeHl)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,real_T,real_T const*);void(*
ssc_core_VpAc4HLF9R4vc5lHk8ztuA)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*,size_t
,real_T,real_T*,real_T*);void(*ssc_core_kosGVqM5sQxa_ilVRRQVR_)(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,PmAllocator*);NeCustomData*(*
mGetCustomDataFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*);int32_T(*
mSetCustomDataFcn)(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*,NeCustomData const*);
ssc_core__TnsaUXKFcKxbitO58_d7o*mData;};ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_VvMTiJ4aNWS9XLZDSLRpBj(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,real_T
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_F4kcadj_4cKHg1ezX_zsql(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,size_t ssc_core__ParkdIrhYxeXmPALk_GF9,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void ssc_core__iidYZ4BYP_PjX5JZknJVI(
real_T ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,
real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core_FrSEQFBq28SaWiGfpVZwav(real_T
ssc_core__J04yncaH90DXHzyG0hSm2,real_T ssc_core_V1YgAr3atRObWulPGeoQrC,real_T
ssc_core_Va6pQIuhOYhUWuCezCFrRy,real_T ssc_core_FxxpkhdCrI0Vc5cOy7vUAj,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core__6TSrGdfXtxLbXc3mviqDL(real_T
ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T
ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);void ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(real_T
ssc_core_VyvvmXk1hAC_byXba4Mz7O,real_T ssc_core_VdcD6u7f_kdPVe9Fz7gaKU,real_T
ssc_core_kxEENIdWfPSaZDyic0CcaO,real_T ssc_core__Hi10z5HjzpmfeY11NOEhD,real_T
ssc_core_VWkG9DXg_ahbc1nka0X4Y9,real_T ssc_core_k_QudKxoYxxwbHSi_v2Byq,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_kxXUtLdQo2hYZaSu_qhot3);typedef struct ssc_core__O0ccrbwinGtZXg5rlKfPs
{size_t ssc_core__1d4qwH2z0_UjyxEKdWfeI;real_T*ssc_core_kxXahU_c_qdpXi0Rw0Y_f4
;}ssc_core__3jAYGRNM_0vZ1_f3K3L68;static ssc_core__3jAYGRNM_0vZ1_f3K3L68
ssc_core__AanNsDwooWtiyayYiR0pB(PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,size_t
pm__dZ3R3yisKSMd19Osaf1CO){ssc_core__3jAYGRNM_0vZ1_f3K3L68 buffer;buffer.
ssc_core__1d4qwH2z0_UjyxEKdWfeI=pm__dZ3R3yisKSMd19Osaf1CO;if(
pm__dZ3R3yisKSMd19Osaf1CO==0){buffer.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4=NULL;}
else{buffer.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4=((pm_FbYb_iLqY2hwZTVlVaiqJY)->
mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(pm__dZ3R3yisKSMd19Osaf1CO),(sizeof(
real_T))));}return buffer;}static void ssc_core_VAscH6T1zTlHhuux1atWp5(
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY,ssc_core__3jAYGRNM_0vZ1_f3K3L68*buffer){
{void*const ssc_core_FxwVSg9vwzG8eLtQskT9KX=(buffer->
ssc_core_kxXahU_c_qdpXi0Rw0Y_f4);PmAllocator*const
ssc_core__QcrDUEx64pIcLN2CBuiTs=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_FxwVSg9vwzG8eLtQskT9KX){(ssc_core__QcrDUEx64pIcLN2CBuiTs)->mFreeFcn(
ssc_core__QcrDUEx64pIcLN2CBuiTs,ssc_core_FxwVSg9vwzG8eLtQskT9KX);}};buffer->
ssc_core_kxXahU_c_qdpXi0Rw0Y_f4=NULL;}static void
ssc_core_kxt5OAGYFJ_4_99Rfwlobp(ssc_core__3jAYGRNM_0vZ1_f3K3L68 buffer,size_t
ssc_core__K0_v7xZPoOLfHFOqAdCLP,real_T pm_kpzAtHMD4_WnheH0UiioSE){size_t
ssc_core_kh3C5f6ZAPlGWXfJykpWPn=(ssc_core__K0_v7xZPoOLfHFOqAdCLP%buffer.
ssc_core__1d4qwH2z0_UjyxEKdWfeI);buffer.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn]=pm_kpzAtHMD4_WnheH0UiioSE;}static real_T
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__3jAYGRNM_0vZ1_f3K3L68 buffer,size_t
ssc_core__K0_v7xZPoOLfHFOqAdCLP){size_t ssc_core_kh3C5f6ZAPlGWXfJykpWPn=(
ssc_core__K0_v7xZPoOLfHFOqAdCLP%buffer.ssc_core__1d4qwH2z0_UjyxEKdWfeI);return
buffer.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[ssc_core_kh3C5f6ZAPlGWXfJykpWPn];}
static size_t ssc_core__fJGgaZdE8pMbDhkbdemHp(real_T
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,real_T ssc_core__S17UNe0OXxtXymW5JFZ1s,size_t
ssc_core_VCyXav4tC_K_VDoOESO0VU,size_t ssc_core_F7nLNJUA5yS5bPnl7pqbSa,real_T
ssc_core__1eAP9V6_J_NYm_1gTIm7A){size_t ssc_core__Qyeh6gPJdSRd1jGEv75gI=(
size_t)floor((ssc_core__1eAP9V6_J_NYm_1gTIm7A-ssc_core_kd8a5_Um6xt3gPWlpqOjmu)
/ssc_core__S17UNe0OXxtXymW5JFZ1s);if((ssc_core__Qyeh6gPJdSRd1jGEv75gI>
ssc_core_VCyXav4tC_K_VDoOESO0VU)&&(ssc_core__1eAP9V6_J_NYm_1gTIm7A<
ssc_core_kd8a5_Um6xt3gPWlpqOjmu+ssc_core__Qyeh6gPJdSRd1jGEv75gI*
ssc_core__S17UNe0OXxtXymW5JFZ1s)){ssc_core__Qyeh6gPJdSRd1jGEv75gI--;}else if((
ssc_core__Qyeh6gPJdSRd1jGEv75gI+1<ssc_core_F7nLNJUA5yS5bPnl7pqbSa)&&(
ssc_core_kd8a5_Um6xt3gPWlpqOjmu+(ssc_core__Qyeh6gPJdSRd1jGEv75gI+1)*
ssc_core__S17UNe0OXxtXymW5JFZ1s<=ssc_core__1eAP9V6_J_NYm_1gTIm7A)){
ssc_core__Qyeh6gPJdSRd1jGEv75gI++;}return ssc_core__Qyeh6gPJdSRd1jGEv75gI;}
static size_t ssc_core__PIEQkFdxOlKVT5w9PEqC0(ssc_core__3jAYGRNM_0vZ1_f3K3L68
ssc_core__lpZlcgROz0vaixgoeyKm8,size_t ssc_core_VCyXav4tC_K_VDoOESO0VU,size_t
ssc_core_F7nLNJUA5yS5bPnl7pqbSa,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A){size_t
mc___aedK39Pax6Ziebprhh0i=ssc_core_VCyXav4tC_K_VDoOESO0VU;size_t
ssc_core__7SfbnIfBcGZYinikDTuBC=ssc_core_F7nLNJUA5yS5bPnl7pqbSa;while(
mc___aedK39Pax6Ziebprhh0i+1<ssc_core__7SfbnIfBcGZYinikDTuBC){size_t
ssc_core_kkX5Np8moDtzfD62egX1Ls=mc___aedK39Pax6Ziebprhh0i+(
ssc_core__7SfbnIfBcGZYinikDTuBC-mc___aedK39Pax6Ziebprhh0i)/2;if(
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_kkX5Np8moDtzfD62egX1Ls)<=ssc_core__1eAP9V6_J_NYm_1gTIm7A){
mc___aedK39Pax6Ziebprhh0i=ssc_core_kkX5Np8moDtzfD62egX1Ls;}else{
ssc_core__7SfbnIfBcGZYinikDTuBC=ssc_core_kkX5Np8moDtzfD62egX1Ls;}}(void)0;
return mc___aedK39Pax6Ziebprhh0i;}static ssc_core_VPCajzt28fK6eatUgrzZrl
ssc_core_VJjzeg2lHXKq_y_Wta2PM6(ssc_core__3jAYGRNM_0vZ1_f3K3L68
ssc_core__lpZlcgROz0vaixgoeyKm8,ssc_core__3jAYGRNM_0vZ1_f3K3L68 value,size_t
ssc_core___6udXZYOhlzcy3nvCqtF3,boolean_T ssc_core_FbSuL6hq06d5jem_imo5oD,
real_T ssc_core_kd8a5_Um6xt3gPWlpqOjmu,real_T ssc_core__S17UNe0OXxtXymW5JFZ1s,
real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T*v,real_T*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl){size_t ssc_core_krj9kT6v2FdG_mfBeNv6mb=value.
ssc_core__1d4qwH2z0_UjyxEKdWfeI;size_t ssc_core_VCyXav4tC_K_VDoOESO0VU=(
ssc_core___6udXZYOhlzcy3nvCqtF3<ssc_core_krj9kT6v2FdG_mfBeNv6mb?0:
ssc_core___6udXZYOhlzcy3nvCqtF3-ssc_core_krj9kT6v2FdG_mfBeNv6mb);size_t
ssc_core_F7nLNJUA5yS5bPnl7pqbSa=(ssc_core___6udXZYOhlzcy3nvCqtF3==0?0:
ssc_core___6udXZYOhlzcy3nvCqtF3-1);(void)0;;if(pmf_is_nan(
ssc_core__1eAP9V6_J_NYm_1gTIm7A)){*v=pmf_get_nan();*
ssc_core_FvV_QvokIEhz_D_P3Ewwdl=pmf_get_nan();return
ssc_core_krzbr94PVv0ZbeCf8B8TOo;}{real_T ssc_core_kTBZzW_gUwt0ZDmXMZatZ8=
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_VCyXav4tC_K_VDoOESO0VU);if(ssc_core__1eAP9V6_J_NYm_1gTIm7A<=
ssc_core_kTBZzW_gUwt0ZDmXMZatZ8){if(ssc_core___6udXZYOhlzcy3nvCqtF3>1){
ssc_core_FrSEQFBq28SaWiGfpVZwav(ssc_core_kTBZzW_gUwt0ZDmXMZatZ8,
ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,ssc_core_VCyXav4tC_K_VDoOESO0VU),
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_VCyXav4tC_K_VDoOESO0VU+1),ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,
ssc_core_VCyXav4tC_K_VDoOESO0VU+1),ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{ssc_core__iidYZ4BYP_PjX5JZknJVI(
ssc_core_kTBZzW_gUwt0ZDmXMZatZ8,ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,
ssc_core_VCyXav4tC_K_VDoOESO0VU),ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}return(ssc_core__1eAP9V6_J_NYm_1gTIm7A==
ssc_core_kTBZzW_gUwt0ZDmXMZatZ8?ssc_core_krzbr94PVv0ZbeCf8B8TOo:
ssc_core__Q97de9wAyd2ai1qgkC7FJ);}}{real_T ssc_core_FNy0ZkOcjO4mW1lHsrhI9w=
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_F7nLNJUA5yS5bPnl7pqbSa);if(ssc_core__1eAP9V6_J_NYm_1gTIm7A>=
ssc_core_FNy0ZkOcjO4mW1lHsrhI9w){if(ssc_core_F7nLNJUA5yS5bPnl7pqbSa>
ssc_core_VCyXav4tC_K_VDoOESO0VU){ssc_core_FrSEQFBq28SaWiGfpVZwav(
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_F7nLNJUA5yS5bPnl7pqbSa-1),ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,
ssc_core_F7nLNJUA5yS5bPnl7pqbSa-1),ssc_core_FNy0ZkOcjO4mW1lHsrhI9w,
ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,ssc_core_F7nLNJUA5yS5bPnl7pqbSa),
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{
ssc_core__iidYZ4BYP_PjX5JZknJVI(ssc_core_FNy0ZkOcjO4mW1lHsrhI9w,
ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,ssc_core_F7nLNJUA5yS5bPnl7pqbSa),
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}return(
ssc_core__1eAP9V6_J_NYm_1gTIm7A==ssc_core_FNy0ZkOcjO4mW1lHsrhI9w?
ssc_core_krzbr94PVv0ZbeCf8B8TOo:ssc_core_kF8uUNHtzb_HVP_tWzVLHo);}}(void)0;;{
size_t mc___aedK39Pax6Ziebprhh0i;real_T ssc_core_Vi8oRBKP0i8QWqSWHoD3hn,
ssc_core_Ftkj4MvR55_MiThmKO41SC;if(ssc_core_FbSuL6hq06d5jem_imo5oD){
mc___aedK39Pax6Ziebprhh0i=ssc_core__fJGgaZdE8pMbDhkbdemHp(
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,ssc_core__S17UNe0OXxtXymW5JFZ1s,
ssc_core_VCyXav4tC_K_VDoOESO0VU,ssc_core_F7nLNJUA5yS5bPnl7pqbSa,
ssc_core__1eAP9V6_J_NYm_1gTIm7A);ssc_core_Vi8oRBKP0i8QWqSWHoD3hn=
ssc_core_kd8a5_Um6xt3gPWlpqOjmu+mc___aedK39Pax6Ziebprhh0i*
ssc_core__S17UNe0OXxtXymW5JFZ1s;ssc_core_Ftkj4MvR55_MiThmKO41SC=
ssc_core_kd8a5_Um6xt3gPWlpqOjmu+(mc___aedK39Pax6Ziebprhh0i+1)*
ssc_core__S17UNe0OXxtXymW5JFZ1s;}else{mc___aedK39Pax6Ziebprhh0i=
ssc_core__PIEQkFdxOlKVT5w9PEqC0(ssc_core__lpZlcgROz0vaixgoeyKm8,
ssc_core_VCyXav4tC_K_VDoOESO0VU,ssc_core_F7nLNJUA5yS5bPnl7pqbSa,
ssc_core__1eAP9V6_J_NYm_1gTIm7A);ssc_core_Vi8oRBKP0i8QWqSWHoD3hn=
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
mc___aedK39Pax6Ziebprhh0i);ssc_core_Ftkj4MvR55_MiThmKO41SC=
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
mc___aedK39Pax6Ziebprhh0i+1);}{real_T ssc_core__J7mN6eQMz0GiH0zqhMMOC=
ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,mc___aedK39Pax6Ziebprhh0i);real_T
ssc_core_V5abNgHip94Xg1Cxrqc55Z=ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,
mc___aedK39Pax6Ziebprhh0i+1);if((ssc_core__1eAP9V6_J_NYm_1gTIm7A==
ssc_core_Vi8oRBKP0i8QWqSWHoD3hn)&&(mc___aedK39Pax6Ziebprhh0i>
ssc_core_VCyXav4tC_K_VDoOESO0VU)){real_T ssc_core_V00P_0WR6ptzZHHH3tmscA=
ssc_core_FbSuL6hq06d5jem_imo5oD?ssc_core_kd8a5_Um6xt3gPWlpqOjmu+(
mc___aedK39Pax6Ziebprhh0i-1)*ssc_core__S17UNe0OXxtXymW5JFZ1s:
ssc_core__bQGVZKX9_OgYPj_yb3iBx(ssc_core__lpZlcgROz0vaixgoeyKm8,
mc___aedK39Pax6Ziebprhh0i-1);ssc_core__QE_9QJ5Be0BaHFtNBzZ7H(
ssc_core_V00P_0WR6ptzZHHH3tmscA,ssc_core__bQGVZKX9_OgYPj_yb3iBx(value,
mc___aedK39Pax6Ziebprhh0i-1),ssc_core_Vi8oRBKP0i8QWqSWHoD3hn,
ssc_core__J7mN6eQMz0GiH0zqhMMOC,ssc_core_Ftkj4MvR55_MiThmKO41SC,
ssc_core_V5abNgHip94Xg1Cxrqc55Z,ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}else{ssc_core__6TSrGdfXtxLbXc3mviqDL(
ssc_core_Vi8oRBKP0i8QWqSWHoD3hn,ssc_core__J7mN6eQMz0GiH0zqhMMOC,
ssc_core_Ftkj4MvR55_MiThmKO41SC,ssc_core_V5abNgHip94Xg1Cxrqc55Z,
ssc_core__1eAP9V6_J_NYm_1gTIm7A,v,ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}}}return
ssc_core_krzbr94PVv0ZbeCf8B8TOo;}struct ssc_core_FpYOP0TyTZhiZaeVw73BmH{size_t
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t ssc_core_kjVMEKO_Gg8beattYY_YXT;real_T
mStartTime;real_T ssc_core__BzytCIJqpK6X9hlBST23v;real_T*
ssc_core__nZjPCaB0EStfHLWknKiTK;size_t ssc_core_VRIOspqolXOuh17mS8hmLZ;
boolean_T ssc_core_VX2XnBO6dhSdjiobTIrB4R;size_t
ssc_core__fwQoFPwhn4V_5mnuVti9m;boolean_T ssc_core_FHomHv6wBfhha1IWL5yG8R;
size_t ssc_core__bDFabAaLypxYXI9wseb77;ssc_core__3jAYGRNM_0vZ1_f3K3L68
ssc_core_FvPt29eXWrtnaywnAkTTzE;ssc_core__3jAYGRNM_0vZ1_f3K3L68*
ssc_core_VELrIEUHeudCamAhgAMD2P;PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY;};static
size_t ssc_core_FIGZ2VTqeu4zbqZZao51NR(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,
real_T ssc_core__FfnGiCP_W8NgT9vxf8vuJ,real_T const*
ssc_core__4PrJ1yDxRxoiyf8WHxOxf){size_t ssc_core__Yr9wlCuNBl2Y9jONoYCM0=8;
size_t ssc_core_FU0OYPIfnMKjie6IYCYQ9D=ssc_core__Yr9wlCuNBl2Y9jONoYCM0;size_t i
;(void)0;;for(i=0;i<ssc_core_V8uoyu0_YA0beyMVkKylrC;i++){size_t
ssc_core_krj9kT6v2FdG_mfBeNv6mb;(void)0;;ssc_core_krj9kT6v2FdG_mfBeNv6mb=(
size_t)ceil(ssc_core__4PrJ1yDxRxoiyf8WHxOxf[i]/ssc_core__FfnGiCP_W8NgT9vxf8vuJ
)+1;ssc_core_krj9kT6v2FdG_mfBeNv6mb=(ssc_core_krj9kT6v2FdG_mfBeNv6mb<
ssc_core__Yr9wlCuNBl2Y9jONoYCM0?ssc_core__Yr9wlCuNBl2Y9jONoYCM0:
ssc_core_krj9kT6v2FdG_mfBeNv6mb);ssc_core_FU0OYPIfnMKjie6IYCYQ9D=(
ssc_core_krj9kT6v2FdG_mfBeNv6mb>ssc_core_FU0OYPIfnMKjie6IYCYQ9D?
ssc_core_krj9kT6v2FdG_mfBeNv6mb:ssc_core_FU0OYPIfnMKjie6IYCYQ9D);}return
ssc_core_FU0OYPIfnMKjie6IYCYQ9D;}static ssc_core__TnsaUXKFcKxbitO58_d7o*
ssc_core_FPENxS4RNQ8T_Dpq_5vgtb(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd,real_T ssc_core_kd8a5_Um6xt3gPWlpqOjmu,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){size_t i;
ssc_core__TnsaUXKFcKxbitO58_d7o*result=(ssc_core__TnsaUXKFcKxbitO58_d7o*)(((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(
ssc_core__TnsaUXKFcKxbitO58_d7o)),(1))));result->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4=ssc_core_V8uoyu0_YA0beyMVkKylrC;result->
mStartTime=ssc_core_kd8a5_Um6xt3gPWlpqOjmu;result->
ssc_core__BzytCIJqpK6X9hlBST23v= -1.0;result->ssc_core_kjVMEKO_Gg8beattYY_YXT=
ssc_core_FNt92uaclVCyYXOJ4ykVyd;result->ssc_core_VX2XnBO6dhSdjiobTIrB4R=false;
result->ssc_core__fwQoFPwhn4V_5mnuVti9m=0;result->
ssc_core_FHomHv6wBfhha1IWL5yG8R=true;result->ssc_core__bDFabAaLypxYXI9wseb77=0
;result->ssc_core_VRIOspqolXOuh17mS8hmLZ=0;result->
ssc_core__nZjPCaB0EStfHLWknKiTK=((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(ssc_core_V8uoyu0_YA0beyMVkKylrC),(sizeof(real_T)))
);for(i=0;i<ssc_core_V8uoyu0_YA0beyMVkKylrC;i++){result->
ssc_core__nZjPCaB0EStfHLWknKiTK[i]= -1.0;}result->
ssc_core_FvPt29eXWrtnaywnAkTTzE=ssc_core__AanNsDwooWtiyayYiR0pB(
pm_FbYb_iLqY2hwZTVlVaiqJY,0);result->ssc_core_VELrIEUHeudCamAhgAMD2P=((
pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((pm_FbYb_iLqY2hwZTVlVaiqJY),(
ssc_core_V8uoyu0_YA0beyMVkKylrC),(sizeof(ssc_core__3jAYGRNM_0vZ1_f3K3L68))));
for(i=0;i<ssc_core_V8uoyu0_YA0beyMVkKylrC;i++){result->
ssc_core_VELrIEUHeudCamAhgAMD2P[i]=ssc_core__AanNsDwooWtiyayYiR0pB(
pm_FbYb_iLqY2hwZTVlVaiqJY,0);}result->pm_FbYb_iLqY2hwZTVlVaiqJY=
pm_FbYb_iLqY2hwZTVlVaiqJY;return result;}static boolean_T
ssc_core_knzRHl4KHw_Ff9qkPqkDfK(ssc_core__TnsaUXKFcKxbitO58_d7o const*
mc__d1alWYexptL_X5HTFhbNK){return mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VX2XnBO6dhSdjiobTIrB4R;}static boolean_T
ssc_core_kTG_5_cRDW8Tc5IgaIX_GH(ssc_core__TnsaUXKFcKxbitO58_d7o const*
mc__d1alWYexptL_X5HTFhbNK){return(ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
mc__d1alWYexptL_X5HTFhbNK)&&mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m>0);}static int32_T
ssc_core_FceKvXWKlO8NYmAfxchkfB(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;real_T ssc_core__FfnGiCP_W8NgT9vxf8vuJ=
mc__d1alWYexptL_X5HTFhbNK->ssc_core__BzytCIJqpK6X9hlBST23v;size_t
ssc_core_FNt92uaclVCyYXOJ4ykVyd=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT;real_T const*ssc_core__4PrJ1yDxRxoiyf8WHxOxf=
mc__d1alWYexptL_X5HTFhbNK->ssc_core__nZjPCaB0EStfHLWknKiTK;size_t
ssc_core_krj9kT6v2FdG_mfBeNv6mb;size_t ssc_core_kBUzpas7Melyf1SN1PiiIY;size_t i
;ssc_core_krj9kT6v2FdG_mfBeNv6mb=ssc_core_FIGZ2VTqeu4zbqZZao51NR(
ssc_core_F5sR7BGiOQO9jq888pvXvp,ssc_core__FfnGiCP_W8NgT9vxf8vuJ,
ssc_core__4PrJ1yDxRxoiyf8WHxOxf);ssc_core_kBUzpas7Melyf1SN1PiiIY=(
ssc_core_F5sR7BGiOQO9jq888pvXvp+1)*ssc_core_krj9kT6v2FdG_mfBeNv6mb*sizeof(
real_T);if(ssc_core_kBUzpas7Melyf1SN1PiiIY>ssc_core_FNt92uaclVCyYXOJ4ykVyd){
return ssc_core_kOw2Uegv5BGjVXro1JWJHO;}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VRIOspqolXOuh17mS8hmLZ=ssc_core_krj9kT6v2FdG_mfBeNv6mb;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FvPt29eXWrtnaywnAkTTzE=
ssc_core__AanNsDwooWtiyayYiR0pB(pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core_krj9kT6v2FdG_mfBeNv6mb);for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i++
){mc__d1alWYexptL_X5HTFhbNK->ssc_core_VELrIEUHeudCamAhgAMD2P[i]=
ssc_core__AanNsDwooWtiyayYiR0pB(pm_FbYb_iLqY2hwZTVlVaiqJY,
ssc_core_krj9kT6v2FdG_mfBeNv6mb);}mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT=0;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VX2XnBO6dhSdjiobTIrB4R=true;(void)0;;return
ssc_core__aIDnqGzhqWcVu6dhPsWV2;}static void ssc_core__Z4HfJeRyKhDVuUR83JXa2(
ssc_core__TnsaUXKFcKxbitO58_d7o*mc__d1alWYexptL_X5HTFhbNK){if(!
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VX2XnBO6dhSdjiobTIrB4R){return;}if(!
ssc_core_knzRHl4KHw_Ff9qkPqkDfK(mc__d1alWYexptL_X5HTFhbNK)){return;}
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m=0;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FHomHv6wBfhha1IWL5yG8R=true;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__bDFabAaLypxYXI9wseb77=0;}static void
ssc_core_VA5Yrvke1DtcgmpP5CoRMR(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK,NeSimulationParameters
ssc_core_k_mRxeK4vft_iezHjHn6V7){(void)0;;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__BzytCIJqpK6X9hlBST23v=ssc_core_k_mRxeK4vft_iezHjHn6V7 .
mFixedStepSize;}static void ssc_core__7u9hiy_msdQXqGceglAfW(
ssc_core__TnsaUXKFcKxbitO58_d7o*mc__d1alWYexptL_X5HTFhbNK,real_T const*
ssc_core__4PrJ1yDxRxoiyf8WHxOxf){size_t ssc_core_F5sR7BGiOQO9jq888pvXvp=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t i;for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){mc__d1alWYexptL_X5HTFhbNK->
ssc_core__nZjPCaB0EStfHLWknKiTK[i]=ssc_core__4PrJ1yDxRxoiyf8WHxOxf[i];}}static
void ssc_core__0BJ4HcCvPSqgy0OBF9T7J(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK){PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY=
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t i;{void*const
ssc_core_kVVXfra4QCpxiLeULyieG4=(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__nZjPCaB0EStfHLWknKiTK);PmAllocator*const
ssc_core__h4W5fAuZmKIWPOaa_AaGM=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_kVVXfra4QCpxiLeULyieG4){(ssc_core__h4W5fAuZmKIWPOaa_AaGM)->mFreeFcn(
ssc_core__h4W5fAuZmKIWPOaa_AaGM,ssc_core_kVVXfra4QCpxiLeULyieG4);}};
ssc_core_VAscH6T1zTlHhuux1atWp5(pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FvPt29eXWrtnaywnAkTTzE));for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){ssc_core_VAscH6T1zTlHhuux1atWp5(
pm_FbYb_iLqY2hwZTVlVaiqJY,&(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VELrIEUHeudCamAhgAMD2P[i]));}{void*const
ssc_core__2OsAhxKE8WA_Di0zZq2D3=(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VELrIEUHeudCamAhgAMD2P);PmAllocator*const
ssc_core_k_dDKYvoaaKygmxUehNJW_=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core__2OsAhxKE8WA_Di0zZq2D3){(ssc_core_k_dDKYvoaaKygmxUehNJW_)->mFreeFcn(
ssc_core_k_dDKYvoaaKygmxUehNJW_,ssc_core__2OsAhxKE8WA_Di0zZq2D3);}};{void*
const ssc_core_FJVtSC212w8b_5YzDYzR_b=(mc__d1alWYexptL_X5HTFhbNK);PmAllocator*
const ssc_core__YudMrqVwTdtgPmzgryoPA=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core_FJVtSC212w8b_5YzDYzR_b){(ssc_core__YudMrqVwTdtgPmzgryoPA)->mFreeFcn(
ssc_core__YudMrqVwTdtgPmzgryoPA,ssc_core_FJVtSC212w8b_5YzDYzR_b);}};}static
int32_T ssc_core_F4ay3mU2KmpqZ1iah9APGb(ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T const*
pm_kpzAtHMD4_WnheH0UiioSE){size_t i;(void)0;if(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m>0){real_T ssc_core_VU4Jmog8PzlRZDinlreIYW=
mc__d1alWYexptL_X5HTFhbNK->mStartTime+mc__d1alWYexptL_X5HTFhbNK->
ssc_core__BzytCIJqpK6X9hlBST23v*mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m;real_T mc_FfDTppU8N_tOWuLK37x_08=16.0*
pmf_get_eps()*((fabs(ssc_core__1eAP9V6_J_NYm_1gTIm7A))>(fabs(
ssc_core_VU4Jmog8PzlRZDinlreIYW))?(fabs(ssc_core__1eAP9V6_J_NYm_1gTIm7A)):(
fabs(ssc_core_VU4Jmog8PzlRZDinlreIYW)));boolean_T
ssc_core_VwbI_3jrk18phDKpdTysTG=(boolean_T)(fabs(
ssc_core__1eAP9V6_J_NYm_1gTIm7A-ssc_core_VU4Jmog8PzlRZDinlreIYW)<=
mc_FfDTppU8N_tOWuLK37x_08);if(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FHomHv6wBfhha1IWL5yG8R){if(!ssc_core_VwbI_3jrk18phDKpdTysTG){
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FHomHv6wBfhha1IWL5yG8R=false;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__bDFabAaLypxYXI9wseb77=0;}}else{if(
ssc_core_VwbI_3jrk18phDKpdTysTG){mc__d1alWYexptL_X5HTFhbNK->
ssc_core__bDFabAaLypxYXI9wseb77++;if(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__bDFabAaLypxYXI9wseb77>=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VRIOspqolXOuh17mS8hmLZ){mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FHomHv6wBfhha1IWL5yG8R=true;}}else{mc__d1alWYexptL_X5HTFhbNK->
ssc_core__bDFabAaLypxYXI9wseb77=0;}}}ssc_core_kxt5OAGYFJ_4_99Rfwlobp(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FvPt29eXWrtnaywnAkTTzE,
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m,
ssc_core__1eAP9V6_J_NYm_1gTIm7A);for(i=0;i<mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;i++){ssc_core_kxt5OAGYFJ_4_99Rfwlobp(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VELrIEUHeudCamAhgAMD2P[i],
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m,
pm_kpzAtHMD4_WnheH0UiioSE[i]);}(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m)++;return ssc_core__aIDnqGzhqWcVu6dhPsWV2;}
static ssc_core_VPCajzt28fK6eatUgrzZrl ssc_core_FufBpOwN0D4CX1YpppLxRH(
ssc_core__TnsaUXKFcKxbitO58_d7o const*mc__d1alWYexptL_X5HTFhbNK,size_t
ssc_core_V17P9xH_Q9hBeeuhligsAZ,real_T ssc_core_VER4IpDoghhAb5UJpdofQJ,real_T*
v,real_T*ssc_core_FvV_QvokIEhz_D_P3Ewwdl){(void)0;;return
ssc_core_VJjzeg2lHXKq_y_Wta2PM6(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FvPt29eXWrtnaywnAkTTzE,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VELrIEUHeudCamAhgAMD2P[ssc_core_V17P9xH_Q9hBeeuhligsAZ],
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FHomHv6wBfhha1IWL5yG8R,
mc__d1alWYexptL_X5HTFhbNK->mStartTime,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__BzytCIJqpK6X9hlBST23v,ssc_core_VER4IpDoghhAb5UJpdofQJ,v,
ssc_core_FvV_QvokIEhz_D_P3Ewwdl);}static boolean_T
ssc_core_VvJR4zMum80_cDaeLoT7uN(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*
ssc_core_V_m2gViqqexRZXIgiYbrwb){return ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static boolean_T
ssc_core_Fl7arEKHgStUWXbyU_0aH5(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*
ssc_core_V_m2gViqqexRZXIgiYbrwb){return ssc_core_kTG_5_cRDW8Tc5IgaIX_GH(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static int32_T
ssc_core_VJWJnUKpoiSYiig4nfjtvs(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,real_T const*ssc_core__4PrJ1yDxRxoiyf8WHxOxf){
(void)0;;ssc_core__7u9hiy_msdQXqGceglAfW(ssc_core_V_m2gViqqexRZXIgiYbrwb->
mData,ssc_core__4PrJ1yDxRxoiyf8WHxOxf);return ssc_core_FceKvXWKlO8NYmAfxchkfB(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}static void
ssc_core__UiIrMM0K_WscP5UshnHvS(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,NeSimulationParameters
ssc_core_k_mRxeK4vft_iezHjHn6V7){(void)0;;ssc_core_VA5Yrvke1DtcgmpP5CoRMR(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData,ssc_core_k_mRxeK4vft_iezHjHn6V7);
ssc_core__Z4HfJeRyKhDVuUR83JXa2(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);}
static int32_T ssc_core_FkK7GheMwDhz_q5GrsV_GG(ssc_core_kIG7sD0lJlWTfaZr6Pehvz
*ssc_core_V_m2gViqqexRZXIgiYbrwb,real_T ssc_core__1eAP9V6_J_NYm_1gTIm7A,real_T
const*pm_kpzAtHMD4_WnheH0UiioSE){(void)0;;return
ssc_core_F4ay3mU2KmpqZ1iah9APGb(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData,
ssc_core__1eAP9V6_J_NYm_1gTIm7A,pm_kpzAtHMD4_WnheH0UiioSE);}static void
ssc_core_Ve0b7jBudDtzcilYG_QRz6(ssc_core_kIG7sD0lJlWTfaZr6Pehvz const*
ssc_core_V_m2gViqqexRZXIgiYbrwb,size_t ssc_core_kh3C5f6ZAPlGWXfJykpWPn,real_T
ssc_core_VER4IpDoghhAb5UJpdofQJ,real_T*pm_kpzAtHMD4_WnheH0UiioSE,real_T*
ssc_core__UXEfLq_c3__YDAWn2ItxA){(void)0;;ssc_core_FufBpOwN0D4CX1YpppLxRH(
ssc_core_V_m2gViqqexRZXIgiYbrwb->mData,ssc_core_kh3C5f6ZAPlGWXfJykpWPn,
ssc_core_VER4IpDoghhAb5UJpdofQJ,pm_kpzAtHMD4_WnheH0UiioSE,
ssc_core__UXEfLq_c3__YDAWn2ItxA);}static void ssc_core_kgQsk5KLchlDgaDrSXDE0B(
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*ssc_core_V_m2gViqqexRZXIgiYbrwb,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY){if(ssc_core_V_m2gViqqexRZXIgiYbrwb!=NULL){
ssc_core__0BJ4HcCvPSqgy0OBF9T7J(ssc_core_V_m2gViqqexRZXIgiYbrwb->mData);{void*
const ssc_core_VnhrUzv0rpdIbe_9ZKOGWj=(ssc_core_V_m2gViqqexRZXIgiYbrwb);
PmAllocator*const ssc_core_FnCw1H0_rxCceathbO2aw8=(pm_FbYb_iLqY2hwZTVlVaiqJY);
if(ssc_core_VnhrUzv0rpdIbe_9ZKOGWj){(ssc_core_FnCw1H0_rxCceathbO2aw8)->
mFreeFcn(ssc_core_FnCw1H0_rxCceathbO2aw8,ssc_core_VnhrUzv0rpdIbe_9ZKOGWj);}};}
}enum ssc_core_F1pZSSX_wdt7d1V0x_QweW{ssc_core_Vr59wrVYWmSwYDdUfsuZK9= -1,
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4,ssc_core_kjVMEKO_Gg8beattYY_YXT,
ssc_core_VX2XnBO6dhSdjiobTIrB4R,ssc_core__fwQoFPwhn4V_5mnuVti9m,
ssc_core_FHomHv6wBfhha1IWL5yG8R,ssc_core__bDFabAaLypxYXI9wseb77,
ssc_core_VRIOspqolXOuh17mS8hmLZ,ssc_core_khIwJz5TXXx6hXgLq38HlW};enum
ssc_core_Fxt_0NEy99GZY1_JyHQbcA{ssc_core_kOpuW4HesWWBX1Wz9f_fiK= -1,mStartTime
,ssc_core__BzytCIJqpK6X9hlBST23v,ssc_core__vi6Wwo2VD4o_i2D0QEYrJ};static
NeCustomData*ssc_core_FGAm5nbshNCChDigIPq3yj(const
ssc_core_kIG7sD0lJlWTfaZr6Pehvz*ssc_core_V_m2gViqqexRZXIgiYbrwb){
NeCustomDataSize mc__0REJ38_cKO_bunM1JCRT_;NeCustomData*
ssc_core_FuIvge0ANAGVYLeQL84M_L;ssc_core__TnsaUXKFcKxbitO58_d7o const*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_V_m2gViqqexRZXIgiYbrwb->mData;boolean_T
ssc_core_kNkRf7grccdcb9zA6ZLzLI=ssc_core_knzRHl4KHw_Ff9qkPqkDfK(
mc__d1alWYexptL_X5HTFhbNK);size_t ssc_core_F5sR7BGiOQO9jq888pvXvp=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t
ssc_core__K0_v7xZPoOLfHFOqAdCLP=mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m;size_t ssc_core_krj9kT6v2FdG_mfBeNv6mb=
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VRIOspqolXOuh17mS8hmLZ;size_t
ssc_core_FuP_vBAI2s_keXl9B8tvML=((ssc_core__K0_v7xZPoOLfHFOqAdCLP)<(
ssc_core_krj9kT6v2FdG_mfBeNv6mb)?(ssc_core__K0_v7xZPoOLfHFOqAdCLP):(
ssc_core_krj9kT6v2FdG_mfBeNv6mb));size_t ssc_core_kh3C5f6ZAPlGWXfJykpWPn;
size_t i,k;mc__0REJ38_cKO_bunM1JCRT_.ssc_core_kAKxIvM1NQGM_TY96YysC5=
ssc_core_khIwJz5TXXx6hXgLq38HlW;mc__0REJ38_cKO_bunM1JCRT_.
ssc_core_VOAPNvYIRPGzhDXn1iCcKS=ssc_core__vi6Wwo2VD4o_i2D0QEYrJ+
ssc_core_F5sR7BGiOQO9jq888pvXvp;if(ssc_core_kNkRf7grccdcb9zA6ZLzLI){
mc__0REJ38_cKO_bunM1JCRT_.ssc_core_VOAPNvYIRPGzhDXn1iCcKS+=(
ssc_core_F5sR7BGiOQO9jq888pvXvp+1)*ssc_core_FuP_vBAI2s_keXl9B8tvML;}
ssc_core_FuIvge0ANAGVYLeQL84M_L=ssc_core_VFzWBz_s8FW9_qamuHujnl(
mc__0REJ38_cKO_bunM1JCRT_);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_k7BUQ6_0kj8_cm39ZbqKv4]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4);
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_kjVMEKO_Gg8beattYY_YXT]=(int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_VX2XnBO6dhSdjiobTIrB4R]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VX2XnBO6dhSdjiobTIrB4R);
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]=(int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_FHomHv6wBfhha1IWL5yG8R]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FHomHv6wBfhha1IWL5yG8R);
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__bDFabAaLypxYXI9wseb77]=(int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__bDFabAaLypxYXI9wseb77);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_VRIOspqolXOuh17mS8hmLZ]=(int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VRIOspqolXOuh17mS8hmLZ);;(void)0;;
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[mStartTime]=(
mc__d1alWYexptL_X5HTFhbNK->mStartTime);ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_VOMV27LEztpmd59gF8yJO0[ssc_core__BzytCIJqpK6X9hlBST23v]=(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__BzytCIJqpK6X9hlBST23v);;
ssc_core_kh3C5f6ZAPlGWXfJykpWPn=ssc_core__vi6Wwo2VD4o_i2D0QEYrJ;for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_VOMV27LEztpmd59gF8yJO0[ssc_core_kh3C5f6ZAPlGWXfJykpWPn++]=
mc__d1alWYexptL_X5HTFhbNK->ssc_core__nZjPCaB0EStfHLWknKiTK[i];}if(
ssc_core_kNkRf7grccdcb9zA6ZLzLI){for(k=0;k<ssc_core_FuP_vBAI2s_keXl9B8tvML;k++
){ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn++]=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FvPt29eXWrtnaywnAkTTzE.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[k];}for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){for(k=0;k<ssc_core_FuP_vBAI2s_keXl9B8tvML
;k++){ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn++]=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VELrIEUHeudCamAhgAMD2P[i].ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[k];}}}(void
)0;;return ssc_core_FuIvge0ANAGVYLeQL84M_L;}static int32_T
ssc_core_k39V8EHbSoCQdHC64RVdZS(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_V_m2gViqqexRZXIgiYbrwb,NeCustomData const*
ssc_core_FuIvge0ANAGVYLeQL84M_L){ssc_core__TnsaUXKFcKxbitO58_d7o*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_V_m2gViqqexRZXIgiYbrwb->mData;size_t
ssc_core_F5sR7BGiOQO9jq888pvXvp=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4;size_t ssc_core_kh3C5f6ZAPlGWXfJykpWPn;size_t i
,k;boolean_T ssc_core__IWYAdgYlQ_7jyIENI5Txc=(boolean_T)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_VX2XnBO6dhSdjiobTIrB4R]);boolean_T ssc_core_kWFn_Iox2P40W91p8PFln_=
ssc_core_knzRHl4KHw_Ff9qkPqkDfK(mc__d1alWYexptL_X5HTFhbNK);if((int32_T)(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_k7BUQ6_0kj8_cm39ZbqKv4)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_k7BUQ6_0kj8_cm39ZbqKv4]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(
mc__d1alWYexptL_X5HTFhbNK->mStartTime!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_VOMV27LEztpmd59gF8yJO0[mStartTime]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(ssc_core__IWYAdgYlQ_7jyIENI5Txc){if(
ssc_core_kWFn_Iox2P40W91p8PFln_==false){int32_T ssc_core_Fbnx9FOLhnW0X1Wd233Ai7
=0;mc__d1alWYexptL_X5HTFhbNK->ssc_core__BzytCIJqpK6X9hlBST23v=(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core__BzytCIJqpK6X9hlBST23v]);;ssc_core_kh3C5f6ZAPlGWXfJykpWPn=
ssc_core__vi6Wwo2VD4o_i2D0QEYrJ;for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i++)
{mc__d1alWYexptL_X5HTFhbNK->ssc_core__nZjPCaB0EStfHLWknKiTK[i]=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn++];}ssc_core_Fbnx9FOLhnW0X1Wd233Ai7=
ssc_core_FceKvXWKlO8NYmAfxchkfB(mc__d1alWYexptL_X5HTFhbNK);if(
ssc_core_Fbnx9FOLhnW0X1Wd233Ai7!=ssc_core__aIDnqGzhqWcVu6dhPsWV2){return
ssc_core_Fbnx9FOLhnW0X1Wd233Ai7;}}if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VX2XnBO6dhSdjiobTIrB4R)!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_VX2XnBO6dhSdjiobTIrB4R]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT)!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_kjVMEKO_Gg8beattYY_YXT]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VRIOspqolXOuh17mS8hmLZ)!=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_VRIOspqolXOuh17mS8hmLZ]){return
ssc_core__XHpTEMxftlSiT4M8UKKvF;};for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;i
++){(void)0;;}ssc_core_kh3C5f6ZAPlGWXfJykpWPn=ssc_core__vi6Wwo2VD4o_i2D0QEYrJ+
ssc_core_F5sR7BGiOQO9jq888pvXvp;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core__fwQoFPwhn4V_5mnuVti9m]);;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FHomHv6wBfhha1IWL5yG8R=(boolean_T)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_FHomHv6wBfhha1IWL5yG8R]);;mc__d1alWYexptL_X5HTFhbNK->
ssc_core__bDFabAaLypxYXI9wseb77=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core__bDFabAaLypxYXI9wseb77]);;{size_t
ssc_core_krj9kT6v2FdG_mfBeNv6mb=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VRIOspqolXOuh17mS8hmLZ;size_t ssc_core_FuP_vBAI2s_keXl9B8tvML=((
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m)<(
ssc_core_krj9kT6v2FdG_mfBeNv6mb)?(mc__d1alWYexptL_X5HTFhbNK->
ssc_core__fwQoFPwhn4V_5mnuVti9m):(ssc_core_krj9kT6v2FdG_mfBeNv6mb));for(k=0;k<
ssc_core_FuP_vBAI2s_keXl9B8tvML;k++){mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FvPt29eXWrtnaywnAkTTzE.ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[k]=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn++];}for(i=0;i<ssc_core_F5sR7BGiOQO9jq888pvXvp;
i++){for(k=0;k<ssc_core_FuP_vBAI2s_keXl9B8tvML;k++){mc__d1alWYexptL_X5HTFhbNK
->ssc_core_VELrIEUHeudCamAhgAMD2P[i].ssc_core_kxXahU_c_qdpXi0Rw0Y_f4[k]=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_VOMV27LEztpmd59gF8yJO0[
ssc_core_kh3C5f6ZAPlGWXfJykpWPn++];}}}(void)0;;}else{if(
ssc_core_kWFn_Iox2P40W91p8PFln_){ssc_core_VAscH6T1zTlHhuux1atWp5(
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FvPt29eXWrtnaywnAkTTzE));for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){ssc_core_VAscH6T1zTlHhuux1atWp5(
mc__d1alWYexptL_X5HTFhbNK->pm_FbYb_iLqY2hwZTVlVaiqJY,&(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VELrIEUHeudCamAhgAMD2P[i]));}
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VX2XnBO6dhSdjiobTIrB4R=(boolean_T)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_VX2XnBO6dhSdjiobTIrB4R]);;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kjVMEKO_Gg8beattYY_YXT=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_kjVMEKO_Gg8beattYY_YXT]);;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m=(size_t)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]);;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FHomHv6wBfhha1IWL5yG8R=(boolean_T)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_FHomHv6wBfhha1IWL5yG8R]);;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__bDFabAaLypxYXI9wseb77=(size_t)(
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__bDFabAaLypxYXI9wseb77]);;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VRIOspqolXOuh17mS8hmLZ=(size_t)(ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_F85sNEuWe1GIjmiT6vHSvn[ssc_core_VRIOspqolXOuh17mS8hmLZ]);;
ssc_core_kh3C5f6ZAPlGWXfJykpWPn=ssc_core__vi6Wwo2VD4o_i2D0QEYrJ;for(i=0;i<
ssc_core_F5sR7BGiOQO9jq888pvXvp;i++){mc__d1alWYexptL_X5HTFhbNK->
ssc_core__nZjPCaB0EStfHLWknKiTK[i]=ssc_core_FuIvge0ANAGVYLeQL84M_L->
ssc_core_VOMV27LEztpmd59gF8yJO0[ssc_core_kh3C5f6ZAPlGWXfJykpWPn++];}(void)0;;}
}if((int32_T)(mc__d1alWYexptL_X5HTFhbNK->ssc_core_VX2XnBO6dhSdjiobTIrB4R)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_VX2XnBO6dhSdjiobTIrB4R]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(
(int32_T)(mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjVMEKO_Gg8beattYY_YXT)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core_kjVMEKO_Gg8beattYY_YXT]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};if(
(int32_T)(mc__d1alWYexptL_X5HTFhbNK->ssc_core__fwQoFPwhn4V_5mnuVti9m)!=
ssc_core_FuIvge0ANAGVYLeQL84M_L->ssc_core_F85sNEuWe1GIjmiT6vHSvn[
ssc_core__fwQoFPwhn4V_5mnuVti9m]){return ssc_core__XHpTEMxftlSiT4M8UKKvF;};
return ssc_core__aIDnqGzhqWcVu6dhPsWV2;}ssc_core_kIG7sD0lJlWTfaZr6Pehvz*
ssc_core_VvMTiJ4aNWS9XLZDSLRpBj(size_t ssc_core_V8uoyu0_YA0beyMVkKylrC,real_T
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,size_t ssc_core_FNt92uaclVCyYXOJ4ykVyd,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){ssc_core_kIG7sD0lJlWTfaZr6Pehvz*result=
(ssc_core_kIG7sD0lJlWTfaZr6Pehvz*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(ssc_core_kIG7sD0lJlWTfaZr6Pehvz)),(1))));
result->ssc_core_kpVC1AX7p50Ja18UISsLi_=ssc_core_VvJR4zMum80_cDaeLoT7uN;result
->ssc_core_F9Kq4Qr_9Z0Yjm1oicqvtn=ssc_core_Fl7arEKHgStUWXbyU_0aH5;result->
mInitializeFcn=ssc_core__UiIrMM0K_WscP5UshnHvS;result->
ssc_core__pl1MSSO99W8WP3QqnoCib=ssc_core_VJWJnUKpoiSYiig4nfjtvs;result->
ssc_core_VG3e0ucOiSGjh1qwaVjeHl=ssc_core_FkK7GheMwDhz_q5GrsV_GG;result->
ssc_core_VpAc4HLF9R4vc5lHk8ztuA=ssc_core_Ve0b7jBudDtzcilYG_QRz6;result->
ssc_core_kosGVqM5sQxa_ilVRRQVR_=ssc_core_kgQsk5KLchlDgaDrSXDE0B;result->
mGetCustomDataFcn=ssc_core_FGAm5nbshNCChDigIPq3yj;result->mSetCustomDataFcn=
ssc_core_k39V8EHbSoCQdHC64RVdZS;result->mData=ssc_core_FPENxS4RNQ8T_Dpq_5vgtb(
ssc_core_V8uoyu0_YA0beyMVkKylrC,ssc_core_FNt92uaclVCyYXOJ4ykVyd,
ssc_core_kd8a5_Um6xt3gPWlpqOjmu,pm_FbYb_iLqY2hwZTVlVaiqJY);(void)0;;return
result;}
