#include "multibody_model_macros.h"
#include "pm_std.h"
#include "ne_std.h"
typedef struct ssc_core_V3scVTYpjYthiPB7SQIxc_ ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8
;typedef struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm ssc_core__SHoBDzmLMOwaLvvD5hSet
;struct ssc_core_kIPOBZ_WiKlfjLUfb6Vbcm{boolean_T(*
ssc_core_FBsF3SW3Cyp_j5Pu5wPhdl)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G,NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k)
;void(*mc_VrNsQKHIiLOFaL3PHRFxZL)(ssc_core__SHoBDzmLMOwaLvvD5hSet const*
ssc_core_FeUzPe0YQn4rca7KjD_v4G);void(*mDestroy)(
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core_FeUzPe0YQn4rca7KjD_v4G);
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*mData;};ssc_core__SHoBDzmLMOwaLvvD5hSet*
ssc_core_kBca8i4PhxS0j9d1s9qjOH(NeSystemInputSizes sizes,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "pm_std.h"
#include "pm_std.h"
#include "ne_std.h"
#include "ne_std.h"
struct ssc_core_V3scVTYpjYthiPB7SQIxc_{boolean_T
ssc_core_FbdZnMFCJSKiWiU7o8qdCq;PmAllocator*ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;};
static boolean_T ssc_core_kTtSUEBuNYSDc5jvQsk369(
ssc_core__SHoBDzmLMOwaLvvD5hSet const*ssc_core_FeUzPe0YQn4rca7KjD_v4G,
NeSystemInput const*mc_kDRphcAfRHSbf1ZLKEDW9k){boolean_T
ssc_core_V9uAItqbMYS0dHXy8Z61XW=false;ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_FeUzPe0YQn4rca7KjD_v4G->mData;(void)
mc_kDRphcAfRHSbf1ZLKEDW9k;if(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FbdZnMFCJSKiWiU7o8qdCq){ssc_core_V9uAItqbMYS0dHXy8Z61XW=true;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FbdZnMFCJSKiWiU7o8qdCq=false;}return
ssc_core_V9uAItqbMYS0dHXy8Z61XW;}static void ssc_core_VKp00NftRMt9VHXCrTxU2Z(
ssc_core__SHoBDzmLMOwaLvvD5hSet const*ssc_core_FeUzPe0YQn4rca7KjD_v4G){
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*mc__d1alWYexptL_X5HTFhbNK=
ssc_core_FeUzPe0YQn4rca7KjD_v4G->mData;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FbdZnMFCJSKiWiU7o8qdCq=true;}static void
ssc_core_VhM6LeTCpVKS_9UnRhu_KK(ssc_core__SHoBDzmLMOwaLvvD5hSet*
ssc_core_FeUzPe0YQn4rca7KjD_v4G){ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*
mc__d1alWYexptL_X5HTFhbNK=ssc_core_FeUzPe0YQn4rca7KjD_v4G->mData;PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa;{void*const ssc_core_FiQnVwFvdWOsZq7B7HjOOu=(
mc__d1alWYexptL_X5HTFhbNK);PmAllocator*const ssc_core_FUEy1LyQ9H_WfmKZ7x6Eym=(
pm_FbYb_iLqY2hwZTVlVaiqJY);if(ssc_core_FiQnVwFvdWOsZq7B7HjOOu){(
ssc_core_FUEy1LyQ9H_WfmKZ7x6Eym)->mFreeFcn(ssc_core_FUEy1LyQ9H_WfmKZ7x6Eym,
ssc_core_FiQnVwFvdWOsZq7B7HjOOu);}};{void*const ssc_core__mENNO85zUh5aaguhhWRBN
=(ssc_core_FeUzPe0YQn4rca7KjD_v4G);PmAllocator*const
ssc_core_FyTGi67_ZvtUZTUHxeAb0S=(pm_FbYb_iLqY2hwZTVlVaiqJY);if(
ssc_core__mENNO85zUh5aaguhhWRBN){(ssc_core_FyTGi67_ZvtUZTUHxeAb0S)->mFreeFcn(
ssc_core_FyTGi67_ZvtUZTUHxeAb0S,ssc_core__mENNO85zUh5aaguhhWRBN);}};}
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core_kBca8i4PhxS0j9d1s9qjOH(
NeSystemInputSizes sizes,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY){
ssc_core__SHoBDzmLMOwaLvvD5hSet*ssc_core_FeUzPe0YQn4rca7KjD_v4G=(
ssc_core__SHoBDzmLMOwaLvvD5hSet*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(ssc_core__SHoBDzmLMOwaLvvD5hSet)),(1))));
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*mc__d1alWYexptL_X5HTFhbNK=(
ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8*)(((pm_FbYb_iLqY2hwZTVlVaiqJY)->mCallocFcn((
pm_FbYb_iLqY2hwZTVlVaiqJY),(sizeof(ssc_core_FlZrG1BcKjtGV1aBRQ0fZ8)),(1))));(
void)sizes;mc__d1alWYexptL_X5HTFhbNK->ssc_core_FbdZnMFCJSKiWiU7o8qdCq=true;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_Ff9S1xA4Ip4ZXeljM4_eEa=
pm_FbYb_iLqY2hwZTVlVaiqJY;ssc_core_FeUzPe0YQn4rca7KjD_v4G->
ssc_core_FBsF3SW3Cyp_j5Pu5wPhdl=ssc_core_kTtSUEBuNYSDc5jvQsk369;
ssc_core_FeUzPe0YQn4rca7KjD_v4G->mc_VrNsQKHIiLOFaL3PHRFxZL=
ssc_core_VKp00NftRMt9VHXCrTxU2Z;ssc_core_FeUzPe0YQn4rca7KjD_v4G->mDestroy=
ssc_core_VhM6LeTCpVKS_9UnRhu_KK;ssc_core_FeUzPe0YQn4rca7KjD_v4G->mData=
mc__d1alWYexptL_X5HTFhbNK;return ssc_core_FeUzPe0YQn4rca7KjD_v4G;}
