#include "multibody_model_macros.h"
#include "pm_std.h"
#include "pm_std.h"
#include "mc_std_fwd.h"
typedef enum{mc_FfS9gFGHqKt_fDwFfcldkw= -1,mc_FFaaXY_gkbSTcyLBvtfrzS,
mc_VUd8H_Dz0yp8cmQqTd7DxF,mc_kmVKy2ciwP4fcTEzXFmnvU,mc_VW_0L0rb93GgXq8_OmdwHv,
mc_kHoWGgwi3OdzaXvPvG1YY7,mc___D_4trEmdK8jyKCH6E_ac,mc_Fei8BCRUgBdwhDvvD5FrSo}
mc_kQtOKCqS08dIbumyDnHNDL;typedef struct mc_VJ95jMweiZWSVLsSPpLjbI
mc__w8slDeOjOCYX5XtAOAaVQ;struct McRealFunctionTag{mc__w8slDeOjOCYX5XtAOAaVQ*
mc_ko6_hiERTRldgDROOJBQCH;mc_kQtOKCqS08dIbumyDnHNDL(*mc_VAvAkWmhpT_WWme_3E1U91
)(void const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*
mc_VgqbsB_3R4GTjLQeEYi1Qc,mc__w8slDeOjOCYX5XtAOAaVQ*mc__d1alWYexptL_X5HTFhbNK)
;void const*(*mc_FXz9GdGvpOKnh5e2dYstBe)(McRealFunction const*
mc_k0CXwzVaibdnZiGUCx6PMZ);void(*mDestroy)(McRealFunction*
mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct mc_VqsYk672m3G9YuweR9VjuM
mc_Vfjzfv7SnSWthXl7BAncu7;struct McIntFunctionTag{mc_Vfjzfv7SnSWthXl7BAncu7*
mc_ko6_hiERTRldgDROOJBQCH;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_Vfjzfv7SnSWthXl7BAncu7*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McIntFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);void
(*mDestroy)(McIntFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};typedef struct
mc_kIf5GUUnTAOChauG3_6hhe mc_k3jb_ssG91tZa9bwLjlWEj;struct McMatrixFunctionTag
{mc_k3jb_ssG91tZa9bwLjlWEj*mc_ko6_hiERTRldgDROOJBQCH;PmSparsityPattern const*
mc_kjWUPQN_Ui4d_enzFJIsF_;void(*mc_VAvAkWmhpT_WWme_3E1U91)(void const*
mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector const*mc_VgqbsB_3R4GTjLQeEYi1Qc,
mc_k3jb_ssG91tZa9bwLjlWEj*mc__d1alWYexptL_X5HTFhbNK);void const*(*
mc_FXz9GdGvpOKnh5e2dYstBe)(McMatrixFunction const*mc_k0CXwzVaibdnZiGUCx6PMZ);
void(*mDestroy)(McMatrixFunction*mc_k0CXwzVaibdnZiGUCx6PMZ);};
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
typedef struct mc_kv3fXx6PfXt7cekeoT00mk mc_kgKqfPHHGatO_9OUxR4PRK;struct
mc_kv3fXx6PfXt7cekeoT00mk{void*mPrivateData;void(*mc_FapEct1OXaSugDZ6N_u_kA)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH);void(*mc_FVdv01I3SEC4hD41rxmnRM)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,real_T mc__d1alWYexptL_X5HTFhbNK);void(*
mc_kPHJTxMUjl8Oi1EQSHes2Q)(mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId mc_k_4pzDDn_u0SjLvR9SBrIH,PmRealVector
const*mc__d1alWYexptL_X5HTFhbNK);void(*mc__WEKdqi2uo0m_Dm8w8T_ZO)(
mc_kgKqfPHHGatO_9OUxR4PRK*,PmfMessageId mc_FgZTwZqzhmd8haAibGoheR,PmfMessageId
mc_k_4pzDDn_u0SjLvR9SBrIH,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmRealVector const*mc__d1alWYexptL_X5HTFhbNK);};typedef struct
mc__nZqLQp3m1lFaHyLAzyG2a mc__39VLhR7TBCGYH016BQq8W;typedef struct
mc__UzXDLpnAvdw_eUt0mYuul mc_FJ2e3LJXmLlbhebizOW1SJ;typedef struct
mc__sr5lnPbYjO_Wyo_mmPUmd mc_Fw_IO5LchthA_LoeiSceRf;struct
mc__sr5lnPbYjO_Wyo_mmPUmd{mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;
void(*mc__6Do0w_54Hh7hDw5A7kAcK)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmfMessageId mc_FgZTwZqzhmd8haAibGoheR);};struct mc__nZqLQp3m1lFaHyLAzyG2a{
mc_FJ2e3LJXmLlbhebizOW1SJ*mPrivateData;PmSparsityPattern const*mPattern;
mc_Fw_IO5LchthA_LoeiSceRf mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__39VLhR7TBCGYH016BQq8W const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*
mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*
mc_VLMY1ozRY0Kkj5P0kyXMgl)(mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__39VLhR7TBCGYH016BQq8W*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_VoVW1IGPg_WaWmrtPlXVfD mc_kxnFIpkyuc0YdXbZO41ABc;typedef struct
mc_FpSYgeBscUCg_qWX4io4Kb mc_FSKepYWjsK8mbHLmdHWO58;typedef struct
mc_F7TCRYOl9IpujDKe3vErcI mc_F3czdn9EwuxfaaYWgN0vfZ;struct
mc_F7TCRYOl9IpujDKe3vErcI{int32_T mc_ksngc9l6D5KFVXNgzwkok8[5];};
PMF_DEPLOY_STATIC mc_F3czdn9EwuxfaaYWgN0vfZ mc_FL6WWuhINbWMW5KJKs2y9t(void){
int32_T i=0;mc_F3czdn9EwuxfaaYWgN0vfZ result;for(i=0;i<5;i++){result.
mc_ksngc9l6D5KFVXNgzwkok8[i]= -1;}return result;}struct
mc_VoVW1IGPg_WaWmrtPlXVfD{mc_FSKepYWjsK8mbHLmdHWO58*mPrivateData;
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
mc_kxnFIpkyuc0YdXbZO41ABc const*mc_kHt1ybY5z_OofadxN4AZsO);
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,PmRealVector*mc_VFDNUF6_N_t4Wu5qkxdJqD);void(*
mc_FF_Aq2b8Cx_iduzooh_sWO)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO,real_T mc_kTckK8teUpOlhm8Ippu8XP);void(*
mc_F_be_I5uNaSddegs3UZPvG)(mc_kxnFIpkyuc0YdXbZO41ABc const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mDestroy)(mc_kxnFIpkyuc0YdXbZO41ABc*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc_kD0xfpE0MgxkYDG6tnWbJN
mc_kKrwrwNLgB_NYDY0UUZRVA;typedef struct mc_k577Fzud3mpCe91P_z0Qf_
mc_FuB6ZnvWHlGVe5AYB_qh1v;struct mc_kD0xfpE0MgxkYDG6tnWbJN{
mc_FuB6ZnvWHlGVe5AYB_qh1v*mPrivateData;mc_kxnFIpkyuc0YdXbZO41ABc*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_kKrwrwNLgB_NYDY0UUZRVA const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__39VLhR7TBCGYH016BQq8W const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_kKrwrwNLgB_NYDY0UUZRVA*
mc__ZzBQ9ei49KTge3YSfX3g7);};typedef struct mc_FjeK_ZSfy_COYuwPPWwrm_
mc__3nzW_mY1qOqgXk2FmdyDG;typedef struct mc__WUe8IvZOGldjumXd_GpEC
mc_kTnNPenyhxlla9Uw7ULRfJ;typedef struct mc_FOtb37LSX8d5_5lHkmfBZj
mc_FfUgsrrKyC4CjixXpmLryh;struct mc_FOtb37LSX8d5_5lHkmfBZj{
mc_kgKqfPHHGatO_9OUxR4PRK*mc_kge3zWSlSoSRhTYHfGl24K;void(*
mc__6Do0w_54Hh7hDw5A7kAcK)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmfMessageId
mc_FgZTwZqzhmd8haAibGoheR);};struct mc_FjeK_ZSfy_COYuwPPWwrm_{
mc_kTnNPenyhxlla9Uw7ULRfJ*mPrivateData;PmSparsityPattern const*mPattern;size_t
mNumModes;mc_FfUgsrrKyC4CjixXpmLryh mc_VZj1rpSBB0tKh5vOG9vb5j;void(*
mc_VF0z4xtGYCxzcHJNRB8l2n)(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_kchvhvYJSIl4dyKnk7tfEC)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VLMY1ozRY0Kkj5P0kyXMgl)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mc_VT_CRoRmbpWajqcrcvcctF)(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc__XfQXtB6cfd9fyc_v3eEup,
PmIntVector*mc_V2mBNcV1EqCifyH9UdCbkF);void(*mDestroy)(
mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O);};typedef struct
mc_kWpl_dOgP5SEdi8_h6_Q0f mc_FeVMxCfnPEW_Ya5WdW0ZiP;typedef struct
mc_VzTwbfayokK_ZT6nhi1fuh mc_kbq0rwTu6XGSZqa8cMRgbH;struct
mc_kWpl_dOgP5SEdi8_h6_Q0f{mc_kbq0rwTu6XGSZqa8cMRgbH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*,
PmIntVector*,PmRealVector*);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(mc_FeVMxCfnPEW_Ya5WdW0ZiP const*
mc_kHt1ybY5z_OofadxN4AZsO);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*mc_kHt1ybY5z_OofadxN4AZsO,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
mc_FeVMxCfnPEW_Ya5WdW0ZiP const*);void(*mDestroy)(mc_FeVMxCfnPEW_Ya5WdW0ZiP*
mc_kHt1ybY5z_OofadxN4AZsO);};typedef struct mc__6rvEkBoZV0Khyk1wEL30q
mc_VLJsdw7KrQK_jqGzFmjnuT;typedef struct mc_VsuhjkXAxQOnYHPheaQV6t
mc_kAOZIOHKDP8Zh9U9Ca0DKK;struct mc__6rvEkBoZV0Khyk1wEL30q{
mc_kAOZIOHKDP8Zh9U9Ca0DKK*mPrivateData;mc_FeVMxCfnPEW_Ya5WdW0ZiP*(*
mc_k_hVWBJWCUlCdPNZka5iZF)(mc_VLJsdw7KrQK_jqGzFmjnuT const*
mc__ZzBQ9ei49KTge3YSfX3g7,mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O);void(*mDestroy)(mc_VLJsdw7KrQK_jqGzFmjnuT*
mc__ZzBQ9ei49KTge3YSfX3g7);};
#include "ne_std.h"
typedef struct ssc_core_Fd3FGkpCS2lhYThVpSV0kq ssc_core_VRw4xIuayc87h10CIYab_d
;typedef struct ssc_core_k1oWXtPHE_xydLoGE_SLjv ssc_core__cqeoq_N8axBWHaE78_gdI
;struct ssc_core_k1oWXtPHE_xydLoGE_SLjv{mc__3nzW_mY1qOqgXk2FmdyDG const*
ssc_core_VM7BxQGhXaKueLTlYnjv9x;PmBoolVector const*
ssc_core_VMZE4Bri2eO_f1fez5gp7L;PmRealVector const*
ssc_core__KFnMWfvZ7_FjylWw_6f82;PmRealVector const*
ssc_core__YBHEbaNs784duVk_OMx7f;ssc_core_VRw4xIuayc87h10CIYab_d*mPrivateData;
void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_core__cqeoq_N8axBWHaE78_gdI const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_klXC4aNpb9GwZu6_HluAlj)(ssc_core__cqeoq_N8axBWHaE78_gdI const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector const*ssc_core_FBNduJ2xtv0UjTuX5_iN4m,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF);NeSystemInputSizes(*mSizes)(
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_kpyeXH2RWcWG_DVSgKEG_O);
mc_F3czdn9EwuxfaaYWgN0vfZ(*ssc_core_kOw3W_1IrxSe_5HOqgvUlK)(
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_kpyeXH2RWcWG_DVSgKEG_O,
mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core_Fy4dLy8_QEOmhuIT5Fg3wh);void(*mDestroy)(
ssc_core__cqeoq_N8axBWHaE78_gdI*);};typedef struct
ssc_core__PWwrOfdEpWRXDbczq38F0 ssc_core__uDVmtdsiy0D_yCTEmgRcK;typedef struct
ssc_core_FYaVeWjobnOncaAFHOiTZt ssc_core__XvzTXJcADdQhPSJjzuq_2;struct
ssc_core_FYaVeWjobnOncaAFHOiTZt{ssc_core__uDVmtdsiy0D_yCTEmgRcK*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(ssc_core__XvzTXJcADdQhPSJjzuq_2 const*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);mc_F3czdn9EwuxfaaYWgN0vfZ(*
mc__vHH72jqKt44cXWzB3_tSu)(ssc_core__XvzTXJcADdQhPSJjzuq_2 const*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*mc_FF_Aq2b8Cx_iduzooh_sWO)(
ssc_core__XvzTXJcADdQhPSJjzuq_2 const*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,real_T
mc_kTckK8teUpOlhm8Ippu8XP);void(*mc_F_be_I5uNaSddegs3UZPvG)(
ssc_core__XvzTXJcADdQhPSJjzuq_2 const*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*
mDestroy)(ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);};
typedef struct ssc_core_FQeUGzSRtZW3VmJLsPkZPe ssc_core___8MOTpW4Mt4ZuJu_r_Tk1
;typedef struct ssc_core__XhEb4z8xhC5gXWbs9csW8 ssc_core_k_Ysw6uqdUGog9On_HQD_u
;struct ssc_core_FQeUGzSRtZW3VmJLsPkZPe{McRealFunction*
ssc_core_V1x7x1550CdbgX8IJywwBm;McMatrixFunction*
ssc_core_Vf_2n0BmZF4scLx_lNA5cM;McMatrixFunction*
ssc_core_FfhFZwHC6MdSZHtqJw7pvo;McRealFunction*ssc_core_VHpOBeHDk6S_fiGSsgZ9AB
;McRealFunction*ssc_core_FFg3rVqFQwGs_Dq1VKNSr6;McIntFunction*
ssc_core_FMBnYHxZ9hp0c13OmXTc2l;mc_VLJsdw7KrQK_jqGzFmjnuT*
ssc_core_k4UYUhUR_X4c_P73M2z6S7;mc_VLJsdw7KrQK_jqGzFmjnuT*
ssc_core_kzOmBWsipN4_b55POG8Wy9;real_T ssc_core_VDBat5RHzMl_iiYwj3kHLQ;};
typedef struct ssc_core_V84iS56AgNh7Wehiscd6YE ssc_core_FWQfR7g70C0iWux7B23nbt
;typedef struct ssc_core_kpi8nelMKZKLgHmdSmftzS ssc_core_kzGBRIvnNK4UgeqEz6lyK2
;struct ssc_core_V84iS56AgNh7Wehiscd6YE{ssc_core_kzGBRIvnNK4UgeqEz6lyK2*
mPrivateData;ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__A0n8EhE_GdLWudFqHsqyZ;
boolean_T ssc_core__6TOr6vPt0dOYqv1RQSns0;mc_kQtOKCqS08dIbumyDnHNDL(*
ssc_core_kvFcrvIoo2CkeaMuIgpw_Z)(ssc_core_FWQfR7g70C0iWux7B23nbt const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);size_t(*ssc_core_FAuiVHFGN6pHZmO_Jw_onC)(
ssc_core_FWQfR7g70C0iWux7B23nbt const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*
mc_VrNsQKHIiLOFaL3PHRFxZL)(ssc_core_FWQfR7g70C0iWux7B23nbt const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*ssc_core_FiEBtV4zgoSIdeQkFLGjXQ)(
ssc_core_FWQfR7g70C0iWux7B23nbt const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
PmRealVector const*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_V3833bWs6PdWiLrp9jD_59)(ssc_core_FWQfR7g70C0iWux7B23nbt const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector const*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*mDestroy)(
ssc_core_FWQfR7g70C0iWux7B23nbt*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);};
#include "ne_std.h"
typedef struct ssc_core__zmT88QePiWuXHXKKqyanU ssc_core_Fb0DCTdd1x_LhajF7VR_DH
;typedef struct ssc_core__FLG1GapEV4XjTTjYZrIMg ssc_core__qiNSbrJ_9KWZXVgsD4AQ2
;struct ssc_core__FLG1GapEV4XjTTjYZrIMg{mc__3nzW_mY1qOqgXk2FmdyDG const*
ssc_core_VM7BxQGhXaKueLTlYnjv9x;ssc_core_Fb0DCTdd1x_LhajF7VR_DH*mPrivateData;
void(*mc_k0h0NPxQNyl2XD95RLG6Hy)(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector const*ssc_core_F0YQPnss_4tuYLGl4cC7yQ,PmRealVector*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*ssc_core_klXC4aNpb9GwZu6_HluAlj)(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput
const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,PmRealVector const*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m,PmRealVector*mc_V2mBNcV1EqCifyH9UdCbkF);
NeSystemInputSizes(*mSizes)(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*
mc_kpyeXH2RWcWG_DVSgKEG_O);mc_F3czdn9EwuxfaaYWgN0vfZ(*
ssc_core_kOw3W_1IrxSe_5HOqgvUlK)(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*
mc_kpyeXH2RWcWG_DVSgKEG_O,mc_F3czdn9EwuxfaaYWgN0vfZ
ssc_core_Fy4dLy8_QEOmhuIT5Fg3wh);void(*mDestroy)(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*);};typedef struct
ssc_core_VRP9x_DQ5n_2heSg80Q9J1 ssc_core_FmNvK1aadXO_Z1C10bLQHH;typedef struct
ssc_core_kSoCk_Oby4Ko_HH6fFzRs0 ssc_core_F2RPS5w2BqGIWuDcIqAr_L;struct
ssc_core_kSoCk_Oby4Ko_HH6fFzRs0{ssc_core_FmNvK1aadXO_Z1C10bLQHH*mPrivateData;
mc_kQtOKCqS08dIbumyDnHNDL(*mSolve)(ssc_core_F2RPS5w2BqGIWuDcIqAr_L const*
ssc_core_Fi_9SaM2iHSHiy7LMBOqpC,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz,PmRealVector const*
ssc_core_F0YQPnss_4tuYLGl4cC7yQ,boolean_T ssc_core_kNbAvqTTfOp8cuUKUpAAhB);
mc_F3czdn9EwuxfaaYWgN0vfZ(*mc__vHH72jqKt44cXWzB3_tSu)(
ssc_core_F2RPS5w2BqGIWuDcIqAr_L const*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);void(*
mDestroy)(ssc_core_F2RPS5w2BqGIWuDcIqAr_L*ssc_core_Fi_9SaM2iHSHiy7LMBOqpC);};
typedef struct ssc_core_kLoKdQ5iTwKDeulP7b4qgr ssc_core_kv1v8GUnv4G8h1yPy_rg74
;typedef struct ssc_core_VdxzFJ37U1Ghhi4CxHw5mD ssc_core_kEVpCpWuAbCLbyV6Z5Ezlj
;struct ssc_core_kLoKdQ5iTwKDeulP7b4qgr{ssc_core_kEVpCpWuAbCLbyV6Z5Ezlj*
mPrivateData;ssc_core_F2RPS5w2BqGIWuDcIqAr_L*ssc_core__A0n8EhE_GdLWudFqHsqyZ;
boolean_T ssc_core__6TOr6vPt0dOYqv1RQSns0;mc_kQtOKCqS08dIbumyDnHNDL(*
ssc_core_kvFcrvIoo2CkeaMuIgpw_Z)(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz);size_t(*ssc_core_FAuiVHFGN6pHZmO_Jw_onC)(
ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);void(*
ssc_core_FiEBtV4zgoSIdeQkFLGjXQ)(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector const*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*ssc_core_V3833bWs6PdWiLrp9jD_59)(
ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,
PmRealVector const*ssc_core_FBNduJ2xtv0UjTuX5_iN4m);void(*
ssc_core_V9XjSx3zX_KuYDW2vSiRKE)(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,real_T ssc_core__lU1mWENxFpCeio7tYki0i);void(*
mDestroy)(ssc_core_kv1v8GUnv4G8h1yPy_rg74*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);};
ssc_core_kv1v8GUnv4G8h1yPy_rg74*ssc_core__5NFPJDr3stmbTrVbZ26HF(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z);
#include "pm_std.h"
#include "pm_std.h"
#include "pm_std.h"
void pm_rv_equals_rv(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_VeeoZXnlJQ4u_112lGs8YD(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
void pm_kpDvbw1GUlp4c5YdnW7V_w(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void pm_V2SLaBJy5WtXim9Lma9hfD(
PmCharVector const*pm__hARyx1bZBxVj1boVQqdtV,PmCharVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);boolean_T pm_FltUsml2sTlHZuCkbw_pdM(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_V8yYQkcd0vp_YaLM_nd75E(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm__P4MWKrtjzGPcercL4W7Fn(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);int_T
pm_create_real_vector_fields(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*pm_create_real_vector(
size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmRealVector*
pm_V_q_QnwoVVl6fHS_0pLvYo(PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_VeffaD_A8DxagH31Usec1H(
PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
void pm_destroy_real_vector(PmRealVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator
*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_int_vector_fields(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
PmIntVector*pm_create_int_vector(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmIntVector*pm__fSS_VMqhWlobeqe6mQF_x(PmIntVector
const*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_V_eFnKjg5I4Uc1DwG4yU27(PmIntVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_destroy_int_vector(PmIntVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T
pm_create_bool_vector_fields(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size
,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*pm__jbisDMumXdocXANx5LhhY
(size_t numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kia_QXK77_xDg9M1NzHr3r(PmBoolVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_VuaGyqV_9K0Ia9Qgn65rsj(PmBoolVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmBoolVector*
pm_kpRdzyG9L_8MV5lRovACCg(PmBoolVector const*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);int_T pm_create_char_vector_fields(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,size_t size,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);PmCharVector*pm_VUwRqkQ4oj4FjX20jJYKVB(size_t
numElements,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_destroy_char_vector_fields(PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,
PmAllocator*pm__8zlSpb2Hixod149p2zadR);void pm_Vb1pkQZ6CdGmbmIAJ3mnfZ(
PmCharVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);
int_T pm_create_size_vector_fields(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,
size_t size,PmAllocator*pm__8zlSpb2Hixod149p2zadR);PmSizeVector*
pm_FZch3YyGWrOM_PQNdo7b2c(size_t numElements,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FlA06lYLRAWkWmGBVmxE1a(PmSizeVector*
pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*pm__8zlSpb2Hixod149p2zadR);void
pm_kWBi8ZqmeopPhmEU9I2aNH(PmSizeVector*pm_FiALy5LWvv87e9O_pJGWPC,PmAllocator*
pm__8zlSpb2Hixod149p2zadR);void pm_FJsPJplguVOI_1EYyUUvfK(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
boolean_T pm_kJR6lA3GKXdrdqFEbgLIwb(PmSizeVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmSizeVector const*pm__YmIqNX3g5Sub1vKK1hZQF);
#include "pm_std.h"
#include "pm_std.h"
size_t mc_VgM3Lx3pYgtLW13T1_txvP(PmBoolVector const*v);void
mc_F4xMxEJX_DlUYXuaiDuSWS(PmIntVector const*mc_kyVj_uOQd__gg9_ljlZ_IY,
PmRealVector const*x,PmRealVector const*mc_FfDTppU8N_tOWuLK37x_08);void
mc_kQso3OAQDyxZaX0RF40IyE(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmIntVector const*
mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_FCOSZaHMkXC6hyEys7zO54(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmIntVector const*mc_F2Ry_cv60wK5bmHWC_sU4g);void mc_V5jydIk5QzCRZTOycShqTL(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FvLmE29WKCKJfaZMHwg3g9(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,int32_T const
mc_kh0AzKGHcX8tfeDoNul_TU,int32_T const mc__Oliq0seKPWShTNRpvAarb);void
mc__pmVtsSuXZls_1NfvVprZ7(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmBoolVector const*
mc_kd_kJxzsgTx9W19pl4H_AH);void mc_FR5FdJeEvDGGcyEVkxeE_x(PmIntVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
boolean_T mc_FL_3a__K44dYi9fe74WHqt);void mc_FK6EqkTbVFGMZ5QwXcurHx(
PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,PmIntVector const*
mc_k8AO2tT20x0_cyxVp0ak3P);void mc_FioOBDJiFMpkWaAcUdBb1E(PmIntVector const*
mc_F6RwpxHXSXp7gDlfFRloPz,int32_T value);void mc_kB1aHs1BVHG5YHNpmLLvkW(
PmBoolVector const*mc_FrF2gTbWxox8geiSROFaFn,PmBoolVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd);void
mc_V2P87Xoe0TGNeXNcn27vUJ(PmBoolVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmBoolVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_VqP4HesDIf47bDn5teE2H2(PmRealVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmRealVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_Vv4EJYeJDW0yZXiH42yCA_(PmIntVector const*mc_VRbT1WwZjwW6f5YGBCFuaD,size_t
mc_FnrjFNs9eQp9V5vCxPaoKw,PmIntVector const*mc__d7LC10lP38OY1VXN_tFqb,size_t
mc_FRuIUemzxbdhfqkjXhoyK7,size_t mc__lO81KuDBk41W9Wd2wAkb0);void
mc_k0zonBZJC2K6baT1NXX1Qo(PmRealVector*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector
const*pm__YmIqNX3g5Sub1vKK1hZQF);size_t mc_FLTxr_Wc1PKSeTxwfrcl5B(PmBoolVector
const*mc__MqKyOds56_XeH9Iv3CTIL);void mc_FX5UXdAa2flS_1wrwznTLh(PmIntVector
const*mc__vpsWwfj3fx1YDJlP_lHTd,PmBoolVector const*mc_VwOeyeOYCKdcVTySJQVoLE);
size_t mc__RsEbvPhcXp6iqwYpH_OQY(PmIntVector const*mc_F6sy5cXK8JOKeiFBw6znSV);
size_t mc__fQVSVSgEBG6fuximVFlkw(PmRealVector const*mc_FawmFe5oOEC_cmkvZc1Kaa)
;size_t mc_FyLahU0kjICfba8O7mWi8Z(PmBoolVector const*mc_FawmFe5oOEC_cmkvZc1Kaa
);boolean_T mc___gjB_jZtTxReaWZSEiFdh(PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);boolean_T mc_kNrn2e3NmaGNbmzmXpvCR0(PmIntVector
const*pm__hARyx1bZBxVj1boVQqdtV,int32_T value);boolean_T
mc_kk65_VI6zC0mWHqRziXpjX(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
value);void mc_FGkd8Riw6p4eaDCAbwBVPv(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FzkrLuS4xMOvaTv5dUw3j7(PmRealVector const*x,real_T v);void
mc_ks_PW4I7dwWbhXAWhHTUCI(PmRealVector const*x,PmRealVector const*y);void
mc__w_RD4J1MZlqcL7as8FLdk(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V3CZVT50_V_xeia9SYYptc(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T a,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VIFqLU9Z6UtwXDWPnvd_zg(PmRealVector const*x
,PmRealVector const*y,PmRealVector const*z);void mc_VWnvos7Q548uVH7p0208jN(
PmRealVector const*x,real_T const a,PmRealVector const*y);void
mc_V7hiVZfxKK0Uj9rPai4LYw(PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,real_T
const mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VM9M6KxYTfKL_q4yuXmOnI(PmRealVector
const*pm__hARyx1bZBxVj1boVQqdtV,real_T const mc_kcda_aHAM4WIXuM_xBDdLt);void
mc_k4v_yYmXHgO1cqVdr5a500(PmIntVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmIntVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_V2CDnBdRcOpuh1IyvRJzfi(
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);void mc_FNVEyWT4js4ebmsePvfFh2(PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc__dsFCQJjA6p_j1tGhi2wWe(PmRealVector const*vector,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_kUD9LJQRjT0FayfqpQrhnP(PmBoolVector const*
vector);void mc__NFj_YrtCgd3dDixI_yrA7(PmRealVector const*vector);void
mc__aNO1s5qwzt6fXwft5YgCz(PmRealVector const*vector);void
mc_FzUHnQbqf_dRhX_X5DoWjW(PmRealVector const*vector,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc_VTlukZ0iimdzge7aTGg7rl(PmIntVector const*
vector,int32_T value);void mc_VDWYuA0FfQClgukbQcp3js(PmIntVector const*vector)
;void mc_k9wkPuvMCi4DY1yebDQPHf(PmIntVector const*vector);void
mc__Nb_EyyxYi4ddPcS0H7Bot(PmBoolVector const*mc_kd_kJxzsgTx9W19pl4H_AH,
PmIntVector const*mc__vpsWwfj3fx1YDJlP_lHTd,boolean_T mc_kcda_aHAM4WIXuM_xBDdLt
);void mc_k1sxUtEClkOZVuHMQ91JqD(PmBoolVector const*vector,boolean_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc_VWloU5QD6gpaXeK8lmytFA(PmBoolVector const*
vector);void mc_VQ1YWbKmkVC6YajZAyvmNH(PmBoolVector const*x,size_t i,size_t
mc__lO81KuDBk41W9Wd2wAkb0);void mc__uq8ZXcr_B_zgDxjibJDSi(PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void
mc_FnkaeEp6tpWlhHVVTP_g3C(PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF);void mc_VWl0s5xjzvW5iL0mXtG_a7(
PmBoolVector const*pm__hARyx1bZBxVj1boVQqdtV,PmBoolVector const*
pm__YmIqNX3g5Sub1vKK1hZQF);real_T mc_F1fvRD4xlFhBdyqJtcgdmn(PmRealVector const
*pm__hARyx1bZBxVj1boVQqdtV);real_T mc_VbeuUcgPWRWgjymCWWPezl(PmRealVector const
*const pm__hARyx1bZBxVj1boVQqdtV);real_T mc_kMPF5fccZd_3jHFMhUSro6(
PmRealVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_kvxcenZbLm4dfenXL8jQAx
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);int32_T mc_Vgo5SAIS_80_VXwmU7JogX
(PmIntVector const*pm_FiALy5LWvv87e9O_pJGWPC);size_t mc_kmglRxesQ3pibiDXK66DHA
(PmSizeVector const*pm_FiALy5LWvv87e9O_pJGWPC);void mc__25pQTf4VutiXiGTGQmvSU(
PmIntVector*mc__nP_wNlJUxWHWLytmZ4pL0,PmIntVector const*
mc_F6sy5cXK8JOKeiFBw6znSV);void mc__LECH_YE38C6YH4eYxxbSd(PmRealVector*
mc_VWoEnwEgWFpobmwHA1Qln5,PmRealVector const*mc_V_rxJBbuhqtwViRHFKhdGC,
PmSparsityPattern const*mc__Df1hQFzAY4fiLCvP0PV12);void
mc_VMRKMuNLnDxXjaBiy1RcMD(PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc__04jybcJBjxwWX7Razqutu(PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void mc_VjtwQ41FT3hkaixcsQFmQH(
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*mc_VDugqW09uVW_VLuociwzvN);void
mc_kM_Y9u9U2F_Cf9sWAtmMMu(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void
mc__Xq_g76c6Y_K_PpYNKcquN(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,real_T const*x);void mc_kXj99iXjC1CoZLWwPRH879(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*mc_FybTf2SinthyWqOxvPdJ5h,size_t mc_VVRAoFgW2Hphcy7H6H9Oh0)
;void mc__75oXIAh8pt6cyvuqOckyG(PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmRealVector const*mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*
mc_VknkCg_msB8Ga9ymQtGggf,PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV,
PmRealVector const*mc_VxvrZHk3QVKlWycYYdZEat);void mc_kLGj2IdnGDG_YeEKAnMkUr(
PmRealVector const*pm__YmIqNX3g5Sub1vKK1hZQF,PmRealVector const*
mc_FCZxG6Iux_GKX1lkqasXdQ,PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,
PmRealVector const*pm__hARyx1bZBxVj1boVQqdtV);void mc_FJN_drUOKh_igHJXVH7xls(
PmRealVector const*y,PmRealVector const*mc_V8ujEMKrDU8Q_mvu4yja1b,
PmSparsityPattern const*mc_V_ku0ZO8TOxhc9438tlsBI,size_t j,real_T
mc_kcda_aHAM4WIXuM_xBDdLt);void mc__WqQP6u7DtdYVDzUK5y971(PmRealVector const*z
,PmRealVector const*x,PmRealVector const*y);void mc_kc89O49Oe18lWqn1Nr_t61(
PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE,PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo);void
mc_F4wnJSMmz0WHaHs2tnfI5y(PmRealVector const*mc_FrF2gTbWxox8geiSROFaFn,
PmIntVector const*mc__sdtG1OgJQtqcikFA20Doo,PmRealVector const*
mc_VwOeyeOYCKdcVTySJQVoLE);void mc_kAamy8ZxNZSIa9FrfB2mHE(PmRealVector const*
mc_FrF2gTbWxox8geiSROFaFn,PmSizeVector const*mc__sdtG1OgJQtqcikFA20Doo,
PmRealVector const*mc_VwOeyeOYCKdcVTySJQVoLE);void mc_VjzTgsx19j0KfHv6VXr4Mp(
PmRealVector const*a,PmIntVector const*i,PmRealVector const*b);void
mc_V_Fp06wJOBhXZyLbA5xU0r(PmRealVector const*a,PmRealVector const*b,
PmBoolVector const*i);void mc_FuY0t5xEb5_QhDQFQ_TXtc(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kkPot0UJiN_EX94QlR_mCs(
PmRealVector const*a,PmBoolVector const*i,real_T x);void
mc_kMo1w3ReRZGIdH5_MNwumc(PmRealVector const*a,PmBoolVector const*i,
PmRealVector const*b);void mc_VYxtXnMKT6hpb1FMldBDLs(PmRealVector const*a,
PmBoolVector const*i,PmRealVector const*b);void mc_kl_UmQrKbdCajPyXz5nOIL(
PmRealVector const*a,PmBoolVector const*i,PmRealVector const*b);void
mc_k2E2oWXDqshMeuCQWrbaKT(PmIntVector const*a,PmBoolVector const*i,PmIntVector
const*b);void mc_FBaB5196Xx0ohX_IWM5ypL(PmIntVector const*a,PmBoolVector const
*i,int32_T x);void mc_F1CG0fHJYfd_ealLMx7Z7U(PmIntVector const*a,PmBoolVector
const*i,PmIntVector const*b);void mc_krXbD205SBpghif1h1n_ei(PmIntVector const*
a,PmBoolVector const*i,PmIntVector const*b);void mc__Qtfmi680EKpj1bOrIroGr(
PmIntVector const*a,PmBoolVector const*i,PmIntVector const*b);void
mc__0IkRn0eQ9Wc_u8mCNbQDh(PmIntVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pbFNjwg_bCPdPFSjC2Wdv(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_VpjBXBa8TTCl_uBXYMLfxC(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc__pFtu1g17h8ZaaZK4PpTkb(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_ko54nz3c1_p2ail0c9p5N6(PmBoolVector const*mc_VUELvXWGXPlKf1brR9MRC3,
PmSparsityPattern const*mc_FBOWjCOBM8SyhqFe64oqrx);void
mc_kMScbNM1RKOTaD4QwTME8Y(PmBoolVector const*result,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*mc_VlnhKi82gfCLgumIqeduOq);void
mc_Fbsqat6MlL0bjPHlNxax8t(PmBoolVector const*pm__YmIqNX3g5Sub1vKK1hZQF,
PmSparsityPattern const*mc_VknkCg_msB8Ga9ymQtGggf,PmBoolVector const*
pm__hARyx1bZBxVj1boVQqdtV);void mc_FSAdXYnRP9pkfmWBYlMkJJ(PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,
PmBoolVector const*mc_F8fT7naL9bOcimTADCVzTC);void mc__NertSre4cWh_mN2RJ5UPq(
PmRealVector const*mc_kVkvrfpzuVduaPTr5FLF8K,PmSparsityPattern const*
mc__srK5LmyWw42ZyPnbOWDWJ,PmBoolVector const*mc_VCVhWy_VaDhraHrlfFWxBa);
PmRealVector mc_VPFwoVShg1G3XTwou1_jbC(PmRealVector const*v,size_t
mc_Fyss_XM3F_C4dm6IKoDw4G,size_t mc_Vs6xonQX17Krc5vXv8T_zq);boolean_T
mc_VS9gg3UoKcpDjqrjuGmymC(PmRealVector const*v);McMatrixFunction*
mc_klSeJe62M_x2gP_uQ8_QU7(McMatrixFunction*mc_kEQ7ZkhePUp8eHqnX6lLap,
McMatrixFunction*mc_VRqcAPiI_zWzcaWghAD8Ra,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc__4fFDnwFhbSuaLZ4NJB06a(
PmSparsityPattern const*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector const*
mc_kVkvrfpzuVduaPTr5FLF8K,void const*mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_Vl4aaEoJK_KwYaROiytCdQ(
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,void const*mc_FK93a0pHvcdVXqZct6q8ja,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*mc_keWxvg6kivCmgu_AS8haey(
PmSparsityPattern*mc__srK5LmyWw42ZyPnbOWDWJ,PmRealVector*
mc_kVkvrfpzuVduaPTr5FLF8K,McMatrixFunction*pm__sjTRWOMR4WzZisVeB2fYm,
PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);McMatrixFunction*
mc__Q7vDy_uzNpkXPF4puasqh(real_T*mc_kHfMSiCBJRSoju34wwOKOx,McMatrixFunction*
mc_FB2sI4KQ92xCX9nxNAIsDi,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
#include "ne_std.h"
#include "ne_std.h"
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core_F7zBQipNH88gfa_9A256_e(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__WuYgVAkb6lGaLEOrHsdum(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);
ssc_core__XvzTXJcADdQhPSJjzuq_2*ssc_core__LKVUa50d7OBWPOR9PJtdt(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
ssc_core__cqeoq_N8axBWHaE78_gdI const*mc_VkOVRwyffyOPbanx3qI3TI,real_T
mc_FfDTppU8N_tOWuLK37x_08,PmAllocator*pm_FbYb_iLqY2hwZTVlVaiqJY);void
ssc_core_Fd_2KMK9UB0LjiYHA_7k_F(ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_core_F2RPS5w2BqGIWuDcIqAr_L*ssc_core_Vps22mc76e44dL0ve7dAWJ(
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core__RtkHrrPEelBbDRCt5cBnV,
mc_VLJsdw7KrQK_jqGzFmjnuT const*ssc_core_FMeq_zKh9_llZm4SgQ9nL_,
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*mc_VkOVRwyffyOPbanx3qI3TI,PmAllocator*
pm_FbYb_iLqY2hwZTVlVaiqJY);static size_t const ssc_core_kbHZQuN3TQGxiq3JDAOzsE
=2;struct mc__WUe8IvZOGldjumXd_GpEC{size_t ssc_core_ViKkQGhWq2pthH4EazW5gY;
PmRealVector*ssc_core__ERgtpAr_fdTcmO70I3iqR;PmRealVector*
ssc_core_F1NRFAaR2ECEYyVlHNvfFi;PmRealVector*ssc_core_FePbFl2MhWldXPV8N5Prx9;
PmRealVector*ssc_core_kFUxZvHCl8lDhDDcKfuJ0p;PmRealVector*
ssc_core_kjv0wzbvqOOfi9QP_4KB6b;real_T ssc_core_kLIDMtKkvD_aePzbV_jg_e;real_T
ssc_core__4IbiAlzDulVjL62bZP__w;NeSystemInput ssc_core__BOls5qMqQO9cXYuVPVeU_;
NeSystemInput*ssc_core_kO9IHyu5O9dR_aJUHrxS45;McMatrixFunction*
ssc_core__N0xoWD4itSU_XX5W0xLis;McMatrixFunction*
ssc_core_VFBBeIPBYK8oa1CItkaOtG;ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*
ssc_core_FIx3hYDxQxCugT28fDgmVT;PmAllocator*ssc_core_FyUeLiATLG4zWes0mMKZnu;};
static void ssc_core_VOpAb89jytKSYHv6tXM1s6(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc){mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_.mX= *mc_kDRphcAfRHSbf1ZLKEDW9k;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_.mM= *
mc_FHw707OTzcOEeaB2IM_AJQ;(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_V1x7x1550CdbgX8IJywwBm)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_VgqbsB_3R4GTjLQeEYi1Qc),((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_V1x7x1550CdbgX8IJywwBm)->mc_ko6_hiERTRldgDROOJBQCH));(*((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->mc_VAvAkWmhpT_WWme_3E1U91))((&(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_)),(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_kFUxZvHCl8lDhDDcKfuJ0p),((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->mc_ko6_hiERTRldgDROOJBQCH));
mc_VIFqLU9Z6UtwXDWPnvd_zg(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FePbFl2MhWldXPV8N5Prx9,mc_kDRphcAfRHSbf1ZLKEDW9k,
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__ERgtpAr_fdTcmO70I3iqR);if(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_ViKkQGhWq2pthH4EazW5gY==
ssc_core_kbHZQuN3TQGxiq3JDAOzsE){mc_V7hiVZfxKK0Uj9rPai4LYw(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FePbFl2MhWldXPV8N5Prx9,
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_kLIDMtKkvD_aePzbV_jg_e);
mc_FGkd8Riw6p4eaDCAbwBVPv(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FePbFl2MhWldXPV8N5Prx9,mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi);}else{mc_V7hiVZfxKK0Uj9rPai4LYw(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FePbFl2MhWldXPV8N5Prx9,
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__4IbiAlzDulVjL62bZP__w);}
mc_kM_Y9u9U2F_Cf9sWAtmMMu(mc_VgqbsB_3R4GTjLQeEYi1Qc,mc_kpyeXH2RWcWG_DVSgKEG_O
->mPrivateData->ssc_core_kFUxZvHCl8lDhDDcKfuJ0p,mc_kpyeXH2RWcWG_DVSgKEG_O->
mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_Vf_2n0BmZF4scLx_lNA5cM
->mc_kjWUPQN_Ui4d_enzFJIsF_,mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FePbFl2MhWldXPV8N5Prx9);}static void ssc_core_krkpWNgjThhyfLymkn4Rny(
mc__3nzW_mY1qOqgXk2FmdyDG const*mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*
mc_FHw707OTzcOEeaB2IM_AJQ,PmRealVector const*mc_kDRphcAfRHSbf1ZLKEDW9k,
PmRealVector*mc_VgqbsB_3R4GTjLQeEYi1Qc){mc_kpyeXH2RWcWG_DVSgKEG_O->
mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_.mX= *mc_kDRphcAfRHSbf1ZLKEDW9k;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_.mM= *
mc_FHw707OTzcOEeaB2IM_AJQ;(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_kFUxZvHCl8lDhDDcKfuJ0p),((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->
mc_ko6_hiERTRldgDROOJBQCH));(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_FfhFZwHC6MdSZHtqJw7pvo)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_kjv0wzbvqOOfi9QP_4KB6b),((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_FfhFZwHC6MdSZHtqJw7pvo)->
mc_ko6_hiERTRldgDROOJBQCH));if(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_ViKkQGhWq2pthH4EazW5gY==ssc_core_kbHZQuN3TQGxiq3JDAOzsE){(*((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__N0xoWD4itSU_XX5W0xLis)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_VgqbsB_3R4GTjLQeEYi1Qc),((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__N0xoWD4itSU_XX5W0xLis)->
mc_ko6_hiERTRldgDROOJBQCH));}else{(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData
->ssc_core_VFBBeIPBYK8oa1CItkaOtG)->mc_VAvAkWmhpT_WWme_3E1U91))((&(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_)),(
mc_VgqbsB_3R4GTjLQeEYi1Qc),((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_VFBBeIPBYK8oa1CItkaOtG)->mc_ko6_hiERTRldgDROOJBQCH));}}static void
ssc_core_F_7u7bwCWPCqc5cwlbM6ps(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmRealVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc){mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_.mX= *mc_kDRphcAfRHSbf1ZLKEDW9k;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_.mM= *
mc_FHw707OTzcOEeaB2IM_AJQ;(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_VHpOBeHDk6S_fiGSsgZ9AB)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_VgqbsB_3R4GTjLQeEYi1Qc),((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_VHpOBeHDk6S_fiGSsgZ9AB)->mc_ko6_hiERTRldgDROOJBQCH));}static void
ssc_core_VNCMDNC4fX0EgmyVRBEoun(mc__3nzW_mY1qOqgXk2FmdyDG const*
mc_kpyeXH2RWcWG_DVSgKEG_O,PmIntVector const*mc_FHw707OTzcOEeaB2IM_AJQ,
PmRealVector const*mc_kDRphcAfRHSbf1ZLKEDW9k,PmIntVector*
mc_VgqbsB_3R4GTjLQeEYi1Qc){mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_.mX= *mc_kDRphcAfRHSbf1ZLKEDW9k;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_.mM= *
mc_FHw707OTzcOEeaB2IM_AJQ;(*((mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_FMBnYHxZ9hp0c13OmXTc2l)->
mc_VAvAkWmhpT_WWme_3E1U91))((&(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_)),(mc_VgqbsB_3R4GTjLQeEYi1Qc),((
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_FMBnYHxZ9hp0c13OmXTc2l)->mc_ko6_hiERTRldgDROOJBQCH));}static void
ssc_core_kc9qhfWw5VdoiH2N7f_sLI(mc__3nzW_mY1qOqgXk2FmdyDG*
mc_kpyeXH2RWcWG_DVSgKEG_O){PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FyUeLiATLG4zWes0mMKZnu;
pm_destroy_real_vector(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__ERgtpAr_fdTcmO70I3iqR,mc_FOGg0ZWot2WdYenO8zaD4Z);
pm_destroy_real_vector(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi,mc_FOGg0ZWot2WdYenO8zaD4Z);
pm_destroy_real_vector(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FePbFl2MhWldXPV8N5Prx9,mc_FOGg0ZWot2WdYenO8zaD4Z);
pm_destroy_real_vector(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_kFUxZvHCl8lDhDDcKfuJ0p,mc_FOGg0ZWot2WdYenO8zaD4Z);
pm_destroy_real_vector(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_kjv0wzbvqOOfi9QP_4KB6b,mc_FOGg0ZWot2WdYenO8zaD4Z);
neu_destroy_system_input(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_kO9IHyu5O9dR_aJUHrxS45,mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_core_Fd_2KMK9UB0LjiYHA_7k_F(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_FIx3hYDxQxCugT28fDgmVT,mc_FOGg0ZWot2WdYenO8zaD4Z);(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core__N0xoWD4itSU_XX5W0xLis)->
mDestroy(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core__N0xoWD4itSU_XX5W0xLis);(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_VFBBeIPBYK8oa1CItkaOtG)->mDestroy(mc_kpyeXH2RWcWG_DVSgKEG_O->
mPrivateData->ssc_core_VFBBeIPBYK8oa1CItkaOtG);{void*const
ssc_core_Fwa600K08ShpeiIoy5zj90=(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData);
PmAllocator*const ssc_core__dbga3QFUO0UeP_FfvztPd=(mc_FOGg0ZWot2WdYenO8zaD4Z);
if(ssc_core_Fwa600K08ShpeiIoy5zj90){(ssc_core__dbga3QFUO0UeP_FfvztPd)->
mFreeFcn(ssc_core__dbga3QFUO0UeP_FfvztPd,ssc_core_Fwa600K08ShpeiIoy5zj90);}};{
void*const ssc_core_Fpkg3s41QJpHgm3s7Y7R8m=(mc_kpyeXH2RWcWG_DVSgKEG_O);
PmAllocator*const ssc_core_F_186SYU9HxHbeQCmOTbUF=(mc_FOGg0ZWot2WdYenO8zaD4Z);
if(ssc_core_Fpkg3s41QJpHgm3s7Y7R8m){(ssc_core_F_186SYU9HxHbeQCmOTbUF)->
mFreeFcn(ssc_core_F_186SYU9HxHbeQCmOTbUF,ssc_core_Fpkg3s41QJpHgm3s7Y7R8m);}};}
static mc__3nzW_mY1qOqgXk2FmdyDG*ssc_core_VA4rtEv5IaWa_XCPeCvEhf(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z){mc__3nzW_mY1qOqgXk2FmdyDG*mc_kpyeXH2RWcWG_DVSgKEG_O
=(mc__3nzW_mY1qOqgXk2FmdyDG*)(((mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((
mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(mc__3nzW_mY1qOqgXk2FmdyDG)),(1))));
mc_kTnNPenyhxlla9Uw7ULRfJ*mc__d1alWYexptL_X5HTFhbNK=(mc_kTnNPenyhxlla9Uw7ULRfJ
*)(((mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(
sizeof(mc_kTnNPenyhxlla9Uw7ULRfJ)),(1))));size_t
ssc_core_VWI2mfRhUISTWTZpjWuG2i=ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM->mc_kjWUPQN_Ui4d_enzFJIsF_->mNumCol;
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kO9IHyu5O9dR_aJUHrxS45=neu_copy_si((
NeSystemInput const*)((ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_V1x7x1550CdbgX8IJywwBm)->mc_FXz9GdGvpOKnh5e2dYstBe((
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_V1x7x1550CdbgX8IJywwBm))),
mc_FOGg0ZWot2WdYenO8zaD4Z);mc__d1alWYexptL_X5HTFhbNK->
ssc_core__BOls5qMqQO9cXYuVPVeU_= *(mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kO9IHyu5O9dR_aJUHrxS45);mc__d1alWYexptL_X5HTFhbNK->
ssc_core__ERgtpAr_fdTcmO70I3iqR=pm_create_real_vector(
ssc_core_VWI2mfRhUISTWTZpjWuG2i,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_F1NRFAaR2ECEYyVlHNvfFi=
pm_create_real_vector(ssc_core_VWI2mfRhUISTWTZpjWuG2i,
mc_FOGg0ZWot2WdYenO8zaD4Z);mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FePbFl2MhWldXPV8N5Prx9=pm_create_real_vector(
ssc_core_VWI2mfRhUISTWTZpjWuG2i,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kFUxZvHCl8lDhDDcKfuJ0p=
pm_create_real_vector(((size_t)(((ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM->mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_Vf_2n0BmZF4scLx_lNA5cM->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjv0wzbvqOOfi9QP_4KB6b=
pm_create_real_vector(((size_t)(((ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo->mc_kjWUPQN_Ui4d_enzFJIsF_)->mJc[(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_FfhFZwHC6MdSZHtqJw7pvo->
mc_kjWUPQN_Ui4d_enzFJIsF_)->mNumCol]))),mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kLIDMtKkvD_aePzbV_jg_e= -2.0/(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_VDBat5RHzMl_iiYwj3kHLQ);
mc__d1alWYexptL_X5HTFhbNK->ssc_core__4IbiAlzDulVjL62bZP__w= -1.0/(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_VDBat5RHzMl_iiYwj3kHLQ);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FIx3hYDxQxCugT28fDgmVT=
ssc_core_keuPMa27xjG1bPeaPl_Oys;mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FyUeLiATLG4zWes0mMKZnu=mc_FOGg0ZWot2WdYenO8zaD4Z;{McMatrixFunction*
ssc_core__EIaXP4H4ZKuZmaTyPyymE=mc__4fFDnwFhbSuaLZ4NJB06a(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_Vf_2n0BmZF4scLx_lNA5cM->
mc_kjWUPQN_Ui4d_enzFJIsF_,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kFUxZvHCl8lDhDDcKfuJ0p,(ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->mc_FXz9GdGvpOKnh5e2dYstBe((
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_Vf_2n0BmZF4scLx_lNA5cM)),
mc_FOGg0ZWot2WdYenO8zaD4Z);McMatrixFunction*ssc_core_kr54pdOF7m03iip5bybdRd=
mc__4fFDnwFhbSuaLZ4NJB06a(ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo->mc_kjWUPQN_Ui4d_enzFJIsF_,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjv0wzbvqOOfi9QP_4KB6b,(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_FfhFZwHC6MdSZHtqJw7pvo)->
mc_FXz9GdGvpOKnh5e2dYstBe((ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo)),mc_FOGg0ZWot2WdYenO8zaD4Z);McMatrixFunction*
ssc_core_VXBy92pEND_OcL9S0tBGeI=mc__Q7vDy_uzNpkXPF4puasqh(&(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kLIDMtKkvD_aePzbV_jg_e),
ssc_core__EIaXP4H4ZKuZmaTyPyymE,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core__N0xoWD4itSU_XX5W0xLis=
mc_klSeJe62M_x2gP_uQ8_QU7(ssc_core_kr54pdOF7m03iip5bybdRd,
ssc_core_VXBy92pEND_OcL9S0tBGeI,mc_FOGg0ZWot2WdYenO8zaD4Z);}{McMatrixFunction*
ssc_core__EIaXP4H4ZKuZmaTyPyymE=mc__4fFDnwFhbSuaLZ4NJB06a(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_Vf_2n0BmZF4scLx_lNA5cM->
mc_kjWUPQN_Ui4d_enzFJIsF_,mc__d1alWYexptL_X5HTFhbNK->
ssc_core_kFUxZvHCl8lDhDDcKfuJ0p,(ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_Vf_2n0BmZF4scLx_lNA5cM)->mc_FXz9GdGvpOKnh5e2dYstBe((
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_Vf_2n0BmZF4scLx_lNA5cM)),
mc_FOGg0ZWot2WdYenO8zaD4Z);McMatrixFunction*ssc_core_kr54pdOF7m03iip5bybdRd=
mc__4fFDnwFhbSuaLZ4NJB06a(ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo->mc_kjWUPQN_Ui4d_enzFJIsF_,
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kjv0wzbvqOOfi9QP_4KB6b,(
ssc_core_keuPMa27xjG1bPeaPl_Oys->ssc_core_FfhFZwHC6MdSZHtqJw7pvo)->
mc_FXz9GdGvpOKnh5e2dYstBe((ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_FfhFZwHC6MdSZHtqJw7pvo)),mc_FOGg0ZWot2WdYenO8zaD4Z);McMatrixFunction*
ssc_core_VXBy92pEND_OcL9S0tBGeI=mc__Q7vDy_uzNpkXPF4puasqh(&(
mc__d1alWYexptL_X5HTFhbNK->ssc_core__4IbiAlzDulVjL62bZP__w),
ssc_core__EIaXP4H4ZKuZmaTyPyymE,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_VFBBeIPBYK8oa1CItkaOtG=
mc_klSeJe62M_x2gP_uQ8_QU7(ssc_core_kr54pdOF7m03iip5bybdRd,
ssc_core_VXBy92pEND_OcL9S0tBGeI,mc_FOGg0ZWot2WdYenO8zaD4Z);}
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData=mc__d1alWYexptL_X5HTFhbNK;
mc_kpyeXH2RWcWG_DVSgKEG_O->mPattern=mc__d1alWYexptL_X5HTFhbNK->
ssc_core__N0xoWD4itSU_XX5W0xLis->mc_kjWUPQN_Ui4d_enzFJIsF_;{NeSystemInputSizes
ssc_core_VcAQyiMtDKWW_yg_qwdz91=neu_get_system_input_sizes(
mc__d1alWYexptL_X5HTFhbNK->ssc_core_kO9IHyu5O9dR_aJUHrxS45);
mc_kpyeXH2RWcWG_DVSgKEG_O->mNumModes=ssc_core_VcAQyiMtDKWW_yg_qwdz91 .mSizes[
NE_SYSTEM_INPUT_ID_M];mc_kpyeXH2RWcWG_DVSgKEG_O->mc_VF0z4xtGYCxzcHJNRB8l2n= &
ssc_core_VOpAb89jytKSYHv6tXM1s6;mc_kpyeXH2RWcWG_DVSgKEG_O->
mc_kchvhvYJSIl4dyKnk7tfEC= &ssc_core_krkpWNgjThhyfLymkn4Rny;
mc_kpyeXH2RWcWG_DVSgKEG_O->mc_VLMY1ozRY0Kkj5P0kyXMgl= &
ssc_core_F_7u7bwCWPCqc5cwlbM6ps;mc_kpyeXH2RWcWG_DVSgKEG_O->
mc_VT_CRoRmbpWajqcrcvcctF= &ssc_core_VNCMDNC4fX0EgmyVRBEoun;
mc_kpyeXH2RWcWG_DVSgKEG_O->mDestroy= &ssc_core_kc9qhfWw5VdoiH2N7f_sLI;(
mc_kpyeXH2RWcWG_DVSgKEG_O)->mc_VZj1rpSBB0tKh5vOG9vb5j.
mc__6Do0w_54Hh7hDw5A7kAcK=NULL;(mc_kpyeXH2RWcWG_DVSgKEG_O)->
mc_VZj1rpSBB0tKh5vOG9vb5j.mc_kge3zWSlSoSRhTYHfGl24K=NULL;;}return
mc_kpyeXH2RWcWG_DVSgKEG_O;}struct ssc_core__zmT88QePiWuXHXKKqyanU{
mc__3nzW_mY1qOqgXk2FmdyDG*ssc_core_VM7BxQGhXaKueLTlYnjv9x;PmAllocator*
ssc_core_FyUeLiATLG4zWes0mMKZnu;};static void ssc_core__MR9P86FHX_DZ1QqXRXig9(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput
const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,PmRealVector const*
ssc_core_F0YQPnss_4tuYLGl4cC7yQ,PmRealVector*ssc_core_FBNduJ2xtv0UjTuX5_iN4m){
(void)0;;mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->
mPrivateData->ssc_core__BOls5qMqQO9cXYuVPVeU_= *
ssc_core_kNbvLmFI_EtAay5OpgNJFz;pm_rv_equals_rv(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core__ERgtpAr_fdTcmO70I3iqR
,&(ssc_core_kNbvLmFI_EtAay5OpgNJFz->mX));pm_rv_equals_rv(
ssc_core_FBNduJ2xtv0UjTuX5_iN4m,ssc_core_F0YQPnss_4tuYLGl4cC7yQ);}static void
ssc_core_VZ4ohsw3Balv_TeZyyFe5Z(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*
mc_kpyeXH2RWcWG_DVSgKEG_O,NeSystemInput const*ssc_core_kNbvLmFI_EtAay5OpgNJFz,
PmRealVector const*ssc_core_FBNduJ2xtv0UjTuX5_iN4m,PmRealVector*
mc_V2mBNcV1EqCifyH9UdCbkF){(void)ssc_core_kNbvLmFI_EtAay5OpgNJFz;
pm_rv_equals_rv(mc_V2mBNcV1EqCifyH9UdCbkF,ssc_core_FBNduJ2xtv0UjTuX5_iN4m);
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core__BOls5qMqQO9cXYuVPVeU_= *(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_kO9IHyu5O9dR_aJUHrxS45
);mc_VIFqLU9Z6UtwXDWPnvd_zg(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_FePbFl2MhWldXPV8N5Prx9
,mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core__ERgtpAr_fdTcmO70I3iqR,ssc_core_FBNduJ2xtv0UjTuX5_iN4m);if(
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_ViKkQGhWq2pthH4EazW5gY==ssc_core_kbHZQuN3TQGxiq3JDAOzsE){
mc_V7hiVZfxKK0Uj9rPai4LYw(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_FePbFl2MhWldXPV8N5Prx9
,mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_kLIDMtKkvD_aePzbV_jg_e);mc_VIFqLU9Z6UtwXDWPnvd_zg(
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi,mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_FePbFl2MhWldXPV8N5Prx9
,mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi);}else{mc_VWnvos7Q548uVH7p0208jN(
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi,mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core__4IbiAlzDulVjL62bZP__w
,mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_FePbFl2MhWldXPV8N5Prx9);}if(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_ViKkQGhWq2pthH4EazW5gY
<ssc_core_kbHZQuN3TQGxiq3JDAOzsE){mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_ViKkQGhWq2pthH4EazW5gY
++;}}static NeSystemInputSizes ssc_core_VZituMnWVplfhDkJqSdK6U(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*mc_kpyeXH2RWcWG_DVSgKEG_O){return
neu_get_system_input_sizes(mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->ssc_core_kO9IHyu5O9dR_aJUHrxS45
);}static mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core__FWm_x3JZL0qZ5B8KWSu6f(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2 const*mc_kpyeXH2RWcWG_DVSgKEG_O,
mc_F3czdn9EwuxfaaYWgN0vfZ ssc_core_kDh9Sdqtd1dhZLBqs4W1eB){(void)
mc_kpyeXH2RWcWG_DVSgKEG_O;return ssc_core_kDh9Sdqtd1dhZLBqs4W1eB;}static void
ssc_core_khdg35BEHwlMdXMmP_7xsN(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*
mc_kpyeXH2RWcWG_DVSgKEG_O){PmAllocator*mc_FOGg0ZWot2WdYenO8zaD4Z=
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->ssc_core_FyUeLiATLG4zWes0mMKZnu;
ssc_core_kc9qhfWw5VdoiH2N7f_sLI(mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData->
ssc_core_VM7BxQGhXaKueLTlYnjv9x);{void*const ssc_core_Fotmx_ApXx45d1fFUyS5o7=(
mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData);PmAllocator*const
ssc_core_k_NYi_UpyO8vZatJ_UBe6S=(mc_FOGg0ZWot2WdYenO8zaD4Z);if(
ssc_core_Fotmx_ApXx45d1fFUyS5o7){(ssc_core_k_NYi_UpyO8vZatJ_UBe6S)->mFreeFcn(
ssc_core_k_NYi_UpyO8vZatJ_UBe6S,ssc_core_Fotmx_ApXx45d1fFUyS5o7);}};{void*
const ssc_core_FjXCdHaJ_jObaPJCNSYUEB=(mc_kpyeXH2RWcWG_DVSgKEG_O);PmAllocator*
const ssc_core_VGUP00nzFAKlgqV_YBguN2=(mc_FOGg0ZWot2WdYenO8zaD4Z);if(
ssc_core_FjXCdHaJ_jObaPJCNSYUEB){(ssc_core_VGUP00nzFAKlgqV_YBguN2)->mFreeFcn(
ssc_core_VGUP00nzFAKlgqV_YBguN2,ssc_core_FjXCdHaJ_jObaPJCNSYUEB);}};}static
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*ssc_core__vV0jb6pYiS9iLCfNXmxUT(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z){ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*
mc_kpyeXH2RWcWG_DVSgKEG_O=(ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core__qiNSbrJ_9KWZXVgsD4AQ2)),(1))));ssc_core_Fb0DCTdd1x_LhajF7VR_DH*
mc__d1alWYexptL_X5HTFhbNK=(ssc_core_Fb0DCTdd1x_LhajF7VR_DH*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_Fb0DCTdd1x_LhajF7VR_DH)),(1))));mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VM7BxQGhXaKueLTlYnjv9x=ssc_core_VA4rtEv5IaWa_XCPeCvEhf(
ssc_core_keuPMa27xjG1bPeaPl_Oys,mc_FOGg0ZWot2WdYenO8zaD4Z);
mc__d1alWYexptL_X5HTFhbNK->ssc_core_FyUeLiATLG4zWes0mMKZnu=
mc_FOGg0ZWot2WdYenO8zaD4Z;mc_kpyeXH2RWcWG_DVSgKEG_O->mPrivateData=
mc__d1alWYexptL_X5HTFhbNK;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_VM7BxQGhXaKueLTlYnjv9x=mc__d1alWYexptL_X5HTFhbNK->
ssc_core_VM7BxQGhXaKueLTlYnjv9x;mc_kpyeXH2RWcWG_DVSgKEG_O->
mc_k0h0NPxQNyl2XD95RLG6Hy= &ssc_core__MR9P86FHX_DZ1QqXRXig9;
mc_kpyeXH2RWcWG_DVSgKEG_O->ssc_core_klXC4aNpb9GwZu6_HluAlj= &
ssc_core_VZ4ohsw3Balv_TeZyyFe5Z;mc_kpyeXH2RWcWG_DVSgKEG_O->mSizes= &
ssc_core_VZituMnWVplfhDkJqSdK6U;mc_kpyeXH2RWcWG_DVSgKEG_O->
ssc_core_kOw3W_1IrxSe_5HOqgvUlK= &ssc_core__FWm_x3JZL0qZ5B8KWSu6f;
mc_kpyeXH2RWcWG_DVSgKEG_O->mDestroy= &ssc_core_khdg35BEHwlMdXMmP_7xsN;return
mc_kpyeXH2RWcWG_DVSgKEG_O;}struct ssc_core_VdxzFJ37U1Ghhi4CxHw5mD{PmAllocator*
ssc_core_FyUeLiATLG4zWes0mMKZnu;ssc_core__qiNSbrJ_9KWZXVgsD4AQ2*
ssc_core__GXTByDnQuh2cP7CO4U72s;};static size_t ssc_core__BZ06N0uzy0ZfeVjFLdbJl
(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx){return
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s
->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi->mN+1;}static mc_kQtOKCqS08dIbumyDnHNDL
ssc_core_FKB1smg9nPWQeLvm3jH36c(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,NeSystemInput const*
ssc_core_kNbvLmFI_EtAay5OpgNJFz){ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData
->ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->
mPrivateData->ssc_core_ViKkQGhWq2pthH4EazW5gY=ssc_core_kbHZQuN3TQGxiq3JDAOzsE;
return(*((ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData
->ssc_core_FIx3hYDxQxCugT28fDgmVT->ssc_core_FFg3rVqFQwGs_Dq1VKNSr6)->
mc_VAvAkWmhpT_WWme_3E1U91))((ssc_core_kNbvLmFI_EtAay5OpgNJFz),(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s
->mPrivateData->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi),((ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x
->mPrivateData->ssc_core_FIx3hYDxQxCugT28fDgmVT->
ssc_core_FFg3rVqFQwGs_Dq1VKNSr6)->mc_ko6_hiERTRldgDROOJBQCH));}static void
ssc_core_Fxj8fcXE3FKBXPLJ_fjxis(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector const*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m){PmRealVector ssc_core___lCcTGur_49_93wyC5NG1=
*ssc_core_FBNduJ2xtv0UjTuX5_iN4m;PmRealVector ssc_core_kVs_MU944sxZiPKQZd5XIv=
*ssc_core_FBNduJ2xtv0UjTuX5_iN4m;(void)0;;ssc_core___lCcTGur_49_93wyC5NG1 .mN=
ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mN-1;ssc_core_kVs_MU944sxZiPKQZd5XIv.mX=
ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mX+(ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mN-1);
ssc_core_kVs_MU944sxZiPKQZd5XIv.mN=1;pm_rv_equals_rv(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s
->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_F1NRFAaR2ECEYyVlHNvfFi,&ssc_core___lCcTGur_49_93wyC5NG1);
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s
->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData->
ssc_core_ViKkQGhWq2pthH4EazW5gY=(size_t)ssc_core_kVs_MU944sxZiPKQZd5XIv.mX[0];
}static void ssc_core__5IuTyXgAT8hjy9QkSnhDh(ssc_core_kv1v8GUnv4G8h1yPy_rg74
const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,PmRealVector const*
ssc_core_FBNduJ2xtv0UjTuX5_iN4m){PmRealVector ssc_core___lCcTGur_49_93wyC5NG1=
*ssc_core_FBNduJ2xtv0UjTuX5_iN4m;PmRealVector ssc_core_kVs_MU944sxZiPKQZd5XIv=
*ssc_core_FBNduJ2xtv0UjTuX5_iN4m;(void)0;;ssc_core___lCcTGur_49_93wyC5NG1 .mN=
ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mN-1;ssc_core_kVs_MU944sxZiPKQZd5XIv.mX=
ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mX+(ssc_core_FBNduJ2xtv0UjTuX5_iN4m->mN-1);
ssc_core_kVs_MU944sxZiPKQZd5XIv.mN=1;pm_rv_equals_rv(&
ssc_core___lCcTGur_49_93wyC5NG1,ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData
->ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->
mPrivateData->ssc_core_F1NRFAaR2ECEYyVlHNvfFi);ssc_core_kVs_MU944sxZiPKQZd5XIv
.mX[0]=(real_T)ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData
->ssc_core_ViKkQGhWq2pthH4EazW5gY;}static void ssc_core_FtMbFxD8uGt9fHXFKkUkAe
(ssc_core_kv1v8GUnv4G8h1yPy_rg74 const*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx,real_T
ssc_core__lU1mWENxFpCeio7tYki0i){ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData
->ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->
mPrivateData->ssc_core__4IbiAlzDulVjL62bZP__w= -1.0/
ssc_core__lU1mWENxFpCeio7tYki0i;ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData
->ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->
mPrivateData->ssc_core_kLIDMtKkvD_aePzbV_jg_e= -2.0/
ssc_core__lU1mWENxFpCeio7tYki0i;}static void ssc_core_kf46zcDA77_jVP1zZZXRqs(
ssc_core_kv1v8GUnv4G8h1yPy_rg74*ssc_core_V8a_FQ2T6YWLgu_s5UfAPx){PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z=ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->
ssc_core_FyUeLiATLG4zWes0mMKZnu;(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
ssc_core__A0n8EhE_GdLWudFqHsqyZ)->mDestroy(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
ssc_core__A0n8EhE_GdLWudFqHsqyZ);(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->
mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s)->mDestroy(
ssc_core_V8a_FQ2T6YWLgu_s5UfAPx->mPrivateData->ssc_core__GXTByDnQuh2cP7CO4U72s
);{void*const ssc_core_Fu2Cj2QHLWSy_XA766AtH0=(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx
->mPrivateData);PmAllocator*const ssc_core_F1_WHSFVFV8mimaqW4olZd=(
mc_FOGg0ZWot2WdYenO8zaD4Z);if(ssc_core_Fu2Cj2QHLWSy_XA766AtH0){(
ssc_core_F1_WHSFVFV8mimaqW4olZd)->mFreeFcn(ssc_core_F1_WHSFVFV8mimaqW4olZd,
ssc_core_Fu2Cj2QHLWSy_XA766AtH0);}};{void*const ssc_core_kN27oqwkSIh3gXQo5OVVTR
=(ssc_core_V8a_FQ2T6YWLgu_s5UfAPx);PmAllocator*const
ssc_core_knCNrX_wPNOuh97CsjqXM7=(mc_FOGg0ZWot2WdYenO8zaD4Z);if(
ssc_core_kN27oqwkSIh3gXQo5OVVTR){(ssc_core_knCNrX_wPNOuh97CsjqXM7)->mFreeFcn(
ssc_core_knCNrX_wPNOuh97CsjqXM7,ssc_core_kN27oqwkSIh3gXQo5OVVTR);}};}
ssc_core_kv1v8GUnv4G8h1yPy_rg74*ssc_core__5NFPJDr3stmbTrVbZ26HF(
ssc_core___8MOTpW4Mt4ZuJu_r_Tk1*ssc_core_keuPMa27xjG1bPeaPl_Oys,PmAllocator*
mc_FOGg0ZWot2WdYenO8zaD4Z){ssc_core_kv1v8GUnv4G8h1yPy_rg74*
ssc_core___JIt75pzT_U_eY1aS3Niq=(ssc_core_kv1v8GUnv4G8h1yPy_rg74*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_kv1v8GUnv4G8h1yPy_rg74)),(1))));ssc_core_kEVpCpWuAbCLbyV6Z5Ezlj*
mc__d1alWYexptL_X5HTFhbNK=(ssc_core_kEVpCpWuAbCLbyV6Z5Ezlj*)(((
mc_FOGg0ZWot2WdYenO8zaD4Z)->mCallocFcn((mc_FOGg0ZWot2WdYenO8zaD4Z),(sizeof(
ssc_core_kEVpCpWuAbCLbyV6Z5Ezlj)),(1))));mc__d1alWYexptL_X5HTFhbNK->
ssc_core_FyUeLiATLG4zWes0mMKZnu=mc_FOGg0ZWot2WdYenO8zaD4Z;
mc__d1alWYexptL_X5HTFhbNK->ssc_core__GXTByDnQuh2cP7CO4U72s=
ssc_core__vV0jb6pYiS9iLCfNXmxUT(ssc_core_keuPMa27xjG1bPeaPl_Oys,
mc_FOGg0ZWot2WdYenO8zaD4Z);mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GXTByDnQuh2cP7CO4U72s->ssc_core_VM7BxQGhXaKueLTlYnjv9x->mPrivateData
->ssc_core_ViKkQGhWq2pthH4EazW5gY=ssc_core_kbHZQuN3TQGxiq3JDAOzsE;
ssc_core___JIt75pzT_U_eY1aS3Niq->mPrivateData=mc__d1alWYexptL_X5HTFhbNK;
ssc_core___JIt75pzT_U_eY1aS3Niq->ssc_core__A0n8EhE_GdLWudFqHsqyZ=
ssc_core_Vps22mc76e44dL0ve7dAWJ(ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_k4UYUhUR_X4c_P73M2z6S7,ssc_core_keuPMa27xjG1bPeaPl_Oys->
ssc_core_kzOmBWsipN4_b55POG8Wy9,mc__d1alWYexptL_X5HTFhbNK->
ssc_core__GXTByDnQuh2cP7CO4U72s,mc_FOGg0ZWot2WdYenO8zaD4Z);
ssc_core___JIt75pzT_U_eY1aS3Niq->ssc_core__6TOr6vPt0dOYqv1RQSns0=true;
ssc_core___JIt75pzT_U_eY1aS3Niq->ssc_core_kvFcrvIoo2CkeaMuIgpw_Z= &
ssc_core_FKB1smg9nPWQeLvm3jH36c;ssc_core___JIt75pzT_U_eY1aS3Niq->
ssc_core_FiEBtV4zgoSIdeQkFLGjXQ= &ssc_core_Fxj8fcXE3FKBXPLJ_fjxis;
ssc_core___JIt75pzT_U_eY1aS3Niq->ssc_core_V3833bWs6PdWiLrp9jD_59= &
ssc_core__5IuTyXgAT8hjy9QkSnhDh;ssc_core___JIt75pzT_U_eY1aS3Niq->
ssc_core_FAuiVHFGN6pHZmO_Jw_onC= &ssc_core__BZ06N0uzy0ZfeVjFLdbJl;
ssc_core___JIt75pzT_U_eY1aS3Niq->ssc_core_V9XjSx3zX_KuYDW2vSiRKE= &
ssc_core_FtMbFxD8uGt9fHXFKkUkAe;ssc_core___JIt75pzT_U_eY1aS3Niq->mDestroy= &
ssc_core_kf46zcDA77_jVP1zZZXRqs;return ssc_core___JIt75pzT_U_eY1aS3Niq;}
